{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/GradientForwardPoints\/bottomLeftToTopRight"},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"bottomLeftToTopRight"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"CGPoint","preciseIdentifier":"c:@S@CGPoint"},{"text":"]","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"sections":[],"metadata":{"role":"symbol","modules":[{"name":"EaseCallUIKit"}],"navigatorTitle":[{"text":"bottomLeftToTopRight","kind":"identifier"}],"roleHeading":"Type Property","externalID":"c:@M@EaseCallUIKit@objc(cs)GradientForwardPoints(cpy)bottomLeftToTopRight","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"bottomLeftToTopRight","kind":"identifier"},{"kind":"text","text":": ["},{"text":"CGPoint","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGPoint"},{"kind":"text","text":"]"}],"title":"bottomLeftToTopRight","symbolKind":"property"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/GradientForwardPoints"]]},"schemaVersion":{"patch":0,"minor":3,"major":0},"variants":[{"paths":["\/documentation\/easecalluikit\/gradientforwardpoints\/bottomlefttotopright"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easecalluikit\/gradientforwardpoints\/bottomlefttotopright"]}],"references":{"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/GradientForwardPoints":{"url":"\/documentation\/easecalluikit\/gradientforwardpoints","kind":"symbol","role":"symbol","title":"GradientForwardPoints","navigatorTitle":[{"text":"GradientForwardPoints","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/GradientForwardPoints","abstract":[],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"GradientForwardPoints","kind":"identifier"}]},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/GradientForwardPoints/bottomLeftToTopRight":{"url":"\/documentation\/easecalluikit\/gradientforwardpoints\/bottomlefttotopright","role":"symbol","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/GradientForwardPoints\/bottomLeftToTopRight","navigatorTitle":[{"kind":"identifier","text":"bottomLeftToTopRight"}],"abstract":[],"title":"bottomLeftToTopRight","kind":"symbol","type":"topic","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"bottomLeftToTopRight","kind":"identifier"},{"kind":"text","text":": ["},{"text":"CGPoint","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGPoint"},{"text":"]","kind":"text"}]},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit":{"title":"EaseCallUIKit","type":"topic","url":"\/documentation\/easecalluikit","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit","abstract":[],"role":"collection","kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Type Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"bottomLeftToTopRight","op":"replace","path":"\/metadata\/title"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"bottomLeftToTopRight"}]},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"class","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<NSValue *>","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"bottomLeftToTopRight","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1GradientForwardPoints\/title","value":"GradientForwardPoints","op":"replace"},{"op":"replace","value":[{"text":"GradientForwardPoints","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1GradientForwardPoints\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"GradientForwardPoints"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1GradientForwardPoints\/navigatorTitle"},{"op":"replace","value":"bottomLeftToTopRight","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1GradientForwardPoints~1bottomLeftToTopRight\/title"},{"value":[{"kind":"identifier","text":"bottomLeftToTopRight"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1GradientForwardPoints~1bottomLeftToTopRight\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}