{"identifier":{"url":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/GradientForwardPoints\/topRightToBottomLeft","interfaceLanguage":"swift"},"sections":[],"schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"externalID":"c:@M@EaseCallUIKit@objc(cs)GradientForwardPoints(cpy)topRightToBottomLeft","role":"symbol","modules":[{"name":"EaseCallUIKit"}],"fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"topRightToBottomLeft","kind":"identifier"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:@S@CGPoint","text":"CGPoint","kind":"typeIdentifier"},{"kind":"text","text":"]"}],"navigatorTitle":[{"kind":"identifier","text":"topRightToBottomLeft"}],"title":"topRightToBottomLeft","symbolKind":"property","roleHeading":"Type Property"},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"topRightToBottomLeft"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:@S@CGPoint","kind":"typeIdentifier","text":"CGPoint"},{"text":"]","kind":"text"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easecalluikit\/gradientforwardpoints\/toprighttobottomleft"]},{"paths":["\/documentation\/easecalluikit\/gradientforwardpoints\/toprighttobottomleft"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/GradientForwardPoints"]]},"references":{"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/GradientForwardPoints":{"url":"\/documentation\/easecalluikit\/gradientforwardpoints","kind":"symbol","role":"symbol","title":"GradientForwardPoints","navigatorTitle":[{"text":"GradientForwardPoints","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/GradientForwardPoints","abstract":[],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"GradientForwardPoints","kind":"identifier"}]},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit":{"title":"EaseCallUIKit","type":"topic","url":"\/documentation\/easecalluikit","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit","abstract":[],"role":"collection","kind":"symbol"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/GradientForwardPoints/topRightToBottomLeft":{"fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"topRightToBottomLeft","kind":"identifier"},{"kind":"text","text":": ["},{"text":"CGPoint","preciseIdentifier":"c:@S@CGPoint","kind":"typeIdentifier"},{"kind":"text","text":"]"}],"role":"symbol","title":"topRightToBottomLeft","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/GradientForwardPoints\/topRightToBottomLeft","type":"topic","navigatorTitle":[{"text":"topRightToBottomLeft","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/easecalluikit\/gradientforwardpoints\/toprighttobottomleft","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Type Property","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"topRightToBottomLeft"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"topRightToBottomLeft","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"class","kind":"keyword"},{"text":", ","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"copy"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSArray<NSValue *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" * "},{"text":"topRightToBottomLeft","kind":"identifier"},{"text":";","kind":"text"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1GradientForwardPoints\/title","value":"GradientForwardPoints"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1GradientForwardPoints\/fragments","value":[{"kind":"identifier","text":"GradientForwardPoints"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1GradientForwardPoints\/navigatorTitle","op":"replace","value":[{"text":"GradientForwardPoints","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1GradientForwardPoints~1topRightToBottomLeft\/title","value":"topRightToBottomLeft"},{"op":"replace","value":[{"text":"topRightToBottomLeft","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1GradientForwardPoints~1topRightToBottomLeft\/fragments"}]}]}