{"metadata":{"roleHeading":"Case","symbolKind":"case","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"dark"}],"modules":[{"name":"EaseCallUIKit"}],"title":"ThemeStyle.dark","role":"symbol","externalID":"c:@M@EaseCallUIKit@E@ThemeStyle@ThemeStyleDark","navigatorTitle":[{"kind":"identifier","text":"ThemeStyleDark"}]},"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","variants":[{"paths":["\/documentation\/easecalluikit\/themestyle\/dark"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/easecalluikit\/themestyle\/dark"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/ThemeStyle\/dark","interfaceLanguage":"swift"},"sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"dark"}],"languages":["swift"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/ThemeStyle"]]},"references":{"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit":{"title":"EaseCallUIKit","type":"topic","url":"\/documentation\/easecalluikit","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit","abstract":[],"role":"collection","kind":"symbol"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/ThemeStyle/dark":{"navigatorTitle":[{"kind":"identifier","text":"ThemeStyleDark"}],"url":"\/documentation\/easecalluikit\/themestyle\/dark","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"dark"}],"title":"ThemeStyle.dark","abstract":[],"type":"topic","role":"symbol","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/ThemeStyle\/dark"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/ThemeStyle":{"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/ThemeStyle","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ThemeStyle"}],"type":"topic","abstract":[{"type":"text","text":"Contain light and dark themes of the ease chat UIKit.If you want to switch custom theme,you’ll modify primary&secondary&error&neutral&neutralSpecial hues properties in "},{"code":"Appearance","type":"codeVoice"},{"type":"text","text":".Then call "},{"type":"codeVoice","code":"Theme.switchTheme(style: .custom)"},{"text":" method","type":"text"}],"url":"\/documentation\/easecalluikit\/themestyle","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ThemeStyle"}],"title":"ThemeStyle"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"ThemeStyleDark"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"value":[{"kind":"identifier","text":"ThemeStyleDark"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"identifier","text":"ThemeStyleDark"}]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1ThemeStyle~1dark\/title","value":"ThemeStyleDark","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1ThemeStyle~1dark\/fragments","value":[{"kind":"identifier","text":"ThemeStyleDark"}]},{"op":"replace","value":"ThemeStyle","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1ThemeStyle\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1ThemeStyle\/fragments","value":[{"kind":"identifier","text":"ThemeStyle"}]},{"value":[{"text":"ThemeStyle","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1ThemeStyle\/navigatorTitle"}]}]}