{"metadata":{"modules":[{"name":"EaseCallUIKit"}],"roleHeading":"Instance Property","title":"enablePIPOn1V1VideoScene","role":"symbol","symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"enablePIPOn1V1VideoScene"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"externalID":"s:13EaseCallUIKit0B9KitConfigC24enablePIPOn1V1VideoSceneSbvp"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitConfig"]]},"abstract":[{"text":"Indicates whether to enable Picture-in-Picture mode for 1v1 video calls","type":"text"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitConfig\/enablePIPOn1V1VideoScene"},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"enablePIPOn1V1VideoScene"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easecalluikit\/callkitconfig\/enablepipon1v1videoscene"]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"references":{"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit":{"title":"EaseCallUIKit","type":"topic","url":"\/documentation\/easecalluikit","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit","abstract":[],"role":"collection","kind":"symbol"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallKitConfig":{"abstract":[],"type":"topic","title":"CallKitConfig","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"CallKitConfig"}],"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitConfig","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"CallKitConfig","kind":"identifier"}],"url":"\/documentation\/easecalluikit\/callkitconfig"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallKitConfig/enablePIPOn1V1VideoScene":{"title":"enablePIPOn1V1VideoScene","abstract":[{"type":"text","text":"Indicates whether to enable Picture-in-Picture mode for 1v1 video calls"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitConfig\/enablePIPOn1V1VideoScene","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"enablePIPOn1V1VideoScene"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"type":"topic","url":"\/documentation\/easecalluikit\/callkitconfig\/enablepipon1v1videoscene","role":"symbol"}},"variantOverrides":[{"patch":[{"value":"CallKitConfig","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallKitConfig\/title"},{"value":[{"kind":"identifier","text":"CallKitConfig"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallKitConfig\/fragments"},{"value":[{"text":"CallKitConfig","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallKitConfig\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}