{"identifier":{"url":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitConfig\/ringTimeOut","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Indicates whether to enable call recording.The minimum cannot be less than 10."}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"ringTimeOut","kind":"identifier"},{"kind":"text","text":": "},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"}],"platforms":["iOS"]}],"kind":"declarations"}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitConfig"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easecalluikit\/callkitconfig\/ringtimeout"]}],"sections":[],"metadata":{"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"ringTimeOut","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"}],"modules":[{"name":"EaseCallUIKit"}],"title":"ringTimeOut","externalID":"s:13EaseCallUIKit0B9KitConfigC11ringTimeOutSivp","symbolKind":"property","roleHeading":"Instance Property"},"references":{"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallKitConfig/ringTimeOut":{"kind":"symbol","role":"symbol","url":"\/documentation\/easecalluikit\/callkitconfig\/ringtimeout","type":"topic","title":"ringTimeOut","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ringTimeOut","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"}],"abstract":[{"type":"text","text":"Indicates whether to enable call recording.The minimum cannot be less than 10."}],"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitConfig\/ringTimeOut"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit":{"title":"EaseCallUIKit","type":"topic","url":"\/documentation\/easecalluikit","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit","abstract":[],"role":"collection","kind":"symbol"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallKitConfig":{"abstract":[],"type":"topic","title":"CallKitConfig","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"CallKitConfig"}],"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitConfig","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"CallKitConfig","kind":"identifier"}],"url":"\/documentation\/easecalluikit\/callkitconfig"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallKitConfig\/title","op":"replace","value":"CallKitConfig"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallKitConfig\/fragments","value":[{"kind":"identifier","text":"CallKitConfig"}]},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallKitConfig\/navigatorTitle","op":"replace","value":[{"text":"CallKitConfig","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}