{"identifier":{"url":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallMultiViewController\/rightAction()","interfaceLanguage":"swift"},"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallMultiViewController"]]},"metadata":{"title":"rightAction()","symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"rightAction","kind":"identifier"},{"kind":"text","text":"()"}],"roleHeading":"Instance Method","modules":[{"name":"EaseCallUIKit"}],"role":"symbol","navigatorTitle":[{"text":"rightAction","kind":"identifier"}],"externalID":"c:@M@EaseCallUIKit@objc(cs)CallMultiViewController(im)rightAction"},"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"attribute","text":"@"},{"kind":"attribute","preciseIdentifier":"s:ScM","text":"MainActor"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"rightAction","kind":"identifier"},{"text":"()","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"paths":["\/documentation\/easecalluikit\/callmultiviewcontroller\/rightaction()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/easecalluikit\/callmultiviewcontroller\/rightaction()"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallMultiViewController":{"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallMultiViewController","kind":"symbol","abstract":[],"type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"CallMultiViewController","kind":"identifier"}],"navigatorTitle":[{"text":"CallMultiViewController","kind":"identifier"}],"url":"\/documentation\/easecalluikit\/callmultiviewcontroller","title":"CallMultiViewController"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallMultiViewController/rightAction()":{"role":"symbol","title":"rightAction()","url":"\/documentation\/easecalluikit\/callmultiviewcontroller\/rightaction()","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"rightAction","kind":"identifier"},{"kind":"text","text":"()"}],"type":"topic","kind":"symbol","navigatorTitle":[{"text":"rightAction","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallMultiViewController\/rightAction()"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit":{"title":"EaseCallUIKit","type":"topic","url":"\/documentation\/easecalluikit","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit","abstract":[],"role":"collection","kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"rightAction","op":"replace"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"rightAction","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"identifier","text":"rightAction"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallMultiViewController\/title","value":"CallMultiViewController"},{"op":"replace","value":[{"kind":"identifier","text":"CallMultiViewController"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallMultiViewController\/fragments"},{"value":[{"kind":"identifier","text":"CallMultiViewController"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallMultiViewController\/navigatorTitle"},{"op":"replace","value":"rightAction","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallMultiViewController~1rightAction()\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"rightAction"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallMultiViewController~1rightAction()\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}