{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"timeChanged"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"text":"timerIdentify","kind":"internalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"interval","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"seconds","kind":"internalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"kind":"text","text":")"}]}]},{"parameters":[{"content":[{"inlineContent":[{"text":"The identify of the timer that has changed.","type":"text"}],"type":"paragraph"}],"name":"timerIdentify"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The new time interval in seconds for the timer."}]}],"name":"seconds"}],"kind":"parameters"}],"sections":[],"metadata":{"navigatorTitle":[{"text":"timeChanged:interval:","kind":"identifier"}],"symbolKind":"method","roleHeading":"Instance Method","modules":[{"name":"EaseCallUIKit"}],"title":"timeChanged(_:interval:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"timeChanged","kind":"identifier"},{"kind":"text","text":"("},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"interval","kind":"externalParam"},{"kind":"text","text":": "},{"text":"UInt","preciseIdentifier":"s:Su","kind":"typeIdentifier"},{"text":")","kind":"text"}],"externalID":"c:@CM@EaseCallUIKit@objc(cs)CallMultiViewController(im)timeChanged:interval:","extendedModule":"EaseCallUIKit"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallMultiViewController","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallMultiViewController\/TimerServiceListener-Implementations"]]},"abstract":[{"type":"text","text":"Called when the time interval for a timer changes."}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallMultiViewController\/timeChanged(_:interval:)"},"variants":[{"paths":["\/documentation\/easecalluikit\/callmultiviewcontroller\/timechanged(_:interval:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/easecalluikit\/callmultiviewcontroller\/timechanged(_:interval:)"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"references":{"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit":{"title":"EaseCallUIKit","type":"topic","url":"\/documentation\/easecalluikit","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit","abstract":[],"role":"collection","kind":"symbol"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallMultiViewController/timeChanged(_:interval:)":{"title":"timeChanged(_:interval:)","type":"topic","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallMultiViewController\/timeChanged(_:interval:)","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"timeChanged:interval:","kind":"identifier"}],"url":"\/documentation\/easecalluikit\/callmultiviewcontroller\/timechanged(_:interval:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"timeChanged","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"text":"interval","kind":"externalParam"},{"kind":"text","text":": "},{"text":"UInt","kind":"typeIdentifier","preciseIdentifier":"s:Su"},{"text":")","kind":"text"}],"abstract":[{"type":"text","text":"Called when the time interval for a timer changes."}]},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallMultiViewController/TimerServiceListener-Implementations":{"role":"collectionGroup","kind":"article","type":"topic","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallMultiViewController\/TimerServiceListener-Implementations","abstract":[],"title":"TimerServiceListener Implementations","url":"\/documentation\/easecalluikit\/callmultiviewcontroller\/timerservicelistener-implementations"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallMultiViewController":{"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallMultiViewController","kind":"symbol","abstract":[],"type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"CallMultiViewController","kind":"identifier"}],"navigatorTitle":[{"text":"CallMultiViewController","kind":"identifier"}],"url":"\/documentation\/easecalluikit\/callmultiviewcontroller","title":"CallMultiViewController"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"value":"timeChanged:interval:","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"timeChanged:interval:","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"text":") ","kind":"text"},{"kind":"identifier","text":"timeChanged:"},{"kind":"text","text":"("},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"timerIdentify","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"interval:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@T@NSUInteger","kind":"typeIdentifier","text":"NSUInteger"},{"text":") ","kind":"text"},{"text":"seconds","kind":"internalParam"},{"kind":"text","text":";"}]}],"kind":"declarations"}},{"op":"replace","value":"timeChanged:interval:","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallMultiViewController~1timeChanged(_:interval:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallMultiViewController~1timeChanged(_:interval:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"timeChanged:interval:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallMultiViewController\/title","value":"CallMultiViewController"},{"value":[{"kind":"identifier","text":"CallMultiViewController"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallMultiViewController\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallMultiViewController\/navigatorTitle","value":[{"kind":"identifier","text":"CallMultiViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}