{"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"role":"symbol","modules":[{"name":"EaseCallUIKit"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"viewDidLoad","kind":"identifier"},{"text":"()","kind":"text"}],"roleHeading":"Instance Method","navigatorTitle":[{"text":"viewDidLoad","kind":"identifier"}],"externalID":"c:@M@EaseCallUIKit@objc(cs)CallMultiViewController(im)viewDidLoad","symbolKind":"method","title":"viewDidLoad()"},"identifier":{"url":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallMultiViewController\/viewDidLoad()","interfaceLanguage":"swift"},"kind":"symbol","variants":[{"paths":["\/documentation\/easecalluikit\/callmultiviewcontroller\/viewdidload()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/easecalluikit\/callmultiviewcontroller\/viewdidload()"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallMultiViewController"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@"},{"preciseIdentifier":"s:ScM","text":"MainActor","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"override"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"viewDidLoad","kind":"identifier"},{"kind":"text","text":"()"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"references":{"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallMultiViewController":{"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallMultiViewController","kind":"symbol","abstract":[],"type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"CallMultiViewController","kind":"identifier"}],"navigatorTitle":[{"text":"CallMultiViewController","kind":"identifier"}],"url":"\/documentation\/easecalluikit\/callmultiviewcontroller","title":"CallMultiViewController"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallMultiViewController/viewDidLoad()":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"viewDidLoad"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallMultiViewController\/viewDidLoad()","title":"viewDidLoad()","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"viewDidLoad"},{"text":"()","kind":"text"}],"url":"\/documentation\/easecalluikit\/callmultiviewcontroller\/viewdidload()","abstract":[]},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit":{"title":"EaseCallUIKit","type":"topic","url":"\/documentation\/easecalluikit","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit","abstract":[],"role":"collection","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"value":"viewDidLoad","path":"\/metadata\/title","op":"replace"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"viewDidLoad"}]},{"path":"\/topicSections","op":"add","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"viewDidLoad","kind":"identifier"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]}},{"value":"CallMultiViewController","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallMultiViewController\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallMultiViewController\/fragments","value":[{"kind":"identifier","text":"CallMultiViewController"}]},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallMultiViewController\/navigatorTitle","value":[{"text":"CallMultiViewController","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallMultiViewController~1viewDidLoad()\/title","value":"viewDidLoad"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"viewDidLoad","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallMultiViewController~1viewDidLoad()\/fragments"}]}]}