{"kind":"symbol","metadata":{"role":"symbol","roleHeading":"Case","externalID":"c:@M@EaseCallUIKit@E@CallButtonType@CallButtonTypeMic_off","title":"CallButtonType.mic_off","modules":[{"name":"EaseCallUIKit"}],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"mic_off","kind":"identifier"}],"symbolKind":"case","navigatorTitle":[{"kind":"identifier","text":"CallButtonTypeMic_off"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"mic_off"}],"platforms":["iOS"],"languages":["swift"]}]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallButtonType"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easecalluikit\/callbuttontype\/mic_off"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easecalluikit\/callbuttontype\/mic_off"]}],"identifier":{"url":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallButtonType\/mic_off","interfaceLanguage":"swift"},"references":{"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallButtonType":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CallButtonType","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/easecalluikit\/callbuttontype","abstract":[],"type":"topic","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallButtonType","title":"CallButtonType","navigatorTitle":[{"text":"CallButtonType","kind":"identifier"}],"role":"symbol"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit":{"title":"EaseCallUIKit","type":"topic","url":"\/documentation\/easecalluikit","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit","abstract":[],"role":"collection","kind":"symbol"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallButtonType/mic_off":{"type":"topic","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"CallButtonTypeMic_off","kind":"identifier"}],"title":"CallButtonType.mic_off","url":"\/documentation\/easecalluikit\/callbuttontype\/mic_off","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"mic_off","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallButtonType\/mic_off","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"CallButtonTypeMic_off"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"CallButtonTypeMic_off"}]},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"CallButtonTypeMic_off","kind":"identifier"}],"platforms":["iOS"]}]}},{"value":"CallButtonType","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallButtonType\/title","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"CallButtonType"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallButtonType\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallButtonType\/navigatorTitle","value":[{"kind":"identifier","text":"CallButtonType"}]},{"value":"CallButtonTypeMic_off","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallButtonType~1mic_off\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallButtonType~1mic_off\/fragments","op":"replace","value":[{"text":"CallButtonTypeMic_off","kind":"identifier"}]}]}]}