{"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"url":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallUserProfileProviderOC\/fetchProfiles(profileIds:completion:)","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/easecalluikit\/calluserprofileprovideroc\/fetchprofiles(profileids:completion:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easecalluikit\/calluserprofileprovideroc\/fetchprofiles(profileids:completion:)"]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallUserProfileProviderOC"]]},"abstract":[{"type":"text","text":"Need to obtain the list display information on the current screen."}],"sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"fetchProfiles"},{"kind":"text","text":"("},{"text":"profileIds","kind":"externalParam"},{"kind":"text","text":": ["},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"], "},{"text":"completion","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"@escaping","kind":"attribute"},{"kind":"text","text":" (["},{"text":"CallProfileProtocol","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallProfileProtocol","preciseIdentifier":"c:@M@EaseCallUIKit@objc(pl)CallProfileProtocol","kind":"typeIdentifier"},{"kind":"text","text":"]) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"text":")","kind":"text"}],"languages":["swift"]}],"kind":"declarations"},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"The corresponding conversation id string array.","type":"text"}]}],"name":"profileIds"},{"content":[{"inlineContent":[{"text":"Callback,obtain Array of the ","type":"text"},{"code":"ChatUserProfileProtocol","type":"codeVoice"},{"type":"text","text":" object."}],"type":"paragraph"}],"name":"completion"}],"kind":"parameters"}],"metadata":{"externalID":"c:@M@EaseCallUIKit@objc(pl)CallUserProfileProviderOC(im)fetchProfilesWithProfileIds:completion:","role":"symbol","modules":[{"name":"EaseCallUIKit"}],"symbolKind":"method","roleHeading":"Instance Method","required":true,"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"fetchProfiles","kind":"identifier"},{"text":"(","kind":"text"},{"text":"profileIds","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"completion"},{"text":": ([","kind":"text"},{"text":"CallProfileProtocol","kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseCallUIKit@objc(pl)CallProfileProtocol"},{"text":"]) -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"navigatorTitle":[{"text":"fetchProfilesWithProfileIds:completion:","kind":"identifier"}],"title":"fetchProfiles(profileIds:completion:)"},"references":{"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallUserProfileProviderOC":{"kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"CallUserProfileProviderOC"}],"title":"CallUserProfileProviderOC","abstract":[{"type":"text","text":"\/\/\/ Profile provider of the ChatUIKit.Only available in Objective-C language."}],"navigatorTitle":[{"kind":"identifier","text":"CallUserProfileProviderOC"}],"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallUserProfileProviderOC","type":"topic","role":"symbol","url":"\/documentation\/easecalluikit\/calluserprofileprovideroc"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallUserProfileProviderOC/fetchProfiles(profileIds:completion:)":{"abstract":[{"type":"text","text":"Need to obtain the list display information on the current screen."}],"required":true,"kind":"symbol","title":"fetchProfiles(profileIds:completion:)","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallUserProfileProviderOC\/fetchProfiles(profileIds:completion:)","url":"\/documentation\/easecalluikit\/calluserprofileprovideroc\/fetchprofiles(profileids:completion:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"fetchProfiles","kind":"identifier"},{"text":"(","kind":"text"},{"text":"profileIds","kind":"externalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"], ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ([","kind":"text"},{"text":"CallProfileProtocol","kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseCallUIKit@objc(pl)CallProfileProtocol"},{"kind":"text","text":"]) -> "},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"kind":"text","text":")"}],"navigatorTitle":[{"text":"fetchProfilesWithProfileIds:completion:","kind":"identifier"}],"role":"symbol","type":"topic"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit":{"title":"EaseCallUIKit","type":"topic","url":"\/documentation\/easecalluikit","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit","abstract":[],"role":"collection","kind":"symbol"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallProfileProtocol":{"url":"\/documentation\/easecalluikit\/callprofileprotocol","role":"symbol","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallProfileProtocol","navigatorTitle":[{"kind":"identifier","text":"CallProfileProtocol"}],"abstract":[],"title":"CallProfileProtocol","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CallProfileProtocol"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"path":"\/metadata\/title","value":"fetchProfilesWithProfileIds:completion:","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"value":[{"text":"- ","kind":"text"},{"text":"fetchProfilesWithProfileIds:completion:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"fetchProfilesWithProfileIds:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSArray<NSString *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" *) "},{"text":"profileIds","kind":"internalParam"},{"kind":"text","text":" "},{"text":"completion:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":" (^","kind":"text"},{"kind":"text","text":")("},{"preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<id<CallProfileProtocol>>","kind":"typeIdentifier"},{"kind":"text","text":" * "},{"kind":"internalParam","text":""},{"kind":"text","text":")) "},{"text":"completion","kind":"internalParam"},{"kind":"text","text":";"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"name":"profileIds","content":[{"type":"paragraph","inlineContent":[{"text":"The corresponding conversation id string array.","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Callback,obtain Array of the "},{"code":"ChatUserProfileProtocol","type":"codeVoice"},{"text":" object.","type":"text"}]}],"name":"completion"}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallUserProfileProviderOC\/title","value":"CallUserProfileProviderOC"},{"value":[{"text":"CallUserProfileProviderOC","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallUserProfileProviderOC\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallUserProfileProviderOC\/navigatorTitle","value":[{"text":"CallUserProfileProviderOC","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallUserProfileProviderOC~1fetchProfiles(profileIds:completion:)\/title","op":"replace","value":"fetchProfilesWithProfileIds:completion:"},{"value":[{"text":"- ","kind":"text"},{"text":"fetchProfilesWithProfileIds:completion:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallUserProfileProviderOC~1fetchProfiles(profileIds:completion:)\/fragments"},{"value":"CallProfileProtocol","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallProfileProtocol\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallProfileProtocol\/fragments","value":[{"text":"CallProfileProtocol","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallProfileProtocol\/navigatorTitle","value":[{"kind":"identifier","text":"CallProfileProtocol"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}