{"abstract":[{"text":"Called when a call is received.","type":"text"}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallServiceListener"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"optional","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"onReceivedCall"},{"text":"(","kind":"text"},{"text":"callType","kind":"externalParam"},{"kind":"text","text":": "},{"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallType","preciseIdentifier":"c:@M@EaseCallUIKit@E@CallType","kind":"typeIdentifier","text":"CallType"},{"kind":"text","text":", "},{"kind":"externalParam","text":"userId"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"extensionInfo","kind":"externalParam"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":" : "},{"text":"Any","kind":"keyword"},{"text":"]?)","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]},{"parameters":[{"name":"callType","content":[{"inlineContent":[{"type":"text","text":"The type of call that was received, such as single audio or single video."},{"isActive":true,"type":"reference","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallType"}],"type":"paragraph"}]},{"name":"userId","content":[{"inlineContent":[{"type":"text","text":"The ID of the user who initiated the call."}],"type":"paragraph"}]},{"name":"extensionInfo","content":[{"inlineContent":[{"text":"Optional additional information about the call, such as custom data or metadata.","type":"text"}],"type":"paragraph"}]}],"kind":"parameters"}],"identifier":{"url":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallServiceListener\/onReceivedCall(callType:userId:extensionInfo:)","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/easecalluikit\/callservicelistener\/onreceivedcall(calltype:userid:extensioninfo:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/easecalluikit\/callservicelistener\/onreceivedcall(calltype:userid:extensioninfo:)"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"modules":[{"name":"EaseCallUIKit"}],"navigatorTitle":[{"text":"onReceivedCallWithCallType:userId:extensionInfo:","kind":"identifier"}],"required":true,"roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onReceivedCall","kind":"identifier"},{"text":"(","kind":"text"},{"text":"callType","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"CallType","preciseIdentifier":"c:@M@EaseCallUIKit@E@CallType"},{"kind":"text","text":", "},{"text":"userId","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"extensionInfo","kind":"externalParam"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"text":"Any","kind":"keyword"},{"text":"]?)","kind":"text"}],"role":"symbol","externalID":"c:@M@EaseCallUIKit@objc(pl)CallServiceListener(im)onReceivedCallWithCallType:userId:extensionInfo:","title":"onReceivedCall(callType:userId:extensionInfo:)","symbolKind":"method"},"references":{"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit":{"title":"EaseCallUIKit","type":"topic","url":"\/documentation\/easecalluikit","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit","abstract":[],"role":"collection","kind":"symbol"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallType":{"kind":"symbol","title":"CallType","navigatorTitle":[{"text":"CallType","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallType","url":"\/documentation\/easecalluikit\/calltype","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CallType"}],"abstract":[]},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallServiceListener":{"abstract":[],"kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"CallServiceListener"}],"url":"\/documentation\/easecalluikit\/callservicelistener","title":"CallServiceListener","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CallServiceListener"}],"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallServiceListener","role":"symbol"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallServiceListener/onReceivedCall(callType:userId:extensionInfo:)":{"abstract":[{"type":"text","text":"Called when a call is received."}],"kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"onReceivedCall"},{"kind":"text","text":"("},{"text":"callType","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@EaseCallUIKit@E@CallType","kind":"typeIdentifier","text":"CallType"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"userId"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"extensionInfo","kind":"externalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]?)"}],"url":"\/documentation\/easecalluikit\/callservicelistener\/onreceivedcall(calltype:userid:extensioninfo:)","title":"onReceivedCall(callType:userId:extensionInfo:)","type":"topic","required":true,"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallServiceListener\/onReceivedCall(callType:userId:extensionInfo:)","navigatorTitle":[{"kind":"identifier","text":"onReceivedCallWithCallType:userId:extensionInfo:"}],"role":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"value":"onReceivedCallWithCallType:userId:extensionInfo:","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"onReceivedCallWithCallType:userId:extensionInfo:","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"onReceivedCallWithCallType:","kind":"identifier"},{"kind":"text","text":"("},{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallType","preciseIdentifier":"c:@M@EaseCallUIKit@E@CallType","kind":"typeIdentifier","text":"CallType"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"callType"},{"kind":"text","text":" "},{"kind":"identifier","text":"userId:"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"userId"},{"text":" ","kind":"text"},{"text":"extensionInfo:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSDictionary<NSString *,id>","preciseIdentifier":"c:Q$objc(cs)NSDictionary"},{"kind":"text","text":" *) "},{"text":"extensionInfo","kind":"internalParam"},{"text":";","kind":"text"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"The type of call that was received, such as single audio or single video.","type":"text"},{"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallType","isActive":true,"type":"reference"}]}],"name":"callType"},{"name":"userId","content":[{"inlineContent":[{"text":"The ID of the user who initiated the call.","type":"text"}],"type":"paragraph"}]},{"name":"extensionInfo","content":[{"inlineContent":[{"type":"text","text":"Optional additional information about the call, such as custom data or metadata."}],"type":"paragraph"}]}]},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallType\/title","value":"CallType"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallType\/fragments","op":"replace","value":[{"text":"CallType","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallType\/navigatorTitle","value":[{"kind":"identifier","text":"CallType"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallServiceListener\/title","value":"CallServiceListener"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallServiceListener\/fragments","value":[{"kind":"identifier","text":"CallServiceListener"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallServiceListener\/navigatorTitle","value":[{"kind":"identifier","text":"CallServiceListener"}]},{"value":"onReceivedCallWithCallType:userId:extensionInfo:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallServiceListener~1onReceivedCall(callType:userId:extensionInfo:)\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallServiceListener~1onReceivedCall(callType:userId:extensionInfo:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"onReceivedCallWithCallType:userId:extensionInfo:","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}