{"abstract":[{"text":"Called when a remote user joins the call.","type":"text"}],"metadata":{"modules":[{"name":"EaseCallUIKit"}],"navigatorTitle":[{"text":"remoteUserDidJoinedWithUserId:channelName:type:","kind":"identifier"}],"symbolKind":"method","role":"symbol","title":"remoteUserDidJoined(userId:channelName:type:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"remoteUserDidJoined"},{"kind":"text","text":"("},{"kind":"externalParam","text":"userId"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"channelName","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"type"},{"kind":"text","text":": "},{"text":"CallType","kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseCallUIKit@E@CallType"},{"kind":"text","text":")"}],"roleHeading":"Instance Method","externalID":"c:@M@EaseCallUIKit@objc(pl)CallServiceListener(im)remoteUserDidJoinedWithUserId:channelName:type:"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallServiceListener"]]},"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallServiceListener\/remoteUserDidJoined(userId:channelName:type:)"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"optional"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"remoteUserDidJoined","kind":"identifier"},{"kind":"text","text":"("},{"text":"userId","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":", ","kind":"text"},{"text":"channelName","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"type"},{"text":": ","kind":"text"},{"text":"CallType","kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseCallUIKit@E@CallType","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallType"},{"text":")","kind":"text"}],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The ID of the remote user who joined the call."}]}],"name":"userId"},{"name":"channelName","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The name of the channel where the call is taking place."}]}]},{"content":[{"inlineContent":[{"text":"The type of call that the remote user joined, such as single audio or single video.","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallType"}],"type":"paragraph"}],"name":"type"}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easecalluikit\/callservicelistener\/remoteuserdidjoined(userid:channelname:type:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easecalluikit\/callservicelistener\/remoteuserdidjoined(userid:channelname:type:)"]}],"references":{"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallType":{"kind":"symbol","title":"CallType","navigatorTitle":[{"text":"CallType","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallType","url":"\/documentation\/easecalluikit\/calltype","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CallType"}],"abstract":[]},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallServiceListener":{"abstract":[],"kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"CallServiceListener"}],"url":"\/documentation\/easecalluikit\/callservicelistener","title":"CallServiceListener","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CallServiceListener"}],"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallServiceListener","role":"symbol"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit":{"title":"EaseCallUIKit","type":"topic","url":"\/documentation\/easecalluikit","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit","abstract":[],"role":"collection","kind":"symbol"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallServiceListener/remoteUserDidJoined(userId:channelName:type:)":{"navigatorTitle":[{"text":"remoteUserDidJoinedWithUserId:channelName:type:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"remoteUserDidJoined"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"userId"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"channelName"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"type","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseCallUIKit@E@CallType","text":"CallType"},{"kind":"text","text":")"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallServiceListener\/remoteUserDidJoined(userId:channelName:type:)","role":"symbol","abstract":[{"text":"Called when a remote user joins the call.","type":"text"}],"type":"topic","url":"\/documentation\/easecalluikit\/callservicelistener\/remoteuserdidjoined(userid:channelname:type:)","title":"remoteUserDidJoined(userId:channelName:type:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"remoteUserDidJoinedWithUserId:channelName:type:"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"remoteUserDidJoinedWithUserId:channelName:type:"}]},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"text":"remoteUserDidJoinedWithUserId:","kind":"identifier"},{"kind":"text","text":"("},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"userId"},{"text":" ","kind":"text"},{"text":"channelName:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"channelName","kind":"internalParam"},{"kind":"text","text":" "},{"text":"type:","kind":"identifier"},{"kind":"text","text":"("},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CallType","kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseCallUIKit@E@CallType","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallType"},{"text":") ","kind":"text"},{"text":"type","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The ID of the remote user who joined the call."}]}],"name":"userId"},{"name":"channelName","content":[{"inlineContent":[{"text":"The name of the channel where the call is taking place.","type":"text"}],"type":"paragraph"}]},{"name":"type","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The type of call that the remote user joined, such as single audio or single video."},{"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallType","isActive":true,"type":"reference"}]}]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallType\/title","value":"CallType"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallType\/fragments","value":[{"kind":"identifier","text":"CallType"}]},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallType\/navigatorTitle","op":"replace","value":[{"text":"CallType","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallServiceListener\/title","value":"CallServiceListener","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallServiceListener\/fragments","op":"replace","value":[{"text":"CallServiceListener","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallServiceListener\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"CallServiceListener"}]},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallServiceListener~1remoteUserDidJoined(userId:channelName:type:)\/title","op":"replace","value":"remoteUserDidJoinedWithUserId:channelName:type:"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"remoteUserDidJoinedWithUserId:channelName:type:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallServiceListener~1remoteUserDidJoined(userId:channelName:type:)\/fragments"}]}]}