{"sections":[],"variants":[{"paths":["\/documentation\/easecalluikit\/userinfoview\/configure(nickname:isaudiomuted:displaymode:)"],"traits":[{"interfaceLanguage":"swift"}]}],"metadata":{"symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"configure","kind":"identifier"},{"text":"(","kind":"text"},{"text":"nickname","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"isAudioMuted","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"displayMode"},{"text":": ","kind":"text"},{"text":"UserInfoDisplayMode","kind":"typeIdentifier","preciseIdentifier":"s:13EaseCallUIKit19UserInfoDisplayModeO"},{"text":")","kind":"text"}],"role":"symbol","modules":[{"name":"EaseCallUIKit"}],"roleHeading":"Instance Method","extendedModule":"EaseCallUIKit","externalID":"s:13EaseCallUIKit12UserInfoViewC9configure8nickname12isAudioMuted11displayModeySS_SbAA0de7DisplayM0OtF","title":"configure(nickname:isAudioMuted:displayMode:)"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/UserInfoView"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/UserInfoView\/configure(nickname:isAudioMuted:displayMode:)"},"kind":"symbol","abstract":[{"type":"text","text":"配置视图的所有属性"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@","kind":"attribute"},{"kind":"attribute","preciseIdentifier":"s:ScM","text":"MainActor"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"configure","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"nickname"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"isAudioMuted","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"text":", ","kind":"text"},{"text":"displayMode","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/UserInfoDisplayMode","kind":"typeIdentifier","text":"UserInfoDisplayMode","preciseIdentifier":"s:13EaseCallUIKit19UserInfoDisplayModeO"},{"kind":"text","text":")"}],"platforms":["iOS"]}]}],"references":{"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit":{"title":"EaseCallUIKit","type":"topic","url":"\/documentation\/easecalluikit","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit","abstract":[],"role":"collection","kind":"symbol"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/UserInfoView/configure(nickname:isAudioMuted:displayMode:)":{"type":"topic","abstract":[{"type":"text","text":"配置视图的所有属性"}],"title":"configure(nickname:isAudioMuted:displayMode:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"configure","kind":"identifier"},{"text":"(","kind":"text"},{"text":"nickname","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"isAudioMuted"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"displayMode","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"UserInfoDisplayMode","preciseIdentifier":"s:13EaseCallUIKit19UserInfoDisplayModeO"},{"kind":"text","text":")"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/UserInfoView\/configure(nickname:isAudioMuted:displayMode:)","url":"\/documentation\/easecalluikit\/userinfoview\/configure(nickname:isaudiomuted:displaymode:)"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/UserInfoDisplayMode":{"role":"symbol","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/UserInfoDisplayMode","title":"UserInfoDisplayMode","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"UserInfoDisplayMode"}],"url":"\/documentation\/easecalluikit\/userinfodisplaymode","type":"topic","abstract":[],"navigatorTitle":[{"text":"UserInfoDisplayMode","kind":"identifier"}]},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/UserInfoView":{"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"UserInfoView","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/UserInfoView","navigatorTitle":[{"kind":"identifier","text":"UserInfoView"}],"url":"\/documentation\/easecalluikit\/userinfoview","title":"UserInfoView","abstract":[],"role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1UserInfoView\/title","op":"replace","value":"UserInfoView"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1UserInfoView\/fragments","value":[{"kind":"identifier","text":"UserInfoView"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1UserInfoView\/navigatorTitle","value":[{"kind":"identifier","text":"UserInfoView"}]}]}]}