{"abstract":[{"type":"text","text":"带动画的模式切换"}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/UserInfoView"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@","kind":"attribute"},{"kind":"attribute","text":"MainActor","preciseIdentifier":"s:ScM"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setDisplayMode","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"mode"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/UserInfoDisplayMode","text":"UserInfoDisplayMode","kind":"typeIdentifier","preciseIdentifier":"s:13EaseCallUIKit19UserInfoDisplayModeO"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"animated"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"platforms":["iOS"],"languages":["swift"]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/UserInfoView\/setDisplayMode(_:animated:)"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easecalluikit\/userinfoview\/setdisplaymode(_:animated:)"]}],"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"extendedModule":"EaseCallUIKit","title":"setDisplayMode(_:animated:)","modules":[{"name":"EaseCallUIKit"}],"externalID":"s:13EaseCallUIKit12UserInfoViewC14setDisplayMode_8animatedyAA0dehI0O_SbtF","roleHeading":"Instance Method","symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"setDisplayMode","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UserInfoDisplayMode","preciseIdentifier":"s:13EaseCallUIKit19UserInfoDisplayModeO"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"animated"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"text":")","kind":"text"}],"role":"symbol"},"references":{"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/UserInfoDisplayMode":{"role":"symbol","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/UserInfoDisplayMode","title":"UserInfoDisplayMode","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"UserInfoDisplayMode"}],"url":"\/documentation\/easecalluikit\/userinfodisplaymode","type":"topic","abstract":[],"navigatorTitle":[{"text":"UserInfoDisplayMode","kind":"identifier"}]},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/UserInfoView":{"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"UserInfoView","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/UserInfoView","navigatorTitle":[{"kind":"identifier","text":"UserInfoView"}],"url":"\/documentation\/easecalluikit\/userinfoview","title":"UserInfoView","abstract":[],"role":"symbol"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit":{"title":"EaseCallUIKit","type":"topic","url":"\/documentation\/easecalluikit","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit","abstract":[],"role":"collection","kind":"symbol"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/UserInfoView/setDisplayMode(_:animated:)":{"title":"setDisplayMode(_:animated:)","url":"\/documentation\/easecalluikit\/userinfoview\/setdisplaymode(_:animated:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setDisplayMode"},{"kind":"text","text":"("},{"text":"UserInfoDisplayMode","kind":"typeIdentifier","preciseIdentifier":"s:13EaseCallUIKit19UserInfoDisplayModeO"},{"kind":"text","text":", "},{"text":"animated","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"text":")","kind":"text"}],"abstract":[{"type":"text","text":"带动画的模式切换"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/UserInfoView\/setDisplayMode(_:animated:)"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1UserInfoView\/title","op":"replace","value":"UserInfoView"},{"value":[{"kind":"identifier","text":"UserInfoView"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1UserInfoView\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1UserInfoView\/navigatorTitle","value":[{"text":"UserInfoView","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}