{"kind":"symbol","sections":[],"variants":[{"paths":["\/documentation\/easecalluikit\/callnavigationbar"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easecalluikit\/callnavigationbar"]}],"identifier":{"url":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallNavigationBar","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit"]]},"abstract":[{"text":"Navigation  bar of the ChatUIKit.","type":"text"}],"metadata":{"role":"symbol","modules":[{"name":"EaseCallUIKit"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"CallNavigationBar"}],"roleHeading":"Class","navigatorTitle":[{"kind":"identifier","text":"CallNavigationBar"}],"externalID":"c:@M@EaseCallUIKit@objc(cs)CallNavigationBar","symbolKind":"class","title":"CallNavigationBar"},"topicSections":[{"identifiers":["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallNavigationBar\/init(coder:)","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallNavigationBar\/init(frame:)","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallNavigationBar\/init(show:showLeftItem:textAlignment:placeHolder:avatarURL:rightImages:hiddenAvatar:nearStatusBar:)","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallNavigationBar\/init(show:textAlignment:rightTitle:)"],"anchor":"Initializers","title":"Initializers","generated":true},{"generated":true,"identifiers":["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallNavigationBar\/avatar","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallNavigationBar\/avatarURL","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallNavigationBar\/backImage","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallNavigationBar\/cancel","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallNavigationBar\/clickClosure","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallNavigationBar\/detail","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallNavigationBar\/editMode","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallNavigationBar\/layout","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallNavigationBar\/leftItem","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallNavigationBar\/nearStatusBar","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallNavigationBar\/originalRenderRightImage","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallNavigationBar\/rightImages","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallNavigationBar\/rightItem","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallNavigationBar\/rightItems","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallNavigationBar\/separateLine","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallNavigationBar\/showLeft","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallNavigationBar\/status","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallNavigationBar\/subtitle","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallNavigationBar\/title","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallNavigationBar\/titleAttribute","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallNavigationBar\/titleLabel","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallNavigationBar\/titleOriginFrame"],"title":"Instance Properties","anchor":"Instance-Properties"},{"generated":true,"anchor":"Instance-Methods","title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallNavigationBar\/addGesture()","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallNavigationBar\/buttonAction(sender:)","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallNavigationBar\/clickAction(gesture:)","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallNavigationBar\/createAvatarStatus()","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallNavigationBar\/updateRightItems(images:original:)"]},{"generated":true,"anchor":"Default-Implementations","title":"Default Implementations","identifiers":["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallNavigationBar\/ThemeSwitchProtocol-Implementations","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallNavigationBar\/UICollectionViewDataSource-Implementations","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallNavigationBar\/UICollectionViewDelegate-Implementations"]}],"relationshipsSections":[{"identifiers":["doc:\/\/org.cocoapods.EaseCallUIKit\/objc(cs)UIView"],"title":"Inherits From","kind":"relationships","type":"inheritsFrom"},{"identifiers":["doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)NSCoding","doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)NSObject","doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)CALayerDelegate","doc:\/\/org.cocoapods.EaseCallUIKit\/s7CVarArgP","doc:\/\/org.cocoapods.EaseCallUIKit\/s8CopyableP","doc:\/\/org.cocoapods.EaseCallUIKit\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.EaseCallUIKit\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.EaseCallUIKit\/SQ","doc:\/\/org.cocoapods.EaseCallUIKit\/SH","doc:\/\/org.cocoapods.EaseCallUIKit\/s8SendableP","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/ThemeSwitchProtocol","doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)UIAccessibilityIdentification","doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)UIAppearance","doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)UIAppearanceContainer","doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)UICollectionViewDataSource","doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)UICollectionViewDelegate","doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)UICoordinateSpace","doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)UIDynamicItem","doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)UIFocusEnvironment","doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)UIFocusItem","doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)UIFocusItemContainer","doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)UILargeContentViewerItem","doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)UIPopoverPresentationControllerSourceItem","doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)UIResponderStandardEditActions","doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)UIScrollViewDelegate","doc:\/\/org.cocoapods.EaseCallUIKit\/5UIKit23UITraitChangeObservableP","doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)UITraitEnvironment","doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)UIUserActivityRestoring"],"kind":"relationships","type":"conformsTo","title":"Conforms To"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objcMembers","kind":"attribute"},{"kind":"text","text":" "},{"text":"@","kind":"attribute"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"CallNavigationBar","kind":"identifier"}]}],"kind":"declarations"}],"references":{"doc://org.cocoapods.EaseCallUIKit/objc(pl)UIAppearance":{"title":"UIKit.UIAppearance","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)UIAppearance"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallNavigationBar/status":{"type":"topic","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallNavigationBar\/status","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"status","kind":"identifier"},{"kind":"text","text":": "},{"text":"UIImageView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImageView"}],"url":"\/documentation\/easecalluikit\/callnavigationbar\/status","navigatorTitle":[{"text":"status","kind":"identifier"}],"title":"status","abstract":[],"kind":"symbol"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallNavigationBar/nearStatusBar":{"type":"topic","navigatorTitle":[{"text":"nearStatusBar","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallNavigationBar\/nearStatusBar","title":"nearStatusBar","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"nearStatusBar"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"url":"\/documentation\/easecalluikit\/callnavigationbar\/nearstatusbar","abstract":[]},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallNavigationBar/rightItems":{"type":"topic","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallNavigationBar\/rightItems","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"rightItems"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UICollectionView","text":"UICollectionView","kind":"typeIdentifier"}],"url":"\/documentation\/easecalluikit\/callnavigationbar\/rightitems","navigatorTitle":[{"text":"rightItems","kind":"identifier"}],"title":"rightItems","abstract":[],"kind":"symbol"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallNavigationBar/leftItem":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"leftItem"}],"kind":"symbol","title":"leftItem","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallNavigationBar\/leftItem","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"leftItem","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIButton","text":"UIButton","kind":"typeIdentifier"}],"url":"\/documentation\/easecalluikit\/callnavigationbar\/leftitem","abstract":[]},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallNavigationBar/originalRenderRightImage":{"type":"topic","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallNavigationBar\/originalRenderRightImage","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"originalRenderRightImage","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"url":"\/documentation\/easecalluikit\/callnavigationbar\/originalrenderrightimage","navigatorTitle":[{"kind":"identifier","text":"originalRenderRightImage"}],"title":"originalRenderRightImage","abstract":[],"kind":"symbol"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallNavigationBar/init(frame:)":{"type":"topic","navigatorTitle":[{"text":"initWithFrame:","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallNavigationBar\/init(frame:)","title":"init(frame:)","role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"frame","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect","text":"CGRect"},{"text":")","kind":"text"}],"url":"\/documentation\/easecalluikit\/callnavigationbar\/init(frame:)","abstract":[]},"doc://org.cocoapods.EaseCallUIKit/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/s28CustomDebugStringConvertibleP","type":"unresolvable","title":"Swift.CustomDebugStringConvertible"},"doc://org.cocoapods.EaseCallUIKit/s8CopyableP":{"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/s8CopyableP","type":"unresolvable","title":"Swift.Copyable"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallNavigationBar/subtitle":{"abstract":[{"text":"Detail’s text.","type":"text"}],"kind":"symbol","title":"subtitle","url":"\/documentation\/easecalluikit\/callnavigationbar\/subtitle","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallNavigationBar\/subtitle","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"subtitle","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"navigatorTitle":[{"kind":"identifier","text":"subtitle"}],"role":"symbol","type":"topic"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallNavigationBar/updateRightItems(images:original:)":{"abstract":[],"type":"topic","kind":"symbol","title":"updateRightItems(images:original:)","navigatorTitle":[{"text":"updateRightItemsWithImages:original:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"updateRightItems"},{"text":"(","kind":"text"},{"text":"images","kind":"externalParam"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"},{"text":"], ","kind":"text"},{"kind":"externalParam","text":"original"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":")","kind":"text"}],"role":"symbol","url":"\/documentation\/easecalluikit\/callnavigationbar\/updaterightitems(images:original:)","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallNavigationBar\/updateRightItems(images:original:)"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallNavigationBar/UICollectionViewDelegate-Implementations":{"type":"topic","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallNavigationBar\/UICollectionViewDelegate-Implementations","role":"collectionGroup","url":"\/documentation\/easecalluikit\/callnavigationbar\/uicollectionviewdelegate-implementations","title":"UICollectionViewDelegate Implementations","abstract":[],"kind":"article"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallNavigationBar/showLeft":{"navigatorTitle":[{"text":"showLeft","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallNavigationBar\/showLeft","url":"\/documentation\/easecalluikit\/callnavigationbar\/showleft","abstract":[],"kind":"symbol","role":"symbol","title":"showLeft","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"showLeft"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}]},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallNavigationBar/rightImages":{"type":"topic","title":"rightImages","kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallNavigationBar\/rightImages","role":"symbol","navigatorTitle":[{"text":"rightImages","kind":"identifier"}],"abstract":[],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"rightImages"},{"text":": [","kind":"text"},{"text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage","kind":"typeIdentifier"},{"kind":"text","text":"]"}],"url":"\/documentation\/easecalluikit\/callnavigationbar\/rightimages"},"doc://org.cocoapods.EaseCallUIKit/objc(pl)NSCoding":{"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)NSCoding","type":"unresolvable","title":"Foundation.NSCoding"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallNavigationBar/cancel":{"role":"symbol","title":"cancel","url":"\/documentation\/easecalluikit\/callnavigationbar\/cancel","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"cancel","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIButton","text":"UIButton"}],"type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"cancel"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallNavigationBar\/cancel"},"doc://org.cocoapods.EaseCallUIKit/objc(pl)UITraitEnvironment":{"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)UITraitEnvironment","type":"unresolvable","title":"UIKit.UITraitEnvironment"},"doc://org.cocoapods.EaseCallUIKit/objc(pl)UICollectionViewDataSource":{"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)UICollectionViewDataSource","type":"unresolvable","title":"UICollectionViewDataSource"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallNavigationBar/titleAttribute":{"type":"topic","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallNavigationBar\/titleAttribute","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"titleAttribute"},{"text":": ","kind":"text"},{"text":"NSAttributedString","preciseIdentifier":"c:objc(cs)NSAttributedString","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"url":"\/documentation\/easecalluikit\/callnavigationbar\/titleattribute","navigatorTitle":[{"text":"titleAttribute","kind":"identifier"}],"title":"titleAttribute","abstract":[{"type":"text","text":"Title kind of the "},{"code":"NSAttributedString","type":"codeVoice"},{"text":".","type":"text"}],"kind":"symbol"},"doc://org.cocoapods.EaseCallUIKit/objc(pl)UICoordinateSpace":{"title":"UIKit.UICoordinateSpace","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)UICoordinateSpace"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallNavigationBar/clickClosure":{"type":"topic","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallNavigationBar\/clickClosure","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"clickClosure","kind":"identifier"},{"text":": ((","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseCallUIKit@E@ChatNavigationBarClickEvent","text":"ChatNavigationBarClickEvent"},{"text":", ","kind":"text"},{"text":"IndexPath","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation9IndexPathV"},{"kind":"text","text":"?) -> ())?"}],"url":"\/documentation\/easecalluikit\/callnavigationbar\/clickclosure","navigatorTitle":[{"text":"clickClosure","kind":"identifier"}],"title":"clickClosure","abstract":[],"kind":"symbol"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallNavigationBar/ThemeSwitchProtocol-Implementations":{"title":"ThemeSwitchProtocol Implementations","abstract":[],"kind":"article","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallNavigationBar\/ThemeSwitchProtocol-Implementations","type":"topic","role":"collectionGroup","url":"\/documentation\/easecalluikit\/callnavigationbar\/themeswitchprotocol-implementations"},"doc://org.cocoapods.EaseCallUIKit/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/s23CustomStringConvertibleP"},"doc://org.cocoapods.EaseCallUIKit/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallNavigationBar/layout":{"navigatorTitle":[{"kind":"identifier","text":"layout"}],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"layout"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UICollectionViewFlowLayout","text":"UICollectionViewFlowLayout"}],"type":"topic","kind":"symbol","title":"layout","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallNavigationBar\/layout","url":"\/documentation\/easecalluikit\/callnavigationbar\/layout"},"doc://org.cocoapods.EaseCallUIKit/objc(pl)UIFocusItemContainer":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)UIFocusItemContainer","title":"UIKit.UIFocusItemContainer"},"doc://org.cocoapods.EaseCallUIKit/objc(pl)UIAppearanceContainer":{"title":"UIKit.UIAppearanceContainer","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)UIAppearanceContainer"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit":{"title":"EaseCallUIKit","type":"topic","url":"\/documentation\/easecalluikit","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit","abstract":[],"role":"collection","kind":"symbol"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallNavigationBar/init(coder:)":{"type":"topic","navigatorTitle":[{"text":"initWithCoder:","kind":"identifier"}],"kind":"symbol","title":"init(coder:)","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallNavigationBar\/init(coder:)","role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"?("},{"text":"coder","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSCoder","text":"NSCoder"},{"text":")","kind":"text"}],"url":"\/documentation\/easecalluikit\/callnavigationbar\/init(coder:)","abstract":[]},"doc://org.cocoapods.EaseCallUIKit/objc(pl)UIPasteConfigurationSupporting":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)UIPasteConfigurationSupporting","title":"UIKit.UIPasteConfigurationSupporting"},"doc://org.cocoapods.EaseCallUIKit/objc(pl)UIPopoverPresentationControllerSourceItem":{"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)UIPopoverPresentationControllerSourceItem","title":"UIKit.UIPopoverPresentationControllerSourceItem","type":"unresolvable"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallNavigationBar/editMode":{"type":"topic","abstract":[{"type":"text","text":"Entry edit mode or not."}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallNavigationBar\/editMode","role":"symbol","url":"\/documentation\/easecalluikit\/callnavigationbar\/editmode","navigatorTitle":[{"text":"editMode","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"editMode","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"title":"editMode"},"doc://org.cocoapods.EaseCallUIKit/SQ":{"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://org.cocoapods.EaseCallUIKit/objc(pl)UIScrollViewDelegate":{"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)UIScrollViewDelegate","title":"UIKit.UIScrollViewDelegate","type":"unresolvable"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallNavigationBar/createAvatarStatus()":{"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"createAvatarStatus","kind":"identifier"},{"text":"() -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImageView","text":"UIImageView"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallNavigationBar\/createAvatarStatus()","navigatorTitle":[{"text":"createAvatarStatus","kind":"identifier"}],"url":"\/documentation\/easecalluikit\/callnavigationbar\/createavatarstatus()","title":"createAvatarStatus()","abstract":[],"role":"symbol"},"doc://org.cocoapods.EaseCallUIKit/objc(pl)UILargeContentViewerItem":{"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)UILargeContentViewerItem","title":"UIKit.UILargeContentViewerItem","type":"unresolvable"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallNavigationBar/rightItem":{"kind":"symbol","abstract":[],"title":"rightItem","type":"topic","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallNavigationBar\/rightItem","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"rightItem"},{"kind":"text","text":": "},{"text":"UIButton","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIButton"}],"navigatorTitle":[{"text":"rightItem","kind":"identifier"}],"url":"\/documentation\/easecalluikit\/callnavigationbar\/rightitem"},"doc://org.cocoapods.EaseCallUIKit/objc(pl)UIFocusItem":{"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)UIFocusItem","title":"UIKit.UIFocusItem","type":"unresolvable"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallNavigationBar/avatarURL":{"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallNavigationBar\/avatarURL","type":"topic","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"avatarURL","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"url":"\/documentation\/easecalluikit\/callnavigationbar\/avatarurl","navigatorTitle":[{"kind":"identifier","text":"avatarURL"}],"title":"avatarURL","abstract":[{"text":"Avatar url.Only available when using initialization method with avatar.","type":"text"}],"kind":"symbol"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallNavigationBar":{"type":"topic","title":"CallNavigationBar","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallNavigationBar","url":"\/documentation\/easecalluikit\/callnavigationbar","role":"symbol","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CallNavigationBar"}],"navigatorTitle":[{"text":"CallNavigationBar","kind":"identifier"}],"abstract":[{"text":"Navigation  bar of the ChatUIKit.","type":"text"}]},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallNavigationBar/avatar":{"title":"avatar","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallNavigationBar\/avatar","role":"symbol","url":"\/documentation\/easecalluikit\/callnavigationbar\/avatar","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"avatar","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@EaseCallUIKit@objc(cs)ImageView","kind":"typeIdentifier","text":"ImageView"}],"navigatorTitle":[{"text":"avatar","kind":"identifier"}],"type":"topic","kind":"symbol","abstract":[]},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallNavigationBar/buttonAction(sender:)":{"kind":"symbol","abstract":[],"title":"buttonAction(sender:)","type":"topic","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallNavigationBar\/buttonAction(sender:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"buttonAction"},{"kind":"text","text":"("},{"text":"sender","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"UIButton","preciseIdentifier":"c:objc(cs)UIButton"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"buttonActionWithSender:"}],"url":"\/documentation\/easecalluikit\/callnavigationbar\/buttonaction(sender:)"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallNavigationBar/init(show:showLeftItem:textAlignment:placeHolder:avatarURL:rightImages:hiddenAvatar:nearStatusBar:)":{"type":"topic","title":"init(show:showLeftItem:textAlignment:placeHolder:avatarURL:rightImages:hiddenAvatar:nearStatusBar:)","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallNavigationBar\/init(show:showLeftItem:textAlignment:placeHolder:avatarURL:rightImages:hiddenAvatar:nearStatusBar:)","url":"\/documentation\/easecalluikit\/callnavigationbar\/init(show:showleftitem:textalignment:placeholder:avatarurl:rightimages:hiddenavatar:nearstatusbar:)","role":"symbol","kind":"symbol","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"show","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CGRect","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"showLeftItem"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"textAlignment","kind":"externalParam"},{"kind":"text","text":": "},{"text":"NSTextAlignment","kind":"typeIdentifier","preciseIdentifier":"c:@E@NSTextAlignment"},{"text":", ","kind":"text"},{"text":"placeHolder","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage"},{"text":"?, ","kind":"text"},{"text":"avatarURL","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"rightImages","kind":"externalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage","kind":"typeIdentifier"},{"text":"], ","kind":"text"},{"kind":"externalParam","text":"hiddenAvatar"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":", "},{"text":"nearStatusBar","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"initWithShow:showLeftItem:textAlignment:placeHolder:avatarURL:rightImages:hiddenAvatar:nearStatusBar:","kind":"identifier"}],"abstract":[{"type":"text","text":"EaseChatNavigationBar init method with right items kind of images."}]},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallNavigationBar/titleLabel":{"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallNavigationBar\/titleLabel","type":"topic","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"titleLabel","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UILabel","text":"UILabel"}],"url":"\/documentation\/easecalluikit\/callnavigationbar\/titlelabel","navigatorTitle":[{"kind":"identifier","text":"titleLabel"}],"title":"titleLabel","abstract":[],"kind":"symbol"},"doc://org.cocoapods.EaseCallUIKit/objc(pl)UIResponderStandardEditActions":{"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)UIResponderStandardEditActions","title":"UIKit.UIResponderStandardEditActions","type":"unresolvable"},"doc://org.cocoapods.EaseCallUIKit/objc(pl)UICollectionViewDelegate":{"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)UICollectionViewDelegate","title":"UICollectionViewDelegate","type":"unresolvable"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallNavigationBar/titleOriginFrame":{"abstract":[],"url":"\/documentation\/easecalluikit\/callnavigationbar\/titleoriginframe","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"titleOriginFrame"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@S@CGRect","kind":"typeIdentifier","text":"CGRect"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallNavigationBar\/titleOriginFrame","title":"titleOriginFrame","type":"topic","navigatorTitle":[{"kind":"identifier","text":"titleOriginFrame"}]},"doc://org.cocoapods.EaseCallUIKit/s7CVarArgP":{"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/s7CVarArgP","title":"Swift.CVarArg","type":"unresolvable"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallNavigationBar/clickAction(gesture:)":{"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"clickAction"},{"kind":"text","text":"("},{"kind":"externalParam","text":"gesture"},{"kind":"text","text":": "},{"text":"UITapGestureRecognizer","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UITapGestureRecognizer"},{"text":")","kind":"text"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallNavigationBar\/clickAction(gesture:)","navigatorTitle":[{"text":"clickActionWithGesture:","kind":"identifier"}],"url":"\/documentation\/easecalluikit\/callnavigationbar\/clickaction(gesture:)","title":"clickAction(gesture:)","abstract":[],"role":"symbol"},"doc://org.cocoapods.EaseCallUIKit/objc(pl)UIAccessibilityIdentification":{"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)UIAccessibilityIdentification","title":"UIKit.UIAccessibilityIdentification","type":"unresolvable"},"doc://org.cocoapods.EaseCallUIKit/objc(pl)UIDynamicItem":{"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)UIDynamicItem","title":"UIKit.UIDynamicItem","type":"unresolvable"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallNavigationBar/UICollectionViewDataSource-Implementations":{"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallNavigationBar\/UICollectionViewDataSource-Implementations","type":"topic","role":"collectionGroup","url":"\/documentation\/easecalluikit\/callnavigationbar\/uicollectionviewdatasource-implementations","title":"UICollectionViewDataSource Implementations","abstract":[],"kind":"article"},"doc://org.cocoapods.EaseCallUIKit/objc(pl)UIUserActivityRestoring":{"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)UIUserActivityRestoring","title":"UIKit.UIUserActivityRestoring","type":"unresolvable"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallNavigationBar/title":{"title":"title","kind":"symbol","role":"symbol","url":"\/documentation\/easecalluikit\/callnavigationbar\/title","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"title","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?"}],"navigatorTitle":[{"kind":"identifier","text":"title"}],"type":"topic","abstract":[{"type":"text","text":"TitleLabel’s text."}],"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallNavigationBar\/title"},"doc://org.cocoapods.EaseCallUIKit/s8SendableP":{"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/s8SendableP","title":"Swift.Sendable","type":"unresolvable"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallNavigationBar/init(show:textAlignment:rightTitle:)":{"navigatorTitle":[{"kind":"identifier","text":"initWithShow:textAlignment:rightTitle:"}],"url":"\/documentation\/easecalluikit\/callnavigationbar\/init(show:textalignment:righttitle:)","kind":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"text":"show","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect","text":"CGRect"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"textAlignment"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@NSTextAlignment","text":"NSTextAlignment"},{"kind":"text","text":", "},{"text":"rightTitle","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?)"}],"title":"init(show:textAlignment:rightTitle:)","abstract":[{"type":"text","text":"EaseChatNavigationBar init method with right item kind of text."}],"type":"topic","role":"symbol","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallNavigationBar\/init(show:textAlignment:rightTitle:)"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallNavigationBar/addGesture()":{"kind":"symbol","navigatorTitle":[{"text":"addGesture","kind":"identifier"}],"abstract":[],"title":"addGesture()","type":"topic","url":"\/documentation\/easecalluikit\/callnavigationbar\/addgesture()","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"addGesture"},{"kind":"text","text":"()"}],"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallNavigationBar\/addGesture()"},"doc://org.cocoapods.EaseCallUIKit/5UIKit23UITraitChangeObservableP":{"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/5UIKit23UITraitChangeObservableP","title":"UIKit.UITraitChangeObservable","type":"unresolvable"},"doc://org.cocoapods.EaseCallUIKit/SH":{"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/ThemeSwitchProtocol":{"type":"topic","url":"\/documentation\/easecalluikit\/themeswitchprotocol","kind":"symbol","navigatorTitle":[{"text":"ThemeSwitchProtocol","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/ThemeSwitchProtocol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"ThemeSwitchProtocol","kind":"identifier"}],"title":"ThemeSwitchProtocol","abstract":[{"text":"When the system theme changes, you can use this static method to switch between the light and dark themes of the ease chat UIKit.","type":"text"}]},"doc://org.cocoapods.EaseCallUIKit/objc(pl)UIActivityItemsConfigurationProviding":{"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)UIActivityItemsConfigurationProviding","title":"UIKit.UIActivityItemsConfigurationProviding","type":"unresolvable"},"doc://org.cocoapods.EaseCallUIKit/objc(pl)CALayerDelegate":{"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)CALayerDelegate","title":"QuartzCore.CALayerDelegate","type":"unresolvable"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallNavigationBar/backImage":{"title":"backImage","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallNavigationBar\/backImage","role":"symbol","url":"\/documentation\/easecalluikit\/callnavigationbar\/backimage","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"backImage","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIImage","kind":"typeIdentifier","text":"UIImage"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"backImage","kind":"identifier"}],"type":"topic","kind":"symbol","abstract":[]},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallNavigationBar/separateLine":{"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallNavigationBar\/separateLine","type":"topic","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"separateLine"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIView","text":"UIView","kind":"typeIdentifier"}],"url":"\/documentation\/easecalluikit\/callnavigationbar\/separateline","navigatorTitle":[{"kind":"identifier","text":"separateLine"}],"title":"separateLine","abstract":[],"kind":"symbol"},"doc://org.cocoapods.EaseCallUIKit/objc(pl)UIFocusEnvironment":{"title":"UIKit.UIFocusEnvironment","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)UIFocusEnvironment","type":"unresolvable"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallNavigationBar/detail":{"abstract":[],"type":"topic","kind":"symbol","title":"detail","navigatorTitle":[{"text":"detail","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"detail","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UILabel","text":"UILabel"}],"role":"symbol","url":"\/documentation\/easecalluikit\/callnavigationbar\/detail","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallNavigationBar\/detail"},"doc://org.cocoapods.EaseCallUIKit/objc(cs)UIView":{"title":"UIView","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/objc(cs)UIView","type":"unresolvable"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","value":"Class","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"CallNavigationBar"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"CallNavigationBar","kind":"identifier"}]},{"path":"\/metadata\/navigatorTitle","value":[{"text":"CallNavigationBar","kind":"identifier"}],"op":"replace"},{"value":[{"generated":true,"anchor":"Instance-Properties","title":"Instance Properties","identifiers":["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallNavigationBar\/avatar","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallNavigationBar\/avatarURL","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallNavigationBar\/backImage","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallNavigationBar\/cancel","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallNavigationBar\/clickClosure","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallNavigationBar\/detail","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallNavigationBar\/editMode","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallNavigationBar\/layout","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallNavigationBar\/leftItem","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallNavigationBar\/nearStatusBar","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallNavigationBar\/originalRenderRightImage","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallNavigationBar\/rightImages","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallNavigationBar\/rightItem","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallNavigationBar\/rightItems","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallNavigationBar\/separateLine","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallNavigationBar\/showLeft","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallNavigationBar\/status","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallNavigationBar\/subtitle","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallNavigationBar\/title","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallNavigationBar\/titleAttribute","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallNavigationBar\/titleLabel","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallNavigationBar\/titleOriginFrame"]},{"identifiers":["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallNavigationBar\/addGesture()","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallNavigationBar\/buttonAction(sender:)","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallNavigationBar\/clickAction(gesture:)","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallNavigationBar\/createAvatarStatus()","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallNavigationBar\/init(coder:)","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallNavigationBar\/init(frame:)","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallNavigationBar\/init(show:showLeftItem:textAlignment:placeHolder:avatarURL:rightImages:hiddenAvatar:nearStatusBar:)","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallNavigationBar\/init(show:textAlignment:rightTitle:)","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallNavigationBar\/updateRightItems(images:original:)"],"title":"Instance Methods","generated":true,"anchor":"Instance-Methods"},{"anchor":"Default-Implementations","generated":true,"identifiers":["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallNavigationBar\/ThemeSwitchProtocol-Implementations","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallNavigationBar\/UICollectionViewDataSource-Implementations","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallNavigationBar\/UICollectionViewDelegate-Implementations"],"title":"Default Implementations"}],"op":"replace","path":"\/topicSections"},{"path":"\/relationshipsSections","op":"replace","value":[{"type":"inheritsFrom","identifiers":["doc:\/\/org.cocoapods.EaseCallUIKit\/objc(cs)UIView"],"title":"Inherits From","kind":"relationships"},{"type":"conformsTo","identifiers":["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/ThemeSwitchProtocol","doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)UICollectionViewDataSource","doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)UICollectionViewDelegate"],"kind":"relationships","title":"Conforms To"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@interface"},{"text":" ","kind":"text"},{"text":"CallNavigationBar","kind":"identifier"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIView","text":"UIView"}]}]}},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallNavigationBar~1status\/title","value":"status","op":"replace"},{"op":"replace","value":[{"text":"status","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallNavigationBar~1status\/fragments"},{"op":"replace","value":"nearStatusBar","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallNavigationBar~1nearStatusBar\/title"},{"value":[{"kind":"identifier","text":"nearStatusBar"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallNavigationBar~1nearStatusBar\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallNavigationBar~1rightItems\/title","op":"replace","value":"rightItems"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallNavigationBar~1rightItems\/fragments","op":"replace","value":[{"text":"rightItems","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallNavigationBar~1leftItem\/title","value":"leftItem"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallNavigationBar~1leftItem\/fragments","value":[{"kind":"identifier","text":"leftItem"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallNavigationBar~1originalRenderRightImage\/title","op":"replace","value":"originalRenderRightImage"},{"value":[{"text":"originalRenderRightImage","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallNavigationBar~1originalRenderRightImage\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallNavigationBar~1init(frame:)\/title","value":"initWithFrame:","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallNavigationBar~1init(frame:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithFrame:","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallNavigationBar~1subtitle\/title","value":"subtitle"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallNavigationBar~1subtitle\/fragments","value":[{"kind":"identifier","text":"subtitle"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallNavigationBar~1updateRightItems(images:original:)\/title","value":"updateRightItemsWithImages:original:","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallNavigationBar~1updateRightItems(images:original:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"updateRightItemsWithImages:original:","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallNavigationBar~1showLeft\/title","value":"showLeft"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallNavigationBar~1showLeft\/fragments","op":"replace","value":[{"kind":"identifier","text":"showLeft"}]},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallNavigationBar~1rightImages\/title","op":"replace","value":"rightImages"},{"value":[{"kind":"identifier","text":"rightImages"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallNavigationBar~1rightImages\/fragments"},{"op":"replace","value":"cancel","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallNavigationBar~1cancel\/title"},{"op":"replace","value":[{"text":"cancel","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallNavigationBar~1cancel\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallNavigationBar~1titleAttribute\/title","value":"titleAttribute","op":"replace"},{"value":[{"text":"titleAttribute","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallNavigationBar~1titleAttribute\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallNavigationBar~1clickClosure\/title","value":"clickClosure"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallNavigationBar~1clickClosure\/fragments","value":[{"kind":"identifier","text":"clickClosure"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallNavigationBar~1layout\/title","op":"replace","value":"layout"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallNavigationBar~1layout\/fragments","op":"replace","value":[{"kind":"identifier","text":"layout"}]},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallNavigationBar~1init(coder:)\/title","op":"replace","value":"initWithCoder:"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithCoder:"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallNavigationBar~1init(coder:)\/fragments","op":"replace"},{"op":"replace","value":"editMode","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallNavigationBar~1editMode\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallNavigationBar~1editMode\/fragments","value":[{"kind":"identifier","text":"editMode"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallNavigationBar~1createAvatarStatus()\/title","value":"createAvatarStatus"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallNavigationBar~1createAvatarStatus()\/fragments","value":[{"kind":"text","text":"- "},{"text":"createAvatarStatus","kind":"identifier"}]},{"op":"replace","value":"rightItem","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallNavigationBar~1rightItem\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallNavigationBar~1rightItem\/fragments","value":[{"kind":"identifier","text":"rightItem"}]},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallNavigationBar~1avatarURL\/title","value":"avatarURL","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallNavigationBar~1avatarURL\/fragments","value":[{"kind":"identifier","text":"avatarURL"}]},{"value":"CallNavigationBar","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallNavigationBar\/title"},{"value":[{"text":"CallNavigationBar","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallNavigationBar\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallNavigationBar\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"CallNavigationBar"}]},{"value":"avatar","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallNavigationBar~1avatar\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallNavigationBar~1avatar\/fragments","op":"replace","value":[{"kind":"identifier","text":"avatar"}]},{"op":"replace","value":"buttonActionWithSender:","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallNavigationBar~1buttonAction(sender:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"buttonActionWithSender:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallNavigationBar~1buttonAction(sender:)\/fragments","op":"replace"},{"value":"initWithShow:showLeftItem:textAlignment:placeHolder:avatarURL:rightImages:hiddenAvatar:nearStatusBar:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallNavigationBar~1init(show:showLeftItem:textAlignment:placeHolder:avatarURL:rightImages:hiddenAvatar:nearStatusBar:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallNavigationBar~1init(show:showLeftItem:textAlignment:placeHolder:avatarURL:rightImages:hiddenAvatar:nearStatusBar:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithShow:showLeftItem:textAlignment:placeHolder:avatarURL:rightImages:hiddenAvatar:nearStatusBar:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallNavigationBar~1titleLabel\/title","value":"titleLabel"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallNavigationBar~1titleLabel\/fragments","value":[{"text":"titleLabel","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallNavigationBar~1titleOriginFrame\/title","op":"replace","value":"titleOriginFrame"},{"value":[{"kind":"identifier","text":"titleOriginFrame"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallNavigationBar~1titleOriginFrame\/fragments"},{"op":"replace","value":"clickActionWithGesture:","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallNavigationBar~1clickAction(gesture:)\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallNavigationBar~1clickAction(gesture:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"clickActionWithGesture:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallNavigationBar~1title\/title","value":"title","op":"replace"},{"value":[{"kind":"identifier","text":"title"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallNavigationBar~1title\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallNavigationBar~1init(show:textAlignment:rightTitle:)\/title","value":"initWithShow:textAlignment:rightTitle:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallNavigationBar~1init(show:textAlignment:rightTitle:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithShow:textAlignment:rightTitle:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallNavigationBar~1addGesture()\/title","value":"addGesture"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"addGesture"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallNavigationBar~1addGesture()\/fragments"},{"value":"ThemeSwitchProtocol","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1ThemeSwitchProtocol\/title"},{"value":[{"kind":"identifier","text":"ThemeSwitchProtocol"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1ThemeSwitchProtocol\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1ThemeSwitchProtocol\/navigatorTitle","value":[{"kind":"identifier","text":"ThemeSwitchProtocol"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallNavigationBar~1backImage\/title","value":"backImage"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallNavigationBar~1backImage\/fragments","value":[{"kind":"identifier","text":"backImage"}],"op":"replace"},{"value":"separateLine","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallNavigationBar~1separateLine\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallNavigationBar~1separateLine\/fragments","op":"replace","value":[{"kind":"identifier","text":"separateLine"}]},{"op":"replace","value":"detail","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallNavigationBar~1detail\/title"},{"value":[{"text":"detail","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallNavigationBar~1detail\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}