{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"CallKitConfig"}],"platforms":["iOS"]}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit"]]},"metadata":{"modules":[{"name":"EaseCallUIKit"}],"role":"symbol","title":"CallKitConfig","navigatorTitle":[{"text":"CallKitConfig","kind":"identifier"}],"roleHeading":"Class","externalID":"c:@M@EaseCallUIKit@objc(cs)CallKitConfig","symbolKind":"class","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"CallKitConfig","kind":"identifier"}]},"relationshipsSections":[{"identifiers":["doc:\/\/org.cocoapods.EaseCallUIKit\/objc(cs)NSObject"],"title":"Inherits From","type":"inheritsFrom","kind":"relationships"},{"identifiers":["doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)NSObject","doc:\/\/org.cocoapods.EaseCallUIKit\/s7CVarArgP","doc:\/\/org.cocoapods.EaseCallUIKit\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.EaseCallUIKit\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.EaseCallUIKit\/SQ","doc:\/\/org.cocoapods.EaseCallUIKit\/SH"],"type":"conformsTo","title":"Conforms To","kind":"relationships"}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easecalluikit\/callkitconfig"]},{"paths":["\/documentation\/easecalluikit\/callkitconfig"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitConfig","interfaceLanguage":"swift"},"topicSections":[{"anchor":"Instance-Properties","generated":true,"identifiers":["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitConfig\/enablePIPOn1V1VideoScene","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitConfig\/enableVOIP","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitConfig\/ringTimeOut"],"title":"Instance Properties"}],"references":{"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallKitConfig":{"abstract":[],"type":"topic","title":"CallKitConfig","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"CallKitConfig"}],"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitConfig","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"CallKitConfig","kind":"identifier"}],"url":"\/documentation\/easecalluikit\/callkitconfig"},"doc://org.cocoapods.EaseCallUIKit/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/SQ"},"doc://org.cocoapods.EaseCallUIKit/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/SH"},"doc://org.cocoapods.EaseCallUIKit/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/objc(cs)NSObject"},"doc://org.cocoapods.EaseCallUIKit/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)NSObject"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallKitConfig/enablePIPOn1V1VideoScene":{"title":"enablePIPOn1V1VideoScene","abstract":[{"type":"text","text":"Indicates whether to enable Picture-in-Picture mode for 1v1 video calls"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitConfig\/enablePIPOn1V1VideoScene","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"enablePIPOn1V1VideoScene"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"type":"topic","url":"\/documentation\/easecalluikit\/callkitconfig\/enablepipon1v1videoscene","role":"symbol"},"doc://org.cocoapods.EaseCallUIKit/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/s7CVarArgP","title":"Swift.CVarArg"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallKitConfig/ringTimeOut":{"kind":"symbol","role":"symbol","url":"\/documentation\/easecalluikit\/callkitconfig\/ringtimeout","type":"topic","title":"ringTimeOut","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ringTimeOut","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"}],"abstract":[{"type":"text","text":"Indicates whether to enable call recording.The minimum cannot be less than 10."}],"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitConfig\/ringTimeOut"},"doc://org.cocoapods.EaseCallUIKit/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallKitConfig/init":{"navigatorTitle":[{"text":"init","kind":"identifier"}],"role":"symbol","type":"topic","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitConfig\/init","title":"init","url":"\/documentation\/easecalluikit\/callkitconfig\/init","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}]},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit":{"title":"EaseCallUIKit","type":"topic","url":"\/documentation\/easecalluikit","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit","abstract":[],"role":"collection","kind":"symbol"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallKitConfig/enableVOIP":{"url":"\/documentation\/easecalluikit\/callkitconfig\/enablevoip","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"enableVOIP"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"title":"enableVOIP","abstract":[{"type":"text","text":"Indicates whether to enable VOIP mode"}],"type":"topic","role":"symbol","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitConfig\/enableVOIP"},"doc://org.cocoapods.EaseCallUIKit/s23CustomStringConvertibleP":{"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Class","op":"replace"},{"value":"CallKitConfig","op":"replace","path":"\/metadata\/title"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"CallKitConfig"}],"path":"\/metadata\/fragments"},{"value":[{"kind":"identifier","text":"CallKitConfig"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":[{"title":"Instance Methods","generated":true,"identifiers":["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitConfig\/init"],"anchor":"Instance-Methods"}],"op":"replace","path":"\/topicSections"},{"value":[{"type":"inheritsFrom","title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/org.cocoapods.EaseCallUIKit\/objc(cs)NSObject"]}],"path":"\/relationshipsSections","op":"replace"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"kind":"text","text":" "},{"text":"CallKitConfig","kind":"identifier"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallKitConfig\/title","value":"CallKitConfig","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallKitConfig\/fragments","value":[{"kind":"identifier","text":"CallKitConfig"}]},{"op":"replace","value":[{"text":"CallKitConfig","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallKitConfig\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}