{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit"]]},"relationshipsSections":[{"kind":"relationships","title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)NSObject"]},{"identifiers":["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallError"],"title":"Conforming Types","kind":"relationships","type":"conformingTypes"}],"variants":[{"paths":["\/documentation\/easecalluikit\/callerrorcodegettable"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easecalluikit\/callerrorcodegettable"]}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CallErrorCodeGettable"},{"text":" : ","kind":"text"},{"text":"NSObjectProtocol","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)NSObject"}]}]}],"identifier":{"url":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallErrorCodeGettable","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Methods","generated":true,"identifiers":["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallErrorCodeGettable\/getCallBusinessError()","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallErrorCodeGettable\/getIMError()","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallErrorCodeGettable\/getRTCError()"],"anchor":"Instance-Methods"}],"schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"externalID":"c:@M@EaseCallUIKit@objc(pl)CallErrorCodeGettable","navigatorTitle":[{"text":"CallErrorCodeGettable","kind":"identifier"}],"title":"CallErrorCodeGettable","symbolKind":"protocol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CallErrorCodeGettable","kind":"identifier"}],"role":"symbol","modules":[{"name":"EaseCallUIKit"}],"roleHeading":"Protocol"},"abstract":[{"text":"The ","type":"text"},{"type":"codeVoice","code":"CallErrorCodeGettable"},{"type":"text","text":" protocol defines methods to retrieve error codes from different modules."}],"references":{"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallErrorCodeGettable":{"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallErrorCodeGettable","abstract":[{"text":"The ","type":"text"},{"code":"CallErrorCodeGettable","type":"codeVoice"},{"type":"text","text":" protocol defines methods to retrieve error codes from different modules."}],"url":"\/documentation\/easecalluikit\/callerrorcodegettable","navigatorTitle":[{"text":"CallErrorCodeGettable","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"CallErrorCodeGettable","kind":"identifier"}],"type":"topic","title":"CallErrorCodeGettable","role":"symbol","kind":"symbol"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallErrorCodeGettable/getIMError()":{"abstract":[{"type":"text","text":"Get error code from the IM module."}],"required":true,"role":"symbol","navigatorTitle":[{"text":"getIMError","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallErrorCodeGettable\/getIMError()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"getIMError","kind":"identifier"},{"text":"() -> ","kind":"text"},{"kind":"typeIdentifier","text":"ChatErrorCode","preciseIdentifier":"s:13EaseCallUIKit13ChatErrorCodea"}],"url":"\/documentation\/easecalluikit\/callerrorcodegettable\/getimerror()","title":"getIMError()","type":"topic"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallErrorCodeGettable/getRTCError()":{"type":"topic","kind":"symbol","title":"getRTCError()","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallErrorCodeGettable\/getRTCError()","navigatorTitle":[{"text":"getRTCError","kind":"identifier"}],"required":true,"abstract":[{"text":"Get error code from the RTC module.","type":"text"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"getRTCError"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"c:@E@AgoraErrorCode","kind":"typeIdentifier","text":"AgoraErrorCode"}],"url":"\/documentation\/easecalluikit\/callerrorcodegettable\/getrtcerror()","role":"symbol"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallError":{"type":"topic","role":"symbol","title":"CallError","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"CallError","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"CallError"},{"type":"text","text":" class encapsulates errors that can occur in the call system, providing a structured way to handle errors from different modules such as IM, RTC, and business logic."}],"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallError","navigatorTitle":[{"kind":"identifier","text":"CallError"}],"url":"\/documentation\/easecalluikit\/callerror"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallErrorCodeGettable/getCallBusinessError()":{"abstract":[{"type":"text","text":"Get error code from the business logic module."}],"type":"topic","required":true,"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"getCallBusinessError","kind":"identifier"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"c:@M@EaseCallUIKit@E@CallBusinessErrorCode","text":"CallBusinessErrorCode","kind":"typeIdentifier"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallErrorCodeGettable\/getCallBusinessError()","role":"symbol","title":"getCallBusinessError()","navigatorTitle":[{"text":"getCallBusinessError","kind":"identifier"}],"url":"\/documentation\/easecalluikit\/callerrorcodegettable\/getcallbusinesserror()"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit":{"title":"EaseCallUIKit","type":"topic","url":"\/documentation\/easecalluikit","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit","abstract":[],"role":"collection","kind":"symbol"},"doc://org.cocoapods.EaseCallUIKit/objc(pl)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)NSObject"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Protocol"},{"value":"CallErrorCodeGettable","op":"replace","path":"\/metadata\/title"},{"value":"protocol","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"CallErrorCodeGettable","kind":"identifier"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"CallErrorCodeGettable","kind":"identifier"}]},{"value":[{"generated":true,"title":"Instance Methods","anchor":"Instance-Methods","identifiers":["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallErrorCodeGettable\/getCallBusinessError()","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallErrorCodeGettable\/getIMError()","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallErrorCodeGettable\/getRTCError()"]}],"op":"replace","path":"\/topicSections"},{"path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)NSObject"],"type":"inheritsFrom","kind":"relationships","title":"Inherits From"},{"type":"conformingTypes","identifiers":["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallError"],"title":"Conforming Types","kind":"relationships"}],"op":"replace"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CallErrorCodeGettable","kind":"identifier"},{"kind":"text","text":" <"},{"text":"NSObject","preciseIdentifier":"c:objc(pl)NSObject","kind":"typeIdentifier"},{"kind":"text","text":">"}]}],"kind":"declarations"}},{"value":"CallErrorCodeGettable","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallErrorCodeGettable\/title"},{"value":[{"text":"CallErrorCodeGettable","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallErrorCodeGettable\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallErrorCodeGettable\/navigatorTitle","value":[{"text":"CallErrorCodeGettable","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"getIMError","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallErrorCodeGettable~1getIMError()\/title"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"getIMError"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallErrorCodeGettable~1getIMError()\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallErrorCodeGettable~1getRTCError()\/title","value":"getRTCError"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"getRTCError","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallErrorCodeGettable~1getRTCError()\/fragments"},{"value":"CallError","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallError\/title","op":"replace"},{"value":[{"kind":"identifier","text":"CallError"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallError\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallError\/navigatorTitle","value":[{"text":"CallError","kind":"identifier"}]},{"value":"getCallBusinessError","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallErrorCodeGettable~1getCallBusinessError()\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallErrorCodeGettable~1getCallBusinessError()\/fragments","value":[{"kind":"text","text":"- "},{"text":"getCallBusinessError","kind":"identifier"}],"op":"replace"}]}]}