{"metadata":{"modules":[{"name":"EaseCallUIKit"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Call1v1AudioViewController","kind":"identifier"}],"navigatorTitle":[{"text":"Call1v1AudioViewController","kind":"identifier"}],"roleHeading":"Class","title":"Call1v1AudioViewController","symbolKind":"class","externalID":"c:@M@EaseCallUIKit@objc(cs)Call1v1AudioViewController","role":"symbol"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit"]]},"sections":[],"variants":[{"paths":["\/documentation\/easecalluikit\/call1v1audioviewcontroller"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easecalluikit\/call1v1audioviewcontroller"]}],"identifier":{"url":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/Call1v1AudioViewController","interfaceLanguage":"swift"},"topicSections":[{"identifiers":["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/Call1v1AudioViewController\/init(role:)"],"anchor":"Initializers","title":"Initializers","generated":true},{"generated":true,"anchor":"Instance-Properties","title":"Instance Properties","identifiers":["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/Call1v1AudioViewController\/background","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/Call1v1AudioViewController\/bottomView","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/Call1v1AudioViewController\/navigationBar","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/Call1v1AudioViewController\/role"]},{"identifiers":["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/Call1v1AudioViewController\/bottomClick(type:)","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/Call1v1AudioViewController\/dismiss(animated:completion:)","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/Call1v1AudioViewController\/navigationClick(type:indexPath:)","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/Call1v1AudioViewController\/pop()","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/Call1v1AudioViewController\/touchesEnded(_:with:)","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/Call1v1AudioViewController\/viewDidLoad()"],"generated":true,"title":"Instance Methods","anchor":"Instance-Methods"},{"title":"Default Implementations","anchor":"Default-Implementations","generated":true,"identifiers":["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/Call1v1AudioViewController\/TimerServiceListener-Implementations"]}],"relationshipsSections":[{"title":"Inherits From","type":"inheritsFrom","kind":"relationships","identifiers":["doc:\/\/org.cocoapods.EaseCallUIKit\/objc(cs)UIViewController"]},{"identifiers":["doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)NSCoding","doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)NSExtensionRequestHandling","doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)NSObject","doc:\/\/org.cocoapods.EaseCallUIKit\/s7CVarArgP","doc:\/\/org.cocoapods.EaseCallUIKit\/s8CopyableP","doc:\/\/org.cocoapods.EaseCallUIKit\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.EaseCallUIKit\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.EaseCallUIKit\/SQ","doc:\/\/org.cocoapods.EaseCallUIKit\/SH","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/TimerServiceListener","doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)UIAppearanceContainer","doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)UIContentContainer","doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)UIFocusEnvironment","doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)UIResponderStandardEditActions","doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)UIStateRestoring","doc:\/\/org.cocoapods.EaseCallUIKit\/5UIKit23UITraitChangeObservableP","doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)UITraitEnvironment","doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)UIUserActivityRestoring"],"kind":"relationships","type":"conformsTo","title":"Conforms To"}],"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM"},{"kind":"text","text":" "},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Call1v1AudioViewController","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"references":{"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/Call1v1AudioViewController/TimerServiceListener-Implementations":{"url":"\/documentation\/easecalluikit\/call1v1audioviewcontroller\/timerservicelistener-implementations","kind":"article","type":"topic","title":"TimerServiceListener Implementations","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/Call1v1AudioViewController\/TimerServiceListener-Implementations","role":"collectionGroup"},"doc://org.cocoapods.EaseCallUIKit/5UIKit23UITraitChangeObservableP":{"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/5UIKit23UITraitChangeObservableP","type":"unresolvable","title":"UIKit.UITraitChangeObservable"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/Call1v1AudioViewController/navigationClick(type:indexPath:)":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"navigationClick"},{"text":"(","kind":"text"},{"text":"type","kind":"externalParam"},{"kind":"text","text":": "},{"text":"ChatNavigationBarClickEvent","kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseCallUIKit@E@ChatNavigationBarClickEvent"},{"kind":"text","text":", "},{"text":"indexPath","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation9IndexPathV","text":"IndexPath"},{"text":"?)","kind":"text"}],"kind":"symbol","abstract":[],"url":"\/documentation\/easecalluikit\/call1v1audioviewcontroller\/navigationclick(type:indexpath:)","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/Call1v1AudioViewController\/navigationClick(type:indexPath:)","type":"topic","title":"navigationClick(type:indexPath:)","navigatorTitle":[{"text":"navigationClickWithType:indexPath:","kind":"identifier"}],"role":"symbol"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit":{"title":"EaseCallUIKit","type":"topic","url":"\/documentation\/easecalluikit","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit","abstract":[],"role":"collection","kind":"symbol"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/Call1v1AudioViewController/touchesEnded(_:with:)":{"kind":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"touchesEnded"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"s:Sh","text":"Set"},{"text":"<","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UITouch","text":"UITouch"},{"text":">, ","kind":"text"},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIEvent","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIEvent"},{"text":"?)","kind":"text"}],"role":"symbol","type":"topic","title":"touchesEnded(_:with:)","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/Call1v1AudioViewController\/touchesEnded(_:with:)","navigatorTitle":[{"text":"touchesEnded:withEvent:","kind":"identifier"}],"url":"\/documentation\/easecalluikit\/call1v1audioviewcontroller\/touchesended(_:with:)"},"doc://org.cocoapods.EaseCallUIKit/SQ":{"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://org.cocoapods.EaseCallUIKit/objc(pl)UIPasteConfigurationSupporting":{"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)UIPasteConfigurationSupporting","type":"unresolvable","title":"UIKit.UIPasteConfigurationSupporting"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/Call1v1AudioViewController/init(role:)":{"navigatorTitle":[{"text":"initWithRole:","kind":"identifier"}],"url":"\/documentation\/easecalluikit\/call1v1audioviewcontroller\/init(role:)","kind":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"role"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseCallUIKit@E@CallRole","text":"CallRole"},{"kind":"text","text":")"}],"title":"init(role:)","abstract":[],"type":"topic","role":"symbol","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/Call1v1AudioViewController\/init(role:)"},"doc://org.cocoapods.EaseCallUIKit/objc(cs)UIViewController":{"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/objc(cs)UIViewController","type":"unresolvable","title":"UIViewController"},"doc://org.cocoapods.EaseCallUIKit/SH":{"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/Call1v1AudioViewController/role":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/Call1v1AudioViewController\/role","url":"\/documentation\/easecalluikit\/call1v1audioviewcontroller\/role","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"role"},{"text":": ","kind":"text"},{"text":"CallRole","kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseCallUIKit@E@CallRole"}],"title":"role","type":"topic","role":"symbol","abstract":[]},"doc://org.cocoapods.EaseCallUIKit/s8CopyableP":{"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/s8CopyableP","type":"unresolvable","title":"Swift.Copyable"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/Call1v1AudioViewController/bottomView":{"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/Call1v1AudioViewController\/bottomView","url":"\/documentation\/easecalluikit\/call1v1audioviewcontroller\/bottomview","type":"topic","abstract":[],"kind":"symbol","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"bottomView","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Call1v1BottomView","kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseCallUIKit@objc(cs)Call1v1BottomView"}],"title":"bottomView"},"doc://org.cocoapods.EaseCallUIKit/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)NSObject"},"doc://org.cocoapods.EaseCallUIKit/objc(pl)UIResponderStandardEditActions":{"title":"UIKit.UIResponderStandardEditActions","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)UIResponderStandardEditActions"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/TimerServiceListener":{"url":"\/documentation\/easecalluikit\/timerservicelistener","kind":"symbol","role":"symbol","title":"TimerServiceListener","navigatorTitle":[{"text":"TimerServiceListener","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/TimerServiceListener","abstract":[],"type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"TimerServiceListener"}]},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/Call1v1AudioViewController/navigationBar":{"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"navigationBar"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@EaseCallUIKit@objc(cs)CallNavigationBar","kind":"typeIdentifier","text":"CallNavigationBar"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/Call1v1AudioViewController\/navigationBar","title":"navigationBar","type":"topic","url":"\/documentation\/easecalluikit\/call1v1audioviewcontroller\/navigationbar","abstract":[],"kind":"symbol"},"doc://org.cocoapods.EaseCallUIKit/objc(pl)UIActivityItemsConfigurationProviding":{"title":"UIKit.UIActivityItemsConfigurationProviding","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)UIActivityItemsConfigurationProviding"},"doc://org.cocoapods.EaseCallUIKit/objc(pl)UIUserActivityRestoring":{"title":"UIKit.UIUserActivityRestoring","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)UIUserActivityRestoring"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/Call1v1AudioViewController":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Call1v1AudioViewController"}],"navigatorTitle":[{"kind":"identifier","text":"Call1v1AudioViewController"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/Call1v1AudioViewController","title":"Call1v1AudioViewController","type":"topic","role":"symbol","abstract":[],"url":"\/documentation\/easecalluikit\/call1v1audioviewcontroller"},"doc://org.cocoapods.EaseCallUIKit/objc(pl)UIStateRestoring":{"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)UIStateRestoring","type":"unresolvable","title":"UIKit.UIStateRestoring"},"doc://org.cocoapods.EaseCallUIKit/objc(pl)UIFocusEnvironment":{"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)UIFocusEnvironment","type":"unresolvable","title":"UIKit.UIFocusEnvironment"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/Call1v1AudioViewController/dismiss(animated:completion:)":{"url":"\/documentation\/easecalluikit\/call1v1audioviewcontroller\/dismiss(animated:completion:)","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"dismiss","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"animated"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": (() -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"text":")?)","kind":"text"}],"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/Call1v1AudioViewController\/dismiss(animated:completion:)","abstract":[],"type":"topic","title":"dismiss(animated:completion:)","navigatorTitle":[{"kind":"identifier","text":"dismissViewControllerAnimated:completion:"}]},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/Call1v1AudioViewController/viewDidLoad()":{"kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewDidLoad"},{"kind":"text","text":"()"}],"url":"\/documentation\/easecalluikit\/call1v1audioviewcontroller\/viewdidload()","role":"symbol","title":"viewDidLoad()","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/Call1v1AudioViewController\/viewDidLoad()","type":"topic","abstract":[],"navigatorTitle":[{"text":"viewDidLoad","kind":"identifier"}]},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/Call1v1AudioViewController/bottomClick(type:)":{"abstract":[],"title":"bottomClick(type:)","type":"topic","url":"\/documentation\/easecalluikit\/call1v1audioviewcontroller\/bottomclick(type:)","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/Call1v1AudioViewController\/bottomClick(type:)","navigatorTitle":[{"text":"bottomClickWithType:","kind":"identifier"}],"kind":"symbol","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"bottomClick","kind":"identifier"},{"text":"(","kind":"text"},{"text":"type","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CallButtonType","preciseIdentifier":"c:@M@EaseCallUIKit@E@CallButtonType","kind":"typeIdentifier"},{"kind":"text","text":")"}]},"doc://org.cocoapods.EaseCallUIKit/objc(pl)NSCoding":{"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)NSCoding","type":"unresolvable","title":"Foundation.NSCoding"},"doc://org.cocoapods.EaseCallUIKit/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/s28CustomDebugStringConvertibleP","type":"unresolvable","title":"Swift.CustomDebugStringConvertible"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/Call1v1AudioViewController/pop()":{"abstract":[],"url":"\/documentation\/easecalluikit\/call1v1audioviewcontroller\/pop()","type":"topic","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/Call1v1AudioViewController\/pop()","title":"pop()","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"pop","kind":"identifier"},{"text":"()","kind":"text"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"pop"}]},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/Call1v1AudioViewController/background":{"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/Call1v1AudioViewController\/background","url":"\/documentation\/easecalluikit\/call1v1audioviewcontroller\/background","type":"topic","abstract":[],"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"background","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImageView","text":"UIImageView"}],"title":"background"},"doc://org.cocoapods.EaseCallUIKit/s23CustomStringConvertibleP":{"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"},"doc://org.cocoapods.EaseCallUIKit/objc(pl)UITraitEnvironment":{"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)UITraitEnvironment","type":"unresolvable","title":"UIKit.UITraitEnvironment"},"doc://org.cocoapods.EaseCallUIKit/objc(pl)UIContentContainer":{"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)UIContentContainer","type":"unresolvable","title":"UIKit.UIContentContainer"},"doc://org.cocoapods.EaseCallUIKit/objc(pl)NSExtensionRequestHandling":{"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)NSExtensionRequestHandling","type":"unresolvable","title":"Foundation.NSExtensionRequestHandling"},"doc://org.cocoapods.EaseCallUIKit/s7CVarArgP":{"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/s7CVarArgP","type":"unresolvable","title":"Swift.CVarArg"},"doc://org.cocoapods.EaseCallUIKit/objc(pl)UIAppearanceContainer":{"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)UIAppearanceContainer","type":"unresolvable","title":"UIKit.UIAppearanceContainer"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Class","path":"\/metadata\/roleHeading","op":"replace"},{"value":"Call1v1AudioViewController","path":"\/metadata\/title","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"Call1v1AudioViewController","kind":"identifier"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"Call1v1AudioViewController","kind":"identifier"}]},{"value":[{"generated":true,"title":"Instance Methods","anchor":"Instance-Methods","identifiers":["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/Call1v1AudioViewController\/bottomClick(type:)","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/Call1v1AudioViewController\/dismiss(animated:completion:)","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/Call1v1AudioViewController\/init(role:)","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/Call1v1AudioViewController\/navigationClick(type:indexPath:)","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/Call1v1AudioViewController\/pop()","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/Call1v1AudioViewController\/touchesEnded(_:with:)","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/Call1v1AudioViewController\/viewDidLoad()"]},{"title":"Default Implementations","generated":true,"anchor":"Default-Implementations","identifiers":["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/Call1v1AudioViewController\/TimerServiceListener-Implementations"]}],"op":"replace","path":"\/topicSections"},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/org.cocoapods.EaseCallUIKit\/objc(cs)UIViewController"],"type":"inheritsFrom","kind":"relationships","title":"Inherits From"},{"kind":"relationships","identifiers":["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/TimerServiceListener"],"type":"conformsTo","title":"Conforms To"}]},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Call1v1AudioViewController","kind":"identifier"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace"},{"op":"replace","value":"navigationClickWithType:indexPath:","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1Call1v1AudioViewController~1navigationClick(type:indexPath:)\/title"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"navigationClickWithType:indexPath:"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1Call1v1AudioViewController~1navigationClick(type:indexPath:)\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1Call1v1AudioViewController~1touchesEnded(_:with:)\/title","value":"touchesEnded:withEvent:","op":"replace"},{"value":[{"kind":"text","text":"- "},{"text":"touchesEnded:withEvent:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1Call1v1AudioViewController~1touchesEnded(_:with:)\/fragments"},{"value":"initWithRole:","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1Call1v1AudioViewController~1init(role:)\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"initWithRole:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1Call1v1AudioViewController~1init(role:)\/fragments"},{"value":"TimerServiceListener","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1TimerServiceListener\/title"},{"value":[{"kind":"identifier","text":"TimerServiceListener"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1TimerServiceListener\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1TimerServiceListener\/navigatorTitle","value":[{"kind":"identifier","text":"TimerServiceListener"}]},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1Call1v1AudioViewController\/title","value":"Call1v1AudioViewController","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1Call1v1AudioViewController\/fragments","value":[{"text":"Call1v1AudioViewController","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1Call1v1AudioViewController\/navigatorTitle","value":[{"text":"Call1v1AudioViewController","kind":"identifier"}]},{"op":"replace","value":"dismissViewControllerAnimated:completion:","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1Call1v1AudioViewController~1dismiss(animated:completion:)\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1Call1v1AudioViewController~1dismiss(animated:completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"dismissViewControllerAnimated:completion:"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1Call1v1AudioViewController~1viewDidLoad()\/title","value":"viewDidLoad"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"viewDidLoad"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1Call1v1AudioViewController~1viewDidLoad()\/fragments","op":"replace"},{"value":"bottomClickWithType:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1Call1v1AudioViewController~1bottomClick(type:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"bottomClickWithType:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1Call1v1AudioViewController~1bottomClick(type:)\/fragments"},{"value":"pop","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1Call1v1AudioViewController~1pop()\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1Call1v1AudioViewController~1pop()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"pop","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}