{"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit"]]},"identifier":{"url":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallServiceListener","interfaceLanguage":"swift"},"sections":[],"topicSections":[{"title":"Instance Methods","generated":true,"identifiers":["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallServiceListener\/didOccurError(error:)","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallServiceListener\/didUpdateCallEndReason(reason:info:)","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallServiceListener\/onReceivedCall(callType:userId:extensionInfo:)","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallServiceListener\/onRtcEngineCreated(engine:)","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallServiceListener\/remoteUserDidJoined(userId:channelName:type:)","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallServiceListener\/remoteUserDidLeft(userId:channelName:type:)"],"anchor":"Instance-Methods"}],"kind":"symbol","metadata":{"navigatorTitle":[{"text":"CallServiceListener","kind":"identifier"}],"symbolKind":"protocol","title":"CallServiceListener","modules":[{"name":"EaseCallUIKit"}],"roleHeading":"Protocol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"CallServiceListener"}],"externalID":"c:@M@EaseCallUIKit@objc(pl)CallServiceListener","role":"symbol"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"CallServiceListener","kind":"identifier"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:objc(pl)NSObject","kind":"typeIdentifier","text":"NSObjectProtocol"}]}]}],"variants":[{"paths":["\/documentation\/easecalluikit\/callservicelistener"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easecalluikit\/callservicelistener"]}],"relationshipsSections":[{"type":"inheritsFrom","kind":"relationships","identifiers":["doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)NSObject"],"title":"Inherits From"}],"references":{"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallServiceListener/didUpdateCallEndReason(reason:info:)":{"abstract":[{"text":"Called when a call is ended.","type":"text"}],"kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"didUpdateCallEndReason"},{"kind":"text","text":"("},{"text":"reason","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@EaseCallUIKit@E@CallEndReason","kind":"typeIdentifier","text":"CallEndReason"},{"kind":"text","text":", "},{"text":"info","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@EaseCallUIKit@objc(cs)CallInfo","kind":"typeIdentifier","text":"CallInfo"},{"text":")","kind":"text"}],"url":"\/documentation\/easecalluikit\/callservicelistener\/didupdatecallendreason(reason:info:)","title":"didUpdateCallEndReason(reason:info:)","type":"topic","navigatorTitle":[{"text":"didUpdateCallEndReasonWithReason:info:","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallServiceListener\/didUpdateCallEndReason(reason:info:)","role":"symbol"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallServiceListener/remoteUserDidJoined(userId:channelName:type:)":{"navigatorTitle":[{"text":"remoteUserDidJoinedWithUserId:channelName:type:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"remoteUserDidJoined"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"userId"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"channelName"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"type","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseCallUIKit@E@CallType","text":"CallType"},{"kind":"text","text":")"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallServiceListener\/remoteUserDidJoined(userId:channelName:type:)","role":"symbol","abstract":[{"text":"Called when a remote user joins the call.","type":"text"}],"type":"topic","url":"\/documentation\/easecalluikit\/callservicelistener\/remoteuserdidjoined(userid:channelname:type:)","title":"remoteUserDidJoined(userId:channelName:type:)"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallServiceListener":{"abstract":[],"kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"CallServiceListener"}],"url":"\/documentation\/easecalluikit\/callservicelistener","title":"CallServiceListener","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CallServiceListener"}],"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallServiceListener","role":"symbol"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallServiceListener/didOccurError(error:)":{"navigatorTitle":[{"text":"didOccurErrorWithError:","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"didOccurError","kind":"identifier"},{"text":"(","kind":"text"},{"text":"error","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@EaseCallUIKit@objc(cs)CallError","kind":"typeIdentifier","text":"CallError"},{"kind":"text","text":")"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallServiceListener\/didOccurError(error:)","role":"symbol","abstract":[{"type":"text","text":"Called when a call is received."}],"type":"topic","url":"\/documentation\/easecalluikit\/callservicelistener\/didoccurerror(error:)","title":"didOccurError(error:)"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallServiceListener/remoteUserDidLeft(userId:channelName:type:)":{"abstract":[{"type":"text","text":"Called when a remote user leaves the call."}],"kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"remoteUserDidLeft","kind":"identifier"},{"text":"(","kind":"text"},{"text":"userId","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"text":"channelName","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"text":"type","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@EaseCallUIKit@E@CallType","kind":"typeIdentifier","text":"CallType"},{"text":")","kind":"text"}],"url":"\/documentation\/easecalluikit\/callservicelistener\/remoteuserdidleft(userid:channelname:type:)","title":"remoteUserDidLeft(userId:channelName:type:)","type":"topic","required":true,"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallServiceListener\/remoteUserDidLeft(userId:channelName:type:)","navigatorTitle":[{"text":"remoteUserDidLeftWithUserId:channelName:type:","kind":"identifier"}],"role":"symbol"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallServiceListener/onRtcEngineCreated(engine:)":{"navigatorTitle":[{"kind":"identifier","text":"onRtcEngineCreatedWithEngine:"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"onRtcEngineCreated"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"engine"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)AgoraRtcEngineKit","text":"AgoraRtcEngineKit","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallServiceListener\/onRtcEngineCreated(engine:)","role":"symbol","abstract":[{"type":"text","text":"Called when a call is connected."}],"type":"topic","required":true,"url":"\/documentation\/easecalluikit\/callservicelistener\/onrtcenginecreated(engine:)","title":"onRtcEngineCreated(engine:)"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallServiceListener/onReceivedCall(callType:userId:extensionInfo:)":{"abstract":[{"type":"text","text":"Called when a call is received."}],"kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"onReceivedCall"},{"kind":"text","text":"("},{"text":"callType","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@EaseCallUIKit@E@CallType","kind":"typeIdentifier","text":"CallType"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"userId"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"extensionInfo","kind":"externalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]?)"}],"url":"\/documentation\/easecalluikit\/callservicelistener\/onreceivedcall(calltype:userid:extensioninfo:)","title":"onReceivedCall(callType:userId:extensionInfo:)","type":"topic","required":true,"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallServiceListener\/onReceivedCall(callType:userId:extensionInfo:)","navigatorTitle":[{"kind":"identifier","text":"onReceivedCallWithCallType:userId:extensionInfo:"}],"role":"symbol"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit":{"title":"EaseCallUIKit","type":"topic","url":"\/documentation\/easecalluikit","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit","abstract":[],"role":"collection","kind":"symbol"},"doc://org.cocoapods.EaseCallUIKit/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)NSObject","title":"NSObject"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"op":"replace","value":"CallServiceListener","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"value":[{"kind":"identifier","text":"CallServiceListener"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"replace","value":[{"text":"CallServiceListener","kind":"identifier"}],"path":"\/metadata\/navigatorTitle"},{"op":"replace","path":"\/topicSections","value":[{"generated":true,"anchor":"Instance-Methods","identifiers":["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallServiceListener\/didOccurError(error:)","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallServiceListener\/didUpdateCallEndReason(reason:info:)","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallServiceListener\/onReceivedCall(callType:userId:extensionInfo:)","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallServiceListener\/onRtcEngineCreated(engine:)","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallServiceListener\/remoteUserDidJoined(userId:channelName:type:)","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallServiceListener\/remoteUserDidLeft(userId:channelName:type:)"],"title":"Instance Methods"}]},{"path":"\/relationshipsSections","op":"replace","value":[{"identifiers":["doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)NSObject"],"type":"inheritsFrom","title":"Inherits From","kind":"relationships"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"@protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"CallServiceListener"},{"text":" <","kind":"text"},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(pl)NSObject"},{"kind":"text","text":">"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallServiceListener~1didUpdateCallEndReason(reason:info:)\/title","value":"didUpdateCallEndReasonWithReason:info:","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"didUpdateCallEndReasonWithReason:info:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallServiceListener~1didUpdateCallEndReason(reason:info:)\/fragments"},{"op":"replace","value":"remoteUserDidJoinedWithUserId:channelName:type:","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallServiceListener~1remoteUserDidJoined(userId:channelName:type:)\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallServiceListener~1remoteUserDidJoined(userId:channelName:type:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"remoteUserDidJoinedWithUserId:channelName:type:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallServiceListener\/title","op":"replace","value":"CallServiceListener"},{"op":"replace","value":[{"text":"CallServiceListener","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallServiceListener\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallServiceListener\/navigatorTitle","value":[{"kind":"identifier","text":"CallServiceListener"}],"op":"replace"},{"op":"replace","value":"didOccurErrorWithError:","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallServiceListener~1didOccurError(error:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"didOccurErrorWithError:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallServiceListener~1didOccurError(error:)\/fragments"},{"value":"remoteUserDidLeftWithUserId:channelName:type:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallServiceListener~1remoteUserDidLeft(userId:channelName:type:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallServiceListener~1remoteUserDidLeft(userId:channelName:type:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"remoteUserDidLeftWithUserId:channelName:type:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallServiceListener~1onRtcEngineCreated(engine:)\/title","value":"onRtcEngineCreatedWithEngine:","op":"replace"},{"value":[{"kind":"text","text":"- "},{"text":"onRtcEngineCreatedWithEngine:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallServiceListener~1onRtcEngineCreated(engine:)\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallServiceListener~1onReceivedCall(callType:userId:extensionInfo:)\/title","value":"onReceivedCallWithCallType:userId:extensionInfo:","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallServiceListener~1onReceivedCall(callType:userId:extensionInfo:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"onReceivedCallWithCallType:userId:extensionInfo:","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}