{"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallErrorModule\/business","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallErrorModule\/im","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallErrorModule\/rtc","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallErrorModule\/unknown"],"anchor":"Enumeration-Cases","generated":true},{"title":"Initializers","generated":true,"identifiers":["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallErrorModule\/init(rawValue:)"],"anchor":"Initializers"},{"identifiers":["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallErrorModule\/Equatable-Implementations","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallErrorModule\/RawRepresentable-Implementations"],"anchor":"Default-Implementations","generated":true,"title":"Default Implementations"}],"kind":"symbol","metadata":{"externalID":"c:@M@EaseCallUIKit@E@CallErrorModule","symbolKind":"enum","role":"symbol","roleHeading":"Enumeration","modules":[{"name":"EaseCallUIKit"}],"title":"CallErrorModule","navigatorTitle":[{"text":"CallErrorModule","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CallErrorModule"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit"]]},"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"url":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallErrorModule","interfaceLanguage":"swift"},"relationshipsSections":[{"title":"Conforms To","kind":"relationships","identifiers":["doc:\/\/org.cocoapods.EaseCallUIKit\/SQ","doc:\/\/org.cocoapods.EaseCallUIKit\/SH","doc:\/\/org.cocoapods.EaseCallUIKit\/SY"],"type":"conformsTo"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"CallErrorModule","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easecalluikit\/callerrormodule"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easecalluikit\/callerrormodule"]}],"references":{"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallErrorModule/init(rawValue:)":{"kind":"symbol","abstract":[],"title":"init(rawValue:)","type":"topic","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallErrorModule\/init(rawValue:)","role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"text":")","kind":"text"}],"url":"\/documentation\/easecalluikit\/callerrormodule\/init(rawvalue:)"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit":{"title":"EaseCallUIKit","type":"topic","url":"\/documentation\/easecalluikit","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit","abstract":[],"role":"collection","kind":"symbol"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallErrorModule/Equatable-Implementations":{"kind":"article","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallErrorModule\/Equatable-Implementations","title":"Equatable Implementations","url":"\/documentation\/easecalluikit\/callerrormodule\/equatable-implementations","role":"collectionGroup","type":"topic","abstract":[]},"doc://org.cocoapods.EaseCallUIKit/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/SH"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallErrorModule/unknown":{"navigatorTitle":[{"text":"CallErrorModuleUnknown","kind":"identifier"}],"title":"CallErrorModule.unknown","abstract":[],"type":"topic","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallErrorModule\/unknown","url":"\/documentation\/easecalluikit\/callerrormodule\/unknown","role":"symbol","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"unknown"}]},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallErrorModule":{"abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallErrorModule","title":"CallErrorModule","role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CallErrorModule"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CallErrorModule"}],"url":"\/documentation\/easecalluikit\/callerrormodule","kind":"symbol"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallErrorModule/im":{"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"im","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallErrorModule\/im","title":"CallErrorModule.im","url":"\/documentation\/easecalluikit\/callerrormodule\/im","role":"symbol","navigatorTitle":[{"text":"CallErrorModuleIm","kind":"identifier"}],"type":"topic","abstract":[]},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallErrorModule/rtc":{"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallErrorModule\/rtc","title":"CallErrorModule.rtc","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"rtc"}],"role":"symbol","url":"\/documentation\/easecalluikit\/callerrormodule\/rtc","kind":"symbol","navigatorTitle":[{"text":"CallErrorModuleRtc","kind":"identifier"}],"type":"topic","abstract":[]},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallErrorModule/business":{"title":"CallErrorModule.business","type":"topic","abstract":[],"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"business"}],"navigatorTitle":[{"text":"CallErrorModuleBusiness","kind":"identifier"}],"url":"\/documentation\/easecalluikit\/callerrormodule\/business","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallErrorModule\/business"},"doc://org.cocoapods.EaseCallUIKit/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/SQ"},"doc://org.cocoapods.EaseCallUIKit/SY":{"title":"Swift.RawRepresentable","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/SY"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallErrorModule/RawRepresentable-Implementations":{"kind":"article","type":"topic","url":"\/documentation\/easecalluikit\/callerrormodule\/rawrepresentable-implementations","title":"RawRepresentable Implementations","role":"collectionGroup","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallErrorModule\/RawRepresentable-Implementations"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Enumeration","op":"replace"},{"value":"CallErrorModule","path":"\/metadata\/title","op":"replace"},{"value":"enum","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"CallErrorModule","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"CallErrorModule"}],"path":"\/metadata\/navigatorTitle"},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","anchor":"Enumeration-Cases","identifiers":["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallErrorModule\/business","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallErrorModule\/im","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallErrorModule\/rtc","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallErrorModule\/unknown"],"generated":true}]},{"path":"\/relationshipsSections","value":null,"op":"replace"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CallErrorModule","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"NSUInteger","preciseIdentifier":"c:@T@NSUInteger"},{"kind":"text","text":";"}]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallErrorModule~1unknown\/title","value":"CallErrorModuleUnknown","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallErrorModule~1unknown\/fragments","value":[{"kind":"identifier","text":"CallErrorModuleUnknown"}]},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallErrorModule\/title","value":"CallErrorModule","op":"replace"},{"op":"replace","value":[{"text":"CallErrorModule","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallErrorModule\/fragments"},{"value":[{"kind":"identifier","text":"CallErrorModule"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallErrorModule\/navigatorTitle","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallErrorModule~1im\/title","value":"CallErrorModuleIm"},{"value":[{"kind":"identifier","text":"CallErrorModuleIm"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallErrorModule~1im\/fragments","op":"replace"},{"value":"CallErrorModuleRtc","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallErrorModule~1rtc\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallErrorModule~1rtc\/fragments","value":[{"kind":"identifier","text":"CallErrorModuleRtc"}],"op":"replace"},{"value":"CallErrorModuleBusiness","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallErrorModule~1business\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallErrorModule~1business\/fragments","value":[{"kind":"identifier","text":"CallErrorModuleBusiness"}]}]}]}