{"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"url":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallRole","interfaceLanguage":"swift"},"metadata":{"title":"CallRole","modules":[{"name":"EaseCallUIKit"}],"externalID":"c:@M@EaseCallUIKit@E@CallRole","symbolKind":"enum","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"CallRole"}],"navigatorTitle":[{"text":"CallRole","kind":"identifier"}],"role":"symbol","roleHeading":"Enumeration"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easecalluikit\/callrole"]},{"paths":["\/documentation\/easecalluikit\/callrole"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/org.cocoapods.EaseCallUIKit\/SQ","doc:\/\/org.cocoapods.EaseCallUIKit\/SH","doc:\/\/org.cocoapods.EaseCallUIKit\/SY"],"type":"conformsTo","title":"Conforms To"}],"sections":[],"topicSections":[{"anchor":"Enumeration-Cases","identifiers":["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallRole\/callee","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallRole\/caller"],"generated":true,"title":"Enumeration Cases"},{"identifiers":["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallRole\/init(rawValue:)"],"anchor":"Initializers","title":"Initializers","generated":true},{"identifiers":["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallRole\/Equatable-Implementations","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallRole\/RawRepresentable-Implementations"],"generated":true,"title":"Default Implementations","anchor":"Default-Implementations"}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"CallRole","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit"]]},"references":{"doc://org.cocoapods.EaseCallUIKit/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/SH"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallRole/caller":{"navigatorTitle":[{"text":"CallRoleCaller","kind":"identifier"}],"url":"\/documentation\/easecalluikit\/callrole\/caller","kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"caller","kind":"identifier"}],"title":"CallRole.caller","abstract":[],"type":"topic","role":"symbol","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallRole\/caller"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallRole/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallRole\/init(rawValue:)","type":"topic","url":"\/documentation\/easecalluikit\/callrole\/init(rawvalue:)","kind":"symbol","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"text":")","kind":"text"}]},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit":{"title":"EaseCallUIKit","type":"topic","url":"\/documentation\/easecalluikit","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit","abstract":[],"role":"collection","kind":"symbol"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallRole/Equatable-Implementations":{"url":"\/documentation\/easecalluikit\/callrole\/equatable-implementations","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallRole\/Equatable-Implementations","role":"collectionGroup","type":"topic","kind":"article","abstract":[],"title":"Equatable Implementations"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallRole/callee":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"callee","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/easecalluikit\/callrole\/callee","abstract":[],"type":"topic","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallRole\/callee","title":"CallRole.callee","navigatorTitle":[{"text":"CallRoleCallee","kind":"identifier"}],"role":"symbol"},"doc://org.cocoapods.EaseCallUIKit/SY":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/SY","title":"Swift.RawRepresentable"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallRole":{"url":"\/documentation\/easecalluikit\/callrole","role":"symbol","title":"CallRole","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallRole","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"CallRole"}],"navigatorTitle":[{"text":"CallRole","kind":"identifier"}],"type":"topic"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallRole/RawRepresentable-Implementations":{"kind":"article","title":"RawRepresentable Implementations","role":"collectionGroup","url":"\/documentation\/easecalluikit\/callrole\/rawrepresentable-implementations","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallRole\/RawRepresentable-Implementations","type":"topic"},"doc://org.cocoapods.EaseCallUIKit/SQ":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/SQ","title":"Swift.Equatable"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Enumeration","path":"\/metadata\/roleHeading"},{"value":"CallRole","op":"replace","path":"\/metadata\/title"},{"value":"enum","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"CallRole","kind":"identifier"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"text":"CallRole","kind":"identifier"}],"op":"replace"},{"op":"replace","value":[{"identifiers":["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallRole\/callee","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallRole\/caller"],"generated":true,"anchor":"Enumeration-Cases","title":"Enumeration Cases"}],"path":"\/topicSections"},{"op":"replace","value":null,"path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CallRole","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSInteger","preciseIdentifier":"c:@T@NSInteger","kind":"typeIdentifier"},{"kind":"text","text":";"}]}]}},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallRole~1caller\/title","op":"replace","value":"CallRoleCaller"},{"value":[{"kind":"identifier","text":"CallRoleCaller"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallRole~1caller\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallRole~1callee\/title","value":"CallRoleCallee","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallRole~1callee\/fragments","op":"replace","value":[{"text":"CallRoleCallee","kind":"identifier"}]},{"value":"CallRole","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallRole\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallRole\/fragments","op":"replace","value":[{"text":"CallRole","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"CallRole"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallRole\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}