{"topicSections":[{"title":"Instance Properties","generated":true,"identifiers":["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallBusiness\/errorCode","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallBusiness\/message"],"anchor":"Instance-Properties"},{"title":"Instance Methods","anchor":"Instance-Methods","identifiers":["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallBusiness\/initWithError:message:"],"generated":true}],"relationshipsSections":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/org.cocoapods.EaseCallUIKit\/objc(cs)NSObject"],"type":"inheritsFrom"},{"kind":"relationships","identifiers":["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallErrorCommonFeature"],"title":"Conforms To","type":"conformsTo"}],"kind":"symbol","sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CallBusiness","kind":"identifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier","text":"NSObject"}]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit"]]},"abstract":[{"type":"text","text":"Convenience initializer for creating a "},{"text":"CallError","type":"text"},{"text":" with a business logic error.","type":"text"}],"metadata":{"role":"symbol","symbolKind":"class","modules":[{"name":"EaseCallUIKit"}],"externalID":"c:@M@EaseCallUIKit@objc(cs)CallBusiness","navigatorTitle":[{"text":"CallBusiness","kind":"identifier"}],"roleHeading":"Class","fragments":[{"kind":"identifier","text":"CallBusiness"}],"title":"CallBusiness"},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easecalluikit\/callbusiness"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallBusiness"},"references":{"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallBusiness/initWithError:message:":{"abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallBusiness\/initWithError:message:","title":"initWithError:message:","url":"\/documentation\/easecalluikit\/callbusiness\/initwitherror:message:","kind":"symbol","fragments":[{"text":"- ","kind":"text"},{"text":"initWithError:message:","kind":"identifier"}],"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithError:message:"}]},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallBusiness":{"type":"topic","url":"\/documentation\/easecalluikit\/callbusiness","kind":"symbol","role":"symbol","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallBusiness","fragments":[{"text":"CallBusiness","kind":"identifier"}],"title":"CallBusiness","abstract":[{"text":"Convenience initializer for creating a ","type":"text"},{"type":"text","text":"CallError"},{"type":"text","text":" with a business logic error."}]},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit":{"title":"EaseCallUIKit","type":"topic","url":"\/documentation\/easecalluikit","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit","abstract":[],"role":"collection","kind":"symbol"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallBusiness/message":{"type":"topic","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallBusiness\/message","role":"symbol","url":"\/documentation\/easecalluikit\/callbusiness\/message","fragments":[{"kind":"identifier","text":"message"}],"title":"message"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallErrorCommonFeature":{"navigatorTitle":[{"text":"CallErrorCommonFeature","kind":"identifier"}],"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"CallErrorCommonFeature","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"CallErrorCommonFeature 协议定义了通用的错误特性"}],"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallErrorCommonFeature","type":"topic","title":"CallErrorCommonFeature","url":"\/documentation\/easecalluikit\/callerrorcommonfeature","role":"symbol"},"doc://org.cocoapods.EaseCallUIKit/objc(cs)NSObject":{"title":"NSObject","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/objc(cs)NSObject"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallBusiness/errorCode":{"type":"topic","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallBusiness\/errorCode","role":"symbol","url":"\/documentation\/easecalluikit\/callbusiness\/errorcode","fragments":[{"kind":"identifier","text":"errorCode"}],"title":"errorCode"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallErrorCommonFeature\/title","value":"CallErrorCommonFeature"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallErrorCommonFeature\/fragments","value":[{"kind":"identifier","text":"CallErrorCommonFeature"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallErrorCommonFeature\/navigatorTitle","op":"replace","value":[{"text":"CallErrorCommonFeature","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}