{"sections":[],"variants":[{"paths":["\/documentation\/easecalluikit\/callerrorcommonfeature"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easecalluikit\/callerrorcommonfeature"]}],"topicSections":[{"title":"Instance Properties","generated":true,"identifiers":["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallErrorCommonFeature\/errorCode","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallErrorCommonFeature\/message"],"anchor":"Instance-Properties"}],"metadata":{"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"CallErrorCommonFeature"}],"externalID":"c:@M@EaseCallUIKit@objc(pl)CallErrorCommonFeature","symbolKind":"protocol","role":"symbol","modules":[{"name":"EaseCallUIKit"}],"title":"CallErrorCommonFeature","roleHeading":"Protocol","navigatorTitle":[{"text":"CallErrorCommonFeature","kind":"identifier"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallErrorCommonFeature"},"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"text":"CallErrorCommonFeature 协议定义了通用的错误特性","type":"text"}],"relationshipsSections":[{"title":"Inherits From","kind":"relationships","type":"inheritsFrom","identifiers":["doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)NSObject"]},{"identifiers":["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallError\/CallBusiness","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallError\/IM","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallError\/RTC"],"type":"conformingTypes","title":"Conforming Types","kind":"relationships"}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"CallErrorCommonFeature","kind":"identifier"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","text":"NSObjectProtocol","preciseIdentifier":"c:objc(pl)NSObject"}],"platforms":["iOS"]}],"kind":"declarations"}],"kind":"symbol","references":{"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallErrorCommonFeature/message":{"type":"topic","kind":"symbol","title":"message","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallErrorCommonFeature\/message","navigatorTitle":[{"text":"message","kind":"identifier"}],"required":true,"abstract":[],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"message","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"url":"\/documentation\/easecalluikit\/callerrorcommonfeature\/message","role":"symbol"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit":{"title":"EaseCallUIKit","type":"topic","url":"\/documentation\/easecalluikit","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit","abstract":[],"role":"collection","kind":"symbol"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallError/CallBusiness":{"navigatorTitle":[{"kind":"identifier","text":"CallBusiness"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CallBusiness"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallError\/CallBusiness","url":"\/documentation\/easecalluikit\/callerror\/callbusiness","type":"topic","title":"CallError.CallBusiness","kind":"symbol","abstract":[{"type":"text","text":"Convenience initializer for creating a "},{"code":"CallError","type":"codeVoice"},{"type":"text","text":" with a business logic error."}]},"doc://org.cocoapods.EaseCallUIKit/objc(pl)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)NSObject"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallError/RTC":{"url":"\/documentation\/easecalluikit\/callerror\/rtc","role":"symbol","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallError\/RTC","navigatorTitle":[{"kind":"identifier","text":"RTC"}],"abstract":[{"text":"Convenience initializer for creating a ","type":"text"},{"type":"codeVoice","code":"CallError"},{"text":" with an IM error.","type":"text"}],"title":"CallError.RTC","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"RTC","kind":"identifier"}]},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/RTC":{"kind":"symbol","url":"\/documentation\/easecalluikit\/rtc","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/RTC","title":"RTC","role":"symbol","type":"topic","abstract":[{"text":"Convenience initializer for creating a ","type":"text"},{"type":"text","text":"CallError"},{"text":" with an IM error.","type":"text"}],"fragments":[{"kind":"identifier","text":"RTC"}]},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallErrorCommonFeature/errorCode":{"url":"\/documentation\/easecalluikit\/callerrorcommonfeature\/errorcode","type":"topic","kind":"symbol","navigatorTitle":[{"text":"errorCode","kind":"identifier"}],"role":"symbol","required":true,"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallErrorCommonFeature\/errorCode","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"errorCode"},{"kind":"text","text":": "},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"}],"title":"errorCode","abstract":[]},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallErrorCommonFeature":{"navigatorTitle":[{"text":"CallErrorCommonFeature","kind":"identifier"}],"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"CallErrorCommonFeature","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"CallErrorCommonFeature 协议定义了通用的错误特性"}],"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallErrorCommonFeature","type":"topic","title":"CallErrorCommonFeature","url":"\/documentation\/easecalluikit\/callerrorcommonfeature","role":"symbol"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallError/IM":{"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallError\/IM","kind":"symbol","title":"CallError.IM","abstract":[{"type":"text","text":"Convenience initializer for creating a "},{"type":"codeVoice","code":"CallError"},{"text":" with an RTC error.","type":"text"}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"IM","kind":"identifier"}],"role":"symbol","url":"\/documentation\/easecalluikit\/callerror\/im","navigatorTitle":[{"kind":"identifier","text":"IM"}]},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallBusiness":{"type":"topic","url":"\/documentation\/easecalluikit\/callbusiness","kind":"symbol","role":"symbol","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallBusiness","fragments":[{"text":"CallBusiness","kind":"identifier"}],"title":"CallBusiness","abstract":[{"text":"Convenience initializer for creating a ","type":"text"},{"type":"text","text":"CallError"},{"type":"text","text":" with a business logic error."}]},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/IM":{"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/IM","url":"\/documentation\/easecalluikit\/im","abstract":[{"type":"text","text":"Convenience initializer for creating a "},{"text":"CallError","type":"text"},{"text":" with an RTC error.","type":"text"}],"type":"topic","fragments":[{"text":"IM","kind":"identifier"}],"role":"symbol","kind":"symbol","title":"IM"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Protocol"},{"value":"CallErrorCommonFeature","path":"\/metadata\/title","op":"replace"},{"value":"protocol","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"CallErrorCommonFeature"}],"path":"\/metadata\/fragments"},{"path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"CallErrorCommonFeature"}],"op":"replace"},{"path":"\/topicSections","op":"replace","value":[{"generated":true,"title":"Instance Properties","identifiers":["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallErrorCommonFeature\/errorCode","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallErrorCommonFeature\/message"],"anchor":"Instance-Properties"}]},{"op":"replace","value":[{"kind":"relationships","identifiers":["doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)NSObject"],"type":"inheritsFrom","title":"Inherits From"},{"kind":"relationships","title":"Conforming Types","identifiers":["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallBusiness","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/IM","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/RTC"],"type":"conformingTypes"}],"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"text":"CallErrorCommonFeature","kind":"identifier"},{"kind":"text","text":" <"},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)NSObject"},{"text":">","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallErrorCommonFeature~1message\/title","value":"message"},{"value":[{"text":"message","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallErrorCommonFeature~1message\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallErrorCommonFeature~1errorCode\/title","op":"replace","value":"errorCode"},{"value":[{"kind":"identifier","text":"errorCode"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallErrorCommonFeature~1errorCode\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallErrorCommonFeature\/title","value":"CallErrorCommonFeature"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallErrorCommonFeature\/fragments","value":[{"kind":"identifier","text":"CallErrorCommonFeature"}]},{"value":[{"text":"CallErrorCommonFeature","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallErrorCommonFeature\/navigatorTitle","op":"replace"}]}]}