{"kind":"symbol","abstract":[{"text":"\/\/\/ Profile provider of the ChatUIKit.Only available in Objective-C language.","type":"text"}],"topicSections":[{"anchor":"Instance-Methods","title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallUserProfileProviderOC\/fetchGroupProfiles(profileIds:completion:)","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallUserProfileProviderOC\/fetchProfiles(profileIds:completion:)"],"generated":true}],"metadata":{"roleHeading":"Protocol","modules":[{"name":"EaseCallUIKit"}],"title":"CallUserProfileProviderOC","navigatorTitle":[{"kind":"identifier","text":"CallUserProfileProviderOC"}],"role":"symbol","symbolKind":"protocol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"CallUserProfileProviderOC","kind":"identifier"}],"externalID":"c:@M@EaseCallUIKit@objc(pl)CallUserProfileProviderOC"},"identifier":{"url":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallUserProfileProviderOC","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit"]]},"relationshipsSections":[{"title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)NSObject"],"type":"inheritsFrom"}],"variants":[{"paths":["\/documentation\/easecalluikit\/calluserprofileprovideroc"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easecalluikit\/calluserprofileprovideroc"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CallUserProfileProviderOC"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:objc(pl)NSObject","text":"NSObjectProtocol","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"references":{"doc://org.cocoapods.EaseCallUIKit/objc(pl)NSObject":{"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)NSObject","type":"unresolvable","title":"NSObject"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallUserProfileProviderOC/fetchGroupProfiles(profileIds:completion:)":{"url":"\/documentation\/easecalluikit\/calluserprofileprovideroc\/fetchgroupprofiles(profileids:completion:)","required":true,"role":"symbol","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallUserProfileProviderOC\/fetchGroupProfiles(profileIds:completion:)","navigatorTitle":[{"text":"fetchGroupProfilesWithProfileIds:completion:","kind":"identifier"}],"abstract":[{"type":"text","text":"Need to obtain the group display information on the current screen."}],"title":"fetchGroupProfiles(profileIds:completion:)","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"fetchGroupProfiles"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"profileIds"},{"kind":"text","text":": ["},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"], ","kind":"text"},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (["},{"preciseIdentifier":"c:@M@EaseCallUIKit@objc(pl)CallProfileProtocol","kind":"typeIdentifier","text":"CallProfileProtocol"},{"text":"]) -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallUserProfileProviderOC/fetchProfiles(profileIds:completion:)":{"abstract":[{"type":"text","text":"Need to obtain the list display information on the current screen."}],"required":true,"kind":"symbol","title":"fetchProfiles(profileIds:completion:)","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallUserProfileProviderOC\/fetchProfiles(profileIds:completion:)","url":"\/documentation\/easecalluikit\/calluserprofileprovideroc\/fetchprofiles(profileids:completion:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"fetchProfiles","kind":"identifier"},{"text":"(","kind":"text"},{"text":"profileIds","kind":"externalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"], ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ([","kind":"text"},{"text":"CallProfileProtocol","kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseCallUIKit@objc(pl)CallProfileProtocol"},{"kind":"text","text":"]) -> "},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"kind":"text","text":")"}],"navigatorTitle":[{"text":"fetchProfilesWithProfileIds:completion:","kind":"identifier"}],"role":"symbol","type":"topic"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallUserProfileProviderOC":{"kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"CallUserProfileProviderOC"}],"title":"CallUserProfileProviderOC","abstract":[{"type":"text","text":"\/\/\/ Profile provider of the ChatUIKit.Only available in Objective-C language."}],"navigatorTitle":[{"kind":"identifier","text":"CallUserProfileProviderOC"}],"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallUserProfileProviderOC","type":"topic","role":"symbol","url":"\/documentation\/easecalluikit\/calluserprofileprovideroc"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit":{"title":"EaseCallUIKit","type":"topic","url":"\/documentation\/easecalluikit","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit","abstract":[],"role":"collection","kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Protocol","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"CallUserProfileProviderOC"},{"path":"\/metadata\/symbolKind","value":"protocol","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"CallUserProfileProviderOC"}]},{"value":[{"text":"CallUserProfileProviderOC","kind":"identifier"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","anchor":"Instance-Methods","identifiers":["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallUserProfileProviderOC\/fetchGroupProfiles(profileIds:completion:)","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallUserProfileProviderOC\/fetchProfiles(profileIds:completion:)"],"generated":true}]},{"op":"replace","value":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)NSObject"],"type":"inheritsFrom"}],"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CallUserProfileProviderOC"},{"text":" <","kind":"text"},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)NSObject"},{"text":">","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallUserProfileProviderOC~1fetchGroupProfiles(profileIds:completion:)\/title","op":"replace","value":"fetchGroupProfilesWithProfileIds:completion:"},{"value":[{"text":"- ","kind":"text"},{"text":"fetchGroupProfilesWithProfileIds:completion:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallUserProfileProviderOC~1fetchGroupProfiles(profileIds:completion:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallUserProfileProviderOC~1fetchProfiles(profileIds:completion:)\/title","value":"fetchProfilesWithProfileIds:completion:"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"fetchProfilesWithProfileIds:completion:"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallUserProfileProviderOC~1fetchProfiles(profileIds:completion:)\/fragments","op":"replace"},{"value":"CallUserProfileProviderOC","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallUserProfileProviderOC\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallUserProfileProviderOC\/fragments","op":"replace","value":[{"text":"CallUserProfileProviderOC","kind":"identifier"}]},{"op":"replace","value":[{"kind":"identifier","text":"CallUserProfileProviderOC"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallUserProfileProviderOC\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}