{"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit"]]},"metadata":{"navigatorTitle":[{"kind":"identifier","text":"CallUserProfile"}],"externalID":"c:@M@EaseCallUIKit@objc(cs)CallUserProfile","title":"CallUserProfile","symbolKind":"class","roleHeading":"Class","modules":[{"name":"EaseCallUIKit"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"CallUserProfile","kind":"identifier"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallUserProfile"},"relationshipsSections":[{"title":"Inherits From","identifiers":["doc:\/\/org.cocoapods.EaseCallUIKit\/objc(cs)NSObject"],"type":"inheritsFrom","kind":"relationships"},{"title":"Conforms To","identifiers":["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallProfileProtocol","doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)NSObject","doc:\/\/org.cocoapods.EaseCallUIKit\/s7CVarArgP","doc:\/\/org.cocoapods.EaseCallUIKit\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.EaseCallUIKit\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.EaseCallUIKit\/SQ","doc:\/\/org.cocoapods.EaseCallUIKit\/SH"],"kind":"relationships","type":"conformsTo"}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objcMembers","kind":"attribute"},{"kind":"text","text":" "},{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"CallUserProfile","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/easecalluikit\/calluserprofile"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/easecalluikit\/calluserprofile"],"traits":[{"interfaceLanguage":"occ"}]}],"topicSections":[{"title":"Instance Properties","generated":true,"identifiers":["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallUserProfile\/avatarURL","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallUserProfile\/id","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallUserProfile\/nickname","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallUserProfile\/selected"],"anchor":"Instance-Properties"},{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallUserProfile\/setValue(_:forUndefinedKey:)","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallUserProfile\/toJsonObject()"],"generated":true,"anchor":"Instance-Methods"}],"references":{"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallProfileProtocol":{"url":"\/documentation\/easecalluikit\/callprofileprotocol","role":"symbol","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallProfileProtocol","navigatorTitle":[{"kind":"identifier","text":"CallProfileProtocol"}],"abstract":[],"title":"CallProfileProtocol","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CallProfileProtocol"}]},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit":{"title":"EaseCallUIKit","type":"topic","url":"\/documentation\/easecalluikit","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit","abstract":[],"role":"collection","kind":"symbol"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallUserProfile/init":{"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallUserProfile\/init","kind":"symbol","abstract":[],"url":"\/documentation\/easecalluikit\/calluserprofile\/init","navigatorTitle":[{"text":"init","kind":"identifier"}],"title":"init","type":"topic","role":"symbol","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}]},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallUserProfile/toJsonObject()":{"abstract":[],"type":"topic","kind":"symbol","title":"toJsonObject()","navigatorTitle":[{"kind":"identifier","text":"toJsonObject"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"toJsonObject"},{"text":"() -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SD","text":"Dictionary"},{"text":"<","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"Any","kind":"keyword"},{"kind":"text","text":">?"}],"role":"symbol","url":"\/documentation\/easecalluikit\/calluserprofile\/tojsonobject()","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallUserProfile\/toJsonObject()"},"doc://org.cocoapods.EaseCallUIKit/SH":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/SH","title":"Swift.Hashable"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallUserProfile":{"type":"topic","title":"CallUserProfile","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallUserProfile","url":"\/documentation\/easecalluikit\/calluserprofile","role":"symbol","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"CallUserProfile"}],"navigatorTitle":[{"kind":"identifier","text":"CallUserProfile"}],"abstract":[]},"doc://org.cocoapods.EaseCallUIKit/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://org.cocoapods.EaseCallUIKit/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/s7CVarArgP","title":"Swift.CVarArg"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallUserProfile/id":{"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallUserProfile\/id","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"id","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"navigatorTitle":[{"kind":"identifier","text":"id"}],"type":"topic","url":"\/documentation\/easecalluikit\/calluserprofile\/id","role":"symbol","abstract":[],"kind":"symbol","title":"id"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallUserProfile/avatarURL":{"url":"\/documentation\/easecalluikit\/calluserprofile\/avatarurl","abstract":[],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"avatarURL"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"navigatorTitle":[{"text":"avatarURL","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallUserProfile\/avatarURL","kind":"symbol","type":"topic","title":"avatarURL","role":"symbol"},"doc://org.cocoapods.EaseCallUIKit/s23CustomStringConvertibleP":{"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallUserProfile/selected":{"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallUserProfile\/selected","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"selected"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"navigatorTitle":[{"kind":"identifier","text":"selected"}],"type":"topic","url":"\/documentation\/easecalluikit\/calluserprofile\/selected","role":"symbol","abstract":[],"kind":"symbol","title":"selected"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallUserProfile/setValue(_:forUndefinedKey:)":{"navigatorTitle":[{"text":"setValue:forUndefinedKey:","kind":"identifier"}],"abstract":[],"title":"setValue(_:forUndefinedKey:)","type":"topic","kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallUserProfile\/setValue(_:forUndefinedKey:)","url":"\/documentation\/easecalluikit\/calluserprofile\/setvalue(_:forundefinedkey:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"setValue","kind":"identifier"},{"kind":"text","text":"("},{"text":"Any","kind":"keyword"},{"kind":"text","text":"?, "},{"text":"forUndefinedKey","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallUserProfile/nickname":{"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallUserProfile\/nickname","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"nickname","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"navigatorTitle":[{"kind":"identifier","text":"nickname"}],"type":"topic","url":"\/documentation\/easecalluikit\/calluserprofile\/nickname","role":"symbol","abstract":[],"kind":"symbol","title":"nickname"},"doc://org.cocoapods.EaseCallUIKit/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"},"doc://org.cocoapods.EaseCallUIKit/SQ":{"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://org.cocoapods.EaseCallUIKit/objc(cs)NSObject":{"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/objc(cs)NSObject","title":"NSObject","type":"unresolvable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"CallUserProfile"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"CallUserProfile","kind":"identifier"}]},{"op":"replace","value":[{"kind":"identifier","text":"CallUserProfile"}],"path":"\/metadata\/navigatorTitle"},{"value":[{"generated":true,"identifiers":["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallUserProfile\/avatarURL","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallUserProfile\/id","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallUserProfile\/nickname","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallUserProfile\/selected"],"title":"Instance Properties","anchor":"Instance-Properties"},{"identifiers":["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallUserProfile\/init","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallUserProfile\/setValue(_:forUndefinedKey:)","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallUserProfile\/toJsonObject()"],"anchor":"Instance-Methods","title":"Instance Methods","generated":true}],"op":"replace","path":"\/topicSections"},{"value":[{"title":"Inherits From","type":"inheritsFrom","kind":"relationships","identifiers":["doc:\/\/org.cocoapods.EaseCallUIKit\/objc(cs)NSObject"]},{"identifiers":["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallProfileProtocol"],"type":"conformsTo","title":"Conforms To","kind":"relationships"}],"op":"replace","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@interface"},{"text":" ","kind":"text"},{"text":"CallUserProfile","kind":"identifier"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"CallProfileProtocol","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallProfileProtocol\/title"},{"value":[{"kind":"identifier","text":"CallProfileProtocol"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallProfileProtocol\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallProfileProtocol\/navigatorTitle","op":"replace","value":[{"text":"CallProfileProtocol","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallUserProfile~1toJsonObject()\/title","value":"toJsonObject","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallUserProfile~1toJsonObject()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"toJsonObject","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallUserProfile\/title","value":"CallUserProfile"},{"value":[{"text":"CallUserProfile","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallUserProfile\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallUserProfile\/navigatorTitle","value":[{"kind":"identifier","text":"CallUserProfile"}]},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallUserProfile~1id\/title","op":"replace","value":"id"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallUserProfile~1id\/fragments","value":[{"text":"id","kind":"identifier"}]},{"value":"avatarURL","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallUserProfile~1avatarURL\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallUserProfile~1avatarURL\/fragments","op":"replace","value":[{"text":"avatarURL","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallUserProfile~1selected\/title","value":"selected","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallUserProfile~1selected\/fragments","value":[{"text":"selected","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"setValue:forUndefinedKey:","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallUserProfile~1setValue(_:forUndefinedKey:)\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallUserProfile~1setValue(_:forUndefinedKey:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setValue:forUndefinedKey:"}]},{"value":"nickname","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallUserProfile~1nickname\/title"},{"op":"replace","value":[{"text":"nickname","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallUserProfile~1nickname\/fragments"}]}]}