{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallMultiViewController"},"relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/org.cocoapods.EaseCallUIKit\/objc(cs)UIViewController"],"title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)NSCoding","doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)NSExtensionRequestHandling","doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)NSObject","doc:\/\/org.cocoapods.EaseCallUIKit\/s7CVarArgP","doc:\/\/org.cocoapods.EaseCallUIKit\/s8CopyableP","doc:\/\/org.cocoapods.EaseCallUIKit\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.EaseCallUIKit\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.EaseCallUIKit\/SQ","doc:\/\/org.cocoapods.EaseCallUIKit\/SH","doc:\/\/org.cocoapods.EaseCallUIKit\/s8SendableP","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/TimerServiceListener","doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)UIAppearanceContainer","doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)UIContentContainer","doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)UIFocusEnvironment","doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)UIResponderStandardEditActions","doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)UIStateRestoring","doc:\/\/org.cocoapods.EaseCallUIKit\/5UIKit23UITraitChangeObservableP","doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)UITraitEnvironment","doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)UIUserActivityRestoring"],"kind":"relationships","type":"conformsTo","title":"Conforms To"}],"kind":"symbol","topicSections":[{"title":"Initializers","anchor":"Initializers","generated":true,"identifiers":["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallMultiViewController\/init(coder:)","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallMultiViewController\/init(role:)"]},{"anchor":"Instance-Properties","generated":true,"title":"Instance Properties","identifiers":["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallMultiViewController\/background","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallMultiViewController\/bottomView","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallMultiViewController\/callView","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallMultiViewController\/navigationBar","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallMultiViewController\/role"]},{"identifiers":["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallMultiViewController\/addCallTimer()","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallMultiViewController\/bottomClick(type:)","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallMultiViewController\/dismiss(animated:completion:)","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallMultiViewController\/navigationClick(type:indexPath:)","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallMultiViewController\/pop()","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallMultiViewController\/rightAction()","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallMultiViewController\/touchesEnded(_:with:)","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallMultiViewController\/viewDidAppear(_:)","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallMultiViewController\/viewDidLoad()"],"generated":true,"title":"Instance Methods","anchor":"Instance-Methods"},{"anchor":"Default-Implementations","generated":true,"title":"Default Implementations","identifiers":["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallMultiViewController\/TimerServiceListener-Implementations"]}],"variants":[{"paths":["\/documentation\/easecalluikit\/callmultiviewcontroller"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/easecalluikit\/callmultiviewcontroller"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"metadata":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CallMultiViewController"}],"symbolKind":"class","roleHeading":"Class","externalID":"c:@M@EaseCallUIKit@objc(cs)CallMultiViewController","title":"CallMultiViewController","navigatorTitle":[{"kind":"identifier","text":"CallMultiViewController"}],"role":"symbol","modules":[{"name":"EaseCallUIKit"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@","kind":"attribute"},{"kind":"attribute","preciseIdentifier":"s:ScM","text":"MainActor"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CallMultiViewController","kind":"identifier"}],"languages":["swift"]}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit"]]},"references":{"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallMultiViewController/rightAction()":{"role":"symbol","title":"rightAction()","url":"\/documentation\/easecalluikit\/callmultiviewcontroller\/rightaction()","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"rightAction","kind":"identifier"},{"kind":"text","text":"()"}],"type":"topic","kind":"symbol","navigatorTitle":[{"text":"rightAction","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallMultiViewController\/rightAction()"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallMultiViewController/dismiss(animated:completion:)":{"url":"\/documentation\/easecalluikit\/callmultiviewcontroller\/dismiss(animated:completion:)","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallMultiViewController\/dismiss(animated:completion:)","role":"symbol","abstract":[],"type":"topic","title":"dismiss(animated:completion:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"dismiss"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"animated"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": (() -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?)"}],"navigatorTitle":[{"text":"dismissViewControllerAnimated:completion:","kind":"identifier"}],"kind":"symbol"},"doc://org.cocoapods.EaseCallUIKit/objc(cs)UIViewController":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/objc(cs)UIViewController","title":"UIViewController"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallMultiViewController":{"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallMultiViewController","kind":"symbol","abstract":[],"type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"CallMultiViewController","kind":"identifier"}],"navigatorTitle":[{"text":"CallMultiViewController","kind":"identifier"}],"url":"\/documentation\/easecalluikit\/callmultiviewcontroller","title":"CallMultiViewController"},"doc://org.cocoapods.EaseCallUIKit/objc(pl)UIContentContainer":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)UIContentContainer","title":"UIKit.UIContentContainer"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallMultiViewController/addCallTimer()":{"navigatorTitle":[{"text":"addCallTimer","kind":"identifier"}],"title":"addCallTimer()","kind":"symbol","url":"\/documentation\/easecalluikit\/callmultiviewcontroller\/addcalltimer()","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"addCallTimer"},{"text":"()","kind":"text"}],"abstract":[],"role":"symbol","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallMultiViewController\/addCallTimer()","type":"topic"},"doc://org.cocoapods.EaseCallUIKit/s8CopyableP":{"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/s8CopyableP","type":"unresolvable","title":"Swift.Copyable"},"doc://org.cocoapods.EaseCallUIKit/SQ":{"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallMultiViewController/bottomClick(type:)":{"navigatorTitle":[{"text":"bottomClickWithType:","kind":"identifier"}],"abstract":[],"url":"\/documentation\/easecalluikit\/callmultiviewcontroller\/bottomclick(type:)","kind":"symbol","title":"bottomClick(type:)","type":"topic","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallMultiViewController\/bottomClick(type:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"bottomClick"},{"kind":"text","text":"("},{"text":"type","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CallButtonType","preciseIdentifier":"c:@M@EaseCallUIKit@E@CallButtonType","kind":"typeIdentifier"},{"kind":"text","text":")"}]},"doc://org.cocoapods.EaseCallUIKit/objc(pl)UIPasteConfigurationSupporting":{"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)UIPasteConfigurationSupporting","type":"unresolvable","title":"UIKit.UIPasteConfigurationSupporting"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallMultiViewController/role":{"url":"\/documentation\/easecalluikit\/callmultiviewcontroller\/role","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"role"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@EaseCallUIKit@E@CallRole","text":"CallRole","kind":"typeIdentifier"}],"title":"role","abstract":[],"type":"topic","role":"symbol","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallMultiViewController\/role"},"doc://org.cocoapods.EaseCallUIKit/objc(pl)NSExtensionRequestHandling":{"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)NSExtensionRequestHandling","type":"unresolvable","title":"Foundation.NSExtensionRequestHandling"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallMultiViewController/navigationClick(type:indexPath:)":{"navigatorTitle":[{"kind":"identifier","text":"navigationClickWithType:indexPath:"}],"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallMultiViewController\/navigationClick(type:indexPath:)","title":"navigationClick(type:indexPath:)","abstract":[],"url":"\/documentation\/easecalluikit\/callmultiviewcontroller\/navigationclick(type:indexpath:)","type":"topic","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"navigationClick"},{"text":"(","kind":"text"},{"text":"type","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"ChatNavigationBarClickEvent","kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseCallUIKit@E@ChatNavigationBarClickEvent"},{"kind":"text","text":", "},{"text":"indexPath","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation9IndexPathV","kind":"typeIdentifier","text":"IndexPath"},{"text":"?)","kind":"text"}],"kind":"symbol"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallMultiViewController/TimerServiceListener-Implementations":{"role":"collectionGroup","kind":"article","type":"topic","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallMultiViewController\/TimerServiceListener-Implementations","abstract":[],"title":"TimerServiceListener Implementations","url":"\/documentation\/easecalluikit\/callmultiviewcontroller\/timerservicelistener-implementations"},"doc://org.cocoapods.EaseCallUIKit/objc(pl)UITraitEnvironment":{"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)UITraitEnvironment","type":"unresolvable","title":"UIKit.UITraitEnvironment"},"doc://org.cocoapods.EaseCallUIKit/SH":{"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://org.cocoapods.EaseCallUIKit/objc(pl)UIActivityItemsConfigurationProviding":{"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)UIActivityItemsConfigurationProviding","type":"unresolvable","title":"UIKit.UIActivityItemsConfigurationProviding"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallMultiViewController/pop()":{"type":"topic","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallMultiViewController\/pop()","navigatorTitle":[{"text":"pop","kind":"identifier"}],"kind":"symbol","abstract":[],"role":"symbol","title":"pop()","url":"\/documentation\/easecalluikit\/callmultiviewcontroller\/pop()","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"pop","kind":"identifier"},{"text":"()","kind":"text"}]},"doc://org.cocoapods.EaseCallUIKit/s23CustomStringConvertibleP":{"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"},"doc://org.cocoapods.EaseCallUIKit/objc(pl)UIStateRestoring":{"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)UIStateRestoring","type":"unresolvable","title":"UIKit.UIStateRestoring"},"doc://org.cocoapods.EaseCallUIKit/objc(pl)UIAppearanceContainer":{"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)UIAppearanceContainer","type":"unresolvable","title":"UIKit.UIAppearanceContainer"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallMultiViewController/init(coder:)":{"navigatorTitle":[{"text":"initWithCoder:","kind":"identifier"}],"title":"init(coder:)","kind":"symbol","url":"\/documentation\/easecalluikit\/callmultiviewcontroller\/init(coder:)","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"coder"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSCoder","text":"NSCoder"},{"text":")","kind":"text"}],"abstract":[],"role":"symbol","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallMultiViewController\/init(coder:)","type":"topic"},"doc://org.cocoapods.EaseCallUIKit/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallMultiViewController/background":{"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallMultiViewController\/background","title":"background","kind":"symbol","abstract":[],"type":"topic","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"background","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIImageView","preciseIdentifier":"c:objc(cs)UIImageView"}],"role":"symbol","url":"\/documentation\/easecalluikit\/callmultiviewcontroller\/background"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallMultiViewController/touchesEnded(_:with:)":{"navigatorTitle":[{"kind":"identifier","text":"touchesEnded:withEvent:"}],"title":"touchesEnded(_:with:)","kind":"symbol","url":"\/documentation\/easecalluikit\/callmultiviewcontroller\/touchesended(_:with:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"touchesEnded","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"s:Sh","kind":"typeIdentifier","text":"Set"},{"text":"<","kind":"text"},{"text":"UITouch","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UITouch"},{"text":">, ","kind":"text"},{"text":"with","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIEvent","preciseIdentifier":"c:objc(cs)UIEvent"},{"text":"?)","kind":"text"}],"abstract":[],"role":"symbol","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallMultiViewController\/touchesEnded(_:with:)","type":"topic"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallMultiViewController/bottomView":{"abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallMultiViewController\/bottomView","title":"bottomView","url":"\/documentation\/easecalluikit\/callmultiviewcontroller\/bottomview","type":"topic","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"bottomView"},{"text":": ","kind":"text"},{"text":"MultiCallBottomView","preciseIdentifier":"c:@M@EaseCallUIKit@objc(cs)MultiCallBottomView","kind":"typeIdentifier"}],"kind":"symbol"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallMultiViewController/callView":{"title":"callView","kind":"symbol","url":"\/documentation\/easecalluikit\/callmultiviewcontroller\/callview","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"callView"},{"kind":"text","text":": "},{"text":"MultiPersonCallView","preciseIdentifier":"c:@M@EaseCallUIKit@objc(cs)MultiPersonCallView","kind":"typeIdentifier"}],"abstract":[],"role":"symbol","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallMultiViewController\/callView","type":"topic"},"doc://org.cocoapods.EaseCallUIKit/5UIKit23UITraitChangeObservableP":{"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/5UIKit23UITraitChangeObservableP","type":"unresolvable","title":"UIKit.UITraitChangeObservable"},"doc://org.cocoapods.EaseCallUIKit/objc(pl)NSCoding":{"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)NSCoding","type":"unresolvable","title":"Foundation.NSCoding"},"doc://org.cocoapods.EaseCallUIKit/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/s28CustomDebugStringConvertibleP","type":"unresolvable","title":"Swift.CustomDebugStringConvertible"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallMultiViewController/navigationBar":{"title":"navigationBar","kind":"symbol","url":"\/documentation\/easecalluikit\/callmultiviewcontroller\/navigationbar","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"navigationBar"},{"text":": ","kind":"text"},{"text":"CallNavigationBar","preciseIdentifier":"c:@M@EaseCallUIKit@objc(cs)CallNavigationBar","kind":"typeIdentifier"}],"abstract":[],"role":"symbol","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallMultiViewController\/navigationBar","type":"topic"},"doc://org.cocoapods.EaseCallUIKit/objc(pl)UIUserActivityRestoring":{"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)UIUserActivityRestoring","title":"UIKit.UIUserActivityRestoring","type":"unresolvable"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/TimerServiceListener":{"url":"\/documentation\/easecalluikit\/timerservicelistener","kind":"symbol","role":"symbol","title":"TimerServiceListener","navigatorTitle":[{"text":"TimerServiceListener","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/TimerServiceListener","abstract":[],"type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"TimerServiceListener"}]},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallMultiViewController/init(role:)":{"navigatorTitle":[{"kind":"identifier","text":"initWithRole:"}],"title":"init(role:)","url":"\/documentation\/easecalluikit\/callmultiviewcontroller\/init(role:)","type":"topic","abstract":[],"kind":"symbol","role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"role"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"CallRole","preciseIdentifier":"c:@M@EaseCallUIKit@E@CallRole"},{"text":")","kind":"text"}],"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallMultiViewController\/init(role:)"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit":{"title":"EaseCallUIKit","type":"topic","url":"\/documentation\/easecalluikit","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit","abstract":[],"role":"collection","kind":"symbol"},"doc://org.cocoapods.EaseCallUIKit/objc(pl)UIFocusEnvironment":{"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)UIFocusEnvironment","title":"UIKit.UIFocusEnvironment","type":"unresolvable"},"doc://org.cocoapods.EaseCallUIKit/s8SendableP":{"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/s8SendableP","title":"Swift.Sendable","type":"unresolvable"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallMultiViewController/viewDidLoad()":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"viewDidLoad"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallMultiViewController\/viewDidLoad()","title":"viewDidLoad()","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"viewDidLoad"},{"text":"()","kind":"text"}],"url":"\/documentation\/easecalluikit\/callmultiviewcontroller\/viewdidload()","abstract":[]},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallMultiViewController/viewDidAppear(_:)":{"title":"viewDidAppear(_:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"viewDidAppear"},{"kind":"text","text":"("},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"kind":"text","text":")"}],"type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"viewDidAppear:"}],"url":"\/documentation\/easecalluikit\/callmultiviewcontroller\/viewdidappear(_:)","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallMultiViewController\/viewDidAppear(_:)"},"doc://org.cocoapods.EaseCallUIKit/objc(pl)UIResponderStandardEditActions":{"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)UIResponderStandardEditActions","title":"UIKit.UIResponderStandardEditActions","type":"unresolvable"},"doc://org.cocoapods.EaseCallUIKit/s7CVarArgP":{"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/s7CVarArgP","title":"Swift.CVarArg","type":"unresolvable"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"path":"\/metadata\/title","value":"CallMultiViewController","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"class"},{"op":"replace","value":[{"text":"CallMultiViewController","kind":"identifier"}],"path":"\/metadata\/fragments"},{"path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"CallMultiViewController"}],"op":"replace"},{"op":"replace","path":"\/topicSections","value":[{"anchor":"Instance-Methods","title":"Instance Methods","generated":true,"identifiers":["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallMultiViewController\/addCallTimer()","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallMultiViewController\/bottomClick(type:)","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallMultiViewController\/dismiss(animated:completion:)","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallMultiViewController\/init(coder:)","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallMultiViewController\/init(role:)","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallMultiViewController\/navigationClick(type:indexPath:)","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallMultiViewController\/pop()","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallMultiViewController\/rightAction()","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallMultiViewController\/touchesEnded(_:with:)","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallMultiViewController\/viewDidAppear(_:)","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallMultiViewController\/viewDidLoad()"]},{"anchor":"Default-Implementations","generated":true,"identifiers":["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallMultiViewController\/TimerServiceListener-Implementations"],"title":"Default Implementations"}]},{"path":"\/relationshipsSections","value":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/org.cocoapods.EaseCallUIKit\/objc(cs)UIViewController"],"type":"inheritsFrom"},{"identifiers":["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/TimerServiceListener"],"type":"conformsTo","kind":"relationships","title":"Conforms To"}],"op":"replace"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"text":"CallMultiViewController","kind":"identifier"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:objc(cs)UIViewController","kind":"typeIdentifier","text":"UIViewController"}],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallMultiViewController~1rightAction()\/title","value":"rightAction","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallMultiViewController~1rightAction()\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"rightAction","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallMultiViewController~1dismiss(animated:completion:)\/title","value":"dismissViewControllerAnimated:completion:"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallMultiViewController~1dismiss(animated:completion:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"dismissViewControllerAnimated:completion:"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallMultiViewController\/title","op":"replace","value":"CallMultiViewController"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallMultiViewController\/fragments","value":[{"text":"CallMultiViewController","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallMultiViewController\/navigatorTitle","op":"replace","value":[{"text":"CallMultiViewController","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallMultiViewController~1addCallTimer()\/title","value":"addCallTimer"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallMultiViewController~1addCallTimer()\/fragments","value":[{"kind":"text","text":"- "},{"text":"addCallTimer","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallMultiViewController~1bottomClick(type:)\/title","value":"bottomClickWithType:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallMultiViewController~1bottomClick(type:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"bottomClickWithType:"}]},{"value":"navigationClickWithType:indexPath:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallMultiViewController~1navigationClick(type:indexPath:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"navigationClickWithType:indexPath:"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallMultiViewController~1navigationClick(type:indexPath:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallMultiViewController~1pop()\/title","value":"pop"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallMultiViewController~1pop()\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"pop"}]},{"value":"initWithCoder:","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallMultiViewController~1init(coder:)\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallMultiViewController~1init(coder:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithCoder:"}]},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallMultiViewController~1touchesEnded(_:with:)\/title","op":"replace","value":"touchesEnded:withEvent:"},{"value":[{"text":"- ","kind":"text"},{"text":"touchesEnded:withEvent:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallMultiViewController~1touchesEnded(_:with:)\/fragments"},{"value":"TimerServiceListener","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1TimerServiceListener\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1TimerServiceListener\/fragments","value":[{"kind":"identifier","text":"TimerServiceListener"}]},{"op":"replace","value":[{"kind":"identifier","text":"TimerServiceListener"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1TimerServiceListener\/navigatorTitle"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallMultiViewController~1init(role:)\/title","op":"replace","value":"initWithRole:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallMultiViewController~1init(role:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"initWithRole:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallMultiViewController~1viewDidLoad()\/title","value":"viewDidLoad","op":"replace"},{"value":[{"kind":"text","text":"- "},{"text":"viewDidLoad","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallMultiViewController~1viewDidLoad()\/fragments"},{"value":"viewDidAppear:","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallMultiViewController~1viewDidAppear(_:)\/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"viewDidAppear:"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallMultiViewController~1viewDidAppear(_:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}