{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit"]]},"relationshipsSections":[{"title":"Conforms To","type":"conformsTo","kind":"relationships","identifiers":["doc:\/\/org.cocoapods.EaseCallUIKit\/SQ","doc:\/\/org.cocoapods.EaseCallUIKit\/SH","doc:\/\/org.cocoapods.EaseCallUIKit\/SY"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallButtonType"},"metadata":{"externalID":"c:@M@EaseCallUIKit@E@CallButtonType","navigatorTitle":[{"text":"CallButtonType","kind":"identifier"}],"title":"CallButtonType","symbolKind":"enum","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"CallButtonType","kind":"identifier"}],"roleHeading":"Enumeration","role":"symbol","modules":[{"name":"EaseCallUIKit"}]},"sections":[],"topicSections":[{"identifiers":["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallButtonType\/accept","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallButtonType\/camera_off","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallButtonType\/camera_on","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallButtonType\/decline","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallButtonType\/end","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallButtonType\/flip_back","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallButtonType\/flip_front","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallButtonType\/mic_off","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallButtonType\/mic_on","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallButtonType\/screen_share_off","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallButtonType\/screen_share_on","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallButtonType\/speaker_off","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallButtonType\/speaker_on","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallButtonType\/virtual_off","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallButtonType\/virtual_on"],"generated":true,"anchor":"Enumeration-Cases","title":"Enumeration Cases"},{"anchor":"Initializers","identifiers":["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallButtonType\/init(rawValue:)"],"generated":true,"title":"Initializers"},{"title":"Default Implementations","identifiers":["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallButtonType\/Equatable-Implementations","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallButtonType\/RawRepresentable-Implementations"],"generated":true,"anchor":"Default-Implementations"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"CallButtonType","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easecalluikit\/callbuttontype"]},{"paths":["\/documentation\/easecalluikit\/callbuttontype"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit":{"title":"EaseCallUIKit","type":"topic","url":"\/documentation\/easecalluikit","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit","abstract":[],"role":"collection","kind":"symbol"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallButtonType/RawRepresentable-Implementations":{"kind":"article","type":"topic","url":"\/documentation\/easecalluikit\/callbuttontype\/rawrepresentable-implementations","title":"RawRepresentable Implementations","role":"collectionGroup","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallButtonType\/RawRepresentable-Implementations"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallButtonType/speaker_off":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallButtonType\/speaker_off","abstract":[],"url":"\/documentation\/easecalluikit\/callbuttontype\/speaker_off","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"speaker_off","kind":"identifier"}],"role":"symbol","type":"topic","title":"CallButtonType.speaker_off","navigatorTitle":[{"text":"CallButtonTypeSpeaker_off","kind":"identifier"}]},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallButtonType/flip_front":{"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallButtonType\/flip_front","kind":"symbol","title":"CallButtonType.flip_front","abstract":[],"type":"topic","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"flip_front"}],"role":"symbol","url":"\/documentation\/easecalluikit\/callbuttontype\/flip_front","navigatorTitle":[{"kind":"identifier","text":"CallButtonTypeFlip_front"}]},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallButtonType/screen_share_off":{"abstract":[],"kind":"symbol","title":"CallButtonType.screen_share_off","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallButtonType\/screen_share_off","url":"\/documentation\/easecalluikit\/callbuttontype\/screen_share_off","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"screen_share_off"}],"navigatorTitle":[{"text":"CallButtonTypeScreen_share_off","kind":"identifier"}],"role":"symbol","type":"topic"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallButtonType":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CallButtonType","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/easecalluikit\/callbuttontype","abstract":[],"type":"topic","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallButtonType","title":"CallButtonType","navigatorTitle":[{"text":"CallButtonType","kind":"identifier"}],"role":"symbol"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallButtonType/speaker_on":{"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"speaker_on","kind":"identifier"}],"title":"CallButtonType.speaker_on","type":"topic","kind":"symbol","url":"\/documentation\/easecalluikit\/callbuttontype\/speaker_on","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallButtonType\/speaker_on","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"CallButtonTypeSpeaker_on"}],"role":"symbol"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallButtonType/camera_on":{"title":"CallButtonType.camera_on","navigatorTitle":[{"text":"CallButtonTypeCamera_on","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallButtonType\/camera_on","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"camera_on","kind":"identifier"}],"abstract":[],"url":"\/documentation\/easecalluikit\/callbuttontype\/camera_on","role":"symbol","type":"topic"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallButtonType/end":{"type":"topic","url":"\/documentation\/easecalluikit\/callbuttontype\/end","kind":"symbol","navigatorTitle":[{"text":"CallButtonTypeEnd","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallButtonType\/end","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"end","kind":"identifier"}],"title":"CallButtonType.end","abstract":[]},"doc://org.cocoapods.EaseCallUIKit/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/SH"},"doc://org.cocoapods.EaseCallUIKit/SY":{"title":"Swift.RawRepresentable","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/SY"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallButtonType/mic_off":{"type":"topic","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"CallButtonTypeMic_off","kind":"identifier"}],"title":"CallButtonType.mic_off","url":"\/documentation\/easecalluikit\/callbuttontype\/mic_off","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"mic_off","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallButtonType\/mic_off","abstract":[]},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallButtonType/flip_back":{"abstract":[],"url":"\/documentation\/easecalluikit\/callbuttontype\/flip_back","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallButtonType\/flip_back","type":"topic","title":"CallButtonType.flip_back","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"flip_back"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"CallButtonTypeFlip_back","kind":"identifier"}]},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallButtonType/screen_share_on":{"type":"topic","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallButtonType\/screen_share_on","role":"symbol","url":"\/documentation\/easecalluikit\/callbuttontype\/screen_share_on","navigatorTitle":[{"kind":"identifier","text":"CallButtonTypeScreen_share_on"}],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"screen_share_on"}],"title":"CallButtonType.screen_share_on"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallButtonType/mic_on":{"url":"\/documentation\/easecalluikit\/callbuttontype\/mic_on","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallButtonType\/mic_on","role":"symbol","abstract":[],"type":"topic","title":"CallButtonType.mic_on","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mic_on","kind":"identifier"}],"navigatorTitle":[{"text":"CallButtonTypeMic_on","kind":"identifier"}],"kind":"symbol"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallButtonType/virtual_on":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallButtonType\/virtual_on","abstract":[],"url":"\/documentation\/easecalluikit\/callbuttontype\/virtual_on","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"virtual_on","kind":"identifier"}],"role":"symbol","type":"topic","title":"CallButtonType.virtual_on","navigatorTitle":[{"text":"CallButtonTypeVirtual_on","kind":"identifier"}]},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallButtonType/virtual_off":{"navigatorTitle":[{"text":"CallButtonTypeVirtual_off","kind":"identifier"}],"kind":"symbol","type":"topic","url":"\/documentation\/easecalluikit\/callbuttontype\/virtual_off","title":"CallButtonType.virtual_off","role":"symbol","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallButtonType\/virtual_off","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"virtual_off","kind":"identifier"}]},"doc://org.cocoapods.EaseCallUIKit/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/SQ"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallButtonType/accept":{"abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallButtonType\/accept","title":"CallButtonType.accept","url":"\/documentation\/easecalluikit\/callbuttontype\/accept","kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"accept"}],"type":"topic","role":"symbol","navigatorTitle":[{"text":"CallButtonTypeAccept","kind":"identifier"}]},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallButtonType/init(rawValue:)":{"type":"topic","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallButtonType\/init(rawValue:)","kind":"symbol","role":"symbol","url":"\/documentation\/easecalluikit\/callbuttontype\/init(rawvalue:)","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"?("},{"text":"rawValue","kind":"externalParam"},{"kind":"text","text":": "},{"text":"UInt","preciseIdentifier":"s:Su","kind":"typeIdentifier"},{"text":")","kind":"text"}],"title":"init(rawValue:)","abstract":[]},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallButtonType/decline":{"type":"topic","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallButtonType\/decline","role":"symbol","url":"\/documentation\/easecalluikit\/callbuttontype\/decline","navigatorTitle":[{"kind":"identifier","text":"CallButtonTypeDecline"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"decline","kind":"identifier"}],"title":"CallButtonType.decline"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallButtonType/Equatable-Implementations":{"title":"Equatable Implementations","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallButtonType\/Equatable-Implementations","role":"collectionGroup","url":"\/documentation\/easecalluikit\/callbuttontype\/equatable-implementations","type":"topic","kind":"article","abstract":[]},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallButtonType/camera_off":{"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallButtonType\/camera_off","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"camera_off"}],"navigatorTitle":[{"text":"CallButtonTypeCamera_off","kind":"identifier"}],"url":"\/documentation\/easecalluikit\/callbuttontype\/camera_off","role":"symbol","abstract":[],"title":"CallButtonType.camera_off","kind":"symbol","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration"},{"path":"\/metadata\/title","op":"replace","value":"CallButtonType"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"path":"\/metadata\/fragments","value":[{"text":"CallButtonType","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"CallButtonType","kind":"identifier"}]},{"path":"\/topicSections","value":[{"title":"Enumeration Cases","anchor":"Enumeration-Cases","generated":true,"identifiers":["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallButtonType\/accept","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallButtonType\/camera_off","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallButtonType\/camera_on","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallButtonType\/decline","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallButtonType\/end","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallButtonType\/flip_back","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallButtonType\/flip_front","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallButtonType\/mic_off","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallButtonType\/mic_on","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallButtonType\/screen_share_off","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallButtonType\/screen_share_on","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallButtonType\/speaker_off","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallButtonType\/speaker_on","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallButtonType\/virtual_off","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallButtonType\/virtual_on"]}],"op":"replace"},{"value":null,"path":"\/relationshipsSections","op":"replace"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"CallButtonType"},{"kind":"text","text":": "},{"text":"NSUInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSUInteger"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallButtonType~1speaker_off\/title","value":"CallButtonTypeSpeaker_off"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallButtonType~1speaker_off\/fragments","value":[{"text":"CallButtonTypeSpeaker_off","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallButtonType~1flip_front\/title","value":"CallButtonTypeFlip_front"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallButtonType~1flip_front\/fragments","value":[{"text":"CallButtonTypeFlip_front","kind":"identifier"}]},{"op":"replace","value":"CallButtonTypeScreen_share_off","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallButtonType~1screen_share_off\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallButtonType~1screen_share_off\/fragments","value":[{"kind":"identifier","text":"CallButtonTypeScreen_share_off"}]},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallButtonType\/title","value":"CallButtonType","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallButtonType\/fragments","value":[{"kind":"identifier","text":"CallButtonType"}]},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallButtonType\/navigatorTitle","value":[{"kind":"identifier","text":"CallButtonType"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallButtonType~1speaker_on\/title","value":"CallButtonTypeSpeaker_on"},{"value":[{"kind":"identifier","text":"CallButtonTypeSpeaker_on"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallButtonType~1speaker_on\/fragments"},{"value":"CallButtonTypeCamera_on","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallButtonType~1camera_on\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallButtonType~1camera_on\/fragments","op":"replace","value":[{"text":"CallButtonTypeCamera_on","kind":"identifier"}]},{"value":"CallButtonTypeEnd","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallButtonType~1end\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallButtonType~1end\/fragments","op":"replace","value":[{"text":"CallButtonTypeEnd","kind":"identifier"}]},{"value":"CallButtonTypeMic_off","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallButtonType~1mic_off\/title"},{"op":"replace","value":[{"kind":"identifier","text":"CallButtonTypeMic_off"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallButtonType~1mic_off\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallButtonType~1flip_back\/title","value":"CallButtonTypeFlip_back","op":"replace"},{"value":[{"kind":"identifier","text":"CallButtonTypeFlip_back"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallButtonType~1flip_back\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallButtonType~1screen_share_on\/title","value":"CallButtonTypeScreen_share_on"},{"value":[{"text":"CallButtonTypeScreen_share_on","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallButtonType~1screen_share_on\/fragments","op":"replace"},{"value":"CallButtonTypeMic_on","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallButtonType~1mic_on\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallButtonType~1mic_on\/fragments","op":"replace","value":[{"kind":"identifier","text":"CallButtonTypeMic_on"}]},{"op":"replace","value":"CallButtonTypeVirtual_on","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallButtonType~1virtual_on\/title"},{"value":[{"text":"CallButtonTypeVirtual_on","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallButtonType~1virtual_on\/fragments","op":"replace"},{"op":"replace","value":"CallButtonTypeVirtual_off","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallButtonType~1virtual_off\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallButtonType~1virtual_off\/fragments","value":[{"kind":"identifier","text":"CallButtonTypeVirtual_off"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallButtonType~1accept\/title","value":"CallButtonTypeAccept"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallButtonType~1accept\/fragments","value":[{"text":"CallButtonTypeAccept","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"CallButtonTypeDecline","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallButtonType~1decline\/title"},{"op":"replace","value":[{"kind":"identifier","text":"CallButtonTypeDecline"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallButtonType~1decline\/fragments"},{"value":"CallButtonTypeCamera_off","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallButtonType~1camera_off\/title","op":"replace"},{"value":[{"kind":"identifier","text":"CallButtonTypeCamera_off"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallButtonType~1camera_off\/fragments","op":"replace"}]}]}