{"topicSections":[{"generated":true,"title":"Initializers","identifiers":["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/Call1v1VideoViewController\/init(coder:)","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/Call1v1VideoViewController\/init(role:)"],"anchor":"Initializers"},{"title":"Instance Properties","generated":true,"identifiers":["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/Call1v1VideoViewController\/background","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/Call1v1VideoViewController\/bottomView","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/Call1v1VideoViewController\/callView","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/Call1v1VideoViewController\/floatView","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/Call1v1VideoViewController\/localStreamTag","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/Call1v1VideoViewController\/micView","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/Call1v1VideoViewController\/navigationBar","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/Call1v1VideoViewController\/pipController","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/Call1v1VideoViewController\/remoteStreamTag","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/Call1v1VideoViewController\/role","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/Call1v1VideoViewController\/videoCallbackController"],"anchor":"Instance-Properties"},{"identifiers":["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/Call1v1VideoViewController\/bottomClick(type:)","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/Call1v1VideoViewController\/dismiss(animated:completion:)","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/Call1v1VideoViewController\/navigationClick(type:indexPath:)","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/Call1v1VideoViewController\/pop()","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/Call1v1VideoViewController\/touchesBegan(_:with:)","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/Call1v1VideoViewController\/viewDidLoad()","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/Call1v1VideoViewController\/viewIsAppearing(_:)","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/Call1v1VideoViewController\/viewWillAppear(_:)","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/Call1v1VideoViewController\/viewWillDisappear(_:)"],"title":"Instance Methods","generated":true,"anchor":"Instance-Methods"},{"identifiers":["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/Call1v1VideoViewController\/AVPictureInPictureControllerDelegate-Implementations","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/Call1v1VideoViewController\/TimerServiceListener-Implementations"],"title":"Default Implementations","anchor":"Default-Implementations","generated":true}],"sections":[],"variants":[{"paths":["\/documentation\/easecalluikit\/call1v1videoviewcontroller"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/easecalluikit\/call1v1videoviewcontroller"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@","kind":"attribute"},{"kind":"attribute","preciseIdentifier":"s:ScM","text":"MainActor"},{"text":" ","kind":"text"},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"Call1v1VideoViewController","kind":"identifier"}]}],"kind":"declarations"}],"relationshipsSections":[{"title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/org.cocoapods.EaseCallUIKit\/objc(cs)UIViewController"],"type":"inheritsFrom"},{"title":"Conforms To","type":"conformsTo","kind":"relationships","identifiers":["doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)AVPictureInPictureControllerDelegate","doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)NSCoding","doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)NSExtensionRequestHandling","doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)NSObject","doc:\/\/org.cocoapods.EaseCallUIKit\/s7CVarArgP","doc:\/\/org.cocoapods.EaseCallUIKit\/s8CopyableP","doc:\/\/org.cocoapods.EaseCallUIKit\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.EaseCallUIKit\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.EaseCallUIKit\/SQ","doc:\/\/org.cocoapods.EaseCallUIKit\/SH","doc:\/\/org.cocoapods.EaseCallUIKit\/s8SendableP","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/TimerServiceListener","doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)UIAppearanceContainer","doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)UIContentContainer","doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)UIFocusEnvironment","doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)UIResponderStandardEditActions","doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)UIStateRestoring","doc:\/\/org.cocoapods.EaseCallUIKit\/5UIKit23UITraitChangeObservableP","doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)UITraitEnvironment","doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)UIUserActivityRestoring"]}],"metadata":{"title":"Call1v1VideoViewController","roleHeading":"Class","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Call1v1VideoViewController"}],"externalID":"c:@M@EaseCallUIKit@objc(cs)Call1v1VideoViewController","modules":[{"name":"EaseCallUIKit"}],"symbolKind":"class","role":"symbol","navigatorTitle":[{"text":"Call1v1VideoViewController","kind":"identifier"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/Call1v1VideoViewController"},"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://org.cocoapods.EaseCallUIKit/objc(pl)UIPasteConfigurationSupporting":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)UIPasteConfigurationSupporting","title":"UIKit.UIPasteConfigurationSupporting"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/Call1v1VideoViewController/pop()":{"title":"pop()","kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/Call1v1VideoViewController\/pop()","role":"symbol","url":"\/documentation\/easecalluikit\/call1v1videoviewcontroller\/pop()","abstract":[],"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"pop","kind":"identifier"},{"kind":"text","text":"()"}],"navigatorTitle":[{"text":"pop","kind":"identifier"}]},"doc://org.cocoapods.EaseCallUIKit/objc(pl)UIResponderStandardEditActions":{"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)UIResponderStandardEditActions","type":"unresolvable","title":"UIKit.UIResponderStandardEditActions"},"doc://org.cocoapods.EaseCallUIKit/objc(pl)UIUserActivityRestoring":{"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)UIUserActivityRestoring","type":"unresolvable","title":"UIKit.UIUserActivityRestoring"},"doc://org.cocoapods.EaseCallUIKit/objc(pl)NSExtensionRequestHandling":{"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)NSExtensionRequestHandling","type":"unresolvable","title":"Foundation.NSExtensionRequestHandling"},"doc://org.cocoapods.EaseCallUIKit/SH":{"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/Call1v1VideoViewController/viewIsAppearing(_:)":{"title":"viewIsAppearing(_:)","role":"symbol","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/Call1v1VideoViewController\/viewIsAppearing(_:)","url":"\/documentation\/easecalluikit\/call1v1videoviewcontroller\/viewisappearing(_:)","kind":"symbol","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"viewIsAppearing","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"viewIsAppearing:"}]},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/Call1v1VideoViewController/init(coder:)":{"title":"init(coder:)","kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/Call1v1VideoViewController\/init(coder:)","role":"symbol","url":"\/documentation\/easecalluikit\/call1v1videoviewcontroller\/init(coder:)","abstract":[],"type":"topic","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"text":"coder","kind":"externalParam"},{"kind":"text","text":": "},{"text":"NSCoder","preciseIdentifier":"c:objc(cs)NSCoder","kind":"typeIdentifier"},{"kind":"text","text":")"}],"navigatorTitle":[{"text":"initWithCoder:","kind":"identifier"}]},"doc://org.cocoapods.EaseCallUIKit/objc(pl)AVPictureInPictureControllerDelegate":{"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)AVPictureInPictureControllerDelegate","type":"unresolvable","title":"AVPictureInPictureControllerDelegate"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/Call1v1VideoViewController/localStreamTag":{"abstract":[],"url":"\/documentation\/easecalluikit\/call1v1videoviewcontroller\/localstreamtag","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/Call1v1VideoViewController\/localStreamTag","type":"topic","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"localStreamTag","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"kind":"symbol","title":"localStreamTag"},"doc://org.cocoapods.EaseCallUIKit/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/s28CustomDebugStringConvertibleP","type":"unresolvable","title":"Swift.CustomDebugStringConvertible"},"doc://org.cocoapods.EaseCallUIKit/s8SendableP":{"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/s8SendableP","type":"unresolvable","title":"Swift.Sendable"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/Call1v1VideoViewController/navigationBar":{"title":"navigationBar","kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/Call1v1VideoViewController\/navigationBar","role":"symbol","url":"\/documentation\/easecalluikit\/call1v1videoviewcontroller\/navigationbar","abstract":[],"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"navigationBar","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@EaseCallUIKit@objc(cs)CallNavigationBar","text":"CallNavigationBar","kind":"typeIdentifier"}]},"doc://org.cocoapods.EaseCallUIKit/SQ":{"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/Call1v1VideoViewController/navigationClick(type:indexPath:)":{"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/Call1v1VideoViewController\/navigationClick(type:indexPath:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"navigationClick","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"type"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@EaseCallUIKit@E@ChatNavigationBarClickEvent","text":"ChatNavigationBarClickEvent","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"indexPath","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"IndexPath","preciseIdentifier":"s:10Foundation9IndexPathV","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"kind":"symbol","navigatorTitle":[{"text":"navigationClickWithType:indexPath:","kind":"identifier"}],"abstract":[],"title":"navigationClick(type:indexPath:)","type":"topic","url":"\/documentation\/easecalluikit\/call1v1videoviewcontroller\/navigationclick(type:indexpath:)"},"doc://org.cocoapods.EaseCallUIKit/objc(pl)NSObject":{"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/Call1v1VideoViewController/viewDidLoad()":{"title":"viewDidLoad()","role":"symbol","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/Call1v1VideoViewController\/viewDidLoad()","url":"\/documentation\/easecalluikit\/call1v1videoviewcontroller\/viewdidload()","kind":"symbol","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"viewDidLoad","kind":"identifier"},{"kind":"text","text":"()"}],"navigatorTitle":[{"text":"viewDidLoad","kind":"identifier"}]},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/Call1v1VideoViewController/bottomClick(type:)":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"bottomClickWithType:"}],"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/Call1v1VideoViewController\/bottomClick(type:)","role":"symbol","type":"topic","url":"\/documentation\/easecalluikit\/call1v1videoviewcontroller\/bottomclick(type:)","abstract":[],"title":"bottomClick(type:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"bottomClick"},{"kind":"text","text":"("},{"text":"type","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseCallUIKit@E@CallButtonType","text":"CallButtonType"},{"text":")","kind":"text"}]},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/Call1v1VideoViewController/videoCallbackController":{"title":"videoCallbackController","kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/Call1v1VideoViewController\/videoCallbackController","role":"symbol","url":"\/documentation\/easecalluikit\/call1v1videoviewcontroller\/videocallbackcontroller","abstract":[{"type":"text","text":"Video container view for Picture-in-Picture"}],"type":"topic","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"videoCallbackController"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)AVPictureInPictureVideoCallViewController","kind":"typeIdentifier","text":"AVPictureInPictureVideoCallViewController"},{"text":"?","kind":"text"}]},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/Call1v1VideoViewController/floatView":{"url":"\/documentation\/easecalluikit\/call1v1videoviewcontroller\/floatview","kind":"symbol","type":"topic","role":"symbol","title":"floatView","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"floatView","kind":"identifier"},{"text":": ","kind":"text"},{"text":"PixelBufferRenderView","kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseCallUIKit@objc(cs)PixelBufferRenderView"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/Call1v1VideoViewController\/floatView"},"doc://org.cocoapods.EaseCallUIKit/s7CVarArgP":{"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/s7CVarArgP","type":"unresolvable","title":"Swift.CVarArg"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/Call1v1VideoViewController/background":{"abstract":[],"url":"\/documentation\/easecalluikit\/call1v1videoviewcontroller\/background","kind":"symbol","title":"background","type":"topic","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/Call1v1VideoViewController\/background","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"background","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImageView","text":"UIImageView"}]},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/Call1v1VideoViewController/init(role:)":{"url":"\/documentation\/easecalluikit\/call1v1videoviewcontroller\/init(role:)","kind":"symbol","type":"topic","role":"symbol","title":"init(role:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"role","kind":"externalParam"},{"kind":"text","text":": "},{"text":"CallRole","kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseCallUIKit@E@CallRole"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/Call1v1VideoViewController\/init(role:)","navigatorTitle":[{"kind":"identifier","text":"initWithRole:"}]},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/Call1v1VideoViewController/callView":{"title":"callView","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/Call1v1VideoViewController\/callView","url":"\/documentation\/easecalluikit\/call1v1videoviewcontroller\/callview","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"callView","kind":"identifier"},{"kind":"text","text":": "},{"text":"PixelBufferRenderView","preciseIdentifier":"c:@M@EaseCallUIKit@objc(cs)PixelBufferRenderView","kind":"typeIdentifier"}],"type":"topic","abstract":[]},"doc://org.cocoapods.EaseCallUIKit/objc(pl)NSCoding":{"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)NSCoding","type":"unresolvable","title":"Foundation.NSCoding"},"doc://org.cocoapods.EaseCallUIKit/s23CustomStringConvertibleP":{"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/Call1v1VideoViewController/remoteStreamTag":{"abstract":[],"title":"remoteStreamTag","type":"topic","kind":"symbol","url":"\/documentation\/easecalluikit\/call1v1videoviewcontroller\/remotestreamtag","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"remoteStreamTag","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/Call1v1VideoViewController\/remoteStreamTag","role":"symbol"},"doc://org.cocoapods.EaseCallUIKit/objc(cs)UIViewController":{"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/objc(cs)UIViewController","type":"unresolvable","title":"UIViewController"},"doc://org.cocoapods.EaseCallUIKit/objc(pl)UIAppearanceContainer":{"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)UIAppearanceContainer","type":"unresolvable","title":"UIKit.UIAppearanceContainer"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/Call1v1VideoViewController/role":{"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/Call1v1VideoViewController\/role","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"role","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CallRole","preciseIdentifier":"c:@M@EaseCallUIKit@E@CallRole"}],"abstract":[],"title":"role","role":"symbol","url":"\/documentation\/easecalluikit\/call1v1videoviewcontroller\/role"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/Call1v1VideoViewController/AVPictureInPictureControllerDelegate-Implementations":{"abstract":[],"kind":"article","type":"topic","title":"AVPictureInPictureControllerDelegate Implementations","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/Call1v1VideoViewController\/AVPictureInPictureControllerDelegate-Implementations","role":"collectionGroup","url":"\/documentation\/easecalluikit\/call1v1videoviewcontroller\/avpictureinpicturecontrollerdelegate-implementations"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/Call1v1VideoViewController/TimerServiceListener-Implementations":{"role":"collectionGroup","title":"TimerServiceListener Implementations","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/Call1v1VideoViewController\/TimerServiceListener-Implementations","type":"topic","kind":"article","url":"\/documentation\/easecalluikit\/call1v1videoviewcontroller\/timerservicelistener-implementations","abstract":[]},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/TimerServiceListener":{"url":"\/documentation\/easecalluikit\/timerservicelistener","kind":"symbol","role":"symbol","title":"TimerServiceListener","navigatorTitle":[{"text":"TimerServiceListener","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/TimerServiceListener","abstract":[],"type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"TimerServiceListener"}]},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/Call1v1VideoViewController/touchesBegan(_:with:)":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"touchesBegan","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"s:Sh","text":"Set"},{"text":"<","kind":"text"},{"text":"UITouch","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UITouch"},{"text":">, ","kind":"text"},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIEvent","text":"UIEvent","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"kind":"symbol","title":"touchesBegan(_:with:)","abstract":[],"navigatorTitle":[{"text":"touchesBegan:withEvent:","kind":"identifier"}],"role":"symbol","url":"\/documentation\/easecalluikit\/call1v1videoviewcontroller\/touchesbegan(_:with:)","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/Call1v1VideoViewController\/touchesBegan(_:with:)","type":"topic"},"doc://org.cocoapods.EaseCallUIKit/objc(pl)UIFocusEnvironment":{"title":"UIKit.UIFocusEnvironment","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)UIFocusEnvironment","type":"unresolvable"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/Call1v1VideoViewController":{"abstract":[],"type":"topic","kind":"symbol","title":"Call1v1VideoViewController","navigatorTitle":[{"kind":"identifier","text":"Call1v1VideoViewController"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"Call1v1VideoViewController","kind":"identifier"}],"role":"symbol","url":"\/documentation\/easecalluikit\/call1v1videoviewcontroller","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/Call1v1VideoViewController"},"doc://org.cocoapods.EaseCallUIKit/objc(pl)UIContentContainer":{"title":"UIKit.UIContentContainer","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)UIContentContainer","type":"unresolvable"},"doc://org.cocoapods.EaseCallUIKit/5UIKit23UITraitChangeObservableP":{"title":"UIKit.UITraitChangeObservable","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/5UIKit23UITraitChangeObservableP","type":"unresolvable"},"doc://org.cocoapods.EaseCallUIKit/s8CopyableP":{"title":"Swift.Copyable","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/s8CopyableP","type":"unresolvable"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/Call1v1VideoViewController/pipController":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/Call1v1VideoViewController\/pipController","type":"topic","url":"\/documentation\/easecalluikit\/call1v1videoviewcontroller\/pipcontroller","abstract":[{"text":"Picture-in-Picture controller","type":"text"}],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"pipController"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)AVPictureInPictureController","text":"AVPictureInPictureController","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"title":"pipController"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit":{"title":"EaseCallUIKit","type":"topic","url":"\/documentation\/easecalluikit","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit","abstract":[],"role":"collection","kind":"symbol"},"doc://org.cocoapods.EaseCallUIKit/objc(pl)UITraitEnvironment":{"title":"UIKit.UITraitEnvironment","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)UITraitEnvironment"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/Call1v1VideoViewController/viewWillAppear(_:)":{"title":"viewWillAppear(_:)","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/Call1v1VideoViewController\/viewWillAppear(_:)","kind":"symbol","abstract":[],"type":"topic","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"viewWillAppear"},{"kind":"text","text":"("},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"text":")","kind":"text"}],"role":"symbol","url":"\/documentation\/easecalluikit\/call1v1videoviewcontroller\/viewwillappear(_:)","navigatorTitle":[{"text":"viewWillAppear:","kind":"identifier"}]},"doc://org.cocoapods.EaseCallUIKit/objc(pl)UIActivityItemsConfigurationProviding":{"title":"UIKit.UIActivityItemsConfigurationProviding","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)UIActivityItemsConfigurationProviding"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/Call1v1VideoViewController/micView":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"micView"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIImageView","text":"UIImageView","kind":"typeIdentifier"}],"kind":"symbol","title":"micView","abstract":[],"role":"symbol","url":"\/documentation\/easecalluikit\/call1v1videoviewcontroller\/micview","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/Call1v1VideoViewController\/micView","type":"topic"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/Call1v1VideoViewController/viewWillDisappear(_:)":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/Call1v1VideoViewController\/viewWillDisappear(_:)","type":"topic","url":"\/documentation\/easecalluikit\/call1v1videoviewcontroller\/viewwilldisappear(_:)","navigatorTitle":[{"text":"viewWillDisappear:","kind":"identifier"}],"abstract":[],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewWillDisappear"},{"text":"(","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":")","kind":"text"}],"title":"viewWillDisappear(_:)"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/Call1v1VideoViewController/bottomView":{"abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/Call1v1VideoViewController\/bottomView","type":"topic","title":"bottomView","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"bottomView","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseCallUIKit@objc(cs)MultiCallBottomView","text":"MultiCallBottomView"}],"role":"symbol","url":"\/documentation\/easecalluikit\/call1v1videoviewcontroller\/bottomview","kind":"symbol"},"doc://org.cocoapods.EaseCallUIKit/objc(pl)UIStateRestoring":{"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)UIStateRestoring","title":"UIKit.UIStateRestoring","type":"unresolvable"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/Call1v1VideoViewController/dismiss(animated:completion:)":{"type":"topic","url":"\/documentation\/easecalluikit\/call1v1videoviewcontroller\/dismiss(animated:completion:)","kind":"symbol","title":"dismiss(animated:completion:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"dismiss","kind":"identifier"},{"kind":"text","text":"("},{"text":"animated","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": (() -> "},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"kind":"text","text":")?)"}],"abstract":[],"role":"symbol","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/Call1v1VideoViewController\/dismiss(animated:completion:)","navigatorTitle":[{"text":"dismissViewControllerAnimated:completion:","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"Call1v1VideoViewController"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"value":[{"text":"Call1v1VideoViewController","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"kind":"identifier","text":"Call1v1VideoViewController"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":[{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/Call1v1VideoViewController\/bottomClick(type:)","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/Call1v1VideoViewController\/dismiss(animated:completion:)","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/Call1v1VideoViewController\/init(coder:)","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/Call1v1VideoViewController\/init(role:)","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/Call1v1VideoViewController\/navigationClick(type:indexPath:)","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/Call1v1VideoViewController\/pop()","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/Call1v1VideoViewController\/touchesBegan(_:with:)","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/Call1v1VideoViewController\/viewDidLoad()","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/Call1v1VideoViewController\/viewIsAppearing(_:)","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/Call1v1VideoViewController\/viewWillAppear(_:)","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/Call1v1VideoViewController\/viewWillDisappear(_:)"],"generated":true,"anchor":"Instance-Methods"},{"title":"Default Implementations","anchor":"Default-Implementations","generated":true,"identifiers":["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/Call1v1VideoViewController\/AVPictureInPictureControllerDelegate-Implementations","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/Call1v1VideoViewController\/TimerServiceListener-Implementations"]}],"op":"replace","path":"\/topicSections"},{"value":[{"kind":"relationships","identifiers":["doc:\/\/org.cocoapods.EaseCallUIKit\/objc(cs)UIViewController"],"title":"Inherits From","type":"inheritsFrom"},{"type":"conformsTo","kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)AVPictureInPictureControllerDelegate","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/TimerServiceListener"]}],"op":"replace","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Call1v1VideoViewController","kind":"identifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController","kind":"typeIdentifier"}],"languages":["occ"]}],"kind":"declarations"}},{"value":"pop","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1Call1v1VideoViewController~1pop()\/title"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"pop"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1Call1v1VideoViewController~1pop()\/fragments"},{"op":"replace","value":"viewIsAppearing:","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1Call1v1VideoViewController~1viewIsAppearing(_:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"viewIsAppearing:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1Call1v1VideoViewController~1viewIsAppearing(_:)\/fragments"},{"value":"initWithCoder:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1Call1v1VideoViewController~1init(coder:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1Call1v1VideoViewController~1init(coder:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithCoder:"}]},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1Call1v1VideoViewController~1navigationClick(type:indexPath:)\/title","op":"replace","value":"navigationClickWithType:indexPath:"},{"value":[{"text":"- ","kind":"text"},{"text":"navigationClickWithType:indexPath:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1Call1v1VideoViewController~1navigationClick(type:indexPath:)\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1Call1v1VideoViewController~1viewDidLoad()\/title","value":"viewDidLoad","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1Call1v1VideoViewController~1viewDidLoad()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"viewDidLoad","kind":"identifier"}]},{"value":"bottomClickWithType:","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1Call1v1VideoViewController~1bottomClick(type:)\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1Call1v1VideoViewController~1bottomClick(type:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"bottomClickWithType:","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"initWithRole:","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1Call1v1VideoViewController~1init(role:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1Call1v1VideoViewController~1init(role:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithRole:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1TimerServiceListener\/title","value":"TimerServiceListener"},{"value":[{"kind":"identifier","text":"TimerServiceListener"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1TimerServiceListener\/fragments"},{"op":"replace","value":[{"text":"TimerServiceListener","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1TimerServiceListener\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1Call1v1VideoViewController~1touchesBegan(_:with:)\/title","value":"touchesBegan:withEvent:"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"touchesBegan:withEvent:"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1Call1v1VideoViewController~1touchesBegan(_:with:)\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1Call1v1VideoViewController\/title","op":"replace","value":"Call1v1VideoViewController"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1Call1v1VideoViewController\/fragments","value":[{"kind":"identifier","text":"Call1v1VideoViewController"}]},{"op":"replace","value":[{"text":"Call1v1VideoViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1Call1v1VideoViewController\/navigatorTitle"},{"op":"replace","value":"viewWillAppear:","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1Call1v1VideoViewController~1viewWillAppear(_:)\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1Call1v1VideoViewController~1viewWillAppear(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"viewWillAppear:"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1Call1v1VideoViewController~1viewWillDisappear(_:)\/title","value":"viewWillDisappear:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1Call1v1VideoViewController~1viewWillDisappear(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"viewWillDisappear:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1Call1v1VideoViewController~1dismiss(animated:completion:)\/title","value":"dismissViewControllerAnimated:completion:"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"dismissViewControllerAnimated:completion:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1Call1v1VideoViewController~1dismiss(animated:completion:)\/fragments"}]}]}