{"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"CallEndReason","kind":"identifier"}],"platforms":["iOS"]}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"variants":[{"paths":["\/documentation\/easecalluikit\/callendreason"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/easecalluikit\/callendreason"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallEndReason","interfaceLanguage":"swift"},"metadata":{"roleHeading":"Enumeration","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CallEndReason"}],"navigatorTitle":[{"text":"CallEndReason","kind":"identifier"}],"role":"symbol","symbolKind":"enum","modules":[{"name":"EaseCallUIKit"}],"title":"CallEndReason","externalID":"c:@M@EaseCallUIKit@E@CallEndReason"},"kind":"symbol","topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallEndReason\/abnormalEnd","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallEndReason\/busy","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallEndReason\/cancel","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallEndReason\/handleOnOtherDevice","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallEndReason\/hangup","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallEndReason\/noResponse","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallEndReason\/refuse","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallEndReason\/remoteCancel","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallEndReason\/remoteNoResponse","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallEndReason\/remoteRefuse"],"generated":true,"anchor":"Enumeration-Cases"},{"title":"Initializers","generated":true,"anchor":"Initializers","identifiers":["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallEndReason\/init(rawValue:)"]},{"generated":true,"title":"Default Implementations","anchor":"Default-Implementations","identifiers":["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallEndReason\/Equatable-Implementations","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallEndReason\/RawRepresentable-Implementations"]}],"relationshipsSections":[{"title":"Conforms To","type":"conformsTo","kind":"relationships","identifiers":["doc:\/\/org.cocoapods.EaseCallUIKit\/SQ","doc:\/\/org.cocoapods.EaseCallUIKit\/SH","doc:\/\/org.cocoapods.EaseCallUIKit\/SY"]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit"]]},"references":{"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallEndReason/remoteRefuse":{"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallEndReason\/remoteRefuse","title":"CallEndReason.remoteRefuse","role":"symbol","url":"\/documentation\/easecalluikit\/callendreason\/remoterefuse","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"remoteRefuse","kind":"identifier"}],"navigatorTitle":[{"text":"CallEndReasonRemoteRefuse","kind":"identifier"}],"type":"topic","kind":"symbol","abstract":[]},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallEndReason/init(rawValue:)":{"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallEndReason\/init(rawValue:)","kind":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"text":"rawValue","kind":"externalParam"},{"kind":"text","text":": "},{"text":"UInt","preciseIdentifier":"s:Su","kind":"typeIdentifier"},{"text":")","kind":"text"}],"type":"topic","url":"\/documentation\/easecalluikit\/callendreason\/init(rawvalue:)","role":"symbol","abstract":[],"title":"init(rawValue:)"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallEndReason/cancel":{"navigatorTitle":[{"text":"CallEndReasonCancel","kind":"identifier"}],"url":"\/documentation\/easecalluikit\/callendreason\/cancel","kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"cancel"}],"title":"CallEndReason.cancel","abstract":[],"type":"topic","role":"symbol","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallEndReason\/cancel"},"doc://org.cocoapods.EaseCallUIKit/SH":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/SH","title":"Swift.Hashable"},"doc://org.cocoapods.EaseCallUIKit/SQ":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/SQ","title":"Swift.Equatable"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallEndReason/hangup":{"navigatorTitle":[{"kind":"identifier","text":"CallEndReasonHangup"}],"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallEndReason\/hangup","type":"topic","kind":"symbol","url":"\/documentation\/easecalluikit\/callendreason\/hangup","abstract":[],"role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"hangup"}],"title":"CallEndReason.hangup"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallEndReason/remoteNoResponse":{"role":"symbol","title":"CallEndReason.remoteNoResponse","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"remoteNoResponse","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"CallEndReasonRemoteNoResponse","kind":"identifier"}],"abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallEndReason\/remoteNoResponse","url":"\/documentation\/easecalluikit\/callendreason\/remotenoresponse"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallEndReason/Equatable-Implementations":{"abstract":[],"title":"Equatable Implementations","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallEndReason\/Equatable-Implementations","url":"\/documentation\/easecalluikit\/callendreason\/equatable-implementations","type":"topic","kind":"article","role":"collectionGroup"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallEndReason/refuse":{"url":"\/documentation\/easecalluikit\/callendreason\/refuse","kind":"symbol","navigatorTitle":[{"text":"CallEndReasonRefuse","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallEndReason\/refuse","type":"topic","title":"CallEndReason.refuse","abstract":[],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"refuse"}]},"doc://org.cocoapods.EaseCallUIKit/SY":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/SY","title":"Swift.RawRepresentable"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallEndReason/handleOnOtherDevice":{"navigatorTitle":[{"text":"CallEndReasonHandleOnOtherDevice","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallEndReason\/handleOnOtherDevice","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"handleOnOtherDevice"}],"type":"topic","url":"\/documentation\/easecalluikit\/callendreason\/handleonotherdevice","role":"symbol","abstract":[],"title":"CallEndReason.handleOnOtherDevice"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallEndReason/busy":{"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallEndReason\/busy","title":"CallEndReason.busy","role":"symbol","url":"\/documentation\/easecalluikit\/callendreason\/busy","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"busy"}],"navigatorTitle":[{"kind":"identifier","text":"CallEndReasonBusy"}],"type":"topic","kind":"symbol","abstract":[]},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallEndReason/noResponse":{"title":"CallEndReason.noResponse","kind":"symbol","role":"symbol","url":"\/documentation\/easecalluikit\/callendreason\/noresponse","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"noResponse","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"CallEndReasonNoResponse"}],"type":"topic","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallEndReason\/noResponse"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit":{"title":"EaseCallUIKit","type":"topic","url":"\/documentation\/easecalluikit","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit","abstract":[],"role":"collection","kind":"symbol"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallEndReason":{"type":"topic","kind":"symbol","title":"CallEndReason","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallEndReason","navigatorTitle":[{"text":"CallEndReason","kind":"identifier"}],"abstract":[],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CallEndReason"}],"url":"\/documentation\/easecalluikit\/callendreason","role":"symbol"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallEndReason/RawRepresentable-Implementations":{"url":"\/documentation\/easecalluikit\/callendreason\/rawrepresentable-implementations","kind":"article","title":"RawRepresentable Implementations","abstract":[],"type":"topic","role":"collectionGroup","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallEndReason\/RawRepresentable-Implementations"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallEndReason/abnormalEnd":{"abstract":[],"url":"\/documentation\/easecalluikit\/callendreason\/abnormalend","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallEndReason\/abnormalEnd","type":"topic","title":"CallEndReason.abnormalEnd","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"abnormalEnd","kind":"identifier"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"CallEndReasonAbnormalEnd","kind":"identifier"}]},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallEndReason/remoteCancel":{"role":"symbol","kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallEndReason\/remoteCancel","title":"CallEndReason.remoteCancel","url":"\/documentation\/easecalluikit\/callendreason\/remotecancel","navigatorTitle":[{"kind":"identifier","text":"CallEndReasonRemoteCancel"}],"type":"topic","abstract":[],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"remoteCancel","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Enumeration","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"CallEndReason"},{"path":"\/metadata\/symbolKind","op":"replace","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"CallEndReason"}]},{"value":[{"text":"CallEndReason","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","generated":true,"anchor":"Enumeration-Cases","identifiers":["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallEndReason\/abnormalEnd","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallEndReason\/busy","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallEndReason\/cancel","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallEndReason\/handleOnOtherDevice","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallEndReason\/hangup","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallEndReason\/noResponse","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallEndReason\/refuse","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallEndReason\/remoteCancel","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallEndReason\/remoteNoResponse","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallEndReason\/remoteRefuse"]}]},{"value":null,"path":"\/relationshipsSections","op":"replace"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","value":{"declarations":[{"tokens":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"CallEndReason"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSUInteger","text":"NSUInteger"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallEndReason~1remoteRefuse\/title","value":"CallEndReasonRemoteRefuse"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallEndReason~1remoteRefuse\/fragments","value":[{"text":"CallEndReasonRemoteRefuse","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallEndReason~1cancel\/title","value":"CallEndReasonCancel"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallEndReason~1cancel\/fragments","value":[{"kind":"identifier","text":"CallEndReasonCancel"}]},{"op":"replace","value":"CallEndReasonHangup","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallEndReason~1hangup\/title"},{"op":"replace","value":[{"kind":"identifier","text":"CallEndReasonHangup"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallEndReason~1hangup\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallEndReason~1remoteNoResponse\/title","value":"CallEndReasonRemoteNoResponse"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallEndReason~1remoteNoResponse\/fragments","value":[{"kind":"identifier","text":"CallEndReasonRemoteNoResponse"}]},{"op":"replace","value":"CallEndReasonRefuse","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallEndReason~1refuse\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallEndReason~1refuse\/fragments","value":[{"text":"CallEndReasonRefuse","kind":"identifier"}]},{"value":"CallEndReasonHandleOnOtherDevice","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallEndReason~1handleOnOtherDevice\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallEndReason~1handleOnOtherDevice\/fragments","op":"replace","value":[{"kind":"identifier","text":"CallEndReasonHandleOnOtherDevice"}]},{"value":"CallEndReasonBusy","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallEndReason~1busy\/title"},{"value":[{"text":"CallEndReasonBusy","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallEndReason~1busy\/fragments","op":"replace"},{"op":"replace","value":"CallEndReasonNoResponse","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallEndReason~1noResponse\/title"},{"op":"replace","value":[{"text":"CallEndReasonNoResponse","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallEndReason~1noResponse\/fragments"},{"value":"CallEndReason","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallEndReason\/title"},{"op":"replace","value":[{"text":"CallEndReason","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallEndReason\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallEndReason\/navigatorTitle","value":[{"text":"CallEndReason","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallEndReason~1abnormalEnd\/title","op":"replace","value":"CallEndReasonAbnormalEnd"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallEndReason~1abnormalEnd\/fragments","value":[{"text":"CallEndReasonAbnormalEnd","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallEndReason~1remoteCancel\/title","value":"CallEndReasonRemoteCancel"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallEndReason~1remoteCancel\/fragments","op":"replace","value":[{"text":"CallEndReasonRemoteCancel","kind":"identifier"}]}]}]}