{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easecalluikit\/callkitmanager"]},{"paths":["\/documentation\/easecalluikit\/callkitmanager"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"relationshipsSections":[{"identifiers":["doc:\/\/org.cocoapods.EaseCallUIKit\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"title":"Conforms To","identifiers":["doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)AgoraRtcEngineDelegate","doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)AgoraVideoFrameDelegate","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallMessageService","doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)EMChatManagerDelegate","doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)EMClientDelegate","doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)NSObject","doc:\/\/org.cocoapods.EaseCallUIKit\/s7CVarArgP","doc:\/\/org.cocoapods.EaseCallUIKit\/s8CopyableP","doc:\/\/org.cocoapods.EaseCallUIKit\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.EaseCallUIKit\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.EaseCallUIKit\/SQ","doc:\/\/org.cocoapods.EaseCallUIKit\/SH","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/TimerServiceListener"],"type":"conformsTo","kind":"relationships"}],"kind":"symbol","topicSections":[{"anchor":"Instance-Properties","identifiers":["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager\/appID","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager\/callInfo","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager\/callVC","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager\/canvasCache","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager\/config","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager\/currentUserInfo","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager\/currentUserRTCUID","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager\/engine","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager\/isVideoExchanged","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager\/itemsCache","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager\/lastPIPFrame","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager\/listeners","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager\/popup","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager\/profileProvider","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager\/profileProviderOC","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager\/receivedCalls","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager\/token","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager\/tokenProvider","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager\/usersCache"],"generated":true,"title":"Instance Properties"},{"anchor":"Instance-Methods","title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager\/calleeAnswerCaller(callId:callerId:callerDeviceId:)","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager\/callerConfirmAnswer(callId:calleeId:calleeDeviceId:result:)","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager\/cancelCall(callId:calleeId:)","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager\/cleanUserDefaults()","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager\/confirmRing(callId:calleeId:calleeDeviceId:is_valid:)","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager\/exchangeVideoFrame()","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager\/resetVideoExchange()","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager\/sendCancelSignal(callId:calleeId:)","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager\/setup(_:)","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager\/setupEngine()","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager\/tearDown()"],"generated":true},{"generated":true,"title":"Type Properties","identifiers":["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager\/shared"],"anchor":"Type-Properties"},{"generated":true,"title":"Default Implementations","anchor":"Default-Implementations","identifiers":["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager\/AgoraRtcEngineDelegate-Implementations","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager\/AgoraVideoFrameDelegate-Implementations","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager\/CallMessageService-Implementations","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager\/EMChatManagerDelegate-Implementations","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager\/EMClientDelegate-Implementations","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager\/TimerServiceListener-Implementations"]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit"]]},"metadata":{"role":"symbol","symbolKind":"class","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CallKitManager","kind":"identifier"}],"roleHeading":"Class","externalID":"c:@M@EaseCallUIKit@objc(cs)CallKitManager","navigatorTitle":[{"kind":"identifier","text":"CallKitManager"}],"title":"CallKitManager","modules":[{"name":"EaseCallUIKit"}]},"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objcMembers","kind":"attribute"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CallKitManager","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager","interfaceLanguage":"swift"},"references":{"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallKitManager/profileProvider":{"title":"profileProvider","type":"topic","abstract":[{"type":"text","text":"Provider for user profiles"}],"role":"symbol","kind":"symbol","url":"\/documentation\/easecalluikit\/callkitmanager\/profileprovider","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"profileProvider","kind":"identifier"},{"kind":"text","text":": "},{"text":"CallUserProfileProvider","preciseIdentifier":"s:13EaseCallUIKit0B19UserProfileProviderP","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager\/profileProvider"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallKitManager/EMClientDelegate-Implementations":{"role":"collectionGroup","title":"EMClientDelegate Implementations","url":"\/documentation\/easecalluikit\/callkitmanager\/emclientdelegate-implementations","kind":"article","abstract":[],"type":"topic","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager\/EMClientDelegate-Implementations"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallMessageService":{"type":"topic","url":"\/documentation\/easecalluikit\/callmessageservice","kind":"symbol","navigatorTitle":[{"text":"CallMessageService","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallMessageService","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"CallMessageService","kind":"identifier"}],"title":"CallMessageService","abstract":[]},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallKitManager/callerConfirmAnswer(callId:calleeId:calleeDeviceId:result:)":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"callerConfirmAnswerWithCallId:calleeId:calleeDeviceId:result:"}],"kind":"symbol","type":"topic","title":"callerConfirmAnswer(callId:calleeId:calleeDeviceId:result:)","url":"\/documentation\/easecalluikit\/callkitmanager\/callerconfirmanswer(callid:calleeid:calleedeviceid:result:)","abstract":[{"text":"Confirm the answer to a call from the caller.","type":"text"}],"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager\/callerConfirmAnswer(callId:calleeId:calleeDeviceId:result:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"callerConfirmAnswer"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"callId"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"calleeId","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"calleeDeviceId"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"result"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}]},"doc://org.cocoapods.EaseCallUIKit/objc(pl)AgoraRtcEngineDelegate":{"type":"unresolvable","title":"AgoraRtcEngineDelegate","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)AgoraRtcEngineDelegate"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallKitManager/token":{"type":"topic","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager\/token","navigatorTitle":[{"text":"token","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"Current user token for Agora SDK","type":"text"}],"role":"symbol","title":"token","url":"\/documentation\/easecalluikit\/callkitmanager\/token","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"token","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}]},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit":{"title":"EaseCallUIKit","type":"topic","url":"\/documentation\/easecalluikit","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit","abstract":[],"role":"collection","kind":"symbol"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallKitManager":{"role":"symbol","title":"CallKitManager","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CallKitManager"}],"abstract":[],"type":"topic","kind":"symbol","url":"\/documentation\/easecalluikit\/callkitmanager","navigatorTitle":[{"text":"CallKitManager","kind":"identifier"}]},"doc://org.cocoapods.EaseCallUIKit/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/SQ"},"doc://org.cocoapods.EaseCallUIKit/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/s28CustomDebugStringConvertibleP"},"doc://org.cocoapods.EaseCallUIKit/SH":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/SH","title":"Swift.Hashable"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallKitManager/callVC":{"url":"\/documentation\/easecalluikit\/callkitmanager\/callvc","kind":"symbol","role":"symbol","abstract":[{"text":"Current call view controller","type":"text"}],"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager\/callVC","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"callVC"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"title":"callVC","type":"topic","navigatorTitle":[{"kind":"identifier","text":"callVC"}]},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallKitManager/profileProviderOC":{"kind":"symbol","title":"profileProviderOC","navigatorTitle":[{"text":"profileProviderOC","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager\/profileProviderOC","url":"\/documentation\/easecalluikit\/callkitmanager\/profileprovideroc","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"profileProviderOC","kind":"identifier"},{"kind":"text","text":": "},{"text":"CallUserProfileProviderOC","preciseIdentifier":"c:@M@EaseCallUIKit@objc(pl)CallUserProfileProviderOC","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"abstract":[{"type":"text","text":"Provider for user profiles in Objective-C"}]},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallKitManager/AgoraVideoFrameDelegate-Implementations":{"title":"AgoraVideoFrameDelegate Implementations","abstract":[],"url":"\/documentation\/easecalluikit\/callkitmanager\/agoravideoframedelegate-implementations","kind":"article","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager\/AgoraVideoFrameDelegate-Implementations","type":"topic","role":"collectionGroup"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallKitManager/cancelCall(callId:calleeId:)":{"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"cancelCall"},{"kind":"text","text":"("},{"kind":"externalParam","text":"callId"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"calleeId","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":")","kind":"text"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager\/cancelCall(callId:calleeId:)","navigatorTitle":[{"kind":"identifier","text":"cancelCallWithCallId:calleeId:"}],"url":"\/documentation\/easecalluikit\/callkitmanager\/cancelcall(callid:calleeid:)","title":"cancelCall(callId:calleeId:)","abstract":[{"type":"text","text":"Cancel an ongoing call from caller."}],"role":"symbol"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallKitManager/usersCache":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"usersCache","kind":"identifier"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":" : ","kind":"text"},{"text":"CallUserProfile","kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseCallUIKit@objc(cs)CallUserProfile"},{"kind":"text","text":"]"}],"kind":"symbol","url":"\/documentation\/easecalluikit\/callkitmanager\/userscache","abstract":[{"type":"text","text":"Cache for user profiles"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager\/usersCache","title":"usersCache","navigatorTitle":[{"text":"usersCache","kind":"identifier"}],"role":"symbol"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallKitManager/isVideoExchanged":{"navigatorTitle":[{"kind":"identifier","text":"isVideoExchanged"}],"url":"\/documentation\/easecalluikit\/callkitmanager\/isvideoexchanged","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isVideoExchanged"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"title":"isVideoExchanged","abstract":[{"text":"Indicates whether the call is currently in a video exchange state","type":"text"}],"type":"topic","role":"symbol","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager\/isVideoExchanged"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallKitManager/sendCancelSignal(callId:calleeId:)":{"navigatorTitle":[{"kind":"identifier","text":"sendCancelSignalWithCallId:calleeId:"}],"abstract":[],"kind":"symbol","role":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager\/sendCancelSignal(callId:calleeId:)","url":"\/documentation\/easecalluikit\/callkitmanager\/sendcancelsignal(callid:calleeid:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sendCancelSignal","kind":"identifier"},{"text":"(","kind":"text"},{"text":"callId","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"calleeId","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":")"}],"title":"sendCancelSignal(callId:calleeId:)"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallKitManager/currentUserRTCUID":{"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager\/currentUserRTCUID","kind":"symbol","url":"\/documentation\/easecalluikit\/callkitmanager\/currentuserrtcuid","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"currentUserRTCUID","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt32","preciseIdentifier":"s:s6UInt32V"}],"abstract":[{"text":"Current user RTC UID","type":"text"}],"type":"topic","title":"currentUserRTCUID","navigatorTitle":[{"kind":"identifier","text":"currentUserRTCUID"}]},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallKitManager/CallMessageService-Implementations":{"url":"\/documentation\/easecalluikit\/callkitmanager\/callmessageservice-implementations","kind":"article","abstract":[],"title":"CallMessageService Implementations","role":"collectionGroup","type":"topic","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager\/CallMessageService-Implementations"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallKitManager/popup":{"type":"topic","title":"popup","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager\/popup","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"popup"}],"url":"\/documentation\/easecalluikit\/callkitmanager\/popup","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"popup"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseCallUIKit@objc(cs)CallPopupView","text":"CallPopupView"},{"text":"?","kind":"text"}],"abstract":[{"type":"text","text":"Popup view for call notifications"}]},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallKitManager/exchangeVideoFrame()":{"kind":"symbol","abstract":[],"title":"exchangeVideoFrame()","type":"topic","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager\/exchangeVideoFrame()","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"exchangeVideoFrame"},{"kind":"text","text":"() -> "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"navigatorTitle":[{"kind":"identifier","text":"exchangeVideoFrame"}],"url":"\/documentation\/easecalluikit\/callkitmanager\/exchangevideoframe()"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallKitManager/setupEngine()":{"kind":"symbol","title":"setupEngine()","navigatorTitle":[{"text":"setupEngine","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager\/setupEngine()","url":"\/documentation\/easecalluikit\/callkitmanager\/setupengine()","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"setupEngine","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"ChatError","kind":"typeIdentifier","preciseIdentifier":"s:13EaseCallUIKit9ChatErrora"},{"kind":"text","text":"?"}],"abstract":[]},"doc://org.cocoapods.EaseCallUIKit/objc(pl)EMClientDelegate":{"type":"unresolvable","title":"EMClientDelegate","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)EMClientDelegate"},"doc://org.cocoapods.EaseCallUIKit/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)NSObject"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallKitManager/shared":{"navigatorTitle":[{"text":"shared","kind":"identifier"}],"abstract":[{"text":"CallKitManager shared instance","type":"text"}],"url":"\/documentation\/easecalluikit\/callkitmanager\/shared","kind":"symbol","title":"shared","type":"topic","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager\/shared","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"shared"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@EaseCallUIKit@objc(cs)CallKitManager","text":"CallKitManager","kind":"typeIdentifier"}]},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallKitManager/callInfo":{"role":"symbol","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager\/callInfo","navigatorTitle":[{"kind":"identifier","text":"callInfo"}],"kind":"symbol","abstract":[{"text":"Current call information","type":"text"}],"type":"topic","url":"\/documentation\/easecalluikit\/callkitmanager\/callinfo","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"callInfo","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@EaseCallUIKit@objc(cs)CallInfo","text":"CallInfo","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"title":"callInfo"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallKitManager/lastPIPFrame":{"navigatorTitle":[{"text":"lastPIPFrame","kind":"identifier"}],"abstract":[{"text":"Last Picture-in-Picture frame","type":"text"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"lastPIPFrame"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@S@CGRect","kind":"typeIdentifier","text":"CGRect"}],"kind":"symbol","type":"topic","url":"\/documentation\/easecalluikit\/callkitmanager\/lastpipframe","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager\/lastPIPFrame","role":"symbol","title":"lastPIPFrame"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallKitManager/appID":{"type":"topic","url":"\/documentation\/easecalluikit\/callkitmanager\/appid","title":"appID","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"Application ID for Agora SDK"}],"navigatorTitle":[{"kind":"identifier","text":"appID"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"appID","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager\/appID"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallKitManager/TimerServiceListener-Implementations":{"kind":"article","type":"topic","url":"\/documentation\/easecalluikit\/callkitmanager\/timerservicelistener-implementations","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager\/TimerServiceListener-Implementations","abstract":[],"title":"TimerServiceListener Implementations","role":"collectionGroup"},"doc://org.cocoapods.EaseCallUIKit/objc(pl)EMChatManagerDelegate":{"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)EMChatManagerDelegate","title":"EMChatManagerDelegate","type":"unresolvable"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallKitManager/listeners":{"type":"topic","abstract":[{"type":"text","text":"Listeners for call events"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager\/listeners","role":"symbol","url":"\/documentation\/easecalluikit\/callkitmanager\/listeners","navigatorTitle":[{"kind":"identifier","text":"listeners"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"listeners"},{"text":": ","kind":"text"},{"text":"NSHashTable","preciseIdentifier":"c:objc(cs)NSHashTable","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"kind":"typeIdentifier","text":"CallServiceListener","preciseIdentifier":"c:@M@EaseCallUIKit@objc(pl)CallServiceListener"},{"kind":"text","text":">"}],"title":"listeners"},"doc://org.cocoapods.EaseCallUIKit/s7CVarArgP":{"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/s7CVarArgP","title":"Swift.CVarArg","type":"unresolvable"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallKitManager/itemsCache":{"kind":"symbol","abstract":[{"text":"Cache for call stream items","type":"text"}],"title":"itemsCache","type":"topic","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager\/itemsCache","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"itemsCache","kind":"identifier"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseCallUIKit@objc(cs)CallStreamItem","text":"CallStreamItem"},{"kind":"text","text":"]"}],"navigatorTitle":[{"kind":"identifier","text":"itemsCache"}],"url":"\/documentation\/easecalluikit\/callkitmanager\/itemscache"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallKitManager/canvasCache":{"type":"topic","abstract":[{"text":"Cache for call stream views","type":"text"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager\/canvasCache","role":"symbol","url":"\/documentation\/easecalluikit\/callkitmanager\/canvascache","navigatorTitle":[{"text":"canvasCache","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"canvasCache"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:@M@EaseCallUIKit@objc(cs)CallStreamView","text":"CallStreamView","kind":"typeIdentifier"},{"text":"]","kind":"text"}],"title":"canvasCache"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallKitManager/setup(_:)":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"setup","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@EaseCallUIKit@objc(cs)CallKitConfig","kind":"typeIdentifier","text":"CallKitConfig"},{"text":"?)","kind":"text"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager\/setup(_:)","title":"setup(_:)","url":"\/documentation\/easecalluikit\/callkitmanager\/setup(_:)","role":"symbol","navigatorTitle":[{"text":"setup:","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"Sets up the CallKitManager with an optional token provider."}]},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallKitManager/engine":{"title":"engine","role":"symbol","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"engine","kind":"identifier"},{"text":": ","kind":"text"},{"text":"AgoraRtcEngineKit","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AgoraRtcEngineKit"},{"kind":"text","text":"?"}],"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager\/engine","abstract":[{"type":"text","text":"AgoraRtcEngineKit instance"}],"url":"\/documentation\/easecalluikit\/callkitmanager\/engine","navigatorTitle":[{"text":"engine","kind":"identifier"}]},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallKitManager/currentUserInfo":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"currentUserInfo"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseCallUIKit@objc(pl)CallProfileProtocol","text":"CallProfileProtocol"},{"text":"?","kind":"text"}],"role":"symbol","title":"currentUserInfo","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager\/currentUserInfo","type":"topic","navigatorTitle":[{"kind":"identifier","text":"currentUserInfo"}],"url":"\/documentation\/easecalluikit\/callkitmanager\/currentuserinfo","kind":"symbol","abstract":[{"text":"Current user profile information","type":"text"}]},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallKitManager/resetVideoExchange()":{"url":"\/documentation\/easecalluikit\/callkitmanager\/resetvideoexchange()","kind":"symbol","role":"symbol","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager\/resetVideoExchange()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"resetVideoExchange"},{"kind":"text","text":"()"}],"title":"resetVideoExchange()","type":"topic","navigatorTitle":[{"text":"resetVideoExchange","kind":"identifier"}]},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallKitManager/cleanUserDefaults()":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"cleanUserDefaults","kind":"identifier"},{"kind":"text","text":"()"}],"kind":"symbol","url":"\/documentation\/easecalluikit\/callkitmanager\/cleanuserdefaults()","abstract":[{"type":"text","text":"When you logout IM SDK, you should call this method to clean up the user defaults."}],"type":"topic","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager\/cleanUserDefaults()","title":"cleanUserDefaults()","navigatorTitle":[{"text":"cleanUserDefaults","kind":"identifier"}],"role":"symbol"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallKitManager/tearDown()":{"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager\/tearDown()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"tearDown"},{"kind":"text","text":"()"}],"navigatorTitle":[{"kind":"identifier","text":"tearDown"}],"url":"\/documentation\/easecalluikit\/callkitmanager\/teardown()","type":"topic","title":"tearDown()","kind":"symbol","abstract":[{"type":"text","text":"Tears down the CallKitManager, releasing resources and stopping the player.Notice that this method should be called when the application is about to terminate or when the CallKitManager is no longer needed."}],"role":"symbol"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallKitManager/calleeAnswerCaller(callId:callerId:callerDeviceId:)":{"kind":"symbol","type":"topic","title":"calleeAnswerCaller(callId:callerId:callerDeviceId:)","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager\/calleeAnswerCaller(callId:callerId:callerDeviceId:)","navigatorTitle":[{"text":"calleeAnswerCallerWithCallId:callerId:callerDeviceId:","kind":"identifier"}],"abstract":[{"type":"text","text":"Caller answers the call from the callee."}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"calleeAnswerCaller","kind":"identifier"},{"kind":"text","text":"("},{"text":"callId","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"callerId","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"callerDeviceId"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":")","kind":"text"}],"url":"\/documentation\/easecalluikit\/callkitmanager\/calleeanswercaller(callid:callerid:callerdeviceid:)","role":"symbol"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/TimerServiceListener":{"url":"\/documentation\/easecalluikit\/timerservicelistener","kind":"symbol","role":"symbol","title":"TimerServiceListener","navigatorTitle":[{"text":"TimerServiceListener","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/TimerServiceListener","abstract":[],"type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"TimerServiceListener"}]},"doc://org.cocoapods.EaseCallUIKit/objc(pl)AgoraVideoFrameDelegate":{"title":"AgoraVideoFrameDelegate","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)AgoraVideoFrameDelegate","type":"unresolvable"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallKitManager/confirmRing(callId:calleeId:calleeDeviceId:is_valid:)":{"role":"symbol","title":"confirmRing(callId:calleeId:calleeDeviceId:is_valid:)","abstract":[{"text":"Confirm the ring for a call from the caller.","type":"text"}],"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager\/confirmRing(callId:calleeId:calleeDeviceId:is_valid:)","type":"topic","url":"\/documentation\/easecalluikit\/callkitmanager\/confirmring(callid:calleeid:calleedeviceid:is_valid:)","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"confirmRing","kind":"identifier"},{"text":"(","kind":"text"},{"text":"callId","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"calleeId"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"calleeDeviceId","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":", ","kind":"text"},{"text":"is_valid","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"confirmRingWithCallId:calleeId:calleeDeviceId:is_valid:","kind":"identifier"}]},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallKitManager/config":{"abstract":[],"title":"config","role":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager\/config","url":"\/documentation\/easecalluikit\/callkitmanager\/config","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"config"},{"kind":"text","text":": "},{"text":"CallKitConfig","preciseIdentifier":"c:@M@EaseCallUIKit@objc(cs)CallKitConfig","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"config","kind":"identifier"}]},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallKitManager/EMChatManagerDelegate-Implementations":{"type":"topic","role":"collectionGroup","kind":"article","title":"EMChatManagerDelegate Implementations","url":"\/documentation\/easecalluikit\/callkitmanager\/emchatmanagerdelegate-implementations","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager\/EMChatManagerDelegate-Implementations","abstract":[]},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallKitManager/receivedCalls":{"abstract":[],"kind":"symbol","title":"receivedCalls","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager\/receivedCalls","url":"\/documentation\/easecalluikit\/callkitmanager\/receivedcalls","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"receivedCalls","kind":"identifier"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":" : "},{"text":"CallInfo","kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseCallUIKit@objc(cs)CallInfo"},{"text":"]","kind":"text"}],"navigatorTitle":[{"text":"receivedCalls","kind":"identifier"}],"role":"symbol","type":"topic"},"doc://org.cocoapods.EaseCallUIKit/objc(cs)NSObject":{"title":"NSObject","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/objc(cs)NSObject","type":"unresolvable"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallKitManager/tokenProvider":{"type":"topic","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager\/tokenProvider","navigatorTitle":[{"text":"tokenProvider","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"Provider for call token","type":"text"}],"role":"symbol","title":"tokenProvider","url":"\/documentation\/easecalluikit\/callkitmanager\/tokenprovider","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"tokenProvider","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CallTokenProvider","preciseIdentifier":"c:@M@EaseCallUIKit@objc(pl)CallTokenProvider"},{"kind":"text","text":"?"}]},"doc://org.cocoapods.EaseCallUIKit/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/s23CustomStringConvertibleP","type":"unresolvable"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallKitManager/AgoraRtcEngineDelegate-Implementations":{"title":"AgoraRtcEngineDelegate Implementations","kind":"article","role":"collectionGroup","url":"\/documentation\/easecalluikit\/callkitmanager\/agorartcenginedelegate-implementations","type":"topic","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager\/AgoraRtcEngineDelegate-Implementations"},"doc://org.cocoapods.EaseCallUIKit/s8CopyableP":{"title":"Swift.Copyable","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/s8CopyableP","type":"unresolvable"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"CallKitManager","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"class"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"CallKitManager","kind":"identifier"}]},{"path":"\/metadata\/navigatorTitle","value":[{"text":"CallKitManager","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/topicSections","value":[{"generated":true,"identifiers":["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager\/appID","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager\/callInfo","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager\/callVC","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager\/canvasCache","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager\/config","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager\/currentUserInfo","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager\/currentUserRTCUID","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager\/engine","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager\/isVideoExchanged","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager\/itemsCache","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager\/lastPIPFrame","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager\/listeners","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager\/popup","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager\/profileProviderOC","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager\/receivedCalls","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager\/token","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager\/tokenProvider","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager\/usersCache"],"title":"Instance Properties","anchor":"Instance-Properties"},{"generated":true,"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager\/calleeAnswerCaller(callId:callerId:callerDeviceId:)","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager\/callerConfirmAnswer(callId:calleeId:calleeDeviceId:result:)","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager\/cancelCall(callId:calleeId:)","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager\/cleanUserDefaults()","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager\/confirmRing(callId:calleeId:calleeDeviceId:is_valid:)","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager\/exchangeVideoFrame()","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager\/resetVideoExchange()","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager\/sendCancelSignal(callId:calleeId:)","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager\/setup(_:)","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager\/setupEngine()","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager\/tearDown()"],"anchor":"Instance-Methods"},{"anchor":"Type-Properties","identifiers":["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager\/shared"],"generated":true,"title":"Type Properties"},{"title":"Default Implementations","generated":true,"anchor":"Default-Implementations","identifiers":["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager\/AgoraRtcEngineDelegate-Implementations","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager\/AgoraVideoFrameDelegate-Implementations","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager\/CallMessageService-Implementations","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager\/EMChatManagerDelegate-Implementations","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager\/EMClientDelegate-Implementations","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager\/TimerServiceListener-Implementations"]}]},{"path":"\/relationshipsSections","op":"replace","value":[{"title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/org.cocoapods.EaseCallUIKit\/objc(cs)NSObject"],"type":"inheritsFrom"},{"kind":"relationships","title":"Conforms To","type":"conformsTo","identifiers":["doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)AgoraRtcEngineDelegate","doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)AgoraVideoFrameDelegate","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallMessageService","doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)EMChatManagerDelegate","doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)EMClientDelegate","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/TimerServiceListener"]}]},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"text":" ","kind":"text"},{"text":"CallKitManager","kind":"identifier"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject"}],"platforms":["iOS"],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallMessageService\/title","value":"CallMessageService"},{"value":[{"text":"CallMessageService","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallMessageService\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallMessageService\/navigatorTitle","value":[{"kind":"identifier","text":"CallMessageService"}]},{"value":"callerConfirmAnswerWithCallId:calleeId:calleeDeviceId:result:","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallKitManager~1callerConfirmAnswer(callId:calleeId:calleeDeviceId:result:)\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallKitManager~1callerConfirmAnswer(callId:calleeId:calleeDeviceId:result:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"callerConfirmAnswerWithCallId:calleeId:calleeDeviceId:result:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallKitManager~1token\/title","value":"token"},{"value":[{"text":"token","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallKitManager~1token\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallKitManager\/title","value":"CallKitManager"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallKitManager\/fragments","value":[{"kind":"identifier","text":"CallKitManager"}]},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallKitManager\/navigatorTitle","op":"replace","value":[{"text":"CallKitManager","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallKitManager~1callVC\/title","value":"callVC","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallKitManager~1callVC\/fragments","value":[{"text":"callVC","kind":"identifier"}]},{"value":"profileProviderOC","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallKitManager~1profileProviderOC\/title","op":"replace"},{"value":[{"text":"profileProviderOC","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallKitManager~1profileProviderOC\/fragments"},{"op":"replace","value":"cancelCallWithCallId:calleeId:","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallKitManager~1cancelCall(callId:calleeId:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallKitManager~1cancelCall(callId:calleeId:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"cancelCallWithCallId:calleeId:"}]},{"op":"replace","value":"usersCache","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallKitManager~1usersCache\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallKitManager~1usersCache\/fragments","op":"replace","value":[{"text":"usersCache","kind":"identifier"}]},{"value":"isVideoExchanged","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallKitManager~1isVideoExchanged\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallKitManager~1isVideoExchanged\/fragments","value":[{"kind":"identifier","text":"isVideoExchanged"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallKitManager~1sendCancelSignal(callId:calleeId:)\/title","value":"sendCancelSignalWithCallId:calleeId:"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"sendCancelSignalWithCallId:calleeId:"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallKitManager~1sendCancelSignal(callId:calleeId:)\/fragments"},{"value":"currentUserRTCUID","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallKitManager~1currentUserRTCUID\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallKitManager~1currentUserRTCUID\/fragments","value":[{"kind":"identifier","text":"currentUserRTCUID"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallKitManager~1popup\/title","value":"popup"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallKitManager~1popup\/fragments","op":"replace","value":[{"text":"popup","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallKitManager~1exchangeVideoFrame()\/title","value":"exchangeVideoFrame"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallKitManager~1exchangeVideoFrame()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"exchangeVideoFrame"}]},{"value":"setupEngine","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallKitManager~1setupEngine()\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallKitManager~1setupEngine()\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"setupEngine","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallKitManager~1shared\/title","op":"replace","value":"shared"},{"value":[{"text":"shared","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallKitManager~1shared\/fragments"},{"value":"callInfo","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallKitManager~1callInfo\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallKitManager~1callInfo\/fragments","op":"replace","value":[{"kind":"identifier","text":"callInfo"}]},{"value":"lastPIPFrame","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallKitManager~1lastPIPFrame\/title","op":"replace"},{"op":"replace","value":[{"text":"lastPIPFrame","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallKitManager~1lastPIPFrame\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallKitManager~1appID\/title","value":"appID"},{"value":[{"kind":"identifier","text":"appID"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallKitManager~1appID\/fragments"},{"value":"listeners","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallKitManager~1listeners\/title"},{"op":"replace","value":[{"kind":"identifier","text":"listeners"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallKitManager~1listeners\/fragments"},{"value":"itemsCache","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallKitManager~1itemsCache\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallKitManager~1itemsCache\/fragments","value":[{"kind":"identifier","text":"itemsCache"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallKitManager~1canvasCache\/title","value":"canvasCache"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallKitManager~1canvasCache\/fragments","value":[{"text":"canvasCache","kind":"identifier"}]},{"value":"setup:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallKitManager~1setup(_:)\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallKitManager~1setup(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"setup:"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallKitManager~1engine\/title","value":"engine"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallKitManager~1engine\/fragments","value":[{"kind":"identifier","text":"engine"}]},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallKitManager~1currentUserInfo\/title","op":"replace","value":"currentUserInfo"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallKitManager~1currentUserInfo\/fragments","value":[{"text":"currentUserInfo","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallKitManager~1resetVideoExchange()\/title","value":"resetVideoExchange","op":"replace"},{"value":[{"kind":"text","text":"- "},{"text":"resetVideoExchange","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallKitManager~1resetVideoExchange()\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallKitManager~1cleanUserDefaults()\/title","op":"replace","value":"cleanUserDefaults"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallKitManager~1cleanUserDefaults()\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"cleanUserDefaults"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallKitManager~1tearDown()\/title","value":"tearDown","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallKitManager~1tearDown()\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"tearDown"}]},{"value":"calleeAnswerCallerWithCallId:callerId:callerDeviceId:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallKitManager~1calleeAnswerCaller(callId:callerId:callerDeviceId:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"calleeAnswerCallerWithCallId:callerId:callerDeviceId:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallKitManager~1calleeAnswerCaller(callId:callerId:callerDeviceId:)\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1TimerServiceListener\/title","value":"TimerServiceListener","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1TimerServiceListener\/fragments","value":[{"text":"TimerServiceListener","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1TimerServiceListener\/navigatorTitle","value":[{"kind":"identifier","text":"TimerServiceListener"}],"op":"replace"},{"op":"replace","value":"confirmRingWithCallId:calleeId:calleeDeviceId:is_valid:","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallKitManager~1confirmRing(callId:calleeId:calleeDeviceId:is_valid:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"confirmRingWithCallId:calleeId:calleeDeviceId:is_valid:"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallKitManager~1confirmRing(callId:calleeId:calleeDeviceId:is_valid:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallKitManager~1config\/title","value":"config"},{"value":[{"kind":"identifier","text":"config"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallKitManager~1config\/fragments","op":"replace"},{"op":"replace","value":"receivedCalls","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallKitManager~1receivedCalls\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallKitManager~1receivedCalls\/fragments","op":"replace","value":[{"kind":"identifier","text":"receivedCalls"}]},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallKitManager~1tokenProvider\/title","op":"replace","value":"tokenProvider"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallKitManager~1tokenProvider\/fragments","value":[{"kind":"identifier","text":"tokenProvider"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}