{"relationshipsSections":[{"title":"Inherits From","type":"inheritsFrom","kind":"relationships","identifiers":["doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)NSObject"]},{"title":"Conforming Types","identifiers":["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager"],"type":"conformingTypes","kind":"relationships"}],"topicSections":[{"identifiers":["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallMessageService\/accept()","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallMessageService\/addListener(_:)","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallMessageService\/call(with:type:extensionInfo:)","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallMessageService\/groupCall(groupId:extensionInfo:)","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallMessageService\/hangup()","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallMessageService\/removeListener(_:)"],"title":"Instance Methods","generated":true,"anchor":"Instance-Methods"}],"identifier":{"url":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallMessageService","interfaceLanguage":"swift"},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"CallMessageService"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(pl)NSObject","text":"NSObjectProtocol","kind":"typeIdentifier"}],"platforms":["iOS"]}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"externalID":"c:@M@EaseCallUIKit@objc(pl)CallMessageService","navigatorTitle":[{"text":"CallMessageService","kind":"identifier"}],"title":"CallMessageService","symbolKind":"protocol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CallMessageService"}],"roleHeading":"Protocol","role":"symbol","modules":[{"name":"EaseCallUIKit"}]},"variants":[{"paths":["\/documentation\/easecalluikit\/callmessageservice"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/easecalluikit\/callmessageservice"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit"]]},"sections":[],"references":{"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallMessageService/accept()":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"accept","kind":"identifier"},{"text":"()","kind":"text"}],"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallMessageService\/accept()","url":"\/documentation\/easecalluikit\/callmessageservice\/accept()","required":true,"navigatorTitle":[{"kind":"identifier","text":"accept"}],"abstract":[{"type":"text","text":"Accepts an incoming call."},{"text":" ","type":"text"},{"type":"text","text":"This method is called when the user decides to answer an incoming call."}],"role":"symbol","type":"topic","kind":"symbol","title":"accept()"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallMessageService/groupCall(groupId:extensionInfo:)":{"navigatorTitle":[{"text":"groupCallWithGroupId:extensionInfo:","kind":"identifier"}],"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"groupCall","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"groupId"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"extensionInfo","kind":"externalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":" : "},{"text":"Any","kind":"keyword"},{"text":"]?)","kind":"text"}],"abstract":[{"type":"text","text":"Initiates a multi-user call with the specified user IDs and group ID."}],"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallMessageService\/groupCall(groupId:extensionInfo:)","role":"symbol","title":"groupCall(groupId:extensionInfo:)","kind":"symbol","url":"\/documentation\/easecalluikit\/callmessageservice\/groupcall(groupid:extensioninfo:)","required":true},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallMessageService/addListener(_:)":{"abstract":[{"type":"text","text":"Adds a listener to receive call-related events."}],"title":"addListener(_:)","url":"\/documentation\/easecalluikit\/callmessageservice\/addlistener(_:)","kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallMessageService\/addListener(_:)","required":true,"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"addListener","kind":"identifier"},{"kind":"text","text":"("},{"text":"CallServiceListener","preciseIdentifier":"c:@M@EaseCallUIKit@objc(pl)CallServiceListener","kind":"typeIdentifier"},{"kind":"text","text":")"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"addListener:"}]},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallMessageService/call(with:type:extensionInfo:)":{"navigatorTitle":[{"text":"callWith:type:extensionInfo:","kind":"identifier"}],"abstract":[{"text":"Initiates a call with the specified user ID and call type.","type":"text"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallMessageService\/call(with:type:extensionInfo:)","type":"topic","url":"\/documentation\/easecalluikit\/callmessageservice\/call(with:type:extensioninfo:)","required":true,"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"call"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"type"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CallType","preciseIdentifier":"c:@M@EaseCallUIKit@E@CallType"},{"kind":"text","text":", "},{"kind":"externalParam","text":"extensionInfo"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"kind":"keyword","text":"Any"},{"text":"]?)","kind":"text"}],"title":"call(with:type:extensionInfo:)"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit":{"title":"EaseCallUIKit","type":"topic","url":"\/documentation\/easecalluikit","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit","abstract":[],"role":"collection","kind":"symbol"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallMessageService/hangup()":{"abstract":[{"type":"text","text":"Hangs up the current call."}],"required":true,"url":"\/documentation\/easecalluikit\/callmessageservice\/hangup()","type":"topic","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallMessageService\/hangup()","title":"hangup()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"hangup"},{"kind":"text","text":"()"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"hangup","kind":"identifier"}]},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallMessageService":{"type":"topic","url":"\/documentation\/easecalluikit\/callmessageservice","kind":"symbol","navigatorTitle":[{"text":"CallMessageService","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallMessageService","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"CallMessageService","kind":"identifier"}],"title":"CallMessageService","abstract":[]},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallKitManager":{"role":"symbol","title":"CallKitManager","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CallKitManager"}],"abstract":[],"type":"topic","kind":"symbol","url":"\/documentation\/easecalluikit\/callkitmanager","navigatorTitle":[{"text":"CallKitManager","kind":"identifier"}]},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallMessageService/removeListener(_:)":{"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallMessageService\/removeListener(_:)","type":"topic","url":"\/documentation\/easecalluikit\/callmessageservice\/removelistener(_:)","kind":"symbol","title":"removeListener(_:)","required":true,"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"removeListener","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@EaseCallUIKit@objc(pl)CallServiceListener","text":"CallServiceListener","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"removeListener:"}],"abstract":[{"text":"Removes a previously added listener from receiving call-related events.","type":"text"}],"role":"symbol"},"doc://org.cocoapods.EaseCallUIKit/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)NSObject","title":"NSObject"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Protocol","op":"replace"},{"value":"CallMessageService","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"CallMessageService"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"CallMessageService"}]},{"op":"replace","value":[{"generated":true,"title":"Instance Methods","anchor":"Instance-Methods","identifiers":["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallMessageService\/accept()","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallMessageService\/addListener(_:)","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallMessageService\/call(with:type:extensionInfo:)","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallMessageService\/groupCall(groupId:extensionInfo:)","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallMessageService\/hangup()","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallMessageService\/removeListener(_:)"]}],"path":"\/topicSections"},{"op":"replace","path":"\/relationshipsSections","value":[{"title":"Inherits From","identifiers":["doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)NSObject"],"type":"inheritsFrom","kind":"relationships"},{"identifiers":["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager"],"title":"Conforming Types","kind":"relationships","type":"conformingTypes"}]},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CallMessageService","kind":"identifier"},{"text":" <","kind":"text"},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)NSObject"},{"text":">","kind":"text"}],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallMessageService~1accept()\/title","value":"accept"},{"value":[{"text":"- ","kind":"text"},{"text":"accept","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallMessageService~1accept()\/fragments"},{"value":"groupCallWithGroupId:extensionInfo:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallMessageService~1groupCall(groupId:extensionInfo:)\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallMessageService~1groupCall(groupId:extensionInfo:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"groupCallWithGroupId:extensionInfo:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallMessageService~1addListener(_:)\/title","value":"addListener:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallMessageService~1addListener(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"addListener:"}]},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallMessageService~1call(with:type:extensionInfo:)\/title","value":"callWith:type:extensionInfo:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallMessageService~1call(with:type:extensionInfo:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"callWith:type:extensionInfo:"}]},{"value":"hangup","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallMessageService~1hangup()\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"hangup","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallMessageService~1hangup()\/fragments","op":"replace"},{"value":"CallMessageService","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallMessageService\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallMessageService\/fragments","value":[{"text":"CallMessageService","kind":"identifier"}]},{"op":"replace","value":[{"text":"CallMessageService","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallMessageService\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallKitManager\/title","value":"CallKitManager"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallKitManager\/fragments","op":"replace","value":[{"kind":"identifier","text":"CallKitManager"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallKitManager\/navigatorTitle","value":[{"text":"CallKitManager","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallMessageService~1removeListener(_:)\/title","op":"replace","value":"removeListener:"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallMessageService~1removeListener(_:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"removeListener:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}