{"abstract":[{"text":"The ","type":"text"},{"code":"CallError","type":"codeVoice"},{"type":"text","text":" class encapsulates errors that can occur in the call system, providing a structured way to handle errors from different modules such as IM, RTC, and business logic."}],"relationshipsSections":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/org.cocoapods.EaseCallUIKit\/objc(cs)NSObject"],"type":"inheritsFrom"},{"kind":"relationships","identifiers":["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallErrorCodeGettable","doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)NSObject","doc:\/\/org.cocoapods.EaseCallUIKit\/s7CVarArgP","doc:\/\/org.cocoapods.EaseCallUIKit\/s8CopyableP","doc:\/\/org.cocoapods.EaseCallUIKit\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.EaseCallUIKit\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.EaseCallUIKit\/SQ","doc:\/\/org.cocoapods.EaseCallUIKit\/SH"],"type":"conformsTo","title":"Conforms To"}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CallError"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"metadata":{"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"CallError","kind":"identifier"}],"symbolKind":"class","modules":[{"name":"EaseCallUIKit"}],"title":"CallError","externalID":"c:@M@EaseCallUIKit@objc(cs)CallError","navigatorTitle":[{"kind":"identifier","text":"CallError"}],"roleHeading":"Class"},"topicSections":[{"anchor":"Classes","identifiers":["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallError\/CallBusiness","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallError\/IM","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallError\/RTC"],"generated":true,"title":"Classes"},{"identifiers":["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallError\/init(_:module:)"],"anchor":"Initializers","title":"Initializers","generated":true},{"title":"Instance Properties","generated":true,"identifiers":["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallError\/error","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallError\/errorMessage","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallError\/errorType","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallError\/module"],"anchor":"Instance-Properties"},{"title":"Default Implementations","generated":true,"anchor":"Default-Implementations","identifiers":["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallError\/CallErrorCodeGettable-Implementations"]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easecalluikit\/callerror"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easecalluikit\/callerror"]}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallError"},"references":{"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallError":{"type":"topic","role":"symbol","title":"CallError","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"CallError","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"CallError"},{"type":"text","text":" class encapsulates errors that can occur in the call system, providing a structured way to handle errors from different modules such as IM, RTC, and business logic."}],"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallError","navigatorTitle":[{"kind":"identifier","text":"CallError"}],"url":"\/documentation\/easecalluikit\/callerror"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallError/CallBusiness":{"navigatorTitle":[{"kind":"identifier","text":"CallBusiness"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CallBusiness"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallError\/CallBusiness","url":"\/documentation\/easecalluikit\/callerror\/callbusiness","type":"topic","title":"CallError.CallBusiness","kind":"symbol","abstract":[{"type":"text","text":"Convenience initializer for creating a "},{"code":"CallError","type":"codeVoice"},{"type":"text","text":" with a business logic error."}]},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallError/errorType":{"title":"errorType","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallError\/errorType","type":"topic","role":"symbol","url":"\/documentation\/easecalluikit\/callerror\/errortype","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"errorType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:13EaseCallUIKit0B9ErrorTypeO","text":"CallErrorType"}],"abstract":[{"type":"text","text":"The "},{"code":"errorType","type":"codeVoice"},{"text":" property categorizes the error based on its module and error code.","type":"text"}],"kind":"symbol"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallErrorCodeGettable":{"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallErrorCodeGettable","abstract":[{"text":"The ","type":"text"},{"code":"CallErrorCodeGettable","type":"codeVoice"},{"type":"text","text":" protocol defines methods to retrieve error codes from different modules."}],"url":"\/documentation\/easecalluikit\/callerrorcodegettable","navigatorTitle":[{"text":"CallErrorCodeGettable","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"CallErrorCodeGettable","kind":"identifier"}],"type":"topic","title":"CallErrorCodeGettable","role":"symbol","kind":"symbol"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallError/CallErrorCodeGettable-Implementations":{"url":"\/documentation\/easecalluikit\/callerror\/callerrorcodegettable-implementations","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallError\/CallErrorCodeGettable-Implementations","role":"collectionGroup","abstract":[],"type":"topic","title":"CallErrorCodeGettable Implementations","kind":"article"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallError/error":{"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallError\/error","abstract":[{"text":"The error details conforming to ","type":"text"},{"type":"codeVoice","code":"CallErrorCommonFeature"},{"type":"text","text":"."}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"error"}],"url":"\/documentation\/easecalluikit\/callerror\/error","title":"error","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"error","kind":"identifier"},{"kind":"text","text":": "},{"text":"CallErrorCommonFeature","kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseCallUIKit@objc(pl)CallErrorCommonFeature"}],"kind":"symbol"},"doc://org.cocoapods.EaseCallUIKit/s8CopyableP":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/s8CopyableP","title":"Swift.Copyable"},"doc://org.cocoapods.EaseCallUIKit/SH":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/SH","title":"Swift.Hashable"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallError/init(_:module:)":{"type":"topic","abstract":[],"role":"symbol","url":"\/documentation\/easecalluikit\/callerror\/init(_:module:)","title":"init(_:module:)","kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallError\/init(_:module:)","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"CallErrorCommonFeature","kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseCallUIKit@objc(pl)CallErrorCommonFeature"},{"kind":"text","text":", "},{"text":"module","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@EaseCallUIKit@E@CallErrorModule","kind":"typeIdentifier","text":"CallErrorModule"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"init:module:","kind":"identifier"}]},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit":{"title":"EaseCallUIKit","type":"topic","url":"\/documentation\/easecalluikit","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit","abstract":[],"role":"collection","kind":"symbol"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallError/RTC":{"url":"\/documentation\/easecalluikit\/callerror\/rtc","role":"symbol","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallError\/RTC","navigatorTitle":[{"kind":"identifier","text":"RTC"}],"abstract":[{"text":"Convenience initializer for creating a ","type":"text"},{"type":"codeVoice","code":"CallError"},{"text":" with an IM error.","type":"text"}],"title":"CallError.RTC","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"RTC","kind":"identifier"}]},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallError/IM":{"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallError\/IM","kind":"symbol","title":"CallError.IM","abstract":[{"type":"text","text":"Convenience initializer for creating a "},{"type":"codeVoice","code":"CallError"},{"text":" with an RTC error.","type":"text"}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"IM","kind":"identifier"}],"role":"symbol","url":"\/documentation\/easecalluikit\/callerror\/im","navigatorTitle":[{"kind":"identifier","text":"IM"}]},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallError/errorMessage":{"url":"\/documentation\/easecalluikit\/callerror\/errormessage","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallError\/errorMessage","role":"symbol","abstract":[],"type":"topic","title":"errorMessage","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"errorMessage"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"kind":"symbol"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallError/module_":{"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallError\/module_","kind":"symbol","title":"module_","abstract":[{"text":"The module where the error occurred.","type":"text"}],"type":"topic","fragments":[{"text":"module_","kind":"identifier"}],"role":"symbol","url":"\/documentation\/easecalluikit\/callerror\/module_"},"doc://org.cocoapods.EaseCallUIKit/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/s7CVarArgP","title":"Swift.CVarArg"},"doc://org.cocoapods.EaseCallUIKit/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://org.cocoapods.EaseCallUIKit/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/objc(cs)NSObject","title":"NSObject"},"doc://org.cocoapods.EaseCallUIKit/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallError/module":{"url":"\/documentation\/easecalluikit\/callerror\/module","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallError\/module","role":"symbol","abstract":[{"type":"text","text":"The module where the error occurred."}],"type":"topic","title":"module","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"module","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseCallUIKit@E@CallErrorModule","text":"CallErrorModule"}],"kind":"symbol"},"doc://org.cocoapods.EaseCallUIKit/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/s28CustomDebugStringConvertibleP"},"doc://org.cocoapods.EaseCallUIKit/SQ":{"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/SQ","type":"unresolvable","title":"Swift.Equatable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"CallError"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"CallError","kind":"identifier"}]},{"op":"replace","value":[{"kind":"identifier","text":"CallError"}],"path":"\/metadata\/navigatorTitle"},{"op":"replace","path":"\/topicSections","value":[{"generated":true,"identifiers":["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallError\/error","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallError\/module_"],"anchor":"Instance-Properties","title":"Instance Properties"},{"anchor":"Instance-Methods","identifiers":["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallError\/init(_:module:)"],"generated":true,"title":"Instance Methods"},{"title":"Default Implementations","identifiers":["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallError\/CallErrorCodeGettable-Implementations"],"anchor":"Default-Implementations","generated":true}]},{"value":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/org.cocoapods.EaseCallUIKit\/objc(cs)NSObject"],"type":"inheritsFrom"},{"title":"Conforms To","identifiers":["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallErrorCodeGettable"],"kind":"relationships","type":"conformsTo"}],"op":"replace","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"text":"CallError","kind":"identifier"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"value":"CallError","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallError\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallError\/fragments","value":[{"kind":"identifier","text":"CallError"}]},{"value":[{"text":"CallError","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallError\/navigatorTitle"},{"op":"replace","value":"CallErrorCodeGettable","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallErrorCodeGettable\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallErrorCodeGettable\/fragments","value":[{"text":"CallErrorCodeGettable","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallErrorCodeGettable\/navigatorTitle","op":"replace","value":[{"text":"CallErrorCodeGettable","kind":"identifier"}]},{"op":"replace","value":"error","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallError~1error\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallError~1error\/fragments","value":[{"kind":"identifier","text":"error"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallError~1init(_:module:)\/title","value":"init:module:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallError~1init(_:module:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"init:module:","kind":"identifier"}]}]}]}