{"relationshipsSections":[{"type":"conformsTo","title":"Conforms To","kind":"relationships","identifiers":["doc:\/\/org.cocoapods.EaseCallUIKit\/SQ","doc:\/\/org.cocoapods.EaseCallUIKit\/SH","doc:\/\/org.cocoapods.EaseCallUIKit\/SY"]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easecalluikit\/callnetworkstatus"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easecalluikit\/callnetworkstatus"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallNetworkStatus"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CallNetworkStatus"}],"platforms":["iOS"],"languages":["swift"]}]}],"metadata":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CallNetworkStatus"}],"symbolKind":"enum","roleHeading":"Enumeration","externalID":"c:@M@EaseCallUIKit@E@CallNetworkStatus","title":"CallNetworkStatus","modules":[{"name":"EaseCallUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"CallNetworkStatus"}],"role":"symbol"},"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"topicSections":[{"title":"Enumeration Cases","anchor":"Enumeration-Cases","generated":true,"identifiers":["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallNetworkStatus\/bad","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallNetworkStatus\/good","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallNetworkStatus\/poor","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallNetworkStatus\/unknown"]},{"title":"Initializers","generated":true,"identifiers":["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallNetworkStatus\/init(rawValue:)"],"anchor":"Initializers"},{"identifiers":["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallNetworkStatus\/Equatable-Implementations","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallNetworkStatus\/RawRepresentable-Implementations"],"anchor":"Default-Implementations","generated":true,"title":"Default Implementations"}],"references":{"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallNetworkStatus/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","type":"topic","url":"\/documentation\/easecalluikit\/callnetworkstatus\/rawrepresentable-implementations","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallNetworkStatus\/RawRepresentable-Implementations","kind":"article"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit":{"title":"EaseCallUIKit","type":"topic","url":"\/documentation\/easecalluikit","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit","abstract":[],"role":"collection","kind":"symbol"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallNetworkStatus/init(rawValue:)":{"title":"init(rawValue:)","type":"topic","role":"symbol","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallNetworkStatus\/init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"text":"?(","kind":"text"},{"kind":"externalParam","text":"rawValue"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Su","text":"UInt"},{"kind":"text","text":")"}],"kind":"symbol","abstract":[],"url":"\/documentation\/easecalluikit\/callnetworkstatus\/init(rawvalue:)"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallNetworkStatus/bad":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"bad","kind":"identifier"}],"role":"symbol","title":"CallNetworkStatus.bad","abstract":[],"url":"\/documentation\/easecalluikit\/callnetworkstatus\/bad","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallNetworkStatus\/bad","navigatorTitle":[{"kind":"identifier","text":"CallNetworkStatusBad"}],"kind":"symbol","type":"topic"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallNetworkStatus/poor":{"url":"\/documentation\/easecalluikit\/callnetworkstatus\/poor","navigatorTitle":[{"text":"CallNetworkStatusPoor","kind":"identifier"}],"kind":"symbol","abstract":[],"type":"topic","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallNetworkStatus\/poor","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"poor"}],"role":"symbol","title":"CallNetworkStatus.poor"},"doc://org.cocoapods.EaseCallUIKit/SH":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/SH","title":"Swift.Hashable"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallNetworkStatus/good":{"url":"\/documentation\/easecalluikit\/callnetworkstatus\/good","navigatorTitle":[{"kind":"identifier","text":"CallNetworkStatusGood"}],"role":"symbol","kind":"symbol","abstract":[],"type":"topic","title":"CallNetworkStatus.good","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"good"}],"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallNetworkStatus\/good"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallNetworkStatus":{"url":"\/documentation\/easecalluikit\/callnetworkstatus","type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"CallNetworkStatus","kind":"identifier"}],"abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallNetworkStatus","role":"symbol","title":"CallNetworkStatus","navigatorTitle":[{"kind":"identifier","text":"CallNetworkStatus"}]},"doc://org.cocoapods.EaseCallUIKit/SY":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/SY","title":"Swift.RawRepresentable"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallNetworkStatus/unknown":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"unknown"}],"abstract":[],"kind":"symbol","type":"topic","title":"CallNetworkStatus.unknown","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallNetworkStatus\/unknown","navigatorTitle":[{"text":"CallNetworkStatusUnknown","kind":"identifier"}],"role":"symbol","url":"\/documentation\/easecalluikit\/callnetworkstatus\/unknown"},"doc://org.cocoapods.EaseCallUIKit/SQ":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/SQ","title":"Swift.Equatable"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallNetworkStatus/Equatable-Implementations":{"url":"\/documentation\/easecalluikit\/callnetworkstatus\/equatable-implementations","kind":"article","title":"Equatable Implementations","abstract":[],"type":"topic","role":"collectionGroup","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallNetworkStatus\/Equatable-Implementations"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration"},{"path":"\/metadata\/title","op":"replace","value":"CallNetworkStatus"},{"path":"\/metadata\/symbolKind","value":"enum","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"CallNetworkStatus","kind":"identifier"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"CallNetworkStatus"}]},{"op":"replace","path":"\/topicSections","value":[{"identifiers":["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallNetworkStatus\/bad","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallNetworkStatus\/good","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallNetworkStatus\/poor","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallNetworkStatus\/unknown"],"generated":true,"anchor":"Enumeration-Cases","title":"Enumeration Cases"}]},{"op":"replace","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CallNetworkStatus","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@NSUInteger","text":"NSUInteger","kind":"typeIdentifier"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallNetworkStatus~1bad\/title","op":"replace","value":"CallNetworkStatusBad"},{"value":[{"text":"CallNetworkStatusBad","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallNetworkStatus~1bad\/fragments","op":"replace"},{"value":"CallNetworkStatusPoor","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallNetworkStatus~1poor\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallNetworkStatus~1poor\/fragments","op":"replace","value":[{"text":"CallNetworkStatusPoor","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallNetworkStatus~1good\/title","value":"CallNetworkStatusGood","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallNetworkStatus~1good\/fragments","value":[{"text":"CallNetworkStatusGood","kind":"identifier"}],"op":"replace"},{"value":"CallNetworkStatus","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallNetworkStatus\/title","op":"replace"},{"op":"replace","value":[{"text":"CallNetworkStatus","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallNetworkStatus\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallNetworkStatus\/navigatorTitle","value":[{"text":"CallNetworkStatus","kind":"identifier"}],"op":"replace"},{"value":"CallNetworkStatusUnknown","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallNetworkStatus~1unknown\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallNetworkStatus~1unknown\/fragments","value":[{"text":"CallNetworkStatusUnknown","kind":"identifier"}],"op":"replace"}]}]}