{"identifier":{"url":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/GradientForwardPoints","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objcMembers","kind":"attribute"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"GradientForwardPoints"}]}]}],"kind":"symbol","variants":[{"paths":["\/documentation\/easecalluikit\/gradientforwardpoints"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easecalluikit\/gradientforwardpoints"]}],"metadata":{"roleHeading":"Class","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"GradientForwardPoints"}],"role":"symbol","symbolKind":"class","title":"GradientForwardPoints","externalID":"c:@M@EaseCallUIKit@objc(cs)GradientForwardPoints","modules":[{"name":"EaseCallUIKit"}],"navigatorTitle":[{"text":"GradientForwardPoints","kind":"identifier"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit"]]},"relationshipsSections":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/org.cocoapods.EaseCallUIKit\/objc(cs)NSObject"],"type":"inheritsFrom"},{"title":"Conforms To","type":"conformsTo","identifiers":["doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)NSObject","doc:\/\/org.cocoapods.EaseCallUIKit\/s7CVarArgP","doc:\/\/org.cocoapods.EaseCallUIKit\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.EaseCallUIKit\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.EaseCallUIKit\/SQ","doc:\/\/org.cocoapods.EaseCallUIKit\/SH"],"kind":"relationships"}],"schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"topicSections":[{"identifiers":["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/GradientForwardPoints\/bottomLeftToTopRight","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/GradientForwardPoints\/bottomRightToTopLeft","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/GradientForwardPoints\/bottomToTop","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/GradientForwardPoints\/leftToRight","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/GradientForwardPoints\/rightToLeft","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/GradientForwardPoints\/topLeftToBottomRight","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/GradientForwardPoints\/topRightToBottomLeft","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/GradientForwardPoints\/topToBottom"],"generated":true,"anchor":"Type-Properties","title":"Type Properties"}],"references":{"doc://org.cocoapods.EaseCallUIKit/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/SH"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/GradientForwardPoints/init":{"url":"\/documentation\/easecalluikit\/gradientforwardpoints\/init","type":"topic","role":"symbol","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/GradientForwardPoints\/init","fragments":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}],"kind":"symbol","abstract":[],"title":"init","navigatorTitle":[{"kind":"identifier","text":"init"}]},"doc://org.cocoapods.EaseCallUIKit/objc(cs)NSObject":{"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/objc(cs)NSObject","type":"unresolvable","title":"NSObject"},"doc://org.cocoapods.EaseCallUIKit/objc(pl)NSObject":{"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)NSObject","type":"unresolvable","title":"ObjectiveC.NSObjectProtocol"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/GradientForwardPoints/bottomToTop":{"kind":"symbol","abstract":[],"title":"bottomToTop","type":"topic","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/GradientForwardPoints\/bottomToTop","role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"bottomToTop"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"CGPoint","preciseIdentifier":"c:@S@CGPoint"},{"text":"]","kind":"text"}],"navigatorTitle":[{"text":"bottomToTop","kind":"identifier"}],"url":"\/documentation\/easecalluikit\/gradientforwardpoints\/bottomtotop"},"doc://org.cocoapods.EaseCallUIKit/SQ":{"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/GradientForwardPoints/topToBottom":{"url":"\/documentation\/easecalluikit\/gradientforwardpoints\/toptobottom","type":"topic","role":"symbol","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/GradientForwardPoints\/topToBottom","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"topToBottom","kind":"identifier"},{"kind":"text","text":": ["},{"text":"CGPoint","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGPoint"},{"text":"]","kind":"text"}],"kind":"symbol","abstract":[],"title":"topToBottom","navigatorTitle":[{"kind":"identifier","text":"topToBottom"}]},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/GradientForwardPoints/topLeftToBottomRight":{"abstract":[],"navigatorTitle":[{"text":"topLeftToBottomRight","kind":"identifier"}],"kind":"symbol","title":"topLeftToBottomRight","role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"topLeftToBottomRight","kind":"identifier"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:@S@CGPoint","text":"CGPoint","kind":"typeIdentifier"},{"text":"]","kind":"text"}],"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/GradientForwardPoints\/topLeftToBottomRight","url":"\/documentation\/easecalluikit\/gradientforwardpoints\/toplefttobottomright","type":"topic"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/GradientForwardPoints":{"url":"\/documentation\/easecalluikit\/gradientforwardpoints","kind":"symbol","role":"symbol","title":"GradientForwardPoints","navigatorTitle":[{"text":"GradientForwardPoints","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/GradientForwardPoints","abstract":[],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"GradientForwardPoints","kind":"identifier"}]},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/GradientForwardPoints/topRightToBottomLeft":{"fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"topRightToBottomLeft","kind":"identifier"},{"kind":"text","text":": ["},{"text":"CGPoint","preciseIdentifier":"c:@S@CGPoint","kind":"typeIdentifier"},{"kind":"text","text":"]"}],"role":"symbol","title":"topRightToBottomLeft","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/GradientForwardPoints\/topRightToBottomLeft","type":"topic","navigatorTitle":[{"text":"topRightToBottomLeft","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/easecalluikit\/gradientforwardpoints\/toprighttobottomleft","abstract":[]},"doc://org.cocoapods.EaseCallUIKit/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/s7CVarArgP","title":"Swift.CVarArg"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/GradientForwardPoints/leftToRight":{"url":"\/documentation\/easecalluikit\/gradientforwardpoints\/lefttoright","type":"topic","role":"symbol","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/GradientForwardPoints\/leftToRight","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"leftToRight","kind":"identifier"},{"kind":"text","text":": ["},{"text":"CGPoint","preciseIdentifier":"c:@S@CGPoint","kind":"typeIdentifier"},{"text":"]","kind":"text"}],"kind":"symbol","abstract":[],"title":"leftToRight","navigatorTitle":[{"kind":"identifier","text":"leftToRight"}]},"doc://org.cocoapods.EaseCallUIKit/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/s28CustomDebugStringConvertibleP","type":"unresolvable","title":"Swift.CustomDebugStringConvertible"},"doc://org.cocoapods.EaseCallUIKit/s23CustomStringConvertibleP":{"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit":{"title":"EaseCallUIKit","type":"topic","url":"\/documentation\/easecalluikit","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit","abstract":[],"role":"collection","kind":"symbol"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/GradientForwardPoints/bottomRightToTopLeft":{"type":"topic","url":"\/documentation\/easecalluikit\/gradientforwardpoints\/bottomrighttotopleft","kind":"symbol","navigatorTitle":[{"text":"bottomRightToTopLeft","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/GradientForwardPoints\/bottomRightToTopLeft","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"bottomRightToTopLeft"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGPoint","text":"CGPoint"},{"text":"]","kind":"text"}],"title":"bottomRightToTopLeft","abstract":[]},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/GradientForwardPoints/bottomLeftToTopRight":{"url":"\/documentation\/easecalluikit\/gradientforwardpoints\/bottomlefttotopright","role":"symbol","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/GradientForwardPoints\/bottomLeftToTopRight","navigatorTitle":[{"kind":"identifier","text":"bottomLeftToTopRight"}],"abstract":[],"title":"bottomLeftToTopRight","kind":"symbol","type":"topic","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"bottomLeftToTopRight","kind":"identifier"},{"kind":"text","text":": ["},{"text":"CGPoint","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGPoint"},{"text":"]","kind":"text"}]},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/GradientForwardPoints/rightToLeft":{"kind":"symbol","title":"rightToLeft","navigatorTitle":[{"kind":"identifier","text":"rightToLeft"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/GradientForwardPoints\/rightToLeft","url":"\/documentation\/easecalluikit\/gradientforwardpoints\/righttoleft","role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"rightToLeft","kind":"identifier"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:@S@CGPoint","kind":"typeIdentifier","text":"CGPoint"},{"text":"]","kind":"text"}],"abstract":[]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"value":"GradientForwardPoints","path":"\/metadata\/title","op":"replace"},{"value":"class","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"GradientForwardPoints"}],"op":"replace"},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"GradientForwardPoints","kind":"identifier"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","generated":true,"identifiers":["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/GradientForwardPoints\/init"],"anchor":"Instance-Methods"},{"identifiers":["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/GradientForwardPoints\/bottomLeftToTopRight","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/GradientForwardPoints\/bottomRightToTopLeft","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/GradientForwardPoints\/bottomToTop","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/GradientForwardPoints\/leftToRight","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/GradientForwardPoints\/rightToLeft","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/GradientForwardPoints\/topLeftToBottomRight","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/GradientForwardPoints\/topRightToBottomLeft","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/GradientForwardPoints\/topToBottom"],"generated":true,"title":"Type Properties","anchor":"Type-Properties"}]},{"op":"replace","value":[{"kind":"relationships","identifiers":["doc:\/\/org.cocoapods.EaseCallUIKit\/objc(cs)NSObject"],"title":"Inherits From","type":"inheritsFrom"}],"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GradientForwardPoints","kind":"identifier"},{"kind":"text","text":" : "},{"text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","value":"bottomToTop","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1GradientForwardPoints~1bottomToTop\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1GradientForwardPoints~1bottomToTop\/fragments","value":[{"kind":"identifier","text":"bottomToTop"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1GradientForwardPoints~1topToBottom\/title","value":"topToBottom"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1GradientForwardPoints~1topToBottom\/fragments","value":[{"text":"topToBottom","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1GradientForwardPoints~1topLeftToBottomRight\/title","value":"topLeftToBottomRight","op":"replace"},{"value":[{"text":"topLeftToBottomRight","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1GradientForwardPoints~1topLeftToBottomRight\/fragments","op":"replace"},{"value":"GradientForwardPoints","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1GradientForwardPoints\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1GradientForwardPoints\/fragments","value":[{"text":"GradientForwardPoints","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1GradientForwardPoints\/navigatorTitle","value":[{"text":"GradientForwardPoints","kind":"identifier"}]},{"value":"topRightToBottomLeft","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1GradientForwardPoints~1topRightToBottomLeft\/title"},{"op":"replace","value":[{"kind":"identifier","text":"topRightToBottomLeft"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1GradientForwardPoints~1topRightToBottomLeft\/fragments"},{"value":"leftToRight","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1GradientForwardPoints~1leftToRight\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1GradientForwardPoints~1leftToRight\/fragments","value":[{"text":"leftToRight","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1GradientForwardPoints~1bottomRightToTopLeft\/title","op":"replace","value":"bottomRightToTopLeft"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1GradientForwardPoints~1bottomRightToTopLeft\/fragments","op":"replace","value":[{"text":"bottomRightToTopLeft","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1GradientForwardPoints~1bottomLeftToTopRight\/title","op":"replace","value":"bottomLeftToTopRight"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1GradientForwardPoints~1bottomLeftToTopRight\/fragments","value":[{"text":"bottomLeftToTopRight","kind":"identifier"}]},{"value":"rightToLeft","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1GradientForwardPoints~1rightToLeft\/title"},{"op":"replace","value":[{"text":"rightToLeft","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1GradientForwardPoints~1rightToLeft\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}