{"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/IM"},"relationshipsSections":[{"type":"inheritsFrom","kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/org.cocoapods.EaseCallUIKit\/objc(cs)NSObject"]},{"kind":"relationships","title":"Conforms To","type":"conformsTo","identifiers":["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallErrorCommonFeature"]}],"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easecalluikit\/im"]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit"]]},"abstract":[{"type":"text","text":"Convenience initializer for creating a "},{"type":"text","text":"CallError"},{"text":" with an RTC error.","type":"text"}],"sections":[],"topicSections":[{"identifiers":["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/IM\/errorCode","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/IM\/message"],"generated":true,"anchor":"Instance-Properties","title":"Instance Properties"},{"anchor":"Instance-Methods","generated":true,"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/IM\/initWithError:"]}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"text":"IM","kind":"identifier"},{"kind":"text","text":" : "},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}],"metadata":{"externalID":"c:@M@EaseCallUIKit@objc(cs)IM","role":"symbol","symbolKind":"class","modules":[{"name":"EaseCallUIKit"}],"roleHeading":"Class","fragments":[{"text":"IM","kind":"identifier"}],"navigatorTitle":[{"text":"IM","kind":"identifier"}],"title":"IM"},"references":{"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/IM/message":{"abstract":[],"role":"symbol","kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/IM\/message","fragments":[{"text":"message","kind":"identifier"}],"url":"\/documentation\/easecalluikit\/im\/message","title":"message","type":"topic"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/IM/errorCode":{"type":"topic","url":"\/documentation\/easecalluikit\/im\/errorcode","kind":"symbol","role":"symbol","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/IM\/errorCode","fragments":[{"kind":"identifier","text":"errorCode"}],"title":"errorCode","abstract":[]},"doc://org.cocoapods.EaseCallUIKit/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/objc(cs)NSObject","title":"NSObject"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallErrorCommonFeature":{"navigatorTitle":[{"text":"CallErrorCommonFeature","kind":"identifier"}],"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"CallErrorCommonFeature","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"CallErrorCommonFeature 协议定义了通用的错误特性"}],"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallErrorCommonFeature","type":"topic","title":"CallErrorCommonFeature","url":"\/documentation\/easecalluikit\/callerrorcommonfeature","role":"symbol"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/IM/initWithError:":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/IM\/initWithError:","abstract":[],"url":"\/documentation\/easecalluikit\/im\/initwitherror:","fragments":[{"kind":"text","text":"- "},{"text":"initWithError:","kind":"identifier"}],"role":"symbol","type":"topic","title":"initWithError:","navigatorTitle":[{"text":"initWithError:","kind":"identifier"}]},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/IM":{"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/IM","url":"\/documentation\/easecalluikit\/im","abstract":[{"type":"text","text":"Convenience initializer for creating a "},{"text":"CallError","type":"text"},{"text":" with an RTC error.","type":"text"}],"type":"topic","fragments":[{"text":"IM","kind":"identifier"}],"role":"symbol","kind":"symbol","title":"IM"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit":{"title":"EaseCallUIKit","type":"topic","url":"\/documentation\/easecalluikit","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit","abstract":[],"role":"collection","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"CallErrorCommonFeature","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallErrorCommonFeature\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallErrorCommonFeature\/fragments","value":[{"text":"CallErrorCommonFeature","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallErrorCommonFeature\/navigatorTitle","op":"replace","value":[{"text":"CallErrorCommonFeature","kind":"identifier"}]}]}]}