{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@","kind":"attribute"},{"preciseIdentifier":"s:ScM","kind":"attribute","text":"MainActor"},{"kind":"text","text":" "},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MultiCallBottomView"}],"platforms":["iOS"]}]}],"relationshipsSections":[{"title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/org.cocoapods.EaseCallUIKit\/objc(cs)UIView"],"kind":"relationships"},{"identifiers":["doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)NSCoding","doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)NSObject","doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)CALayerDelegate","doc:\/\/org.cocoapods.EaseCallUIKit\/s7CVarArgP","doc:\/\/org.cocoapods.EaseCallUIKit\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.EaseCallUIKit\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.EaseCallUIKit\/SQ","doc:\/\/org.cocoapods.EaseCallUIKit\/SH","doc:\/\/org.cocoapods.EaseCallUIKit\/s8SendableP","doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)UIAccessibilityIdentification","doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)UIAppearance","doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)UIAppearanceContainer","doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)UICoordinateSpace","doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)UIDynamicItem","doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)UIFocusEnvironment","doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)UIFocusItem","doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)UIFocusItemContainer","doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)UILargeContentViewerItem","doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)UIPopoverPresentationControllerSourceItem","doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)UIResponderStandardEditActions","doc:\/\/org.cocoapods.EaseCallUIKit\/5UIKit23UITraitChangeObservableP","doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)UITraitEnvironment","doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)UIUserActivityRestoring"],"type":"conformsTo","kind":"relationships","title":"Conforms To"}],"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit"]]},"metadata":{"navigatorTitle":[{"kind":"identifier","text":"MultiCallBottomView"}],"symbolKind":"class","externalID":"c:@M@EaseCallUIKit@objc(cs)MultiCallBottomView","role":"symbol","roleHeading":"Class","modules":[{"name":"EaseCallUIKit"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MultiCallBottomView"}],"title":"MultiCallBottomView"},"kind":"symbol","identifier":{"url":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/MultiCallBottomView","interfaceLanguage":"swift"},"topicSections":[{"anchor":"Initializers","identifiers":["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/MultiCallBottomView\/init(frame:connected:)"],"title":"Initializers","generated":true},{"generated":true,"identifiers":["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/MultiCallBottomView\/buttonData","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/MultiCallBottomView\/didTapButton"],"anchor":"Instance-Properties","title":"Instance Properties"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easecalluikit\/multicallbottomview"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easecalluikit\/multicallbottomview"]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://org.cocoapods.EaseCallUIKit/SH":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/SH","title":"Swift.Hashable"},"doc://org.cocoapods.EaseCallUIKit/objc(pl)UIResponderStandardEditActions":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)UIResponderStandardEditActions","title":"UIKit.UIResponderStandardEditActions"},"doc://org.cocoapods.EaseCallUIKit/objc(pl)UICoordinateSpace":{"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)UICoordinateSpace","type":"unresolvable","title":"UIKit.UICoordinateSpace"},"doc://org.cocoapods.EaseCallUIKit/objc(pl)UIUserActivityRestoring":{"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)UIUserActivityRestoring","type":"unresolvable","title":"UIKit.UIUserActivityRestoring"},"doc://org.cocoapods.EaseCallUIKit/s23CustomStringConvertibleP":{"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"},"doc://org.cocoapods.EaseCallUIKit/objc(pl)UIAccessibilityIdentification":{"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)UIAccessibilityIdentification","type":"unresolvable","title":"UIKit.UIAccessibilityIdentification"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/MultiCallBottomView/init(frame:connected:)":{"navigatorTitle":[{"kind":"identifier","text":"initWithFrame:connected:"}],"abstract":[],"kind":"symbol","role":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/MultiCallBottomView\/init(frame:connected:)","url":"\/documentation\/easecalluikit\/multicallbottomview\/init(frame:connected:)","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"frame","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@S@CGRect","kind":"typeIdentifier","text":"CGRect"},{"kind":"text","text":", "},{"kind":"externalParam","text":"connected"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"text":")","kind":"text"}],"title":"init(frame:connected:)"},"doc://org.cocoapods.EaseCallUIKit/objc(pl)NSCoding":{"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)NSCoding","title":"Foundation.NSCoding","type":"unresolvable"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit":{"title":"EaseCallUIKit","type":"topic","url":"\/documentation\/easecalluikit","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit","abstract":[],"role":"collection","kind":"symbol"},"doc://org.cocoapods.EaseCallUIKit/s8SendableP":{"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/s8SendableP","title":"Swift.Sendable","type":"unresolvable"},"doc://org.cocoapods.EaseCallUIKit/objc(pl)UIActivityItemsConfigurationProviding":{"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)UIActivityItemsConfigurationProviding","title":"UIKit.UIActivityItemsConfigurationProviding","type":"unresolvable"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/MultiCallBottomView/buttonData":{"abstract":[],"kind":"symbol","role":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/MultiCallBottomView\/buttonData","url":"\/documentation\/easecalluikit\/multicallbottomview\/buttondata","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"buttonData"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseCallUIKit@objc(cs)CallButtonData","text":"CallButtonData"},{"kind":"text","text":"]"}],"title":"buttonData"},"doc://org.cocoapods.EaseCallUIKit/objc(pl)UIFocusItemContainer":{"title":"UIKit.UIFocusItemContainer","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)UIFocusItemContainer"},"doc://org.cocoapods.EaseCallUIKit/objc(pl)UIPopoverPresentationControllerSourceItem":{"title":"UIKit.UIPopoverPresentationControllerSourceItem","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)UIPopoverPresentationControllerSourceItem"},"doc://org.cocoapods.EaseCallUIKit/5UIKit23UITraitChangeObservableP":{"title":"UIKit.UITraitChangeObservable","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/5UIKit23UITraitChangeObservableP"},"doc://org.cocoapods.EaseCallUIKit/objc(pl)NSObject":{"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)NSObject","type":"unresolvable","title":"ObjectiveC.NSObjectProtocol"},"doc://org.cocoapods.EaseCallUIKit/objc(pl)UIAppearance":{"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)UIAppearance","type":"unresolvable","title":"UIKit.UIAppearance"},"doc://org.cocoapods.EaseCallUIKit/objc(pl)UIAppearanceContainer":{"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)UIAppearanceContainer","type":"unresolvable","title":"UIKit.UIAppearanceContainer"},"doc://org.cocoapods.EaseCallUIKit/objc(pl)UIDynamicItem":{"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)UIDynamicItem","type":"unresolvable","title":"UIKit.UIDynamicItem"},"doc://org.cocoapods.EaseCallUIKit/objc(pl)UITraitEnvironment":{"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)UITraitEnvironment","type":"unresolvable","title":"UIKit.UITraitEnvironment"},"doc://org.cocoapods.EaseCallUIKit/objc(pl)UILargeContentViewerItem":{"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)UILargeContentViewerItem","type":"unresolvable","title":"UIKit.UILargeContentViewerItem"},"doc://org.cocoapods.EaseCallUIKit/objc(cs)UIView":{"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/objc(cs)UIView","type":"unresolvable","title":"UIView"},"doc://org.cocoapods.EaseCallUIKit/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/s28CustomDebugStringConvertibleP","type":"unresolvable","title":"Swift.CustomDebugStringConvertible"},"doc://org.cocoapods.EaseCallUIKit/objc(pl)CALayerDelegate":{"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)CALayerDelegate","type":"unresolvable","title":"QuartzCore.CALayerDelegate"},"doc://org.cocoapods.EaseCallUIKit/objc(pl)UIPasteConfigurationSupporting":{"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)UIPasteConfigurationSupporting","type":"unresolvable","title":"UIKit.UIPasteConfigurationSupporting"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/MultiCallBottomView/didTapButton":{"abstract":[],"kind":"symbol","role":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/MultiCallBottomView\/didTapButton","url":"\/documentation\/easecalluikit\/multicallbottomview\/didtapbutton","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"didTapButton"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","text":"CallButtonType","preciseIdentifier":"c:@M@EaseCallUIKit@E@CallButtonType"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"text":")?","kind":"text"}],"title":"didTapButton"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/MultiCallBottomView":{"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/MultiCallBottomView","url":"\/documentation\/easecalluikit\/multicallbottomview","abstract":[],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"MultiCallBottomView","kind":"identifier"}],"navigatorTitle":[{"text":"MultiCallBottomView","kind":"identifier"}],"role":"symbol","kind":"symbol","title":"MultiCallBottomView"},"doc://org.cocoapods.EaseCallUIKit/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/s7CVarArgP"},"doc://org.cocoapods.EaseCallUIKit/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/SQ"},"doc://org.cocoapods.EaseCallUIKit/objc(pl)UIFocusEnvironment":{"title":"UIKit.UIFocusEnvironment","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)UIFocusEnvironment"},"doc://org.cocoapods.EaseCallUIKit/objc(pl)UIFocusItem":{"title":"UIKit.UIFocusItem","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)UIFocusItem"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"path":"\/metadata\/title","op":"replace","value":"MultiCallBottomView"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","value":[{"kind":"identifier","text":"MultiCallBottomView"}],"path":"\/metadata\/fragments"},{"value":[{"kind":"identifier","text":"MultiCallBottomView"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":[{"title":"Instance Methods","generated":true,"identifiers":["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/MultiCallBottomView\/init(frame:connected:)"],"anchor":"Instance-Methods"}],"op":"replace","path":"\/topicSections"},{"value":[{"kind":"relationships","type":"inheritsFrom","identifiers":["doc:\/\/org.cocoapods.EaseCallUIKit\/objc(cs)UIView"],"title":"Inherits From"}],"op":"replace","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MultiCallBottomView"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIView","kind":"typeIdentifier","text":"UIView"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","value":"initWithFrame:connected:","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1MultiCallBottomView~1init(frame:connected:)\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1MultiCallBottomView~1init(frame:connected:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithFrame:connected:"}],"op":"replace"},{"value":"MultiCallBottomView","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1MultiCallBottomView\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1MultiCallBottomView\/fragments","value":[{"kind":"identifier","text":"MultiCallBottomView"}]},{"op":"replace","value":[{"kind":"identifier","text":"MultiCallBottomView"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1MultiCallBottomView\/navigatorTitle"}]}]}