{"relationshipsSections":[{"type":"inheritsFrom","identifiers":["doc:\/\/org.cocoapods.EaseCallUIKit\/objc(cs)UIViewController"],"title":"Inherits From","kind":"relationships"},{"type":"conformsTo","title":"Conforms To","kind":"relationships","identifiers":["doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)NSCoding","doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)NSExtensionRequestHandling","doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)NSObject","doc:\/\/org.cocoapods.EaseCallUIKit\/s7CVarArgP","doc:\/\/org.cocoapods.EaseCallUIKit\/s8CopyableP","doc:\/\/org.cocoapods.EaseCallUIKit\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.EaseCallUIKit\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.EaseCallUIKit\/SQ","doc:\/\/org.cocoapods.EaseCallUIKit\/SH","doc:\/\/org.cocoapods.EaseCallUIKit\/s8SendableP","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/ThemeSwitchProtocol","doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)UIAppearanceContainer","doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)UIContentContainer","doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)UIFocusEnvironment","doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)UIResponderStandardEditActions","doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)UIScrollViewDelegate","doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)UIStateRestoring","doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)UITableViewDataSource","doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)UITableViewDelegate","doc:\/\/org.cocoapods.EaseCallUIKit\/5UIKit23UITraitChangeObservableP","doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)UITraitEnvironment","doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)UIUserActivityRestoring"]}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"@","kind":"attribute"},{"kind":"attribute","preciseIdentifier":"s:ScM","text":"MainActor"},{"text":" ","kind":"text"},{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"MultiCallParticipantsController","kind":"identifier"}]}],"kind":"declarations"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"title":"MultiCallParticipantsController","roleHeading":"Class","modules":[{"name":"EaseCallUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"MultiCallParticipantsController"}],"role":"symbol","symbolKind":"class","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MultiCallParticipantsController"}],"externalID":"c:@M@EaseCallUIKit@objc(cs)MultiCallParticipantsController"},"variants":[{"paths":["\/documentation\/easecalluikit\/multicallparticipantscontroller"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/easecalluikit\/multicallparticipantscontroller"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/MultiCallParticipantsController"},"kind":"symbol","topicSections":[{"generated":true,"anchor":"Initializers","identifiers":["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/MultiCallParticipantsController\/init(coder:)","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/MultiCallParticipantsController\/init(groupId:excludeUsers:closure:)"],"title":"Initializers"},{"title":"Instance Properties","identifiers":["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/MultiCallParticipantsController\/cursor","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/MultiCallParticipantsController\/excludeUsers","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/MultiCallParticipantsController\/groupId","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/MultiCallParticipantsController\/navigation","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/MultiCallParticipantsController\/participants","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/MultiCallParticipantsController\/participantsList"],"generated":true,"anchor":"Instance-Properties"},{"anchor":"Instance-Methods","identifiers":["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/MultiCallParticipantsController\/cellForRowAt(indexPath:)","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/MultiCallParticipantsController\/createNavigation()","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/MultiCallParticipantsController\/didSelectRowAt(indexPath:)","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/MultiCallParticipantsController\/navigationClick(type:indexPath:)","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/MultiCallParticipantsController\/pop()","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/MultiCallParticipantsController\/rightAction()","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/MultiCallParticipantsController\/viewDidLoad()"],"title":"Instance Methods","generated":true},{"identifiers":["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/MultiCallParticipantsController\/ThemeSwitchProtocol-Implementations","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/MultiCallParticipantsController\/UITableViewDataSource-Implementations","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/MultiCallParticipantsController\/UITableViewDelegate-Implementations"],"generated":true,"title":"Default Implementations","anchor":"Default-Implementations"}],"references":{"doc://org.cocoapods.EaseCallUIKit/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/MultiCallParticipantsController/init(groupId:excludeUsers:closure:)":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/MultiCallParticipantsController\/init(groupId:excludeUsers:closure:)","abstract":[],"url":"\/documentation\/easecalluikit\/multicallparticipantscontroller\/init(groupid:excludeusers:closure:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"groupId"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"excludeUsers"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"], ","kind":"text"},{"text":"closure","kind":"externalParam"},{"text":": ([","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"], ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"text":")","kind":"text"}],"role":"symbol","type":"topic","title":"init(groupId:excludeUsers:closure:)","navigatorTitle":[{"text":"initWithGroupId:excludeUsers:closure:","kind":"identifier"}]},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/MultiCallParticipantsController/participantsList":{"url":"\/documentation\/easecalluikit\/multicallparticipantscontroller\/participantslist","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"participantsList","kind":"identifier"},{"kind":"text","text":": "},{"text":"UITableView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UITableView"}],"kind":"symbol","role":"symbol","type":"topic","abstract":[],"title":"participantsList","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/MultiCallParticipantsController\/participantsList"},"doc://org.cocoapods.EaseCallUIKit/SH":{"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/MultiCallParticipantsController/cellForRowAt(indexPath:)":{"kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cellForRowAt","kind":"identifier"},{"text":"(","kind":"text"},{"text":"indexPath","kind":"externalParam"},{"kind":"text","text":": "},{"text":"IndexPath","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation9IndexPathV"},{"kind":"text","text":") -> "},{"text":"UITableViewCell","preciseIdentifier":"c:objc(cs)UITableViewCell","kind":"typeIdentifier"}],"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/MultiCallParticipantsController\/cellForRowAt(indexPath:)","type":"topic","abstract":[],"url":"\/documentation\/easecalluikit\/multicallparticipantscontroller\/cellforrowat(indexpath:)","role":"symbol","navigatorTitle":[{"text":"cellForRowAtIndexPath:","kind":"identifier"}],"title":"cellForRowAt(indexPath:)"},"doc://org.cocoapods.EaseCallUIKit/objc(pl)NSExtensionRequestHandling":{"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)NSExtensionRequestHandling","title":"Foundation.NSExtensionRequestHandling","type":"unresolvable"},"doc://org.cocoapods.EaseCallUIKit/objc(pl)UIFocusEnvironment":{"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)UIFocusEnvironment","title":"UIKit.UIFocusEnvironment","type":"unresolvable"},"doc://org.cocoapods.EaseCallUIKit/5UIKit23UITraitChangeObservableP":{"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/5UIKit23UITraitChangeObservableP","title":"UIKit.UITraitChangeObservable","type":"unresolvable"},"doc://org.cocoapods.EaseCallUIKit/SQ":{"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://org.cocoapods.EaseCallUIKit/objc(pl)UIScrollViewDelegate":{"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)UIScrollViewDelegate","title":"UIKit.UIScrollViewDelegate","type":"unresolvable"},"doc://org.cocoapods.EaseCallUIKit/objc(pl)UIAppearanceContainer":{"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)UIAppearanceContainer","title":"UIKit.UIAppearanceContainer","type":"unresolvable"},"doc://org.cocoapods.EaseCallUIKit/s8CopyableP":{"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/s8CopyableP","title":"Swift.Copyable","type":"unresolvable"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/MultiCallParticipantsController/cursor":{"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/MultiCallParticipantsController\/cursor","url":"\/documentation\/easecalluikit\/multicallparticipantscontroller\/cursor","title":"cursor","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"cursor","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"kind":"symbol","abstract":[],"type":"topic"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/MultiCallParticipantsController/init(coder:)":{"url":"\/documentation\/easecalluikit\/multicallparticipantscontroller\/init(coder:)","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"coder","kind":"externalParam"},{"kind":"text","text":": "},{"text":"NSCoder","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSCoder"},{"text":")","kind":"text"}],"kind":"symbol","role":"symbol","type":"topic","abstract":[],"title":"init(coder:)","navigatorTitle":[{"kind":"identifier","text":"initWithCoder:"}],"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/MultiCallParticipantsController\/init(coder:)"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/MultiCallParticipantsController/navigation":{"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/MultiCallParticipantsController\/navigation","url":"\/documentation\/easecalluikit\/multicallparticipantscontroller\/navigation","title":"navigation","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"navigation","kind":"identifier"},{"kind":"text","text":": "},{"text":"CallNavigationBar","kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseCallUIKit@objc(cs)CallNavigationBar"}],"kind":"symbol","abstract":[],"type":"topic"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/MultiCallParticipantsController/rightAction()":{"abstract":[],"title":"rightAction()","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/MultiCallParticipantsController\/rightAction()","url":"\/documentation\/easecalluikit\/multicallparticipantscontroller\/rightaction()","type":"topic","navigatorTitle":[{"kind":"identifier","text":"rightAction"}],"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"rightAction"},{"text":"()","kind":"text"}]},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/MultiCallParticipantsController/didSelectRowAt(indexPath:)":{"type":"topic","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"didSelectRowAtIndexPath:","kind":"identifier"}],"title":"didSelectRowAt(indexPath:)","url":"\/documentation\/easecalluikit\/multicallparticipantscontroller\/didselectrowat(indexpath:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"didSelectRowAt","kind":"identifier"},{"text":"(","kind":"text"},{"text":"indexPath","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation9IndexPathV","text":"IndexPath"},{"text":")","kind":"text"}],"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/MultiCallParticipantsController\/didSelectRowAt(indexPath:)","abstract":[]},"doc://org.cocoapods.EaseCallUIKit/objc(pl)UIActivityItemsConfigurationProviding":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)UIActivityItemsConfigurationProviding","title":"UIKit.UIActivityItemsConfigurationProviding"},"doc://org.cocoapods.EaseCallUIKit/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://org.cocoapods.EaseCallUIKit/s8SendableP":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/s8SendableP","title":"Swift.Sendable"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/MultiCallParticipantsController/pop()":{"abstract":[],"kind":"symbol","title":"pop()","url":"\/documentation\/easecalluikit\/multicallparticipantscontroller\/pop()","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/MultiCallParticipantsController\/pop()","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"pop","kind":"identifier"},{"kind":"text","text":"()"}],"navigatorTitle":[{"text":"pop","kind":"identifier"}],"role":"symbol","type":"topic"},"doc://org.cocoapods.EaseCallUIKit/objc(pl)UIPasteConfigurationSupporting":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)UIPasteConfigurationSupporting","title":"UIKit.UIPasteConfigurationSupporting"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/MultiCallParticipantsController/groupId":{"url":"\/documentation\/easecalluikit\/multicallparticipantscontroller\/groupid","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"groupId","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"kind":"symbol","role":"symbol","type":"topic","abstract":[],"title":"groupId","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/MultiCallParticipantsController\/groupId"},"doc://org.cocoapods.EaseCallUIKit/objc(pl)UIResponderStandardEditActions":{"type":"unresolvable","title":"UIKit.UIResponderStandardEditActions","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)UIResponderStandardEditActions"},"doc://org.cocoapods.EaseCallUIKit/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/s7CVarArgP"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/MultiCallParticipantsController/viewDidLoad()":{"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/MultiCallParticipantsController\/viewDidLoad()","url":"\/documentation\/easecalluikit\/multicallparticipantscontroller\/viewdidload()","navigatorTitle":[{"kind":"identifier","text":"viewDidLoad"}],"title":"viewDidLoad()","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"viewDidLoad","kind":"identifier"},{"text":"()","kind":"text"}],"kind":"symbol","abstract":[],"type":"topic"},"doc://org.cocoapods.EaseCallUIKit/objc(pl)UIUserActivityRestoring":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)UIUserActivityRestoring","title":"UIKit.UIUserActivityRestoring"},"doc://org.cocoapods.EaseCallUIKit/objc(cs)UIViewController":{"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/objc(cs)UIViewController","title":"UIViewController","type":"unresolvable"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/MultiCallParticipantsController/UITableViewDataSource-Implementations":{"abstract":[],"kind":"article","title":"UITableViewDataSource Implementations","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/MultiCallParticipantsController\/UITableViewDataSource-Implementations","url":"\/documentation\/easecalluikit\/multicallparticipantscontroller\/uitableviewdatasource-implementations","role":"collectionGroup","type":"topic"},"doc://org.cocoapods.EaseCallUIKit/objc(pl)UIStateRestoring":{"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)UIStateRestoring","title":"UIKit.UIStateRestoring","type":"unresolvable"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/MultiCallParticipantsController/participants":{"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"participants"},{"text":": [","kind":"text"},{"text":"CallProfileProtocol","preciseIdentifier":"c:@M@EaseCallUIKit@objc(pl)CallProfileProtocol","kind":"typeIdentifier"},{"kind":"text","text":"]"}],"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/MultiCallParticipantsController\/participants","title":"participants","url":"\/documentation\/easecalluikit\/multicallparticipantscontroller\/participants","abstract":[],"type":"topic","kind":"symbol"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/MultiCallParticipantsController/UITableViewDelegate-Implementations":{"kind":"article","title":"UITableViewDelegate Implementations","type":"topic","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/MultiCallParticipantsController\/UITableViewDelegate-Implementations","url":"\/documentation\/easecalluikit\/multicallparticipantscontroller\/uitableviewdelegate-implementations","role":"collectionGroup","abstract":[]},"doc://org.cocoapods.EaseCallUIKit/objc(pl)UITraitEnvironment":{"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)UITraitEnvironment","title":"UIKit.UITraitEnvironment","type":"unresolvable"},"doc://org.cocoapods.EaseCallUIKit/objc(pl)UITableViewDelegate":{"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)UITableViewDelegate","title":"UITableViewDelegate","type":"unresolvable"},"doc://org.cocoapods.EaseCallUIKit/objc(pl)UITableViewDataSource":{"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)UITableViewDataSource","title":"UITableViewDataSource","type":"unresolvable"},"doc://org.cocoapods.EaseCallUIKit/objc(pl)NSCoding":{"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)NSCoding","title":"Foundation.NSCoding","type":"unresolvable"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit":{"title":"EaseCallUIKit","type":"topic","url":"\/documentation\/easecalluikit","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit","abstract":[],"role":"collection","kind":"symbol"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/MultiCallParticipantsController/createNavigation()":{"type":"topic","title":"createNavigation()","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/MultiCallParticipantsController\/createNavigation()","url":"\/documentation\/easecalluikit\/multicallparticipantscontroller\/createnavigation()","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"createNavigation","kind":"identifier"},{"text":"() -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseCallUIKit@objc(cs)CallNavigationBar","text":"CallNavigationBar"}],"navigatorTitle":[{"kind":"identifier","text":"createNavigation"}],"abstract":[]},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/ThemeSwitchProtocol":{"type":"topic","url":"\/documentation\/easecalluikit\/themeswitchprotocol","kind":"symbol","navigatorTitle":[{"text":"ThemeSwitchProtocol","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/ThemeSwitchProtocol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"ThemeSwitchProtocol","kind":"identifier"}],"title":"ThemeSwitchProtocol","abstract":[{"text":"When the system theme changes, you can use this static method to switch between the light and dark themes of the ease chat UIKit.","type":"text"}]},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/MultiCallParticipantsController/excludeUsers":{"url":"\/documentation\/easecalluikit\/multicallparticipantscontroller\/excludeusers","type":"topic","title":"excludeUsers","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"excludeUsers","kind":"identifier"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"]","kind":"text"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/MultiCallParticipantsController\/excludeUsers","abstract":[]},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/MultiCallParticipantsController":{"url":"\/documentation\/easecalluikit\/multicallparticipantscontroller","role":"symbol","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/MultiCallParticipantsController","title":"MultiCallParticipantsController","navigatorTitle":[{"text":"MultiCallParticipantsController","kind":"identifier"}],"type":"topic","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MultiCallParticipantsController","kind":"identifier"}],"kind":"symbol"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/MultiCallParticipantsController/ThemeSwitchProtocol-Implementations":{"url":"\/documentation\/easecalluikit\/multicallparticipantscontroller\/themeswitchprotocol-implementations","title":"ThemeSwitchProtocol Implementations","role":"collectionGroup","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/MultiCallParticipantsController\/ThemeSwitchProtocol-Implementations","abstract":[],"type":"topic","kind":"article"},"doc://org.cocoapods.EaseCallUIKit/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://org.cocoapods.EaseCallUIKit/objc(pl)UIContentContainer":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)UIContentContainer","title":"UIKit.UIContentContainer"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/MultiCallParticipantsController/navigationClick(type:indexPath:)":{"type":"topic","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/MultiCallParticipantsController\/navigationClick(type:indexPath:)","role":"symbol","abstract":[],"title":"navigationClick(type:indexPath:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"navigationClick"},{"text":"(","kind":"text"},{"text":"type","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"ChatNavigationBarClickEvent","kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseCallUIKit@E@ChatNavigationBarClickEvent"},{"text":", ","kind":"text"},{"text":"indexPath","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation9IndexPathV","text":"IndexPath","kind":"typeIdentifier"},{"kind":"text","text":"?)"}],"url":"\/documentation\/easecalluikit\/multicallparticipantscontroller\/navigationclick(type:indexpath:)","navigatorTitle":[{"text":"navigationClickWithType:indexPath:","kind":"identifier"}],"kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"MultiCallParticipantsController"},{"op":"replace","value":"class","path":"\/metadata\/symbolKind"},{"value":[{"text":"MultiCallParticipantsController","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"MultiCallParticipantsController"}]},{"value":[{"generated":true,"identifiers":["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/MultiCallParticipantsController\/cellForRowAt(indexPath:)","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/MultiCallParticipantsController\/createNavigation()","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/MultiCallParticipantsController\/didSelectRowAt(indexPath:)","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/MultiCallParticipantsController\/init(coder:)","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/MultiCallParticipantsController\/init(groupId:excludeUsers:closure:)","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/MultiCallParticipantsController\/navigationClick(type:indexPath:)","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/MultiCallParticipantsController\/pop()","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/MultiCallParticipantsController\/rightAction()","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/MultiCallParticipantsController\/viewDidLoad()"],"anchor":"Instance-Methods","title":"Instance Methods"},{"generated":true,"anchor":"Default-Implementations","identifiers":["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/MultiCallParticipantsController\/ThemeSwitchProtocol-Implementations","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/MultiCallParticipantsController\/UITableViewDataSource-Implementations","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/MultiCallParticipantsController\/UITableViewDelegate-Implementations"],"title":"Default Implementations"}],"op":"replace","path":"\/topicSections"},{"op":"replace","value":[{"title":"Inherits From","identifiers":["doc:\/\/org.cocoapods.EaseCallUIKit\/objc(cs)UIViewController"],"kind":"relationships","type":"inheritsFrom"},{"kind":"relationships","identifiers":["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/ThemeSwitchProtocol","doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)UITableViewDataSource","doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)UITableViewDelegate"],"type":"conformsTo","title":"Conforms To"}],"path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MultiCallParticipantsController"},{"kind":"text","text":" : "},{"text":"UIViewController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"initWithGroupId:excludeUsers:closure:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1MultiCallParticipantsController~1init(groupId:excludeUsers:closure:)\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1MultiCallParticipantsController~1init(groupId:excludeUsers:closure:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithGroupId:excludeUsers:closure:","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1MultiCallParticipantsController~1cellForRowAt(indexPath:)\/title","value":"cellForRowAtIndexPath:"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1MultiCallParticipantsController~1cellForRowAt(indexPath:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"cellForRowAtIndexPath:","kind":"identifier"}]},{"value":"initWithCoder:","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1MultiCallParticipantsController~1init(coder:)\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1MultiCallParticipantsController~1init(coder:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithCoder:"}]},{"value":"rightAction","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1MultiCallParticipantsController~1rightAction()\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1MultiCallParticipantsController~1rightAction()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"rightAction"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1MultiCallParticipantsController~1didSelectRowAt(indexPath:)\/title","value":"didSelectRowAtIndexPath:"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1MultiCallParticipantsController~1didSelectRowAt(indexPath:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"didSelectRowAtIndexPath:","kind":"identifier"}]},{"value":"pop","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1MultiCallParticipantsController~1pop()\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1MultiCallParticipantsController~1pop()\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"pop"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1MultiCallParticipantsController~1viewDidLoad()\/title","value":"viewDidLoad"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1MultiCallParticipantsController~1viewDidLoad()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"viewDidLoad","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1MultiCallParticipantsController~1createNavigation()\/title","value":"createNavigation"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1MultiCallParticipantsController~1createNavigation()\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"createNavigation"}]},{"value":"ThemeSwitchProtocol","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1ThemeSwitchProtocol\/title"},{"value":[{"text":"ThemeSwitchProtocol","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1ThemeSwitchProtocol\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1ThemeSwitchProtocol\/navigatorTitle","value":[{"kind":"identifier","text":"ThemeSwitchProtocol"}]},{"value":"MultiCallParticipantsController","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1MultiCallParticipantsController\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1MultiCallParticipantsController\/fragments","op":"replace","value":[{"text":"MultiCallParticipantsController","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"MultiCallParticipantsController"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1MultiCallParticipantsController\/navigatorTitle","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1MultiCallParticipantsController~1navigationClick(type:indexPath:)\/title","value":"navigationClickWithType:indexPath:"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"navigationClickWithType:indexPath:"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1MultiCallParticipantsController~1navigationClick(type:indexPath:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}