{"kind":"symbol","topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/RingAlert\/actionClosure"],"generated":true,"anchor":"Instance-Properties"},{"identifiers":["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/RingAlert\/touchesBegan(_:with:)"],"title":"Instance Methods","generated":true,"anchor":"Instance-Methods"}],"metadata":{"roleHeading":"Class","modules":[{"name":"EaseCallUIKit"}],"title":"RingAlert","navigatorTitle":[{"text":"RingAlert","kind":"identifier"}],"role":"symbol","symbolKind":"class","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"RingAlert"}],"externalID":"c:@M@EaseCallUIKit@objc(cs)RingAlert"},"identifier":{"url":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/RingAlert","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit"]]},"relationshipsSections":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/org.cocoapods.EaseCallUIKit\/objc(cs)UIView"],"type":"inheritsFrom"},{"kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)NSCoding","doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)NSObject","doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)CALayerDelegate","doc:\/\/org.cocoapods.EaseCallUIKit\/s7CVarArgP","doc:\/\/org.cocoapods.EaseCallUIKit\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.EaseCallUIKit\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.EaseCallUIKit\/SQ","doc:\/\/org.cocoapods.EaseCallUIKit\/SH","doc:\/\/org.cocoapods.EaseCallUIKit\/s8SendableP","doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)UIAccessibilityIdentification","doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)UIAppearance","doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)UIAppearanceContainer","doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)UICoordinateSpace","doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)UIDynamicItem","doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)UIFocusEnvironment","doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)UIFocusItem","doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)UIFocusItemContainer","doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)UILargeContentViewerItem","doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)UIPopoverPresentationControllerSourceItem","doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)UIResponderStandardEditActions","doc:\/\/org.cocoapods.EaseCallUIKit\/5UIKit23UITraitChangeObservableP","doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)UITraitEnvironment","doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)UIUserActivityRestoring"],"type":"conformsTo"}],"variants":[{"paths":["\/documentation\/easecalluikit\/ringalert"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easecalluikit\/ringalert"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"RingAlert","kind":"identifier"}]}]}],"references":{"doc://org.cocoapods.EaseCallUIKit/objc(cs)UIView":{"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/objc(cs)UIView","type":"unresolvable","title":"UIView"},"doc://org.cocoapods.EaseCallUIKit/objc(pl)UIPasteConfigurationSupporting":{"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)UIPasteConfigurationSupporting","type":"unresolvable","title":"UIKit.UIPasteConfigurationSupporting"},"doc://org.cocoapods.EaseCallUIKit/s7CVarArgP":{"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/s7CVarArgP","type":"unresolvable","title":"Swift.CVarArg"},"doc://org.cocoapods.EaseCallUIKit/objc(pl)UIPopoverPresentationControllerSourceItem":{"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)UIPopoverPresentationControllerSourceItem","type":"unresolvable","title":"UIKit.UIPopoverPresentationControllerSourceItem"},"doc://org.cocoapods.EaseCallUIKit/objc(pl)UIUserActivityRestoring":{"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)UIUserActivityRestoring","type":"unresolvable","title":"UIKit.UIUserActivityRestoring"},"doc://org.cocoapods.EaseCallUIKit/objc(pl)UIDynamicItem":{"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)UIDynamicItem","type":"unresolvable","title":"UIKit.UIDynamicItem"},"doc://org.cocoapods.EaseCallUIKit/objc(pl)UIResponderStandardEditActions":{"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)UIResponderStandardEditActions","type":"unresolvable","title":"UIKit.UIResponderStandardEditActions"},"doc://org.cocoapods.EaseCallUIKit/objc(pl)NSCoding":{"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)NSCoding","type":"unresolvable","title":"Foundation.NSCoding"},"doc://org.cocoapods.EaseCallUIKit/SH":{"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/RingAlert":{"url":"\/documentation\/easecalluikit\/ringalert","type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"RingAlert"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/RingAlert","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RingAlert","kind":"identifier"}],"title":"RingAlert","abstract":[]},"doc://org.cocoapods.EaseCallUIKit/s23CustomStringConvertibleP":{"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"},"doc://org.cocoapods.EaseCallUIKit/objc(pl)CALayerDelegate":{"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)CALayerDelegate","type":"unresolvable","title":"QuartzCore.CALayerDelegate"},"doc://org.cocoapods.EaseCallUIKit/objc(pl)UIFocusItemContainer":{"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)UIFocusItemContainer","type":"unresolvable","title":"UIKit.UIFocusItemContainer"},"doc://org.cocoapods.EaseCallUIKit/objc(pl)UIFocusItem":{"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)UIFocusItem","type":"unresolvable","title":"UIKit.UIFocusItem"},"doc://org.cocoapods.EaseCallUIKit/objc(pl)UIAccessibilityIdentification":{"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)UIAccessibilityIdentification","type":"unresolvable","title":"UIKit.UIAccessibilityIdentification"},"doc://org.cocoapods.EaseCallUIKit/objc(pl)UIAppearanceContainer":{"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)UIAppearanceContainer","type":"unresolvable","title":"UIKit.UIAppearanceContainer"},"doc://org.cocoapods.EaseCallUIKit/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/s28CustomDebugStringConvertibleP","type":"unresolvable","title":"Swift.CustomDebugStringConvertible"},"doc://org.cocoapods.EaseCallUIKit/s8SendableP":{"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/s8SendableP","type":"unresolvable","title":"Swift.Sendable"},"doc://org.cocoapods.EaseCallUIKit/objc(pl)UICoordinateSpace":{"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)UICoordinateSpace","type":"unresolvable","title":"UIKit.UICoordinateSpace"},"doc://org.cocoapods.EaseCallUIKit/SQ":{"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://org.cocoapods.EaseCallUIKit/objc(pl)UIFocusEnvironment":{"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)UIFocusEnvironment","type":"unresolvable","title":"UIKit.UIFocusEnvironment"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/RingAlert/actionClosure":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/RingAlert\/actionClosure","abstract":[],"url":"\/documentation\/easecalluikit\/ringalert\/actionclosure","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"actionClosure","kind":"identifier"},{"text":": ((","kind":"text"},{"preciseIdentifier":"c:@M@EaseCallUIKit@E@RingAlertAction","text":"RingAlertAction","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"kind":"text","text":")?"}],"role":"symbol","type":"topic","title":"actionClosure"},"doc://org.cocoapods.EaseCallUIKit/5UIKit23UITraitChangeObservableP":{"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/5UIKit23UITraitChangeObservableP","type":"unresolvable","title":"UIKit.UITraitChangeObservable"},"doc://org.cocoapods.EaseCallUIKit/objc(pl)UILargeContentViewerItem":{"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)UILargeContentViewerItem","type":"unresolvable","title":"UIKit.UILargeContentViewerItem"},"doc://org.cocoapods.EaseCallUIKit/objc(pl)NSObject":{"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)NSObject","type":"unresolvable","title":"ObjectiveC.NSObjectProtocol"},"doc://org.cocoapods.EaseCallUIKit/objc(pl)UITraitEnvironment":{"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)UITraitEnvironment","type":"unresolvable","title":"UIKit.UITraitEnvironment"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit":{"title":"EaseCallUIKit","type":"topic","url":"\/documentation\/easecalluikit","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit","abstract":[],"role":"collection","kind":"symbol"},"doc://org.cocoapods.EaseCallUIKit/objc(pl)UIActivityItemsConfigurationProviding":{"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)UIActivityItemsConfigurationProviding","type":"unresolvable","title":"UIKit.UIActivityItemsConfigurationProviding"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/RingAlert/touchesBegan(_:with:)":{"url":"\/documentation\/easecalluikit\/ringalert\/touchesbegan(_:with:)","kind":"symbol","title":"touchesBegan(_:with:)","abstract":[],"navigatorTitle":[{"text":"touchesBegan:withEvent:","kind":"identifier"}],"role":"symbol","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"touchesBegan","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"s:Sh","text":"Set"},{"kind":"text","text":"<"},{"text":"UITouch","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UITouch"},{"kind":"text","text":">, "},{"text":"with","kind":"externalParam"},{"kind":"text","text":": "},{"text":"UIEvent","preciseIdentifier":"c:objc(cs)UIEvent","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/RingAlert\/touchesBegan(_:with:)"},"doc://org.cocoapods.EaseCallUIKit/objc(pl)UIAppearance":{"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)UIAppearance","type":"unresolvable","title":"UIKit.UIAppearance"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"path":"\/metadata\/title","value":"RingAlert","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","value":[{"text":"RingAlert","kind":"identifier"}],"path":"\/metadata\/fragments"},{"value":[{"text":"RingAlert","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"path":"\/topicSections","op":"replace","value":[{"anchor":"Instance-Methods","title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/RingAlert\/touchesBegan(_:with:)"],"generated":true}]},{"value":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/org.cocoapods.EaseCallUIKit\/objc(cs)UIView"],"type":"inheritsFrom"}],"path":"\/relationshipsSections","op":"replace"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"RingAlert"},{"text":" : ","kind":"text"},{"text":"UIView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIView"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"value":"RingAlert","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1RingAlert\/title"},{"op":"replace","value":[{"kind":"identifier","text":"RingAlert"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1RingAlert\/fragments"},{"op":"replace","value":[{"text":"RingAlert","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1RingAlert\/navigatorTitle"},{"value":"touchesBegan:withEvent:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1RingAlert~1touchesBegan(_:with:)\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1RingAlert~1touchesBegan(_:with:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"touchesBegan:withEvent:"}],"op":"replace"}]}]}