{"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TimerService","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObjectProtocol","preciseIdentifier":"c:objc(pl)NSObject","kind":"typeIdentifier"}]}]}],"relationshipsSections":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)NSObject"],"type":"inheritsFrom"},{"identifiers":["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/GlobalTimerManager"],"kind":"relationships","type":"conformingTypes","title":"Conforming Types"}],"metadata":{"role":"symbol","modules":[{"name":"EaseCallUIKit"}],"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"TimerService","kind":"identifier"}],"roleHeading":"Protocol","navigatorTitle":[{"text":"TimerService","kind":"identifier"}],"externalID":"c:@M@EaseCallUIKit@objc(pl)TimerService","title":"TimerService","symbolKind":"protocol"},"kind":"symbol","identifier":{"url":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/TimerService","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"minor":3,"major":0},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit"]]},"topicSections":[{"identifiers":["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/TimerService\/registerListener(_:timerIdentify:)","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/TimerService\/removeListener(_:timerIdentify:)","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/TimerService\/replaceTimer(_:timerIdentify:)"],"anchor":"Instance-Methods","title":"Instance Methods","generated":true}],"variants":[{"paths":["\/documentation\/easecalluikit\/timerservice"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easecalluikit\/timerservice"]}],"references":{"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/TimerService":{"title":"TimerService","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"TimerService"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/TimerService","url":"\/documentation\/easecalluikit\/timerservice","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TimerService","kind":"identifier"}],"abstract":[]},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/TimerService/registerListener(_:timerIdentify:)":{"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/TimerService\/registerListener(_:timerIdentify:)","navigatorTitle":[{"text":"registerListener:timerIdentify:","kind":"identifier"}],"type":"topic","title":"registerListener(_:timerIdentify:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"registerListener"},{"text":"(","kind":"text"},{"text":"TimerServiceListener","preciseIdentifier":"c:@M@EaseCallUIKit@objc(pl)TimerServiceListener","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"timerIdentify","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":")"}],"abstract":[{"text":"Adds a listener to receive timer-related events.","type":"text"}],"kind":"symbol","required":true,"role":"symbol","url":"\/documentation\/easecalluikit\/timerservice\/registerlistener(_:timeridentify:)"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/TimerService/replaceTimer(_:timerIdentify:)":{"title":"replaceTimer(_:timerIdentify:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"replaceTimer"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@EaseCallUIKit@objc(pl)TimerServiceListener","kind":"typeIdentifier","text":"TimerServiceListener"},{"kind":"text","text":", "},{"text":"timerIdentify","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":")","kind":"text"}],"abstract":[{"type":"text","text":"Replaces an existing timer with a new one."}],"kind":"symbol","type":"topic","url":"\/documentation\/easecalluikit\/timerservice\/replacetimer(_:timeridentify:)","required":true,"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/TimerService\/replaceTimer(_:timerIdentify:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"replaceTimer:timerIdentify:"}]},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit":{"title":"EaseCallUIKit","type":"topic","url":"\/documentation\/easecalluikit","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit","abstract":[],"role":"collection","kind":"symbol"},"doc://org.cocoapods.EaseCallUIKit/objc(pl)NSObject":{"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)NSObject","title":"NSObject","type":"unresolvable"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/GlobalTimerManager":{"kind":"symbol","title":"GlobalTimerManager","navigatorTitle":[{"text":"GlobalTimerManager","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/GlobalTimerManager","url":"\/documentation\/easecalluikit\/globaltimermanager","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GlobalTimerManager"}],"abstract":[]},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/TimerService/removeListener(_:timerIdentify:)":{"abstract":[{"text":"Removes a previously added listener from receiving timer-related events.","type":"text"}],"required":true,"kind":"symbol","title":"removeListener(_:timerIdentify:)","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/TimerService\/removeListener(_:timerIdentify:)","url":"\/documentation\/easecalluikit\/timerservice\/removelistener(_:timeridentify:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"removeListener","kind":"identifier"},{"text":"(","kind":"text"},{"text":"TimerServiceListener","kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseCallUIKit@objc(pl)TimerServiceListener"},{"kind":"text","text":", "},{"text":"timerIdentify","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"removeListener:timerIdentify:","kind":"identifier"}],"role":"symbol","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Protocol","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"TimerService"},{"path":"\/metadata\/symbolKind","op":"replace","value":"protocol"},{"value":[{"kind":"identifier","text":"TimerService"}],"path":"\/metadata\/fragments","op":"replace"},{"value":[{"text":"TimerService","kind":"identifier"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"path":"\/topicSections","op":"replace","value":[{"anchor":"Instance-Methods","title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/TimerService\/registerListener(_:timerIdentify:)","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/TimerService\/removeListener(_:timerIdentify:)","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/TimerService\/replaceTimer(_:timerIdentify:)"],"generated":true}]},{"value":[{"type":"inheritsFrom","kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)NSObject"]},{"type":"conformingTypes","title":"Conforming Types","identifiers":["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/GlobalTimerManager"],"kind":"relationships"}],"op":"replace","path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"@protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TimerService","kind":"identifier"},{"kind":"text","text":" <"},{"preciseIdentifier":"c:objc(pl)NSObject","text":"NSObject","kind":"typeIdentifier"},{"kind":"text","text":">"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1TimerService\/title","value":"TimerService","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1TimerService\/fragments","value":[{"kind":"identifier","text":"TimerService"}]},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1TimerService\/navigatorTitle","value":[{"kind":"identifier","text":"TimerService"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1TimerService~1registerListener(_:timerIdentify:)\/title","value":"registerListener:timerIdentify:"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"registerListener:timerIdentify:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1TimerService~1registerListener(_:timerIdentify:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1TimerService~1replaceTimer(_:timerIdentify:)\/title","value":"replaceTimer:timerIdentify:"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"replaceTimer:timerIdentify:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1TimerService~1replaceTimer(_:timerIdentify:)\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1GlobalTimerManager\/title","value":"GlobalTimerManager","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1GlobalTimerManager\/fragments","value":[{"text":"GlobalTimerManager","kind":"identifier"}],"op":"replace"},{"op":"replace","value":[{"text":"GlobalTimerManager","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1GlobalTimerManager\/navigatorTitle"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1TimerService~1removeListener(_:timerIdentify:)\/title","value":"removeListener:timerIdentify:","op":"replace"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"removeListener:timerIdentify:"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1TimerService~1removeListener(_:timerIdentify:)\/fragments"}]}]}