{"variants":[{"paths":["\/documentation\/easecalluikit\/userinfoview"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/easecalluikit\/userinfoview"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"title":"Inherits From","type":"inheritsFrom","kind":"relationships","identifiers":["doc:\/\/org.cocoapods.EaseCallUIKit\/objc(cs)UIView"]},{"type":"conformsTo","kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)NSCoding","doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)NSObject","doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)CALayerDelegate","doc:\/\/org.cocoapods.EaseCallUIKit\/s7CVarArgP","doc:\/\/org.cocoapods.EaseCallUIKit\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.EaseCallUIKit\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.EaseCallUIKit\/SQ","doc:\/\/org.cocoapods.EaseCallUIKit\/SH","doc:\/\/org.cocoapods.EaseCallUIKit\/s8SendableP","doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)UIAccessibilityIdentification","doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)UIAppearance","doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)UIAppearanceContainer","doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)UICoordinateSpace","doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)UIDynamicItem","doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)UIFocusEnvironment","doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)UIFocusItem","doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)UIFocusItemContainer","doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)UILargeContentViewerItem","doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)UIPopoverPresentationControllerSourceItem","doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)UIResponderStandardEditActions","doc:\/\/org.cocoapods.EaseCallUIKit\/5UIKit23UITraitChangeObservableP","doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)UITraitEnvironment","doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)UIUserActivityRestoring"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/UserInfoView"},"topicSections":[{"anchor":"Instance-Properties","identifiers":["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/UserInfoView\/actualWidth","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/UserInfoView\/intrinsicContentSize"],"generated":true,"title":"Instance Properties"},{"identifiers":["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/UserInfoView\/configure(nickname:isAudioMuted:displayMode:)","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/UserInfoView\/enableDebugMode()","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/UserInfoView\/layoutSubviews()","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/UserInfoView\/setDisplayMode(_:animated:)"],"title":"Instance Methods","generated":true,"anchor":"Instance-Methods"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@"},{"kind":"attribute","preciseIdentifier":"s:ScM","text":"MainActor"},{"text":" ","kind":"text"},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"UserInfoView","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit"]]},"metadata":{"roleHeading":"Class","symbolKind":"class","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"UserInfoView"}],"title":"UserInfoView","modules":[{"name":"EaseCallUIKit"}],"role":"symbol","externalID":"c:@M@EaseCallUIKit@objc(cs)UserInfoView","navigatorTitle":[{"kind":"identifier","text":"UserInfoView"}]},"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","references":{"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/UserInfoView/setDisplayMode(_:animated:)":{"title":"setDisplayMode(_:animated:)","url":"\/documentation\/easecalluikit\/userinfoview\/setdisplaymode(_:animated:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setDisplayMode"},{"kind":"text","text":"("},{"text":"UserInfoDisplayMode","kind":"typeIdentifier","preciseIdentifier":"s:13EaseCallUIKit19UserInfoDisplayModeO"},{"kind":"text","text":", "},{"text":"animated","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"text":")","kind":"text"}],"abstract":[{"type":"text","text":"带动画的模式切换"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/UserInfoView\/setDisplayMode(_:animated:)"},"doc://org.cocoapods.EaseCallUIKit/objc(pl)UIResponderStandardEditActions":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)UIResponderStandardEditActions","title":"UIKit.UIResponderStandardEditActions"},"doc://org.cocoapods.EaseCallUIKit/SH":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/SH","title":"Swift.Hashable"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/UserInfoView/actualWidth":{"kind":"symbol","url":"\/documentation\/easecalluikit\/userinfoview\/actualwidth","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"actualWidth"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat"}],"title":"actualWidth","abstract":[{"type":"text","text":"获取当前视图的实际宽度"}],"type":"topic","role":"symbol","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/UserInfoView\/actualWidth"},"doc://org.cocoapods.EaseCallUIKit/objc(pl)UICoordinateSpace":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)UICoordinateSpace","title":"UIKit.UICoordinateSpace"},"doc://org.cocoapods.EaseCallUIKit/objc(pl)UIUserActivityRestoring":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)UIUserActivityRestoring","title":"UIKit.UIUserActivityRestoring"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/UserInfoView/enableDebugMode()":{"abstract":[{"type":"text","text":"添加边框以便调试"}],"title":"enableDebugMode()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"enableDebugMode"},{"kind":"text","text":"()"}],"url":"\/documentation\/easecalluikit\/userinfoview\/enabledebugmode()","kind":"symbol","type":"topic","role":"symbol","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/UserInfoView\/enableDebugMode()"},"doc://org.cocoapods.EaseCallUIKit/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://org.cocoapods.EaseCallUIKit/objc(pl)UIAccessibilityIdentification":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)UIAccessibilityIdentification","title":"UIKit.UIAccessibilityIdentification"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit":{"title":"EaseCallUIKit","type":"topic","url":"\/documentation\/easecalluikit","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit","abstract":[],"role":"collection","kind":"symbol"},"doc://org.cocoapods.EaseCallUIKit/objc(pl)NSCoding":{"title":"Foundation.NSCoding","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)NSCoding","type":"unresolvable"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/UserInfoView/intrinsicContentSize":{"role":"symbol","abstract":[],"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"intrinsicContentSize"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGSize","preciseIdentifier":"c:@S@CGSize"}],"type":"topic","navigatorTitle":[{"text":"intrinsicContentSize","kind":"identifier"}],"url":"\/documentation\/easecalluikit\/userinfoview\/intrinsiccontentsize","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/UserInfoView\/intrinsicContentSize","title":"intrinsicContentSize"},"doc://org.cocoapods.EaseCallUIKit/objc(pl)UIActivityItemsConfigurationProviding":{"title":"UIKit.UIActivityItemsConfigurationProviding","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)UIActivityItemsConfigurationProviding","type":"unresolvable"},"doc://org.cocoapods.EaseCallUIKit/s8SendableP":{"title":"Swift.Sendable","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/s8SendableP","type":"unresolvable"},"doc://org.cocoapods.EaseCallUIKit/objc(pl)UIPopoverPresentationControllerSourceItem":{"title":"UIKit.UIPopoverPresentationControllerSourceItem","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)UIPopoverPresentationControllerSourceItem","type":"unresolvable"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/UserInfoView":{"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"UserInfoView","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/UserInfoView","navigatorTitle":[{"kind":"identifier","text":"UserInfoView"}],"url":"\/documentation\/easecalluikit\/userinfoview","title":"UserInfoView","abstract":[],"role":"symbol"},"doc://org.cocoapods.EaseCallUIKit/objc(pl)UIFocusItemContainer":{"title":"UIKit.UIFocusItemContainer","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)UIFocusItemContainer","type":"unresolvable"},"doc://org.cocoapods.EaseCallUIKit/5UIKit23UITraitChangeObservableP":{"title":"UIKit.UITraitChangeObservable","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/5UIKit23UITraitChangeObservableP","type":"unresolvable"},"doc://org.cocoapods.EaseCallUIKit/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)NSObject","type":"unresolvable"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/UserInfoView/configure(nickname:isAudioMuted:displayMode:)":{"type":"topic","abstract":[{"type":"text","text":"配置视图的所有属性"}],"title":"configure(nickname:isAudioMuted:displayMode:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"configure","kind":"identifier"},{"text":"(","kind":"text"},{"text":"nickname","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"isAudioMuted"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"displayMode","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"UserInfoDisplayMode","preciseIdentifier":"s:13EaseCallUIKit19UserInfoDisplayModeO"},{"kind":"text","text":")"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/UserInfoView\/configure(nickname:isAudioMuted:displayMode:)","url":"\/documentation\/easecalluikit\/userinfoview\/configure(nickname:isaudiomuted:displaymode:)"},"doc://org.cocoapods.EaseCallUIKit/objc(pl)UIAppearance":{"title":"UIKit.UIAppearance","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)UIAppearance","type":"unresolvable"},"doc://org.cocoapods.EaseCallUIKit/objc(pl)UIAppearanceContainer":{"title":"UIKit.UIAppearanceContainer","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)UIAppearanceContainer","type":"unresolvable"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/UserInfoView/layoutSubviews()":{"abstract":[],"navigatorTitle":[{"kind":"identifier","text":"layoutSubviews"}],"title":"layoutSubviews()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"layoutSubviews","kind":"identifier"},{"text":"()","kind":"text"}],"url":"\/documentation\/easecalluikit\/userinfoview\/layoutsubviews()","kind":"symbol","type":"topic","role":"symbol","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/UserInfoView\/layoutSubviews()"},"doc://org.cocoapods.EaseCallUIKit/objc(pl)UIDynamicItem":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)UIDynamicItem","title":"UIKit.UIDynamicItem"},"doc://org.cocoapods.EaseCallUIKit/objc(pl)UITraitEnvironment":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)UITraitEnvironment","title":"UIKit.UITraitEnvironment"},"doc://org.cocoapods.EaseCallUIKit/objc(pl)UILargeContentViewerItem":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)UILargeContentViewerItem","title":"UIKit.UILargeContentViewerItem"},"doc://org.cocoapods.EaseCallUIKit/objc(cs)UIView":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/objc(cs)UIView","title":"UIView"},"doc://org.cocoapods.EaseCallUIKit/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://org.cocoapods.EaseCallUIKit/objc(pl)CALayerDelegate":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)CALayerDelegate","title":"QuartzCore.CALayerDelegate"},"doc://org.cocoapods.EaseCallUIKit/objc(pl)UIPasteConfigurationSupporting":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)UIPasteConfigurationSupporting","title":"UIKit.UIPasteConfigurationSupporting"},"doc://org.cocoapods.EaseCallUIKit/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/s7CVarArgP","title":"Swift.CVarArg"},"doc://org.cocoapods.EaseCallUIKit/SQ":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/SQ","title":"Swift.Equatable"},"doc://org.cocoapods.EaseCallUIKit/objc(pl)UIFocusEnvironment":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)UIFocusEnvironment","title":"UIKit.UIFocusEnvironment"},"doc://org.cocoapods.EaseCallUIKit/objc(pl)UIFocusItem":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/objc(pl)UIFocusItem","title":"UIKit.UIFocusItem"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"value":"UserInfoView","op":"replace","path":"\/metadata\/title"},{"op":"replace","value":"class","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"UserInfoView","kind":"identifier"}],"op":"replace"},{"value":[{"kind":"identifier","text":"UserInfoView"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"path":"\/topicSections","value":[{"generated":true,"anchor":"Instance-Properties","title":"Instance Properties","identifiers":["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/UserInfoView\/intrinsicContentSize"]},{"title":"Instance Methods","generated":true,"identifiers":["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/UserInfoView\/layoutSubviews()"],"anchor":"Instance-Methods"}],"op":"replace"},{"op":"replace","path":"\/relationshipsSections","value":[{"kind":"relationships","identifiers":["doc:\/\/org.cocoapods.EaseCallUIKit\/objc(cs)UIView"],"title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"text":"UserInfoView","kind":"identifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIView","kind":"typeIdentifier","text":"UIView"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1UserInfoView~1intrinsicContentSize\/title","value":"intrinsicContentSize"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1UserInfoView~1intrinsicContentSize\/fragments","op":"replace","value":[{"kind":"identifier","text":"intrinsicContentSize"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1UserInfoView\/title","value":"UserInfoView"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1UserInfoView\/fragments","value":[{"text":"UserInfoView","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1UserInfoView\/navigatorTitle","value":[{"kind":"identifier","text":"UserInfoView"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1UserInfoView~1layoutSubviews()\/title","op":"replace","value":"layoutSubviews"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1UserInfoView~1layoutSubviews()\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"layoutSubviews"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}