{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallBusinessErrorCode"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"param","kind":"identifier"}],"platforms":["iOS"]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallBusinessErrorCode\/param"},"variants":[{"paths":["\/documentation\/easecalluikit\/callbusinesserrorcode\/param"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/easecalluikit\/callbusinesserrorcode\/param"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"externalID":"c:@M@EaseCallUIKit@E@CallBusinessErrorCode@CallBusinessErrorCodeParam","navigatorTitle":[{"text":"CallBusinessErrorCodeParam","kind":"identifier"}],"title":"CallBusinessErrorCode.param","symbolKind":"case","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"param","kind":"identifier"}],"roleHeading":"Case","modules":[{"name":"EaseCallUIKit"}],"role":"symbol"},"references":{"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallBusinessErrorCode/param":{"type":"topic","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallBusinessErrorCode\/param","role":"symbol","url":"\/documentation\/easecalluikit\/callbusinesserrorcode\/param","navigatorTitle":[{"text":"CallBusinessErrorCodeParam","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"param"}],"title":"CallBusinessErrorCode.param"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit":{"title":"EaseCallUIKit","type":"topic","url":"\/documentation\/easecalluikit","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit","abstract":[],"role":"collection","kind":"symbol"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallBusinessErrorCode":{"abstract":[],"type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"CallBusinessErrorCode","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallBusinessErrorCode","role":"symbol","title":"CallBusinessErrorCode","navigatorTitle":[{"text":"CallBusinessErrorCode","kind":"identifier"}],"url":"\/documentation\/easecalluikit\/callbusinesserrorcode"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"CallBusinessErrorCodeParam"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"CallBusinessErrorCodeParam"}]},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"CallBusinessErrorCodeParam","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallBusinessErrorCode~1param\/title","op":"replace","value":"CallBusinessErrorCodeParam"},{"value":[{"kind":"identifier","text":"CallBusinessErrorCodeParam"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallBusinessErrorCode~1param\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallBusinessErrorCode\/title","value":"CallBusinessErrorCode"},{"value":[{"text":"CallBusinessErrorCode","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallBusinessErrorCode\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallBusinessErrorCode\/navigatorTitle","value":[{"kind":"identifier","text":"CallBusinessErrorCode"}]}]}]}