{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallBusinessErrorCode"]]},"metadata":{"externalID":"c:@M@EaseCallUIKit@E@CallBusinessErrorCode@CallBusinessErrorCodeState","navigatorTitle":[{"text":"CallBusinessErrorCodeState","kind":"identifier"}],"title":"CallBusinessErrorCode.state","symbolKind":"case","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"state","kind":"identifier"}],"roleHeading":"Case","modules":[{"name":"EaseCallUIKit"}],"role":"symbol"},"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallBusinessErrorCode\/state"},"sections":[],"variants":[{"paths":["\/documentation\/easecalluikit\/callbusinesserrorcode\/state"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/easecalluikit\/callbusinesserrorcode\/state"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"state"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"references":{"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallBusinessErrorCode":{"abstract":[],"type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"CallBusinessErrorCode","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallBusinessErrorCode","role":"symbol","title":"CallBusinessErrorCode","navigatorTitle":[{"text":"CallBusinessErrorCode","kind":"identifier"}],"url":"\/documentation\/easecalluikit\/callbusinesserrorcode"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallBusinessErrorCode/state":{"type":"topic","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallBusinessErrorCode\/state","role":"symbol","url":"\/documentation\/easecalluikit\/callbusinesserrorcode\/state","navigatorTitle":[{"text":"CallBusinessErrorCodeState","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"state","kind":"identifier"}],"title":"CallBusinessErrorCode.state"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit":{"title":"EaseCallUIKit","type":"topic","url":"\/documentation\/easecalluikit","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit","abstract":[],"role":"collection","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"CallBusinessErrorCodeState"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"value":[{"text":"CallBusinessErrorCodeState","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"declarations":[{"tokens":[{"text":"CallBusinessErrorCodeState","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallBusinessErrorCode\/title","value":"CallBusinessErrorCode"},{"value":[{"text":"CallBusinessErrorCode","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallBusinessErrorCode\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallBusinessErrorCode\/navigatorTitle","value":[{"text":"CallBusinessErrorCode","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallBusinessErrorCode~1state\/title","value":"CallBusinessErrorCodeState"},{"op":"replace","value":[{"text":"CallBusinessErrorCodeState","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallBusinessErrorCode~1state\/fragments"}]}]}