{"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@"},{"preciseIdentifier":"s:ScM","text":"MainActor","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"dragDirection"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@EaseCallUIKit@E@DragDirection","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/DragDirection","text":"DragDirection","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"metadata":{"modules":[{"name":"EaseCallUIKit"}],"title":"dragDirection","role":"symbol","roleHeading":"Instance Property","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"dragDirection","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DragDirection","preciseIdentifier":"c:@M@EaseCallUIKit@E@DragDirection"}],"externalID":"s:13EaseCallUIKit13DragFloatViewC13dragDirectionAA0dH0Ovp","symbolKind":"property"},"abstract":[{"type":"text","text":"拖曳的方向，默认为 .any，任意方向"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/DragFloatView"]]},"kind":"symbol","identifier":{"url":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/DragFloatView\/dragDirection","interfaceLanguage":"swift"},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easecalluikit\/dragfloatview\/dragdirection"]}],"references":{"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/DragFloatView":{"kind":"symbol","title":"DragFloatView","navigatorTitle":[{"text":"DragFloatView","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DragFloatView"}],"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/DragFloatView","abstract":[],"type":"topic","role":"symbol","url":"\/documentation\/easecalluikit\/dragfloatview"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/DragFloatView/dragDirection":{"kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"dragDirection","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@EaseCallUIKit@E@DragDirection","text":"DragDirection","kind":"typeIdentifier"}],"type":"topic","url":"\/documentation\/easecalluikit\/dragfloatview\/dragdirection","role":"symbol","abstract":[{"text":"拖曳的方向，默认为 .any，任意方向","type":"text"}],"title":"dragDirection","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/DragFloatView\/dragDirection"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/DragDirection":{"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/DragDirection","abstract":[],"url":"\/documentation\/easecalluikit\/dragdirection","kind":"symbol","role":"symbol","type":"topic","title":"DragDirection","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"DragDirection"}],"navigatorTitle":[{"text":"DragDirection","kind":"identifier"}]},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit":{"title":"EaseCallUIKit","type":"topic","url":"\/documentation\/easecalluikit","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit","abstract":[],"role":"collection","kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1DragFloatView\/title","op":"replace","value":"DragFloatView"},{"value":[{"kind":"identifier","text":"DragFloatView"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1DragFloatView\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1DragFloatView\/navigatorTitle","value":[{"kind":"identifier","text":"DragFloatView"}]},{"value":"DragDirection","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1DragDirection\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1DragDirection\/fragments","op":"replace","value":[{"text":"DragDirection","kind":"identifier"}]},{"value":[{"text":"DragDirection","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1DragDirection\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}