{"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easecalluikit\/dragfloatview\/duringdragblock"]}],"kind":"symbol","abstract":[{"type":"text","text":"拖动中的回调"}],"metadata":{"externalID":"s:13EaseCallUIKit13DragFloatViewC06duringD5BlockyACcSgvp","modules":[{"name":"EaseCallUIKit"}],"title":"duringDragBlock","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"duringDragBlock"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","text":"DragFloatView","preciseIdentifier":"c:@M@EaseCallUIKit@objc(cs)DragFloatView"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"text":")?","kind":"text"}],"roleHeading":"Instance Property","symbolKind":"property"},"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/DragFloatView\/duringDragBlock"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@"},{"preciseIdentifier":"s:ScM","text":"MainActor","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"duringDragBlock"},{"kind":"text","text":": (("},{"preciseIdentifier":"c:@M@EaseCallUIKit@objc(cs)DragFloatView","text":"DragFloatView","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/DragFloatView"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":")?","kind":"text"}]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/DragFloatView"]]},"references":{"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/DragFloatView/duringDragBlock":{"abstract":[{"text":"拖动中的回调","type":"text"}],"type":"topic","kind":"symbol","title":"duringDragBlock","url":"\/documentation\/easecalluikit\/dragfloatview\/duringdragblock","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/DragFloatView\/duringDragBlock","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"duringDragBlock","kind":"identifier"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","text":"DragFloatView","preciseIdentifier":"c:@M@EaseCallUIKit@objc(cs)DragFloatView"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?"}]},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit":{"title":"EaseCallUIKit","type":"topic","url":"\/documentation\/easecalluikit","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit","abstract":[],"role":"collection","kind":"symbol"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/DragFloatView":{"kind":"symbol","title":"DragFloatView","navigatorTitle":[{"text":"DragFloatView","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DragFloatView"}],"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/DragFloatView","abstract":[],"type":"topic","role":"symbol","url":"\/documentation\/easecalluikit\/dragfloatview"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1DragFloatView\/title","op":"replace","value":"DragFloatView"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1DragFloatView\/fragments","value":[{"text":"DragFloatView","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1DragFloatView\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"DragFloatView"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}