{"variants":[{"paths":["\/documentation\/easecalluikit\/dragfloatview\/enddragblock"],"traits":[{"interfaceLanguage":"swift"}]}],"abstract":[{"text":"结束拖动的回调","type":"text"}],"identifier":{"url":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/DragFloatView\/endDragBlock","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@","kind":"attribute"},{"preciseIdentifier":"s:ScM","kind":"attribute","text":"MainActor"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"endDragBlock","kind":"identifier"},{"text":": ((","kind":"text"},{"kind":"typeIdentifier","text":"DragFloatView","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/DragFloatView","preciseIdentifier":"c:@M@EaseCallUIKit@objc(cs)DragFloatView"},{"kind":"text","text":") -> "},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?"}]}],"kind":"declarations"}],"kind":"symbol","sections":[],"schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"externalID":"s:13EaseCallUIKit13DragFloatViewC03endD5BlockyACcSgvp","symbolKind":"property","role":"symbol","roleHeading":"Instance Property","modules":[{"name":"EaseCallUIKit"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"endDragBlock"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","text":"DragFloatView","preciseIdentifier":"c:@M@EaseCallUIKit@objc(cs)DragFloatView"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?"}],"title":"endDragBlock"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/DragFloatView"]]},"references":{"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/DragFloatView":{"kind":"symbol","title":"DragFloatView","navigatorTitle":[{"text":"DragFloatView","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DragFloatView"}],"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/DragFloatView","abstract":[],"type":"topic","role":"symbol","url":"\/documentation\/easecalluikit\/dragfloatview"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/DragFloatView/endDragBlock":{"role":"symbol","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/DragFloatView\/endDragBlock","url":"\/documentation\/easecalluikit\/dragfloatview\/enddragblock","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"endDragBlock","kind":"identifier"},{"text":": ((","kind":"text"},{"preciseIdentifier":"c:@M@EaseCallUIKit@objc(cs)DragFloatView","kind":"typeIdentifier","text":"DragFloatView"},{"kind":"text","text":") -> "},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?"}],"abstract":[{"text":"结束拖动的回调","type":"text"}],"kind":"symbol","title":"endDragBlock","type":"topic"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit":{"title":"EaseCallUIKit","type":"topic","url":"\/documentation\/easecalluikit","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit","abstract":[],"role":"collection","kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1DragFloatView\/title","value":"DragFloatView","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1DragFloatView\/fragments","value":[{"kind":"identifier","text":"DragFloatView"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1DragFloatView\/navigatorTitle","value":[{"kind":"identifier","text":"DragFloatView"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}