{"variants":[{"paths":["\/documentation\/easecalluikit\/dragfloatview\/freerect"],"traits":[{"interfaceLanguage":"swift"}]}],"abstract":[{"text":"活动范围，默认为父视图的 frame 范围内","type":"text"},{"text":" ","type":"text"},{"text":"如果设置了，则会在给定的范围内活动","type":"text"},{"type":"text","text":" "},{"text":"如果没设置，则会在父视图范围内活动","type":"text"},{"text":" ","type":"text"},{"text":"注意：设置的 frame 不要大于父视图范围","type":"text"},{"type":"text","text":" "},{"text":"注意：设置的 frame 为 .zero 表示活动的范围为默认的父视图 frame，如果想要不能活动，请设置 dragEnable 为 false","type":"text"}],"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/DragFloatView\/freeRect"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/DragFloatView"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@"},{"kind":"attribute","preciseIdentifier":"s:ScM","text":"MainActor"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"freeRect"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@S@CGRect","kind":"typeIdentifier","text":"CGRect"},{"kind":"text","text":" { "},{"text":"get","kind":"keyword"},{"kind":"text","text":" "},{"text":"set","kind":"keyword"},{"kind":"text","text":" }"}]}],"kind":"declarations"}],"metadata":{"roleHeading":"Instance Property","externalID":"s:13EaseCallUIKit13DragFloatViewC8freeRectSo6CGRectVvp","symbolKind":"property","modules":[{"name":"EaseCallUIKit"}],"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"freeRect","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect","text":"CGRect"}],"title":"freeRect"},"sections":[],"references":{"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/DragFloatView/freeRect":{"kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"freeRect","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@S@CGRect","text":"CGRect","kind":"typeIdentifier"}],"type":"topic","url":"\/documentation\/easecalluikit\/dragfloatview\/freerect","role":"symbol","abstract":[{"text":"活动范围，默认为父视图的 frame 范围内","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"如果设置了，则会在给定的范围内活动"},{"type":"text","text":" "},{"type":"text","text":"如果没设置，则会在父视图范围内活动"},{"type":"text","text":" "},{"type":"text","text":"注意：设置的 frame 不要大于父视图范围"},{"type":"text","text":" "},{"text":"注意：设置的 frame 为 .zero 表示活动的范围为默认的父视图 frame，如果想要不能活动，请设置 dragEnable 为 false","type":"text"}],"title":"freeRect","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/DragFloatView\/freeRect"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit":{"title":"EaseCallUIKit","type":"topic","url":"\/documentation\/easecalluikit","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit","abstract":[],"role":"collection","kind":"symbol"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/DragFloatView":{"kind":"symbol","title":"DragFloatView","navigatorTitle":[{"text":"DragFloatView","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DragFloatView"}],"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/DragFloatView","abstract":[],"type":"topic","role":"symbol","url":"\/documentation\/easecalluikit\/dragfloatview"}},"variantOverrides":[{"patch":[{"value":"DragFloatView","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1DragFloatView\/title"},{"op":"replace","value":[{"text":"DragFloatView","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1DragFloatView\/fragments"},{"value":[{"text":"DragFloatView","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1DragFloatView\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}