{"topicSections":[{"generated":true,"identifiers":["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/DragFloatView\/gestureRecognizerShouldBegin(_:)"],"title":"Instance Methods","anchor":"Instance-Methods"}],"kind":"article","hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/DragFloatView"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easecalluikit\/dragfloatview\/uigesturerecognizerdelegate-implementations"]},{"paths":["\/documentation\/easecalluikit\/dragfloatview\/uigesturerecognizerdelegate-implementations"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/DragFloatView\/UIGestureRecognizerDelegate-Implementations"},"metadata":{"title":"UIGestureRecognizerDelegate Implementations","role":"collectionGroup","roleHeading":"API Collection","modules":[{"name":"EaseCallUIKit"}]},"references":{"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit":{"title":"EaseCallUIKit","type":"topic","url":"\/documentation\/easecalluikit","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit","abstract":[],"role":"collection","kind":"symbol"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/DragFloatView/gestureRecognizerShouldBegin(_:)":{"abstract":[],"navigatorTitle":[{"text":"gestureRecognizerShouldBegin:","kind":"identifier"}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/DragFloatView\/gestureRecognizerShouldBegin(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"gestureRecognizerShouldBegin"},{"text":"(","kind":"text"},{"text":"UIGestureRecognizer","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIGestureRecognizer"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"url":"\/documentation\/easecalluikit\/dragfloatview\/gesturerecognizershouldbegin(_:)","title":"gestureRecognizerShouldBegin(_:)","type":"topic"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/DragFloatView":{"kind":"symbol","title":"DragFloatView","navigatorTitle":[{"text":"DragFloatView","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DragFloatView"}],"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/DragFloatView","abstract":[],"type":"topic","role":"symbol","url":"\/documentation\/easecalluikit\/dragfloatview"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":[{"title":"Instance Methods","generated":true,"identifiers":["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/DragFloatView\/gestureRecognizerShouldBegin(_:)"],"anchor":"Instance-Methods"}],"op":"replace","path":"\/topicSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":"gestureRecognizerShouldBegin:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1DragFloatView~1gestureRecognizerShouldBegin(_:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"gestureRecognizerShouldBegin:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1DragFloatView~1gestureRecognizerShouldBegin(_:)\/fragments"},{"value":"DragFloatView","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1DragFloatView\/title"},{"value":[{"kind":"identifier","text":"DragFloatView"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1DragFloatView\/fragments"},{"value":[{"kind":"identifier","text":"DragFloatView"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1DragFloatView\/navigatorTitle","op":"replace"}]}]}