{"metadata":{"extendedModule":"EaseCallUIKit","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"addListener","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"keyword","text":"any"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:@M@EaseCallUIKit@objc(pl)CallServiceListener","kind":"typeIdentifier","text":"CallServiceListener"},{"kind":"text","text":")"}],"symbolKind":"method","role":"symbol","roleHeading":"Instance Method","title":"addListener(_:)","externalID":"c:@CM@EaseCallUIKit@objc(cs)CallKitManager(im)addListener:","modules":[{"name":"EaseCallUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"addListener:"}]},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"addListener"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"listener"},{"text":": ","kind":"text"},{"text":"any","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallServiceListener","text":"CallServiceListener","preciseIdentifier":"c:@M@EaseCallUIKit@objc(pl)CallServiceListener"},{"kind":"text","text":")"}],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"name":"listener","content":[{"type":"paragraph","inlineContent":[{"text":"An object conforming to the ","type":"text"},{"type":"reference","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallServiceListener","isActive":true},{"type":"text","text":" protocol that will receive call events."}]}]}]}],"abstract":[{"type":"text","text":"Adds a listener to receive call-related events."}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager\/CallMessageService-Implementations"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager\/addListener(_:)"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easecalluikit\/callkitmanager\/addlistener(_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easecalluikit\/callkitmanager\/addlistener(_:)"]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallKitManager":{"role":"symbol","title":"CallKitManager","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CallKitManager"}],"abstract":[],"type":"topic","kind":"symbol","url":"\/documentation\/easecalluikit\/callkitmanager","navigatorTitle":[{"text":"CallKitManager","kind":"identifier"}]},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallServiceListener":{"abstract":[],"kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"CallServiceListener"}],"url":"\/documentation\/easecalluikit\/callservicelistener","title":"CallServiceListener","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CallServiceListener"}],"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallServiceListener","role":"symbol"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit":{"title":"EaseCallUIKit","type":"topic","url":"\/documentation\/easecalluikit","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit","abstract":[],"role":"collection","kind":"symbol"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallKitManager/addListener(_:)":{"navigatorTitle":[{"text":"addListener:","kind":"identifier"}],"title":"addListener(_:)","abstract":[{"type":"text","text":"Adds a listener to receive call-related events."}],"type":"topic","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager\/addListener(_:)","url":"\/documentation\/easecalluikit\/callkitmanager\/addlistener(_:)","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"addListener","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"keyword","text":"any"},{"kind":"text","text":" "},{"text":"CallServiceListener","kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseCallUIKit@objc(pl)CallServiceListener"},{"kind":"text","text":")"}]},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallKitManager/CallMessageService-Implementations":{"url":"\/documentation\/easecalluikit\/callkitmanager\/callmessageservice-implementations","kind":"article","abstract":[],"title":"CallMessageService Implementations","role":"collectionGroup","type":"topic","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager\/CallMessageService-Implementations"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"addListener:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"addListener:","kind":"identifier"}],"op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"text":") ","kind":"text"},{"text":"addListener:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"id<CallServiceListener>","kind":"typeIdentifier","preciseIdentifier":"c:Qo@M@EaseCallUIKit@objc(pl)CallServiceListener"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"listener"},{"text":";","kind":"text"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallKitManager\/title","value":"CallKitManager","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallKitManager\/fragments","op":"replace","value":[{"text":"CallKitManager","kind":"identifier"}]},{"op":"replace","value":[{"kind":"identifier","text":"CallKitManager"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallKitManager\/navigatorTitle"},{"value":"CallServiceListener","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallServiceListener\/title","op":"replace"},{"value":[{"text":"CallServiceListener","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallServiceListener\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"CallServiceListener"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallServiceListener\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallKitManager~1addListener(_:)\/title","value":"addListener:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallKitManager~1addListener(_:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"addListener:","kind":"identifier"}]}]}]}