{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager"]]},"topicSections":[{"identifiers":["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager\/rtcEngine(_:didAudioMuted:byUid:)","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager\/rtcEngine(_:didAudioRouteChanged:)","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager\/rtcEngine(_:didJoinChannel:withUid:elapsed:)","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager\/rtcEngine(_:didJoinedOfUid:elapsed:)","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager\/rtcEngine(_:didOccurError:)","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager\/rtcEngine(_:didOfflineOfUid:reason:)","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager\/rtcEngine(_:networkQuality:txQuality:rxQuality:)","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager\/rtcEngine(_:remoteVideoStateChangedOfUid:state:reason:elapsed:)","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager\/rtcEngine(_:reportAudioVolumeIndicationOfSpeakers:totalVolume:)","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager\/rtcEngine(_:tokenPrivilegeWillExpire:)","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager\/rtcEngineRequestToken(_:)"],"anchor":"Instance-Methods","title":"Instance Methods","generated":true}],"variants":[{"paths":["\/documentation\/easecalluikit\/callkitmanager\/agorartcenginedelegate-implementations"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/easecalluikit\/callkitmanager\/agorartcenginedelegate-implementations"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"kind":"article","metadata":{"title":"AgoraRtcEngineDelegate Implementations","role":"collectionGroup","modules":[{"name":"EaseCallUIKit"}],"roleHeading":"API Collection"},"identifier":{"url":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager\/AgoraRtcEngineDelegate-Implementations","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallKitManager/rtcEngine(_:remoteVideoStateChangedOfUid:state:reason:elapsed:)":{"url":"\/documentation\/easecalluikit\/callkitmanager\/rtcengine(_:remotevideostatechangedofuid:state:reason:elapsed:)","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"rtcEngine"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)AgoraRtcEngineKit","kind":"typeIdentifier","text":"AgoraRtcEngineKit"},{"text":", ","kind":"text"},{"text":"remoteVideoStateChangedOfUid","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Su","text":"UInt","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"state","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@E@AgoraVideoRemoteState","text":"AgoraVideoRemoteState","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"reason","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"AgoraVideoRemoteReason","kind":"typeIdentifier","preciseIdentifier":"c:@E@AgoraVideoRemoteReason"},{"kind":"text","text":", "},{"kind":"externalParam","text":"elapsed"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"kind":"text","text":")"}],"abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager\/rtcEngine(_:remoteVideoStateChangedOfUid:state:reason:elapsed:)","role":"symbol","title":"rtcEngine(_:remoteVideoStateChangedOfUid:state:reason:elapsed:)","navigatorTitle":[{"text":"rtcEngine:remoteVideoStateChangedOfUid:state:reason:elapsed:","kind":"identifier"}]},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallKitManager/rtcEngine(_:didAudioMuted:byUid:)":{"type":"topic","url":"\/documentation\/easecalluikit\/callkitmanager\/rtcengine(_:didaudiomuted:byuid:)","kind":"symbol","title":"rtcEngine(_:didAudioMuted:byUid:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"rtcEngine","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AgoraRtcEngineKit","text":"AgoraRtcEngineKit"},{"kind":"text","text":", "},{"text":"didAudioMuted","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"byUid","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UInt","kind":"typeIdentifier","preciseIdentifier":"s:Su"},{"kind":"text","text":")"}],"abstract":[],"role":"symbol","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager\/rtcEngine(_:didAudioMuted:byUid:)","navigatorTitle":[{"text":"rtcEngine:didAudioMuted:byUid:","kind":"identifier"}]},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallKitManager/rtcEngine(_:tokenPrivilegeWillExpire:)":{"url":"\/documentation\/easecalluikit\/callkitmanager\/rtcengine(_:tokenprivilegewillexpire:)","role":"symbol","title":"rtcEngine(_:tokenPrivilegeWillExpire:)","navigatorTitle":[{"kind":"identifier","text":"rtcEngine:tokenPrivilegeWillExpire:"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager\/rtcEngine(_:tokenPrivilegeWillExpire:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"rtcEngine","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)AgoraRtcEngineKit","text":"AgoraRtcEngineKit","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"tokenPrivilegeWillExpire","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[]},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallKitManager/rtcEngine(_:didJoinChannel:withUid:elapsed:)":{"url":"\/documentation\/easecalluikit\/callkitmanager\/rtcengine(_:didjoinchannel:withuid:elapsed:)","role":"symbol","title":"rtcEngine(_:didJoinChannel:withUid:elapsed:)","navigatorTitle":[{"kind":"identifier","text":"rtcEngine:didJoinChannel:withUid:elapsed:"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager\/rtcEngine(_:didJoinChannel:withUid:elapsed:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"rtcEngine","kind":"identifier"},{"text":"(","kind":"text"},{"text":"AgoraRtcEngineKit","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AgoraRtcEngineKit"},{"text":", ","kind":"text"},{"text":"didJoinChannel","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"withUid"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Su","text":"UInt","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"elapsed","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":")","kind":"text"}],"abstract":[]},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallKitManager/rtcEngine(_:didOccurError:)":{"url":"\/documentation\/easecalluikit\/callkitmanager\/rtcengine(_:didoccurerror:)","role":"symbol","title":"rtcEngine(_:didOccurError:)","navigatorTitle":[{"text":"rtcEngine:didOccurError:","kind":"identifier"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager\/rtcEngine(_:didOccurError:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"rtcEngine"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)AgoraRtcEngineKit","kind":"typeIdentifier","text":"AgoraRtcEngineKit"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"didOccurError"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@E@AgoraErrorCode","text":"AgoraErrorCode","kind":"typeIdentifier"},{"kind":"text","text":")"}],"abstract":[]},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallKitManager/rtcEngine(_:didJoinedOfUid:elapsed:)":{"url":"\/documentation\/easecalluikit\/callkitmanager\/rtcengine(_:didjoinedofuid:elapsed:)","role":"symbol","title":"rtcEngine(_:didJoinedOfUid:elapsed:)","navigatorTitle":[{"text":"rtcEngine:didJoinedOfUid:elapsed:","kind":"identifier"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager\/rtcEngine(_:didJoinedOfUid:elapsed:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"rtcEngine"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)AgoraRtcEngineKit","text":"AgoraRtcEngineKit","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"didJoinedOfUid","kind":"externalParam"},{"kind":"text","text":": "},{"text":"UInt","kind":"typeIdentifier","preciseIdentifier":"s:Su"},{"text":", ","kind":"text"},{"text":"elapsed","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":")","kind":"text"}],"abstract":[]},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallKitManager/rtcEngineRequestToken(_:)":{"url":"\/documentation\/easecalluikit\/callkitmanager\/rtcenginerequesttoken(_:)","role":"symbol","title":"rtcEngineRequestToken(_:)","navigatorTitle":[{"kind":"identifier","text":"rtcEngineRequestToken:"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager\/rtcEngineRequestToken(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"rtcEngineRequestToken","kind":"identifier"},{"text":"(","kind":"text"},{"text":"AgoraRtcEngineKit","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AgoraRtcEngineKit"},{"text":")","kind":"text"}],"abstract":[]},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallKitManager/rtcEngine(_:networkQuality:txQuality:rxQuality:)":{"url":"\/documentation\/easecalluikit\/callkitmanager\/rtcengine(_:networkquality:txquality:rxquality:)","role":"symbol","title":"rtcEngine(_:networkQuality:txQuality:rxQuality:)","navigatorTitle":[{"kind":"identifier","text":"rtcEngine:networkQuality:txQuality:rxQuality:"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager\/rtcEngine(_:networkQuality:txQuality:rxQuality:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"rtcEngine","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)AgoraRtcEngineKit","text":"AgoraRtcEngineKit","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"networkQuality"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Su","kind":"typeIdentifier","text":"UInt"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"txQuality"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@E@AgoraNetworkQuality","text":"AgoraNetworkQuality","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"rxQuality","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"AgoraNetworkQuality","kind":"typeIdentifier","preciseIdentifier":"c:@E@AgoraNetworkQuality"},{"kind":"text","text":")"}],"abstract":[]},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallKitManager":{"role":"symbol","title":"CallKitManager","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CallKitManager"}],"abstract":[],"type":"topic","kind":"symbol","url":"\/documentation\/easecalluikit\/callkitmanager","navigatorTitle":[{"text":"CallKitManager","kind":"identifier"}]},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallKitManager/rtcEngine(_:didAudioRouteChanged:)":{"title":"rtcEngine(_:didAudioRouteChanged:)","type":"topic","abstract":[],"kind":"symbol","role":"symbol","url":"\/documentation\/easecalluikit\/callkitmanager\/rtcengine(_:didaudioroutechanged:)","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager\/rtcEngine(_:didAudioRouteChanged:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"rtcEngine"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AgoraRtcEngineKit","text":"AgoraRtcEngineKit"},{"kind":"text","text":", "},{"text":"didAudioRouteChanged","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"AgoraAudioOutputRouting","kind":"typeIdentifier","preciseIdentifier":"c:@E@AgoraAudioOutputRouting"},{"text":")","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"rtcEngine:didAudioRouteChanged:"}]},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallKitManager/rtcEngine(_:didOfflineOfUid:reason:)":{"url":"\/documentation\/easecalluikit\/callkitmanager\/rtcengine(_:didofflineofuid:reason:)","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"rtcEngine","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AgoraRtcEngineKit","text":"AgoraRtcEngineKit"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"didOfflineOfUid"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Su","text":"UInt","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"reason","kind":"externalParam"},{"kind":"text","text":": "},{"text":"AgoraUserOfflineReason","kind":"typeIdentifier","preciseIdentifier":"c:@E@AgoraUserOfflineReason"},{"text":")","kind":"text"}],"abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager\/rtcEngine(_:didOfflineOfUid:reason:)","role":"symbol","title":"rtcEngine(_:didOfflineOfUid:reason:)","navigatorTitle":[{"text":"rtcEngine:didOfflineOfUid:reason:","kind":"identifier"}]},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallKitManager/rtcEngine(_:reportAudioVolumeIndicationOfSpeakers:totalVolume:)":{"url":"\/documentation\/easecalluikit\/callkitmanager\/rtcengine(_:reportaudiovolumeindicationofspeakers:totalvolume:)","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"rtcEngine","kind":"identifier"},{"kind":"text","text":"("},{"text":"AgoraRtcEngineKit","preciseIdentifier":"c:objc(cs)AgoraRtcEngineKit","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"reportAudioVolumeIndicationOfSpeakers","kind":"externalParam"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AgoraRtcAudioVolumeInfo","text":"AgoraRtcAudioVolumeInfo"},{"text":"], ","kind":"text"},{"kind":"externalParam","text":"totalVolume"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":")","kind":"text"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager\/rtcEngine(_:reportAudioVolumeIndicationOfSpeakers:totalVolume:)","kind":"symbol","role":"symbol","title":"rtcEngine(_:reportAudioVolumeIndicationOfSpeakers:totalVolume:)","navigatorTitle":[{"kind":"identifier","text":"rtcEngine:reportAudioVolumeIndicationOfSpeakers:totalVolume:"}]},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit":{"title":"EaseCallUIKit","type":"topic","url":"\/documentation\/easecalluikit","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit","abstract":[],"role":"collection","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":[{"title":"Instance Methods","anchor":"Instance-Methods","generated":true,"identifiers":["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager\/rtcEngine(_:didAudioMuted:byUid:)","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager\/rtcEngine(_:didAudioRouteChanged:)","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager\/rtcEngine(_:didJoinChannel:withUid:elapsed:)","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager\/rtcEngine(_:didJoinedOfUid:elapsed:)","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager\/rtcEngine(_:didOccurError:)","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager\/rtcEngine(_:didOfflineOfUid:reason:)","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager\/rtcEngine(_:networkQuality:txQuality:rxQuality:)","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager\/rtcEngine(_:remoteVideoStateChangedOfUid:state:reason:elapsed:)","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager\/rtcEngine(_:reportAudioVolumeIndicationOfSpeakers:totalVolume:)","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager\/rtcEngine(_:tokenPrivilegeWillExpire:)","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager\/rtcEngineRequestToken(_:)"]}],"op":"replace","path":"\/topicSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallKitManager~1rtcEngine(_:remoteVideoStateChangedOfUid:state:reason:elapsed:)\/title","value":"rtcEngine:remoteVideoStateChangedOfUid:state:reason:elapsed:"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallKitManager~1rtcEngine(_:remoteVideoStateChangedOfUid:state:reason:elapsed:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"rtcEngine:remoteVideoStateChangedOfUid:state:reason:elapsed:"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallKitManager~1rtcEngine(_:didAudioMuted:byUid:)\/title","op":"replace","value":"rtcEngine:didAudioMuted:byUid:"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"rtcEngine:didAudioMuted:byUid:"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallKitManager~1rtcEngine(_:didAudioMuted:byUid:)\/fragments"},{"value":"rtcEngine:tokenPrivilegeWillExpire:","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallKitManager~1rtcEngine(_:tokenPrivilegeWillExpire:)\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"rtcEngine:tokenPrivilegeWillExpire:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallKitManager~1rtcEngine(_:tokenPrivilegeWillExpire:)\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallKitManager~1rtcEngine(_:didJoinChannel:withUid:elapsed:)\/title","value":"rtcEngine:didJoinChannel:withUid:elapsed:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallKitManager~1rtcEngine(_:didJoinChannel:withUid:elapsed:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"rtcEngine:didJoinChannel:withUid:elapsed:"}]},{"value":"rtcEngine:didOccurError:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallKitManager~1rtcEngine(_:didOccurError:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallKitManager~1rtcEngine(_:didOccurError:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"rtcEngine:didOccurError:","kind":"identifier"}]},{"value":"rtcEngine:didJoinedOfUid:elapsed:","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallKitManager~1rtcEngine(_:didJoinedOfUid:elapsed:)\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"rtcEngine:didJoinedOfUid:elapsed:"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallKitManager~1rtcEngine(_:didJoinedOfUid:elapsed:)\/fragments"},{"value":"rtcEngineRequestToken:","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallKitManager~1rtcEngineRequestToken(_:)\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallKitManager~1rtcEngineRequestToken(_:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"rtcEngineRequestToken:"}]},{"value":"rtcEngine:networkQuality:txQuality:rxQuality:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallKitManager~1rtcEngine(_:networkQuality:txQuality:rxQuality:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallKitManager~1rtcEngine(_:networkQuality:txQuality:rxQuality:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"rtcEngine:networkQuality:txQuality:rxQuality:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallKitManager\/title","value":"CallKitManager"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallKitManager\/fragments","op":"replace","value":[{"text":"CallKitManager","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"CallKitManager"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallKitManager\/navigatorTitle"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallKitManager~1rtcEngine(_:didAudioRouteChanged:)\/title","op":"replace","value":"rtcEngine:didAudioRouteChanged:"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"rtcEngine:didAudioRouteChanged:"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallKitManager~1rtcEngine(_:didAudioRouteChanged:)\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallKitManager~1rtcEngine(_:didOfflineOfUid:reason:)\/title","value":"rtcEngine:didOfflineOfUid:reason:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallKitManager~1rtcEngine(_:didOfflineOfUid:reason:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"rtcEngine:didOfflineOfUid:reason:"}]},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallKitManager~1rtcEngine(_:reportAudioVolumeIndicationOfSpeakers:totalVolume:)\/title","op":"replace","value":"rtcEngine:reportAudioVolumeIndicationOfSpeakers:totalVolume:"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallKitManager~1rtcEngine(_:reportAudioVolumeIndicationOfSpeakers:totalVolume:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"rtcEngine:reportAudioVolumeIndicationOfSpeakers:totalVolume:","kind":"identifier"}],"op":"replace"}]}]}