{"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager"]]},"abstract":[{"type":"text","text":"Confirm the answer to a call from the caller."}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager\/callerConfirmAnswer(callId:calleeId:calleeDeviceId:result:)"},"metadata":{"navigatorTitle":[{"kind":"identifier","text":"callerConfirmAnswerWithCallId:calleeId:calleeDeviceId:result:"}],"symbolKind":"method","roleHeading":"Instance Method","modules":[{"name":"EaseCallUIKit"}],"title":"callerConfirmAnswer(callId:calleeId:calleeDeviceId:result:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"callerConfirmAnswer"},{"text":"(","kind":"text"},{"text":"callId","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"calleeId","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"calleeDeviceId","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":", ","kind":"text"},{"text":"result","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"externalID":"c:@CM@EaseCallUIKit@objc(cs)CallKitManager(im)callerConfirmAnswerWithCallId:calleeId:calleeDeviceId:result:","extendedModule":"EaseCallUIKit"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easecalluikit\/callkitmanager\/callerconfirmanswer(callid:calleeid:calleedeviceid:result:)"]},{"paths":["\/documentation\/easecalluikit\/callkitmanager\/callerconfirmanswer(callid:calleeid:calleedeviceid:result:)"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"callerConfirmAnswer","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"callId"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"calleeId"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"calleeDeviceId","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"result","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":")","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},{"parameters":[{"content":[{"inlineContent":[{"text":"The unique identifier for the call.","type":"text"}],"type":"paragraph"}],"name":"callId"},{"name":"calleeId","content":[{"type":"paragraph","inlineContent":[{"text":"The ID of the callee.","type":"text"}]}]},{"name":"calleeDeviceId","content":[{"inlineContent":[{"text":"The device ID of the callee.","type":"text"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":"The result of the call, such as “accept”, “busy”, or “refuse”."}],"type":"paragraph"}],"name":"result"}],"kind":"parameters"}],"references":{"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit":{"title":"EaseCallUIKit","type":"topic","url":"\/documentation\/easecalluikit","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit","abstract":[],"role":"collection","kind":"symbol"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallKitManager":{"role":"symbol","title":"CallKitManager","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CallKitManager"}],"abstract":[],"type":"topic","kind":"symbol","url":"\/documentation\/easecalluikit\/callkitmanager","navigatorTitle":[{"text":"CallKitManager","kind":"identifier"}]},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallKitManager/callerConfirmAnswer(callId:calleeId:calleeDeviceId:result:)":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"callerConfirmAnswerWithCallId:calleeId:calleeDeviceId:result:"}],"kind":"symbol","type":"topic","title":"callerConfirmAnswer(callId:calleeId:calleeDeviceId:result:)","url":"\/documentation\/easecalluikit\/callkitmanager\/callerconfirmanswer(callid:calleeid:calleedeviceid:result:)","abstract":[{"text":"Confirm the answer to a call from the caller.","type":"text"}],"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager\/callerConfirmAnswer(callId:calleeId:calleeDeviceId:result:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"callerConfirmAnswer"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"callId"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"calleeId","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"calleeDeviceId"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"result"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"value":"callerConfirmAnswerWithCallId:calleeId:calleeDeviceId:result:","op":"replace","path":"\/metadata\/title"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"callerConfirmAnswerWithCallId:calleeId:calleeDeviceId:result:","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"callerConfirmAnswerWithCallId:","kind":"identifier"},{"kind":"text","text":"("},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"callId","kind":"internalParam"},{"kind":"text","text":" "},{"text":"calleeId:","kind":"identifier"},{"kind":"text","text":"("},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"calleeId"},{"text":" ","kind":"text"},{"kind":"identifier","text":"calleeDeviceId:"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"calleeDeviceId"},{"text":" ","kind":"text"},{"kind":"identifier","text":"result:"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"result"},{"text":";","kind":"text"}]}]},"op":"replace"},{"op":"replace","path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"The unique identifier for the call.","type":"text"}]}],"name":"callId"},{"name":"calleeId","content":[{"inlineContent":[{"type":"text","text":"The ID of the callee."}],"type":"paragraph"}]},{"name":"calleeDeviceId","content":[{"inlineContent":[{"text":"The device ID of the callee.","type":"text"}],"type":"paragraph"}]},{"name":"result","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The result of the call, such as “accept”, “busy”, or “refuse”."}]}]}]}},{"op":"replace","value":"CallKitManager","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallKitManager\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallKitManager\/fragments","op":"replace","value":[{"text":"CallKitManager","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallKitManager\/navigatorTitle","op":"replace","value":[{"text":"CallKitManager","kind":"identifier"}]},{"op":"replace","value":"callerConfirmAnswerWithCallId:calleeId:calleeDeviceId:result:","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallKitManager~1callerConfirmAnswer(callId:calleeId:calleeDeviceId:result:)\/title"},{"value":[{"kind":"text","text":"- "},{"text":"callerConfirmAnswerWithCallId:calleeId:calleeDeviceId:result:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallKitManager~1callerConfirmAnswer(callId:calleeId:calleeDeviceId:result:)\/fragments"}]}]}