{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager"]]},"identifier":{"url":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager\/calleeAnswerCaller(callId:callerId:callerDeviceId:)","interfaceLanguage":"swift"},"sections":[],"kind":"symbol","metadata":{"extendedModule":"EaseCallUIKit","externalID":"c:@CM@EaseCallUIKit@objc(cs)CallKitManager(im)calleeAnswerCallerWithCallId:callerId:callerDeviceId:","modules":[{"name":"EaseCallUIKit"}],"title":"calleeAnswerCaller(callId:callerId:callerDeviceId:)","navigatorTitle":[{"kind":"identifier","text":"calleeAnswerCallerWithCallId:callerId:callerDeviceId:"}],"roleHeading":"Instance Method","symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"calleeAnswerCaller","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"callId"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"callerId"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"callerDeviceId","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":")","kind":"text"}],"role":"symbol"},"abstract":[{"type":"text","text":"Caller answers the call from the callee."}],"variants":[{"paths":["\/documentation\/easecalluikit\/callkitmanager\/calleeanswercaller(callid:callerid:callerdeviceid:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/easecalluikit\/callkitmanager\/calleeanswercaller(callid:callerid:callerdeviceid:)"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"calleeAnswerCaller"},{"text":"(","kind":"text"},{"text":"callId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"callerId"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"callerDeviceId","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"languages":["swift"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The unique identifier for the call."}]}],"name":"callId"},{"name":"callerId","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The ID of the caller."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The device ID of the caller."}]}],"name":"callerDeviceId"}]}],"references":{"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit":{"title":"EaseCallUIKit","type":"topic","url":"\/documentation\/easecalluikit","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit","abstract":[],"role":"collection","kind":"symbol"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallKitManager/calleeAnswerCaller(callId:callerId:callerDeviceId:)":{"kind":"symbol","type":"topic","title":"calleeAnswerCaller(callId:callerId:callerDeviceId:)","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager\/calleeAnswerCaller(callId:callerId:callerDeviceId:)","navigatorTitle":[{"text":"calleeAnswerCallerWithCallId:callerId:callerDeviceId:","kind":"identifier"}],"abstract":[{"type":"text","text":"Caller answers the call from the callee."}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"calleeAnswerCaller","kind":"identifier"},{"kind":"text","text":"("},{"text":"callId","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"callerId","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"callerDeviceId"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":")","kind":"text"}],"url":"\/documentation\/easecalluikit\/callkitmanager\/calleeanswercaller(callid:callerid:callerdeviceid:)","role":"symbol"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallKitManager":{"role":"symbol","title":"CallKitManager","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CallKitManager"}],"abstract":[],"type":"topic","kind":"symbol","url":"\/documentation\/easecalluikit\/callkitmanager","navigatorTitle":[{"text":"CallKitManager","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"value":"calleeAnswerCallerWithCallId:callerId:callerDeviceId:","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"calleeAnswerCallerWithCallId:callerId:callerDeviceId:"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"identifier","text":"calleeAnswerCallerWithCallId:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"text":"callId","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"callerId:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"callerId"},{"text":" ","kind":"text"},{"kind":"identifier","text":"callerDeviceId:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"callerDeviceId"},{"kind":"text","text":";"}]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/primaryContentSections\/1","value":{"parameters":[{"name":"callId","content":[{"inlineContent":[{"type":"text","text":"The unique identifier for the call."}],"type":"paragraph"}]},{"name":"callerId","content":[{"inlineContent":[{"text":"The ID of the caller.","type":"text"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":"The device ID of the caller."}],"type":"paragraph"}],"name":"callerDeviceId"}],"kind":"parameters"}},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallKitManager~1calleeAnswerCaller(callId:callerId:callerDeviceId:)\/title","op":"replace","value":"calleeAnswerCallerWithCallId:callerId:callerDeviceId:"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"calleeAnswerCallerWithCallId:callerId:callerDeviceId:"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallKitManager~1calleeAnswerCaller(callId:callerId:callerDeviceId:)\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallKitManager\/title","op":"replace","value":"CallKitManager"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallKitManager\/fragments","value":[{"kind":"identifier","text":"CallKitManager"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallKitManager\/navigatorTitle","value":[{"kind":"identifier","text":"CallKitManager"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}