{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager"]]},"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"config"},{"text":": ","kind":"text"},{"text":"CallKitConfig","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitConfig","preciseIdentifier":"c:@M@EaseCallUIKit@objc(cs)CallKitConfig"},{"kind":"text","text":" { get }"}],"platforms":["iOS"],"languages":["swift"]}]}],"metadata":{"modules":[{"name":"EaseCallUIKit"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"config","kind":"identifier"},{"text":": ","kind":"text"},{"text":"CallKitConfig","preciseIdentifier":"c:@M@EaseCallUIKit@objc(cs)CallKitConfig","kind":"typeIdentifier"}],"externalID":"c:@M@EaseCallUIKit@objc(cs)CallKitManager(py)config","navigatorTitle":[{"kind":"identifier","text":"config"}],"roleHeading":"Instance Property","symbolKind":"property","title":"config","role":"symbol"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easecalluikit\/callkitmanager\/config"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easecalluikit\/callkitmanager\/config"]}],"identifier":{"url":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager\/config","interfaceLanguage":"swift"},"references":{"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallKitManager/config":{"abstract":[],"title":"config","role":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager\/config","url":"\/documentation\/easecalluikit\/callkitmanager\/config","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"config"},{"kind":"text","text":": "},{"text":"CallKitConfig","preciseIdentifier":"c:@M@EaseCallUIKit@objc(cs)CallKitConfig","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"config","kind":"identifier"}]},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit":{"title":"EaseCallUIKit","type":"topic","url":"\/documentation\/easecalluikit","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit","abstract":[],"role":"collection","kind":"symbol"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallKitConfig":{"abstract":[],"type":"topic","title":"CallKitConfig","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"CallKitConfig"}],"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitConfig","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"CallKitConfig","kind":"identifier"}],"url":"\/documentation\/easecalluikit\/callkitconfig"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallKitManager":{"role":"symbol","title":"CallKitManager","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CallKitManager"}],"abstract":[],"type":"topic","kind":"symbol","url":"\/documentation\/easecalluikit\/callkitmanager","navigatorTitle":[{"text":"CallKitManager","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"config"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"value":[{"kind":"identifier","text":"config"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"CallKitConfig","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitConfig","preciseIdentifier":"c:@M@EaseCallUIKit@objc(cs)CallKitConfig"},{"text":" * ","kind":"text"},{"text":"config","kind":"identifier"},{"kind":"text","text":";"}]}]}},{"op":"replace","value":"config","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallKitManager~1config\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallKitManager~1config\/fragments","value":[{"text":"config","kind":"identifier"}],"op":"replace"},{"value":"CallKitConfig","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallKitConfig\/title"},{"value":[{"text":"CallKitConfig","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallKitConfig\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallKitConfig\/navigatorTitle","value":[{"kind":"identifier","text":"CallKitConfig"}]},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallKitManager\/title","value":"CallKitManager","op":"replace"},{"value":[{"text":"CallKitManager","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallKitManager\/fragments"},{"value":[{"text":"CallKitManager","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallKitManager\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}