{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"confirmRing","kind":"identifier"},{"kind":"text","text":"("},{"text":"callId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"calleeId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"calleeDeviceId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"is_valid"},{"kind":"text","text":": "},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":")","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]},{"parameters":[{"name":"callId","content":[{"type":"paragraph","inlineContent":[{"text":"The unique identifier for the call.","type":"text"}]}]},{"name":"calleeId","content":[{"type":"paragraph","inlineContent":[{"text":"The ID of the callee.","type":"text"}]}]},{"content":[{"inlineContent":[{"text":"The device ID of the callee.","type":"text"}],"type":"paragraph"}],"name":"calleeDeviceId"},{"name":"is_valid","content":[{"type":"paragraph","inlineContent":[{"text":"A boolean indicating whether the ring is valid or not.","type":"text"}]}]}],"kind":"parameters"}],"metadata":{"navigatorTitle":[{"text":"confirmRingWithCallId:calleeId:calleeDeviceId:is_valid:","kind":"identifier"}],"externalID":"c:@CM@EaseCallUIKit@objc(cs)CallKitManager(im)confirmRingWithCallId:calleeId:calleeDeviceId:is_valid:","symbolKind":"method","role":"symbol","roleHeading":"Instance Method","modules":[{"name":"EaseCallUIKit"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"confirmRing","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"callId"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"calleeId","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"text":"calleeDeviceId","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"is_valid","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"title":"confirmRing(callId:calleeId:calleeDeviceId:is_valid:)","extendedModule":"EaseCallUIKit"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager"]]},"sections":[],"identifier":{"url":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager\/confirmRing(callId:calleeId:calleeDeviceId:is_valid:)","interfaceLanguage":"swift"},"kind":"symbol","abstract":[{"text":"Confirm the ring for a call from the caller.","type":"text"}],"variants":[{"paths":["\/documentation\/easecalluikit\/callkitmanager\/confirmring(callid:calleeid:calleedeviceid:is_valid:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easecalluikit\/callkitmanager\/confirmring(callid:calleeid:calleedeviceid:is_valid:)"]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallKitManager/confirmRing(callId:calleeId:calleeDeviceId:is_valid:)":{"role":"symbol","title":"confirmRing(callId:calleeId:calleeDeviceId:is_valid:)","abstract":[{"text":"Confirm the ring for a call from the caller.","type":"text"}],"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager\/confirmRing(callId:calleeId:calleeDeviceId:is_valid:)","type":"topic","url":"\/documentation\/easecalluikit\/callkitmanager\/confirmring(callid:calleeid:calleedeviceid:is_valid:)","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"confirmRing","kind":"identifier"},{"text":"(","kind":"text"},{"text":"callId","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"calleeId"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"calleeDeviceId","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":", ","kind":"text"},{"text":"is_valid","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"confirmRingWithCallId:calleeId:calleeDeviceId:is_valid:","kind":"identifier"}]},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallKitManager":{"role":"symbol","title":"CallKitManager","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CallKitManager"}],"abstract":[],"type":"topic","kind":"symbol","url":"\/documentation\/easecalluikit\/callkitmanager","navigatorTitle":[{"text":"CallKitManager","kind":"identifier"}]},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit":{"title":"EaseCallUIKit","type":"topic","url":"\/documentation\/easecalluikit","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit","abstract":[],"role":"collection","kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"value":"confirmRingWithCallId:calleeId:calleeDeviceId:is_valid:","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"confirmRingWithCallId:calleeId:calleeDeviceId:is_valid:"}]},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"text":"confirmRingWithCallId:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"callId","kind":"internalParam"},{"kind":"text","text":" "},{"text":"calleeId:","kind":"identifier"},{"kind":"text","text":"("},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"calleeId"},{"kind":"text","text":" "},{"kind":"identifier","text":"calleeDeviceId:"},{"text":"(","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"calleeDeviceId"},{"kind":"text","text":" "},{"text":"is_valid:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"is_valid"},{"text":";","kind":"text"}]}]}},{"value":{"parameters":[{"name":"callId","content":[{"type":"paragraph","inlineContent":[{"text":"The unique identifier for the call.","type":"text"}]}]},{"name":"calleeId","content":[{"inlineContent":[{"type":"text","text":"The ID of the callee."}],"type":"paragraph"}]},{"name":"calleeDeviceId","content":[{"inlineContent":[{"type":"text","text":"The device ID of the callee."}],"type":"paragraph"}]},{"name":"is_valid","content":[{"inlineContent":[{"type":"text","text":"A boolean indicating whether the ring is valid or not."}],"type":"paragraph"}]}],"kind":"parameters"},"path":"\/primaryContentSections\/1","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallKitManager~1confirmRing(callId:calleeId:calleeDeviceId:is_valid:)\/title","op":"replace","value":"confirmRingWithCallId:calleeId:calleeDeviceId:is_valid:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallKitManager~1confirmRing(callId:calleeId:calleeDeviceId:is_valid:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"confirmRingWithCallId:calleeId:calleeDeviceId:is_valid:"}]},{"value":"CallKitManager","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallKitManager\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallKitManager\/fragments","value":[{"kind":"identifier","text":"CallKitManager"}]},{"value":[{"text":"CallKitManager","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallKitManager\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}