{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"connectionStateDidChange","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"aConnectionState"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/ConnectionState","text":"ConnectionState","kind":"typeIdentifier","preciseIdentifier":"s:13EaseCallUIKit15ConnectionStatea"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"identifier":{"url":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager\/connectionStateDidChange(_:)","interfaceLanguage":"swift"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager\/EMClientDelegate-Implementations"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"abstract":[{"type":"text","text":"Inherited from "},{"code":"EMClientDelegate.connectionStateDidChange(_:)","type":"codeVoice"},{"text":".","type":"text"}],"metadata":{"symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"connectionStateDidChange:"}],"roleHeading":"Instance Method","modules":[{"name":"EaseCallUIKit"}],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"connectionStateDidChange","kind":"identifier"},{"text":"(","kind":"text"},{"text":"ConnectionState","kind":"typeIdentifier","preciseIdentifier":"s:13EaseCallUIKit15ConnectionStatea"},{"text":")","kind":"text"}],"externalID":"c:@CM@EaseCallUIKit@objc(cs)CallKitManager(im)connectionStateDidChange:","title":"connectionStateDidChange(_:)","extendedModule":"EaseCallUIKit"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easecalluikit\/callkitmanager\/connectionstatedidchange(_:)"]},{"paths":["\/documentation\/easecalluikit\/callkitmanager\/connectionstatedidchange(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/ConnectionState":{"title":"ConnectionState","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/ConnectionState","role":"symbol","type":"topic","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ConnectionState","kind":"identifier"}],"navigatorTitle":[{"text":"ConnectionState","kind":"identifier"}],"url":"\/documentation\/easecalluikit\/connectionstate","abstract":[],"kind":"symbol"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallKitManager/connectionStateDidChange(_:)":{"type":"topic","url":"\/documentation\/easecalluikit\/callkitmanager\/connectionstatedidchange(_:)","kind":"symbol","title":"connectionStateDidChange(_:)","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager\/connectionStateDidChange(_:)","abstract":[],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"connectionStateDidChange","kind":"identifier"},{"text":"(","kind":"text"},{"text":"ConnectionState","kind":"typeIdentifier","preciseIdentifier":"s:13EaseCallUIKit15ConnectionStatea"},{"text":")","kind":"text"}],"role":"symbol","navigatorTitle":[{"text":"connectionStateDidChange:","kind":"identifier"}]},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallKitManager":{"role":"symbol","title":"CallKitManager","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CallKitManager"}],"abstract":[],"type":"topic","kind":"symbol","url":"\/documentation\/easecalluikit\/callkitmanager","navigatorTitle":[{"text":"CallKitManager","kind":"identifier"}]},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallKitManager/EMClientDelegate-Implementations":{"role":"collectionGroup","title":"EMClientDelegate Implementations","url":"\/documentation\/easecalluikit\/callkitmanager\/emclientdelegate-implementations","kind":"article","abstract":[],"type":"topic","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager\/EMClientDelegate-Implementations"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit":{"title":"EaseCallUIKit","type":"topic","url":"\/documentation\/easecalluikit","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit","abstract":[],"role":"collection","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"connectionStateDidChange:"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"connectionStateDidChange:","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"text":") ","kind":"text"},{"text":"connectionStateDidChange:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@E@EMConnectionState","kind":"typeIdentifier","text":"EMConnectionState"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"aConnectionState"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallKitManager~1connectionStateDidChange(_:)\/title","value":"connectionStateDidChange:"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallKitManager~1connectionStateDidChange(_:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"connectionStateDidChange:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallKitManager\/title","value":"CallKitManager"},{"value":[{"text":"CallKitManager","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallKitManager\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"CallKitManager"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallKitManager\/navigatorTitle"}]}]}