{"metadata":{"role":"collectionGroup","modules":[{"name":"EaseCallUIKit"}],"title":"EMClientDelegate Implementations","roleHeading":"API Collection"},"schemaVersion":{"minor":3,"patch":0,"major":0},"topicSections":[{"anchor":"Instance-Methods","identifiers":["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager\/connectionStateDidChange(_:)","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager\/userAccountDidForced(toLogout:)","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager\/userAccountDidLoginFromOtherDevice(with:)","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager\/userAccountDidRemoveFromServer()","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager\/userDidForbidByServer()"],"generated":true,"title":"Instance Methods"}],"kind":"article","variants":[{"paths":["\/documentation\/easecalluikit\/callkitmanager\/emclientdelegate-implementations"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/easecalluikit\/callkitmanager\/emclientdelegate-implementations"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager\/EMClientDelegate-Implementations","interfaceLanguage":"swift"},"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager"]]},"references":{"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallKitManager/connectionStateDidChange(_:)":{"type":"topic","url":"\/documentation\/easecalluikit\/callkitmanager\/connectionstatedidchange(_:)","kind":"symbol","title":"connectionStateDidChange(_:)","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager\/connectionStateDidChange(_:)","abstract":[],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"connectionStateDidChange","kind":"identifier"},{"text":"(","kind":"text"},{"text":"ConnectionState","kind":"typeIdentifier","preciseIdentifier":"s:13EaseCallUIKit15ConnectionStatea"},{"text":")","kind":"text"}],"role":"symbol","navigatorTitle":[{"text":"connectionStateDidChange:","kind":"identifier"}]},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallKitManager/userAccountDidRemoveFromServer()":{"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"userAccountDidRemoveFromServer","kind":"identifier"}],"title":"userAccountDidRemoveFromServer()","abstract":[],"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"userAccountDidRemoveFromServer","kind":"identifier"},{"text":"()","kind":"text"}],"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager\/userAccountDidRemoveFromServer()","url":"\/documentation\/easecalluikit\/callkitmanager\/useraccountdidremovefromserver()"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallKitManager/userAccountDidForced(toLogout:)":{"navigatorTitle":[{"kind":"identifier","text":"userAccountDidForcedToLogout:"}],"url":"\/documentation\/easecalluikit\/callkitmanager\/useraccountdidforced(tologout:)","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"userAccountDidForced"},{"kind":"text","text":"("},{"kind":"externalParam","text":"toLogout"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"ChatError","preciseIdentifier":"s:13EaseCallUIKit9ChatErrora"},{"kind":"text","text":"?)"}],"title":"userAccountDidForced(toLogout:)","abstract":[],"type":"topic","role":"symbol","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager\/userAccountDidForced(toLogout:)"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit":{"title":"EaseCallUIKit","type":"topic","url":"\/documentation\/easecalluikit","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit","abstract":[],"role":"collection","kind":"symbol"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallKitManager":{"role":"symbol","title":"CallKitManager","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CallKitManager"}],"abstract":[],"type":"topic","kind":"symbol","url":"\/documentation\/easecalluikit\/callkitmanager","navigatorTitle":[{"text":"CallKitManager","kind":"identifier"}]},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallKitManager/userDidForbidByServer()":{"url":"\/documentation\/easecalluikit\/callkitmanager\/userdidforbidbyserver()","role":"symbol","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager\/userDidForbidByServer()","title":"userDidForbidByServer()","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"userDidForbidByServer"},{"kind":"text","text":"()"}],"navigatorTitle":[{"text":"userDidForbidByServer","kind":"identifier"}],"type":"topic"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallKitManager/userAccountDidLoginFromOtherDevice(with:)":{"navigatorTitle":[{"text":"userAccountDidLoginFromOtherDeviceWithInfo:","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager\/userAccountDidLoginFromOtherDevice(with:)","type":"topic","kind":"symbol","url":"\/documentation\/easecalluikit\/callkitmanager\/useraccountdidloginfromotherdevice(with:)","abstract":[],"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"userAccountDidLoginFromOtherDevice"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:13EaseCallUIKit18LoginExtensionInfoa","text":"LoginExtensionInfo","kind":"typeIdentifier"},{"kind":"text","text":"?)"}],"title":"userAccountDidLoginFromOtherDevice(with:)"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/topicSections","op":"replace","value":[{"identifiers":["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager\/connectionStateDidChange(_:)","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager\/userAccountDidForced(toLogout:)","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager\/userAccountDidLoginFromOtherDevice(with:)","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager\/userAccountDidRemoveFromServer()","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager\/userDidForbidByServer()"],"generated":true,"anchor":"Instance-Methods","title":"Instance Methods"}]},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallKitManager~1connectionStateDidChange(_:)\/title","value":"connectionStateDidChange:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallKitManager~1connectionStateDidChange(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"connectionStateDidChange:"}]},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallKitManager~1userAccountDidRemoveFromServer()\/title","op":"replace","value":"userAccountDidRemoveFromServer"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"userAccountDidRemoveFromServer"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallKitManager~1userAccountDidRemoveFromServer()\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallKitManager~1userAccountDidForced(toLogout:)\/title","value":"userAccountDidForcedToLogout:","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallKitManager~1userAccountDidForced(toLogout:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"userAccountDidForcedToLogout:","kind":"identifier"}],"op":"replace"},{"value":"CallKitManager","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallKitManager\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallKitManager\/fragments","op":"replace","value":[{"text":"CallKitManager","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallKitManager\/navigatorTitle","value":[{"text":"CallKitManager","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallKitManager~1userDidForbidByServer()\/title","value":"userDidForbidByServer"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallKitManager~1userDidForbidByServer()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"userDidForbidByServer","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallKitManager~1userAccountDidLoginFromOtherDevice(with:)\/title","op":"replace","value":"userAccountDidLoginFromOtherDeviceWithInfo:"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"userAccountDidLoginFromOtherDeviceWithInfo:"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallKitManager~1userAccountDidLoginFromOtherDevice(with:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}