{"identifier":{"url":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager\/onCapture(_:sourceType:)","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"onCapture"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"videoFrame","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)AgoraOutputVideoFrame","kind":"typeIdentifier","text":"AgoraOutputVideoFrame"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"sourceType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraVideoSourceType","preciseIdentifier":"c:@E@AgoraVideoSourceType"},{"text":") -> ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easecalluikit\/callkitmanager\/oncapture(_:sourcetype:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easecalluikit\/callkitmanager\/oncapture(_:sourcetype:)"]}],"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"AgoraVideoFrameDelegate.onCapture(_:sourceType:)"},{"text":".","type":"text"}],"sections":[],"metadata":{"extendedModule":"EaseCallUIKit","roleHeading":"Instance Method","modules":[{"name":"EaseCallUIKit"}],"title":"onCapture(_:sourceType:)","navigatorTitle":[{"kind":"identifier","text":"onCaptureVideoFrame:sourceType:"}],"role":"symbol","symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"onCapture"},{"text":"(","kind":"text"},{"text":"AgoraOutputVideoFrame","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AgoraOutputVideoFrame"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"sourceType"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@AgoraVideoSourceType","text":"AgoraVideoSourceType"},{"text":") -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"externalID":"c:@CM@EaseCallUIKit@objc(cs)CallKitManager(im)onCaptureVideoFrame:sourceType:"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager\/AgoraVideoFrameDelegate-Implementations"]]},"references":{"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallKitManager/AgoraVideoFrameDelegate-Implementations":{"title":"AgoraVideoFrameDelegate Implementations","abstract":[],"url":"\/documentation\/easecalluikit\/callkitmanager\/agoravideoframedelegate-implementations","kind":"article","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager\/AgoraVideoFrameDelegate-Implementations","type":"topic","role":"collectionGroup"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit":{"title":"EaseCallUIKit","type":"topic","url":"\/documentation\/easecalluikit","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit","abstract":[],"role":"collection","kind":"symbol"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallKitManager":{"role":"symbol","title":"CallKitManager","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CallKitManager"}],"abstract":[],"type":"topic","kind":"symbol","url":"\/documentation\/easecalluikit\/callkitmanager","navigatorTitle":[{"text":"CallKitManager","kind":"identifier"}]},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallKitManager/onCapture(_:sourceType:)":{"kind":"symbol","abstract":[],"url":"\/documentation\/easecalluikit\/callkitmanager\/oncapture(_:sourcetype:)","type":"topic","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager\/onCapture(_:sourceType:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"onCapture"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AgoraOutputVideoFrame","text":"AgoraOutputVideoFrame"},{"text":", ","kind":"text"},{"text":"sourceType","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@AgoraVideoSourceType","text":"AgoraVideoSourceType"},{"kind":"text","text":") -> "},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"navigatorTitle":[{"kind":"identifier","text":"onCaptureVideoFrame:sourceType:"}],"title":"onCapture(_:sourceType:)"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"onCaptureVideoFrame:sourceType:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"onCaptureVideoFrame:sourceType:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":") ","kind":"text"},{"text":"onCaptureVideoFrame:","kind":"identifier"},{"kind":"text","text":"("},{"text":"AgoraOutputVideoFrame","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AgoraOutputVideoFrame"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"videoFrame"},{"text":" ","kind":"text"},{"text":"sourceType:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@E@AgoraVideoSourceType","kind":"typeIdentifier","text":"AgoraVideoSourceType"},{"kind":"text","text":") "},{"text":"sourceType","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","value":"CallKitManager","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallKitManager\/title"},{"value":[{"kind":"identifier","text":"CallKitManager"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallKitManager\/fragments","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"CallKitManager"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallKitManager\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallKitManager~1onCapture(_:sourceType:)\/title","value":"onCaptureVideoFrame:sourceType:"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"onCaptureVideoFrame:sourceType:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallKitManager~1onCapture(_:sourceType:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}