{"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onRenderVideoFrame"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"videoFrame","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"AgoraOutputVideoFrame","preciseIdentifier":"c:objc(cs)AgoraOutputVideoFrame","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"uid","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Su","text":"UInt","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"channelId"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":") -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"sections":[],"kind":"symbol","variants":[{"paths":["\/documentation\/easecalluikit\/callkitmanager\/onrendervideoframe(_:uid:channelid:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easecalluikit\/callkitmanager\/onrendervideoframe(_:uid:channelid:)"]}],"identifier":{"url":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager\/onRenderVideoFrame(_:uid:channelId:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager\/AgoraVideoFrameDelegate-Implementations"]]},"metadata":{"modules":[{"name":"EaseCallUIKit"}],"extendedModule":"EaseCallUIKit","externalID":"c:@CM@EaseCallUIKit@objc(cs)CallKitManager(im)onRenderVideoFrame:uid:channelId:","symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onRenderVideoFrame","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AgoraOutputVideoFrame","text":"AgoraOutputVideoFrame"},{"kind":"text","text":", "},{"text":"uid","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Su","kind":"typeIdentifier","text":"UInt"},{"text":", ","kind":"text"},{"text":"channelId","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"roleHeading":"Instance Method","title":"onRenderVideoFrame(_:uid:channelId:)","navigatorTitle":[{"text":"onRenderVideoFrame:uid:channelId:","kind":"identifier"}],"role":"symbol"},"schemaVersion":{"major":0,"patch":0,"minor":3},"abstract":[{"text":"Inherited from ","type":"text"},{"code":"AgoraVideoFrameDelegate.onRenderVideoFrame(_:uid:channelId:)","type":"codeVoice"},{"type":"text","text":"."}],"references":{"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallKitManager":{"role":"symbol","title":"CallKitManager","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CallKitManager"}],"abstract":[],"type":"topic","kind":"symbol","url":"\/documentation\/easecalluikit\/callkitmanager","navigatorTitle":[{"text":"CallKitManager","kind":"identifier"}]},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallKitManager/AgoraVideoFrameDelegate-Implementations":{"title":"AgoraVideoFrameDelegate Implementations","abstract":[],"url":"\/documentation\/easecalluikit\/callkitmanager\/agoravideoframedelegate-implementations","kind":"article","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager\/AgoraVideoFrameDelegate-Implementations","type":"topic","role":"collectionGroup"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit":{"title":"EaseCallUIKit","type":"topic","url":"\/documentation\/easecalluikit","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit","abstract":[],"role":"collection","kind":"symbol"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallKitManager/onRenderVideoFrame(_:uid:channelId:)":{"type":"topic","url":"\/documentation\/easecalluikit\/callkitmanager\/onrendervideoframe(_:uid:channelid:)","kind":"symbol","title":"onRenderVideoFrame(_:uid:channelId:)","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager\/onRenderVideoFrame(_:uid:channelId:)","abstract":[],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onRenderVideoFrame","kind":"identifier"},{"text":"(","kind":"text"},{"text":"AgoraOutputVideoFrame","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AgoraOutputVideoFrame"},{"kind":"text","text":", "},{"text":"uid","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Su","text":"UInt"},{"text":", ","kind":"text"},{"text":"channelId","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"onRenderVideoFrame:uid:channelId:"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"onRenderVideoFrame:uid:channelId:"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"onRenderVideoFrame:uid:channelId:","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:@T@BOOL","text":"BOOL","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"onRenderVideoFrame:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"AgoraOutputVideoFrame","preciseIdentifier":"c:objc(cs)AgoraOutputVideoFrame","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"videoFrame","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"uid:"},{"kind":"text","text":"("},{"text":"NSUInteger","preciseIdentifier":"c:@T@NSUInteger","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"uid","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"channelId:","kind":"identifier"},{"kind":"text","text":"("},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"channelId"},{"text":";","kind":"text"}]}]}},{"value":"CallKitManager","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallKitManager\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallKitManager\/fragments","op":"replace","value":[{"text":"CallKitManager","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallKitManager\/navigatorTitle","value":[{"text":"CallKitManager","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallKitManager~1onRenderVideoFrame(_:uid:channelId:)\/title","value":"onRenderVideoFrame:uid:channelId:"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onRenderVideoFrame:uid:channelId:"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallKitManager~1onRenderVideoFrame(_:uid:channelId:)\/fragments"}]}]}