{"metadata":{"symbolKind":"property","title":"profileProviderOC","modules":[{"name":"EaseCallUIKit"}],"navigatorTitle":[{"text":"profileProviderOC","kind":"identifier"}],"externalID":"c:@M@EaseCallUIKit@objc(cs)CallKitManager(py)profileProviderOC","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"profileProviderOC","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@EaseCallUIKit@objc(pl)CallUserProfileProviderOC","kind":"typeIdentifier","text":"CallUserProfileProviderOC"},{"text":"?","kind":"text"}],"roleHeading":"Instance Property"},"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"type":"text","text":"Provider for user profiles in Objective-C"}],"variants":[{"paths":["\/documentation\/easecalluikit\/callkitmanager\/profileprovideroc"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/easecalluikit\/callkitmanager\/profileprovideroc"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"profileProviderOC","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@EaseCallUIKit@objc(pl)CallUserProfileProviderOC","kind":"typeIdentifier","text":"CallUserProfileProviderOC","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallUserProfileProviderOC"},{"text":"?","kind":"text"}]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager\/profileProviderOC"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager"]]},"sections":[],"references":{"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallKitManager":{"role":"symbol","title":"CallKitManager","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CallKitManager"}],"abstract":[],"type":"topic","kind":"symbol","url":"\/documentation\/easecalluikit\/callkitmanager","navigatorTitle":[{"text":"CallKitManager","kind":"identifier"}]},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallUserProfileProviderOC":{"kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"CallUserProfileProviderOC"}],"title":"CallUserProfileProviderOC","abstract":[{"type":"text","text":"\/\/\/ Profile provider of the ChatUIKit.Only available in Objective-C language."}],"navigatorTitle":[{"kind":"identifier","text":"CallUserProfileProviderOC"}],"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallUserProfileProviderOC","type":"topic","role":"symbol","url":"\/documentation\/easecalluikit\/calluserprofileprovideroc"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit":{"title":"EaseCallUIKit","type":"topic","url":"\/documentation\/easecalluikit","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit","abstract":[],"role":"collection","kind":"symbol"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallKitManager/profileProviderOC":{"kind":"symbol","title":"profileProviderOC","navigatorTitle":[{"text":"profileProviderOC","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager\/profileProviderOC","url":"\/documentation\/easecalluikit\/callkitmanager\/profileprovideroc","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"profileProviderOC","kind":"identifier"},{"kind":"text","text":": "},{"text":"CallUserProfileProviderOC","preciseIdentifier":"c:@M@EaseCallUIKit@objc(pl)CallUserProfileProviderOC","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"abstract":[{"type":"text","text":"Provider for user profiles in Objective-C"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"path":"\/metadata\/title","value":"profileProviderOC","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"value":[{"kind":"identifier","text":"profileProviderOC"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"strong","kind":"keyword"},{"text":") ","kind":"text"},{"text":"id<CallUserProfileProviderOC>","kind":"typeIdentifier","preciseIdentifier":"c:Qo@M@EaseCallUIKit@objc(pl)CallUserProfileProviderOC"},{"text":" ","kind":"text"},{"text":"profileProviderOC","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","value":"CallKitManager","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallKitManager\/title"},{"op":"replace","value":[{"text":"CallKitManager","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallKitManager\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallKitManager\/navigatorTitle","op":"replace","value":[{"text":"CallKitManager","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallUserProfileProviderOC\/title","op":"replace","value":"CallUserProfileProviderOC"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallUserProfileProviderOC\/fragments","value":[{"kind":"identifier","text":"CallUserProfileProviderOC"}]},{"op":"replace","value":[{"text":"CallUserProfileProviderOC","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallUserProfileProviderOC\/navigatorTitle"},{"op":"replace","value":"profileProviderOC","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallKitManager~1profileProviderOC\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallKitManager~1profileProviderOC\/fragments","value":[{"kind":"identifier","text":"profileProviderOC"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}