{"sections":[],"identifier":{"url":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager\/receivedCalls","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager"]]},"variants":[{"paths":["\/documentation\/easecalluikit\/callkitmanager\/receivedcalls"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easecalluikit\/callkitmanager\/receivedcalls"]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"receivedCalls","kind":"identifier"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":" : ","kind":"text"},{"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallInfo","preciseIdentifier":"c:@M@EaseCallUIKit@objc(cs)CallInfo","kind":"typeIdentifier","text":"CallInfo"},{"text":"] { get }","kind":"text"}]}]}],"kind":"symbol","metadata":{"roleHeading":"Instance Property","title":"receivedCalls","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"receivedCalls","kind":"identifier"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:@M@EaseCallUIKit@objc(cs)CallInfo","text":"CallInfo","kind":"typeIdentifier"},{"text":"]","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"receivedCalls"}],"externalID":"c:@M@EaseCallUIKit@objc(cs)CallKitManager(py)receivedCalls","role":"symbol","symbolKind":"property","modules":[{"name":"EaseCallUIKit"}]},"references":{"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallKitManager/receivedCalls":{"abstract":[],"kind":"symbol","title":"receivedCalls","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager\/receivedCalls","url":"\/documentation\/easecalluikit\/callkitmanager\/receivedcalls","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"receivedCalls","kind":"identifier"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":" : "},{"text":"CallInfo","kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseCallUIKit@objc(cs)CallInfo"},{"text":"]","kind":"text"}],"navigatorTitle":[{"text":"receivedCalls","kind":"identifier"}],"role":"symbol","type":"topic"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit":{"title":"EaseCallUIKit","type":"topic","url":"\/documentation\/easecalluikit","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit","abstract":[],"role":"collection","kind":"symbol"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallKitManager":{"role":"symbol","title":"CallKitManager","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CallKitManager"}],"abstract":[],"type":"topic","kind":"symbol","url":"\/documentation\/easecalluikit\/callkitmanager","navigatorTitle":[{"text":"CallKitManager","kind":"identifier"}]},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallInfo":{"navigatorTitle":[{"text":"CallInfo","kind":"identifier"}],"title":"CallInfo","url":"\/documentation\/easecalluikit\/callinfo","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CallInfo","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallInfo","type":"topic","kind":"symbol","abstract":[],"role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"value":"receivedCalls","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"receivedCalls","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"text":"NSDictionary<NSString *,CallInfo *>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSDictionary"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"receivedCalls"},{"kind":"text","text":";"}],"languages":["occ"]}]}},{"op":"replace","value":"receivedCalls","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallKitManager~1receivedCalls\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallKitManager~1receivedCalls\/fragments","value":[{"kind":"identifier","text":"receivedCalls"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallKitManager\/title","op":"replace","value":"CallKitManager"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallKitManager\/fragments","value":[{"kind":"identifier","text":"CallKitManager"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallKitManager\/navigatorTitle","value":[{"text":"CallKitManager","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallInfo\/title","op":"replace","value":"CallInfo"},{"op":"replace","value":[{"kind":"identifier","text":"CallInfo"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallInfo\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallInfo\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"CallInfo"}]}]}]}