{"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager\/AgoraRtcEngineDelegate-Implementations"]]},"variants":[{"paths":["\/documentation\/easecalluikit\/callkitmanager\/rtcengine(_:tokenprivilegewillexpire:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easecalluikit\/callkitmanager\/rtcengine(_:tokenprivilegewillexpire:)"]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","metadata":{"title":"rtcEngine(_:tokenPrivilegeWillExpire:)","extendedModule":"EaseCallUIKit","navigatorTitle":[{"text":"rtcEngine:tokenPrivilegeWillExpire:","kind":"identifier"}],"externalID":"c:@CM@EaseCallUIKit@objc(cs)CallKitManager(im)rtcEngine:tokenPrivilegeWillExpire:","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"rtcEngine"},{"text":"(","kind":"text"},{"text":"AgoraRtcEngineKit","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AgoraRtcEngineKit"},{"text":", ","kind":"text"},{"text":"tokenPrivilegeWillExpire","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":")","kind":"text"}],"symbolKind":"method","role":"symbol","roleHeading":"Instance Method","modules":[{"name":"EaseCallUIKit"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager\/rtcEngine(_:tokenPrivilegeWillExpire:)"},"abstract":[{"type":"text","text":"Inherited from "},{"code":"AgoraRtcEngineDelegate.rtcEngine(_:tokenPrivilegeWillExpire:)","type":"codeVoice"},{"text":".","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"rtcEngine","kind":"identifier"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"text":"engine","kind":"internalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)AgoraRtcEngineKit","text":"AgoraRtcEngineKit","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"tokenPrivilegeWillExpire","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"token"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}]}]}],"references":{"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallKitManager/AgoraRtcEngineDelegate-Implementations":{"title":"AgoraRtcEngineDelegate Implementations","kind":"article","role":"collectionGroup","url":"\/documentation\/easecalluikit\/callkitmanager\/agorartcenginedelegate-implementations","type":"topic","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager\/AgoraRtcEngineDelegate-Implementations"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit":{"title":"EaseCallUIKit","type":"topic","url":"\/documentation\/easecalluikit","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit","abstract":[],"role":"collection","kind":"symbol"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallKitManager/rtcEngine(_:tokenPrivilegeWillExpire:)":{"url":"\/documentation\/easecalluikit\/callkitmanager\/rtcengine(_:tokenprivilegewillexpire:)","role":"symbol","title":"rtcEngine(_:tokenPrivilegeWillExpire:)","navigatorTitle":[{"kind":"identifier","text":"rtcEngine:tokenPrivilegeWillExpire:"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager\/rtcEngine(_:tokenPrivilegeWillExpire:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"rtcEngine","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)AgoraRtcEngineKit","text":"AgoraRtcEngineKit","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"tokenPrivilegeWillExpire","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[]},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallKitManager":{"role":"symbol","title":"CallKitManager","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CallKitManager"}],"abstract":[],"type":"topic","kind":"symbol","url":"\/documentation\/easecalluikit\/callkitmanager","navigatorTitle":[{"text":"CallKitManager","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"rtcEngine:tokenPrivilegeWillExpire:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"rtcEngine:tokenPrivilegeWillExpire:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"rtcEngine:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AgoraRtcEngineKit","text":"AgoraRtcEngineKit"},{"text":" *) ","kind":"text"},{"text":"engine","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"tokenPrivilegeWillExpire:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"token","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallKitManager~1rtcEngine(_:tokenPrivilegeWillExpire:)\/title","value":"rtcEngine:tokenPrivilegeWillExpire:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallKitManager~1rtcEngine(_:tokenPrivilegeWillExpire:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"rtcEngine:tokenPrivilegeWillExpire:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallKitManager\/title","value":"CallKitManager","op":"replace"},{"value":[{"text":"CallKitManager","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallKitManager\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallKitManager\/navigatorTitle","op":"replace","value":[{"text":"CallKitManager","kind":"identifier"}]}]}]}