{"variants":[{"paths":["\/documentation\/easecalluikit\/callkitmanager\/rtcengine(_:reportaudiovolumeindicationofspeakers:totalvolume:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/easecalluikit\/callkitmanager\/rtcengine(_:reportaudiovolumeindicationofspeakers:totalvolume:)"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"roleHeading":"Instance Method","symbolKind":"method","navigatorTitle":[{"text":"rtcEngine:reportAudioVolumeIndicationOfSpeakers:totalVolume:","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"rtcEngine"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"AgoraRtcEngineKit","preciseIdentifier":"c:objc(cs)AgoraRtcEngineKit"},{"kind":"text","text":", "},{"kind":"externalParam","text":"reportAudioVolumeIndicationOfSpeakers"},{"kind":"text","text":": ["},{"text":"AgoraRtcAudioVolumeInfo","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AgoraRtcAudioVolumeInfo"},{"text":"], ","kind":"text"},{"text":"totalVolume","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":")","kind":"text"}],"title":"rtcEngine(_:reportAudioVolumeIndicationOfSpeakers:totalVolume:)","modules":[{"name":"EaseCallUIKit"}],"role":"symbol","externalID":"c:@CM@EaseCallUIKit@objc(cs)CallKitManager(im)rtcEngine:reportAudioVolumeIndicationOfSpeakers:totalVolume:","extendedModule":"EaseCallUIKit"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager\/AgoraRtcEngineDelegate-Implementations"]]},"identifier":{"url":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager\/rtcEngine(_:reportAudioVolumeIndicationOfSpeakers:totalVolume:)","interfaceLanguage":"swift"},"sections":[],"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"AgoraRtcEngineDelegate.rtcEngine(_:reportAudioVolumeIndicationOfSpeakers:totalVolume:)"},{"type":"text","text":"."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"rtcEngine","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"text":"engine","kind":"internalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)AgoraRtcEngineKit","kind":"typeIdentifier","text":"AgoraRtcEngineKit"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"reportAudioVolumeIndicationOfSpeakers"},{"kind":"text","text":" "},{"text":"speakers","kind":"internalParam"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AgoraRtcAudioVolumeInfo","text":"AgoraRtcAudioVolumeInfo"},{"kind":"text","text":"], "},{"text":"totalVolume","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"kind":"text","text":")"}],"platforms":["iOS"],"languages":["swift"]}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","references":{"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallKitManager/AgoraRtcEngineDelegate-Implementations":{"title":"AgoraRtcEngineDelegate Implementations","kind":"article","role":"collectionGroup","url":"\/documentation\/easecalluikit\/callkitmanager\/agorartcenginedelegate-implementations","type":"topic","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager\/AgoraRtcEngineDelegate-Implementations"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallKitManager/rtcEngine(_:reportAudioVolumeIndicationOfSpeakers:totalVolume:)":{"url":"\/documentation\/easecalluikit\/callkitmanager\/rtcengine(_:reportaudiovolumeindicationofspeakers:totalvolume:)","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"rtcEngine","kind":"identifier"},{"kind":"text","text":"("},{"text":"AgoraRtcEngineKit","preciseIdentifier":"c:objc(cs)AgoraRtcEngineKit","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"reportAudioVolumeIndicationOfSpeakers","kind":"externalParam"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AgoraRtcAudioVolumeInfo","text":"AgoraRtcAudioVolumeInfo"},{"text":"], ","kind":"text"},{"kind":"externalParam","text":"totalVolume"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":")","kind":"text"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager\/rtcEngine(_:reportAudioVolumeIndicationOfSpeakers:totalVolume:)","kind":"symbol","role":"symbol","title":"rtcEngine(_:reportAudioVolumeIndicationOfSpeakers:totalVolume:)","navigatorTitle":[{"kind":"identifier","text":"rtcEngine:reportAudioVolumeIndicationOfSpeakers:totalVolume:"}]},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit":{"title":"EaseCallUIKit","type":"topic","url":"\/documentation\/easecalluikit","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit","abstract":[],"role":"collection","kind":"symbol"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallKitManager":{"role":"symbol","title":"CallKitManager","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CallKitManager"}],"abstract":[],"type":"topic","kind":"symbol","url":"\/documentation\/easecalluikit\/callkitmanager","navigatorTitle":[{"text":"CallKitManager","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"value":"rtcEngine:reportAudioVolumeIndicationOfSpeakers:totalVolume:","op":"replace","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"value":[{"text":"- ","kind":"text"},{"text":"rtcEngine:reportAudioVolumeIndicationOfSpeakers:totalVolume:","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"text":") ","kind":"text"},{"kind":"identifier","text":"rtcEngine:"},{"kind":"text","text":"("},{"text":"AgoraRtcEngineKit","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AgoraRtcEngineKit"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"engine"},{"kind":"text","text":" "},{"text":"reportAudioVolumeIndicationOfSpeakers:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:Q$objc(cs)NSArray","kind":"typeIdentifier","text":"NSArray<AgoraRtcAudioVolumeInfo *>"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"speakers"},{"kind":"text","text":" "},{"kind":"identifier","text":"totalVolume:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@T@NSInteger","text":"NSInteger","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"totalVolume","kind":"internalParam"},{"text":";","kind":"text"}]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallKitManager~1rtcEngine(_:reportAudioVolumeIndicationOfSpeakers:totalVolume:)\/title","value":"rtcEngine:reportAudioVolumeIndicationOfSpeakers:totalVolume:"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallKitManager~1rtcEngine(_:reportAudioVolumeIndicationOfSpeakers:totalVolume:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"rtcEngine:reportAudioVolumeIndicationOfSpeakers:totalVolume:","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallKitManager\/title","value":"CallKitManager"},{"op":"replace","value":[{"kind":"identifier","text":"CallKitManager"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallKitManager\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallKitManager\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"CallKitManager"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}