{"metadata":{"roleHeading":"Instance Method","symbolKind":"method","navigatorTitle":[{"text":"rtcEngineRequestToken:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"rtcEngineRequestToken","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AgoraRtcEngineKit","text":"AgoraRtcEngineKit"},{"kind":"text","text":")"}],"title":"rtcEngineRequestToken(_:)","modules":[{"name":"EaseCallUIKit"}],"role":"symbol","externalID":"c:@CM@EaseCallUIKit@objc(cs)CallKitManager(im)rtcEngineRequestToken:","extendedModule":"EaseCallUIKit"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager\/AgoraRtcEngineDelegate-Implementations"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"AgoraRtcEngineDelegate.rtcEngineRequestToken(_:)"},{"text":".","type":"text"}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"rtcEngineRequestToken","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"engine"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraRtcEngineKit","preciseIdentifier":"c:objc(cs)AgoraRtcEngineKit"},{"text":")","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easecalluikit\/callkitmanager\/rtcenginerequesttoken(_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easecalluikit\/callkitmanager\/rtcenginerequesttoken(_:)"]}],"identifier":{"url":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager\/rtcEngineRequestToken(_:)","interfaceLanguage":"swift"},"sections":[],"references":{"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit":{"title":"EaseCallUIKit","type":"topic","url":"\/documentation\/easecalluikit","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit","abstract":[],"role":"collection","kind":"symbol"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallKitManager":{"role":"symbol","title":"CallKitManager","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CallKitManager"}],"abstract":[],"type":"topic","kind":"symbol","url":"\/documentation\/easecalluikit\/callkitmanager","navigatorTitle":[{"text":"CallKitManager","kind":"identifier"}]},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallKitManager/AgoraRtcEngineDelegate-Implementations":{"title":"AgoraRtcEngineDelegate Implementations","kind":"article","role":"collectionGroup","url":"\/documentation\/easecalluikit\/callkitmanager\/agorartcenginedelegate-implementations","type":"topic","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager\/AgoraRtcEngineDelegate-Implementations"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallKitManager/rtcEngineRequestToken(_:)":{"url":"\/documentation\/easecalluikit\/callkitmanager\/rtcenginerequesttoken(_:)","role":"symbol","title":"rtcEngineRequestToken(_:)","navigatorTitle":[{"kind":"identifier","text":"rtcEngineRequestToken:"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager\/rtcEngineRequestToken(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"rtcEngineRequestToken","kind":"identifier"},{"text":"(","kind":"text"},{"text":"AgoraRtcEngineKit","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AgoraRtcEngineKit"},{"text":")","kind":"text"}],"abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","value":"rtcEngineRequestToken:","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"rtcEngineRequestToken:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"text":") ","kind":"text"},{"kind":"identifier","text":"rtcEngineRequestToken:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)AgoraRtcEngineKit","kind":"typeIdentifier","text":"AgoraRtcEngineKit"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"engine"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"}},{"value":"CallKitManager","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallKitManager\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallKitManager\/fragments","value":[{"text":"CallKitManager","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"CallKitManager"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallKitManager\/navigatorTitle"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallKitManager~1rtcEngineRequestToken(_:)\/title","value":"rtcEngineRequestToken:","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallKitManager~1rtcEngineRequestToken(_:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"rtcEngineRequestToken:"}]}]}]}