{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager\/rtcEngine(_:didJoinChannel:withUid:elapsed:)"},"sections":[],"variants":[{"paths":["\/documentation\/easecalluikit\/callkitmanager\/rtcengine(_:didjoinchannel:withuid:elapsed:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easecalluikit\/callkitmanager\/rtcengine(_:didjoinchannel:withuid:elapsed:)"]}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"rtcEngine"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"text":"engine","kind":"internalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AgoraRtcEngineKit","text":"AgoraRtcEngineKit"},{"kind":"text","text":", "},{"text":"didJoinChannel","kind":"externalParam"},{"kind":"text","text":" "},{"text":"channel","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"text":"withUid","kind":"externalParam"},{"kind":"text","text":" "},{"text":"uid","kind":"internalParam"},{"kind":"text","text":": "},{"text":"UInt","kind":"typeIdentifier","preciseIdentifier":"s:Su"},{"text":", ","kind":"text"},{"text":"elapsed","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"},{"kind":"text","text":")"}]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager\/AgoraRtcEngineDelegate-Implementations"]]},"metadata":{"navigatorTitle":[{"text":"rtcEngine:didJoinChannel:withUid:elapsed:","kind":"identifier"}],"symbolKind":"method","modules":[{"name":"EaseCallUIKit"}],"roleHeading":"Instance Method","title":"rtcEngine(_:didJoinChannel:withUid:elapsed:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"rtcEngine","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraRtcEngineKit","preciseIdentifier":"c:objc(cs)AgoraRtcEngineKit"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didJoinChannel"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"withUid","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Su","text":"UInt","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"elapsed"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":")","kind":"text"}],"externalID":"c:@CM@EaseCallUIKit@objc(cs)CallKitManager(im)rtcEngine:didJoinChannel:withUid:elapsed:","extendedModule":"EaseCallUIKit"},"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","abstract":[{"text":"Inherited from ","type":"text"},{"type":"codeVoice","code":"AgoraRtcEngineDelegate.rtcEngine(_:didJoinChannel:withUid:elapsed:)"},{"type":"text","text":"."}],"references":{"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallKitManager/rtcEngine(_:didJoinChannel:withUid:elapsed:)":{"url":"\/documentation\/easecalluikit\/callkitmanager\/rtcengine(_:didjoinchannel:withuid:elapsed:)","role":"symbol","title":"rtcEngine(_:didJoinChannel:withUid:elapsed:)","navigatorTitle":[{"kind":"identifier","text":"rtcEngine:didJoinChannel:withUid:elapsed:"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager\/rtcEngine(_:didJoinChannel:withUid:elapsed:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"rtcEngine","kind":"identifier"},{"text":"(","kind":"text"},{"text":"AgoraRtcEngineKit","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AgoraRtcEngineKit"},{"text":", ","kind":"text"},{"text":"didJoinChannel","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"withUid"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Su","text":"UInt","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"elapsed","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":")","kind":"text"}],"abstract":[]},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallKitManager":{"role":"symbol","title":"CallKitManager","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CallKitManager"}],"abstract":[],"type":"topic","kind":"symbol","url":"\/documentation\/easecalluikit\/callkitmanager","navigatorTitle":[{"text":"CallKitManager","kind":"identifier"}]},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit":{"title":"EaseCallUIKit","type":"topic","url":"\/documentation\/easecalluikit","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit","abstract":[],"role":"collection","kind":"symbol"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallKitManager/AgoraRtcEngineDelegate-Implementations":{"title":"AgoraRtcEngineDelegate Implementations","kind":"article","role":"collectionGroup","url":"\/documentation\/easecalluikit\/callkitmanager\/agorartcenginedelegate-implementations","type":"topic","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager\/AgoraRtcEngineDelegate-Implementations"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"rtcEngine:didJoinChannel:withUid:elapsed:","op":"replace"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"rtcEngine:didJoinChannel:withUid:elapsed:","kind":"identifier"}],"op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"text":") ","kind":"text"},{"text":"rtcEngine:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"AgoraRtcEngineKit","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AgoraRtcEngineKit"},{"text":" *) ","kind":"text"},{"text":"engine","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"didJoinChannel:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"text":"channel","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"withUid:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSUInteger","text":"NSUInteger"},{"kind":"text","text":") "},{"text":"uid","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"elapsed:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger","text":"NSInteger"},{"text":") ","kind":"text"},{"text":"elapsed","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallKitManager~1rtcEngine(_:didJoinChannel:withUid:elapsed:)\/title","value":"rtcEngine:didJoinChannel:withUid:elapsed:"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallKitManager~1rtcEngine(_:didJoinChannel:withUid:elapsed:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"rtcEngine:didJoinChannel:withUid:elapsed:"}]},{"op":"replace","value":"CallKitManager","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallKitManager\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallKitManager\/fragments","op":"replace","value":[{"text":"CallKitManager","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"CallKitManager"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallKitManager\/navigatorTitle"}]}]}