{"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager\/rtcEngine(_:didOfflineOfUid:reason:)"},"metadata":{"title":"rtcEngine(_:didOfflineOfUid:reason:)","externalID":"c:@CM@EaseCallUIKit@objc(cs)CallKitManager(im)rtcEngine:didOfflineOfUid:reason:","modules":[{"name":"EaseCallUIKit"}],"extendedModule":"EaseCallUIKit","navigatorTitle":[{"kind":"identifier","text":"rtcEngine:didOfflineOfUid:reason:"}],"roleHeading":"Instance Method","symbolKind":"method","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"rtcEngine"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)AgoraRtcEngineKit","text":"AgoraRtcEngineKit","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"didOfflineOfUid"},{"text":": ","kind":"text"},{"text":"UInt","kind":"typeIdentifier","preciseIdentifier":"s:Su"},{"text":", ","kind":"text"},{"text":"reason","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@E@AgoraUserOfflineReason","text":"AgoraUserOfflineReason","kind":"typeIdentifier"},{"text":")","kind":"text"}],"role":"symbol"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager\/AgoraRtcEngineDelegate-Implementations"]]},"abstract":[{"text":"Inherited from ","type":"text"},{"type":"codeVoice","code":"AgoraRtcEngineDelegate.rtcEngine(_:didOfflineOfUid:reason:)"},{"type":"text","text":"."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easecalluikit\/callkitmanager\/rtcengine(_:didofflineofuid:reason:)"]},{"paths":["\/documentation\/easecalluikit\/callkitmanager\/rtcengine(_:didofflineofuid:reason:)"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"rtcEngine"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"engine","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)AgoraRtcEngineKit","kind":"typeIdentifier","text":"AgoraRtcEngineKit"},{"text":", ","kind":"text"},{"text":"didOfflineOfUid","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"uid"},{"text":": ","kind":"text"},{"text":"UInt","preciseIdentifier":"s:Su","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"reason","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@AgoraUserOfflineReason","text":"AgoraUserOfflineReason"},{"text":")","kind":"text"}],"languages":["swift"]}]}],"references":{"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallKitManager/rtcEngine(_:didOfflineOfUid:reason:)":{"url":"\/documentation\/easecalluikit\/callkitmanager\/rtcengine(_:didofflineofuid:reason:)","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"rtcEngine","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AgoraRtcEngineKit","text":"AgoraRtcEngineKit"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"didOfflineOfUid"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Su","text":"UInt","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"reason","kind":"externalParam"},{"kind":"text","text":": "},{"text":"AgoraUserOfflineReason","kind":"typeIdentifier","preciseIdentifier":"c:@E@AgoraUserOfflineReason"},{"text":")","kind":"text"}],"abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager\/rtcEngine(_:didOfflineOfUid:reason:)","role":"symbol","title":"rtcEngine(_:didOfflineOfUid:reason:)","navigatorTitle":[{"text":"rtcEngine:didOfflineOfUid:reason:","kind":"identifier"}]},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallKitManager/AgoraRtcEngineDelegate-Implementations":{"title":"AgoraRtcEngineDelegate Implementations","kind":"article","role":"collectionGroup","url":"\/documentation\/easecalluikit\/callkitmanager\/agorartcenginedelegate-implementations","type":"topic","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager\/AgoraRtcEngineDelegate-Implementations"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit":{"title":"EaseCallUIKit","type":"topic","url":"\/documentation\/easecalluikit","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit","abstract":[],"role":"collection","kind":"symbol"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallKitManager":{"role":"symbol","title":"CallKitManager","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CallKitManager"}],"abstract":[],"type":"topic","kind":"symbol","url":"\/documentation\/easecalluikit\/callkitmanager","navigatorTitle":[{"text":"CallKitManager","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"rtcEngine:didOfflineOfUid:reason:"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"rtcEngine:didOfflineOfUid:reason:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"identifier","text":"rtcEngine:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraRtcEngineKit","preciseIdentifier":"c:objc(cs)AgoraRtcEngineKit"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"engine"},{"text":" ","kind":"text"},{"kind":"identifier","text":"didOfflineOfUid:"},{"text":"(","kind":"text"},{"text":"NSUInteger","preciseIdentifier":"c:@T@NSUInteger","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"uid"},{"kind":"text","text":" "},{"kind":"identifier","text":"reason:"},{"kind":"text","text":"("},{"text":"AgoraUserOfflineReason","preciseIdentifier":"c:@E@AgoraUserOfflineReason","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"reason"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallKitManager~1rtcEngine(_:didOfflineOfUid:reason:)\/title","value":"rtcEngine:didOfflineOfUid:reason:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallKitManager~1rtcEngine(_:didOfflineOfUid:reason:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"rtcEngine:didOfflineOfUid:reason:"}]},{"value":"CallKitManager","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallKitManager\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallKitManager\/fragments","value":[{"text":"CallKitManager","kind":"identifier"}]},{"value":[{"text":"CallKitManager","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallKitManager\/navigatorTitle","op":"replace"}]}]}