{"metadata":{"title":"rtcEngine(_:didAudioRouteChanged:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"rtcEngine"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AgoraRtcEngineKit","text":"AgoraRtcEngineKit"},{"kind":"text","text":", "},{"text":"didAudioRouteChanged","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@E@AgoraAudioOutputRouting","text":"AgoraAudioOutputRouting","kind":"typeIdentifier"},{"kind":"text","text":")"}],"roleHeading":"Instance Method","navigatorTitle":[{"kind":"identifier","text":"rtcEngine:didAudioRouteChanged:"}],"symbolKind":"method","role":"symbol","externalID":"c:@CM@EaseCallUIKit@objc(cs)CallKitManager(im)rtcEngine:didAudioRouteChanged:","modules":[{"name":"EaseCallUIKit"}],"extendedModule":"EaseCallUIKit"},"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager\/AgoraRtcEngineDelegate-Implementations"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager\/rtcEngine(_:didAudioRouteChanged:)"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easecalluikit\/callkitmanager\/rtcengine(_:didaudioroutechanged:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easecalluikit\/callkitmanager\/rtcengine(_:didaudioroutechanged:)"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"rtcEngine","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"engine","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"AgoraRtcEngineKit","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AgoraRtcEngineKit"},{"text":", ","kind":"text"},{"text":"didAudioRouteChanged","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"routing"},{"text":": ","kind":"text"},{"text":"AgoraAudioOutputRouting","preciseIdentifier":"c:@E@AgoraAudioOutputRouting","kind":"typeIdentifier"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"abstract":[{"text":"Inherited from ","type":"text"},{"type":"codeVoice","code":"AgoraRtcEngineDelegate.rtcEngine(_:didAudioRouteChanged:)"},{"type":"text","text":"."}],"references":{"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallKitManager/rtcEngine(_:didAudioRouteChanged:)":{"title":"rtcEngine(_:didAudioRouteChanged:)","type":"topic","abstract":[],"kind":"symbol","role":"symbol","url":"\/documentation\/easecalluikit\/callkitmanager\/rtcengine(_:didaudioroutechanged:)","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager\/rtcEngine(_:didAudioRouteChanged:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"rtcEngine"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AgoraRtcEngineKit","text":"AgoraRtcEngineKit"},{"kind":"text","text":", "},{"text":"didAudioRouteChanged","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"AgoraAudioOutputRouting","kind":"typeIdentifier","preciseIdentifier":"c:@E@AgoraAudioOutputRouting"},{"text":")","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"rtcEngine:didAudioRouteChanged:"}]},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallKitManager/AgoraRtcEngineDelegate-Implementations":{"title":"AgoraRtcEngineDelegate Implementations","kind":"article","role":"collectionGroup","url":"\/documentation\/easecalluikit\/callkitmanager\/agorartcenginedelegate-implementations","type":"topic","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager\/AgoraRtcEngineDelegate-Implementations"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallKitManager":{"role":"symbol","title":"CallKitManager","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CallKitManager"}],"abstract":[],"type":"topic","kind":"symbol","url":"\/documentation\/easecalluikit\/callkitmanager","navigatorTitle":[{"text":"CallKitManager","kind":"identifier"}]},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit":{"title":"EaseCallUIKit","type":"topic","url":"\/documentation\/easecalluikit","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit","abstract":[],"role":"collection","kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"rtcEngine:didAudioRouteChanged:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"rtcEngine:didAudioRouteChanged:","kind":"identifier"}]},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"text":"rtcEngine:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AgoraRtcEngineKit","text":"AgoraRtcEngineKit"},{"text":" *) ","kind":"text"},{"text":"engine","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"didAudioRouteChanged:"},{"kind":"text","text":"("},{"text":"AgoraAudioOutputRouting","preciseIdentifier":"c:@E@AgoraAudioOutputRouting","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"routing","kind":"internalParam"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"rtcEngine:didAudioRouteChanged:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallKitManager~1rtcEngine(_:didAudioRouteChanged:)\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallKitManager~1rtcEngine(_:didAudioRouteChanged:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"rtcEngine:didAudioRouteChanged:","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallKitManager\/title","value":"CallKitManager"},{"value":[{"text":"CallKitManager","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallKitManager\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallKitManager\/navigatorTitle","value":[{"kind":"identifier","text":"CallKitManager"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}