{"metadata":{"symbolKind":"method","title":"rtcEngine(_:networkQuality:txQuality:rxQuality:)","roleHeading":"Instance Method","modules":[{"name":"EaseCallUIKit"}],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"rtcEngine"},{"kind":"text","text":"("},{"text":"AgoraRtcEngineKit","preciseIdentifier":"c:objc(cs)AgoraRtcEngineKit","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"networkQuality","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UInt","kind":"typeIdentifier","preciseIdentifier":"s:Su"},{"kind":"text","text":", "},{"text":"txQuality","kind":"externalParam"},{"kind":"text","text":": "},{"text":"AgoraNetworkQuality","preciseIdentifier":"c:@E@AgoraNetworkQuality","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"rxQuality","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"AgoraNetworkQuality","kind":"typeIdentifier","preciseIdentifier":"c:@E@AgoraNetworkQuality"},{"text":")","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"rtcEngine:networkQuality:txQuality:rxQuality:"}],"extendedModule":"EaseCallUIKit","externalID":"c:@CM@EaseCallUIKit@objc(cs)CallKitManager(im)rtcEngine:networkQuality:txQuality:rxQuality:"},"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","abstract":[{"type":"text","text":"Inherited from "},{"code":"AgoraRtcEngineDelegate.rtcEngine(_:networkQuality:txQuality:rxQuality:)","type":"codeVoice"},{"type":"text","text":"."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easecalluikit\/callkitmanager\/rtcengine(_:networkquality:txquality:rxquality:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easecalluikit\/callkitmanager\/rtcengine(_:networkquality:txquality:rxquality:)"]}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager\/rtcEngine(_:networkQuality:txQuality:rxQuality:)"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"rtcEngine","kind":"identifier"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"text":"engine","kind":"internalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AgoraRtcEngineKit","preciseIdentifier":"c:objc(cs)AgoraRtcEngineKit"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"networkQuality"},{"kind":"text","text":" "},{"kind":"internalParam","text":"uid"},{"text":": ","kind":"text"},{"text":"UInt","preciseIdentifier":"s:Su","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"txQuality"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@E@AgoraNetworkQuality","kind":"typeIdentifier","text":"AgoraNetworkQuality"},{"kind":"text","text":", "},{"text":"rxQuality","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@E@AgoraNetworkQuality","text":"AgoraNetworkQuality","kind":"typeIdentifier"},{"text":")","kind":"text"}]}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager\/AgoraRtcEngineDelegate-Implementations"]]},"references":{"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallKitManager":{"role":"symbol","title":"CallKitManager","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CallKitManager"}],"abstract":[],"type":"topic","kind":"symbol","url":"\/documentation\/easecalluikit\/callkitmanager","navigatorTitle":[{"text":"CallKitManager","kind":"identifier"}]},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit":{"title":"EaseCallUIKit","type":"topic","url":"\/documentation\/easecalluikit","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit","abstract":[],"role":"collection","kind":"symbol"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallKitManager/AgoraRtcEngineDelegate-Implementations":{"title":"AgoraRtcEngineDelegate Implementations","kind":"article","role":"collectionGroup","url":"\/documentation\/easecalluikit\/callkitmanager\/agorartcenginedelegate-implementations","type":"topic","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager\/AgoraRtcEngineDelegate-Implementations"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallKitManager/rtcEngine(_:networkQuality:txQuality:rxQuality:)":{"url":"\/documentation\/easecalluikit\/callkitmanager\/rtcengine(_:networkquality:txquality:rxquality:)","role":"symbol","title":"rtcEngine(_:networkQuality:txQuality:rxQuality:)","navigatorTitle":[{"kind":"identifier","text":"rtcEngine:networkQuality:txQuality:rxQuality:"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager\/rtcEngine(_:networkQuality:txQuality:rxQuality:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"rtcEngine","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)AgoraRtcEngineKit","text":"AgoraRtcEngineKit","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"networkQuality"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Su","kind":"typeIdentifier","text":"UInt"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"txQuality"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@E@AgoraNetworkQuality","text":"AgoraNetworkQuality","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"rxQuality","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"AgoraNetworkQuality","kind":"typeIdentifier","preciseIdentifier":"c:@E@AgoraNetworkQuality"},{"kind":"text","text":")"}],"abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"value":"rtcEngine:networkQuality:txQuality:rxQuality:","path":"\/metadata\/title","op":"replace"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"rtcEngine:networkQuality:txQuality:rxQuality:"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"rtcEngine:"},{"kind":"text","text":"("},{"text":"AgoraRtcEngineKit","preciseIdentifier":"c:objc(cs)AgoraRtcEngineKit","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"engine"},{"text":" ","kind":"text"},{"kind":"identifier","text":"networkQuality:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSUInteger","text":"NSUInteger"},{"text":") ","kind":"text"},{"text":"uid","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"txQuality:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraNetworkQuality","preciseIdentifier":"c:@E@AgoraNetworkQuality"},{"text":") ","kind":"text"},{"text":"txQuality","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"rxQuality:"},{"kind":"text","text":"("},{"text":"AgoraNetworkQuality","kind":"typeIdentifier","preciseIdentifier":"c:@E@AgoraNetworkQuality"},{"text":") ","kind":"text"},{"text":"rxQuality","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallKitManager\/title","op":"replace","value":"CallKitManager"},{"op":"replace","value":[{"kind":"identifier","text":"CallKitManager"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallKitManager\/fragments"},{"value":[{"text":"CallKitManager","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallKitManager\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallKitManager~1rtcEngine(_:networkQuality:txQuality:rxQuality:)\/title","value":"rtcEngine:networkQuality:txQuality:rxQuality:"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"rtcEngine:networkQuality:txQuality:rxQuality:"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallKitManager~1rtcEngine(_:networkQuality:txQuality:rxQuality:)\/fragments"}]}]}