{"metadata":{"symbolKind":"method","role":"symbol","modules":[{"name":"EaseCallUIKit"}],"title":"userAccountDidRemoveFromServer()","externalID":"c:@CM@EaseCallUIKit@objc(cs)CallKitManager(im)userAccountDidRemoveFromServer","navigatorTitle":[{"kind":"identifier","text":"userAccountDidRemoveFromServer"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"userAccountDidRemoveFromServer"},{"text":"()","kind":"text"}],"roleHeading":"Instance Method","extendedModule":"EaseCallUIKit"},"identifier":{"url":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager\/userAccountDidRemoveFromServer()","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easecalluikit\/callkitmanager\/useraccountdidremovefromserver()"]},{"paths":["\/documentation\/easecalluikit\/callkitmanager\/useraccountdidremovefromserver()"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager\/EMClientDelegate-Implementations"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"userAccountDidRemoveFromServer"},{"kind":"text","text":"()"}]}]}],"sections":[],"kind":"symbol","abstract":[{"type":"text","text":"Inherited from "},{"code":"EMClientDelegate.userAccountDidRemoveFromServer()","type":"codeVoice"},{"type":"text","text":"."}],"references":{"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallKitManager/userAccountDidRemoveFromServer()":{"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"userAccountDidRemoveFromServer","kind":"identifier"}],"title":"userAccountDidRemoveFromServer()","abstract":[],"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"userAccountDidRemoveFromServer","kind":"identifier"},{"text":"()","kind":"text"}],"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager\/userAccountDidRemoveFromServer()","url":"\/documentation\/easecalluikit\/callkitmanager\/useraccountdidremovefromserver()"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallKitManager":{"role":"symbol","title":"CallKitManager","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CallKitManager"}],"abstract":[],"type":"topic","kind":"symbol","url":"\/documentation\/easecalluikit\/callkitmanager","navigatorTitle":[{"text":"CallKitManager","kind":"identifier"}]},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallKitManager/EMClientDelegate-Implementations":{"role":"collectionGroup","title":"EMClientDelegate Implementations","url":"\/documentation\/easecalluikit\/callkitmanager\/emclientdelegate-implementations","kind":"article","abstract":[],"type":"topic","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager\/EMClientDelegate-Implementations"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit":{"title":"EaseCallUIKit","type":"topic","url":"\/documentation\/easecalluikit","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit","abstract":[],"role":"collection","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"value":"userAccountDidRemoveFromServer","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"userAccountDidRemoveFromServer"}]},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"identifier","text":"userAccountDidRemoveFromServer"},{"text":";","kind":"text"}],"platforms":["iOS"]}]}},{"value":"userAccountDidRemoveFromServer","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallKitManager~1userAccountDidRemoveFromServer()\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallKitManager~1userAccountDidRemoveFromServer()\/fragments","value":[{"kind":"text","text":"- "},{"text":"userAccountDidRemoveFromServer","kind":"identifier"}]},{"op":"replace","value":"CallKitManager","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallKitManager\/title"},{"op":"replace","value":[{"text":"CallKitManager","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallKitManager\/fragments"},{"value":[{"kind":"identifier","text":"CallKitManager"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallKitManager\/navigatorTitle"}]}]}