{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"userAccountDidForced","kind":"identifier"},{"text":"(","kind":"text"},{"text":"toLogout","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"aError"},{"kind":"text","text":": "},{"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/ChatError","kind":"typeIdentifier","text":"ChatError","preciseIdentifier":"s:13EaseCallUIKit9ChatErrora"},{"text":"?)","kind":"text"}],"languages":["swift"]}],"kind":"declarations"}],"metadata":{"externalID":"c:@CM@EaseCallUIKit@objc(cs)CallKitManager(im)userAccountDidForcedToLogout:","symbolKind":"method","extendedModule":"EaseCallUIKit","role":"symbol","roleHeading":"Instance Method","navigatorTitle":[{"kind":"identifier","text":"userAccountDidForcedToLogout:"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"userAccountDidForced"},{"text":"(","kind":"text"},{"text":"toLogout","kind":"externalParam"},{"kind":"text","text":": "},{"text":"ChatError","kind":"typeIdentifier","preciseIdentifier":"s:13EaseCallUIKit9ChatErrora"},{"kind":"text","text":"?)"}],"title":"userAccountDidForced(toLogout:)","modules":[{"name":"EaseCallUIKit"}]},"abstract":[{"text":"Inherited from ","type":"text"},{"code":"EMClientDelegate.userAccountDidForced(toLogout:)","type":"codeVoice"},{"type":"text","text":"."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easecalluikit\/callkitmanager\/useraccountdidforced(tologout:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easecalluikit\/callkitmanager\/useraccountdidforced(tologout:)"]}],"kind":"symbol","identifier":{"url":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager\/userAccountDidForced(toLogout:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager\/EMClientDelegate-Implementations"]]},"schemaVersion":{"patch":0,"minor":3,"major":0},"sections":[],"references":{"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallKitManager/userAccountDidForced(toLogout:)":{"navigatorTitle":[{"kind":"identifier","text":"userAccountDidForcedToLogout:"}],"url":"\/documentation\/easecalluikit\/callkitmanager\/useraccountdidforced(tologout:)","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"userAccountDidForced"},{"kind":"text","text":"("},{"kind":"externalParam","text":"toLogout"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"ChatError","preciseIdentifier":"s:13EaseCallUIKit9ChatErrora"},{"kind":"text","text":"?)"}],"title":"userAccountDidForced(toLogout:)","abstract":[],"type":"topic","role":"symbol","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager\/userAccountDidForced(toLogout:)"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/ChatError":{"type":"topic","title":"ChatError","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/ChatError","url":"\/documentation\/easecalluikit\/chaterror","role":"symbol","kind":"symbol","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ChatError","kind":"identifier"}],"navigatorTitle":[{"text":"ChatError","kind":"identifier"}],"abstract":[]},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallKitManager/EMClientDelegate-Implementations":{"role":"collectionGroup","title":"EMClientDelegate Implementations","url":"\/documentation\/easecalluikit\/callkitmanager\/emclientdelegate-implementations","kind":"article","abstract":[],"type":"topic","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager\/EMClientDelegate-Implementations"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit":{"title":"EaseCallUIKit","type":"topic","url":"\/documentation\/easecalluikit","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit","abstract":[],"role":"collection","kind":"symbol"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallKitManager":{"role":"symbol","title":"CallKitManager","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallKitManager","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CallKitManager"}],"abstract":[],"type":"topic","kind":"symbol","url":"\/documentation\/easecalluikit\/callkitmanager","navigatorTitle":[{"text":"CallKitManager","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"value":"userAccountDidForcedToLogout:","path":"\/metadata\/title","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"userAccountDidForcedToLogout:","kind":"identifier"}]},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"userAccountDidForcedToLogout:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"EMError","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)EMError"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"aError"},{"kind":"text","text":";"}],"platforms":["iOS"]}]},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallKitManager~1userAccountDidForced(toLogout:)\/title","value":"userAccountDidForcedToLogout:"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"userAccountDidForcedToLogout:"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallKitManager~1userAccountDidForced(toLogout:)\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallKitManager\/title","op":"replace","value":"CallKitManager"},{"op":"replace","value":[{"text":"CallKitManager","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallKitManager\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallKitManager\/navigatorTitle","value":[{"kind":"identifier","text":"CallKitManager"}]}]}]}