{"sections":[],"identifier":{"url":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallErrorModule\/unknown","interfaceLanguage":"swift"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallErrorModule"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"paths":["\/documentation\/easecalluikit\/callerrormodule\/unknown"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/easecalluikit\/callerrormodule\/unknown"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"unknown","kind":"identifier"}]}],"kind":"declarations"}],"metadata":{"roleHeading":"Case","externalID":"c:@M@EaseCallUIKit@E@CallErrorModule@CallErrorModuleUnknown","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"unknown","kind":"identifier"}],"symbolKind":"case","navigatorTitle":[{"text":"CallErrorModuleUnknown","kind":"identifier"}],"modules":[{"name":"EaseCallUIKit"}],"role":"symbol","title":"CallErrorModule.unknown"},"references":{"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit":{"title":"EaseCallUIKit","type":"topic","url":"\/documentation\/easecalluikit","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit","abstract":[],"role":"collection","kind":"symbol"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallErrorModule/unknown":{"navigatorTitle":[{"text":"CallErrorModuleUnknown","kind":"identifier"}],"title":"CallErrorModule.unknown","abstract":[],"type":"topic","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallErrorModule\/unknown","url":"\/documentation\/easecalluikit\/callerrormodule\/unknown","role":"symbol","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"unknown"}]},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallErrorModule":{"abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallErrorModule","title":"CallErrorModule","role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CallErrorModule"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CallErrorModule"}],"url":"\/documentation\/easecalluikit\/callerrormodule","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Enumeration Case","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"CallErrorModuleUnknown"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"value":[{"text":"CallErrorModuleUnknown","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"identifier","text":"CallErrorModuleUnknown"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallErrorModule~1unknown\/title","value":"CallErrorModuleUnknown","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallErrorModule~1unknown\/fragments","value":[{"text":"CallErrorModuleUnknown","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallErrorModule\/title","op":"replace","value":"CallErrorModule"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallErrorModule\/fragments","value":[{"text":"CallErrorModule","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallErrorModule\/navigatorTitle","value":[{"text":"CallErrorModule","kind":"identifier"}],"op":"replace"}]}]}