{"identifier":{"url":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallFontTheme\/bodyExtraSmall","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallFontTheme"]]},"metadata":{"roleHeading":"Instance Property","externalID":"c:@M@EaseCallUIKit@objc(cs)CallFontTheme(py)bodyExtraSmall","role":"symbol","title":"bodyExtraSmall","modules":[{"name":"EaseCallUIKit"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"bodyExtraSmall"},{"kind":"text","text":": "},{"text":"UIFont","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIFont"}],"navigatorTitle":[{"kind":"identifier","text":"bodyExtraSmall"}],"symbolKind":"property"},"schemaVersion":{"patch":0,"minor":3,"major":0},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"bodyExtraSmall"},{"text":": ","kind":"text"},{"text":"UIFont","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIFont"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easecalluikit\/callfonttheme\/bodyextrasmall"]},{"paths":["\/documentation\/easecalluikit\/callfonttheme\/bodyextrasmall"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"references":{"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallFontTheme/bodyExtraSmall":{"navigatorTitle":[{"kind":"identifier","text":"bodyExtraSmall"}],"abstract":[],"kind":"symbol","role":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallFontTheme\/bodyExtraSmall","url":"\/documentation\/easecalluikit\/callfonttheme\/bodyextrasmall","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"bodyExtraSmall"},{"kind":"text","text":": "},{"text":"UIFont","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIFont"}],"title":"bodyExtraSmall"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit":{"title":"EaseCallUIKit","type":"topic","url":"\/documentation\/easecalluikit","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit","abstract":[],"role":"collection","kind":"symbol"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallFontTheme":{"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallFontTheme","kind":"symbol","role":"symbol","url":"\/documentation\/easecalluikit\/callfonttheme","navigatorTitle":[{"text":"CallFontTheme","kind":"identifier"}],"title":"CallFontTheme","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CallFontTheme","kind":"identifier"}],"abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"bodyExtraSmall"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"bodyExtraSmall","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"text":"strong","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIFont","kind":"typeIdentifier","text":"UIFont"},{"kind":"text","text":" * "},{"text":"bodyExtraSmall","kind":"identifier"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"value":"bodyExtraSmall","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallFontTheme~1bodyExtraSmall\/title"},{"value":[{"kind":"identifier","text":"bodyExtraSmall"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallFontTheme~1bodyExtraSmall\/fragments"},{"op":"replace","value":"CallFontTheme","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallFontTheme\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallFontTheme\/fragments","value":[{"kind":"identifier","text":"CallFontTheme"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallFontTheme\/navigatorTitle","value":[{"text":"CallFontTheme","kind":"identifier"}]}]}]}