{"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"modules":[{"name":"EaseCallUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"bodySmall"}],"symbolKind":"property","role":"symbol","title":"bodySmall","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"bodySmall"},{"text":": ","kind":"text"},{"text":"UIFont","preciseIdentifier":"c:objc(cs)UIFont","kind":"typeIdentifier"}],"roleHeading":"Instance Property","externalID":"c:@M@EaseCallUIKit@objc(cs)CallFontTheme(py)bodySmall"},"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallFontTheme"]]},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallFontTheme\/bodySmall"},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"bodySmall"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIFont","kind":"typeIdentifier","text":"UIFont"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easecalluikit\/callfonttheme\/bodysmall"]},{"paths":["\/documentation\/easecalluikit\/callfonttheme\/bodysmall"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallFontTheme":{"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallFontTheme","kind":"symbol","role":"symbol","url":"\/documentation\/easecalluikit\/callfonttheme","navigatorTitle":[{"text":"CallFontTheme","kind":"identifier"}],"title":"CallFontTheme","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CallFontTheme","kind":"identifier"}],"abstract":[]},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallFontTheme/bodySmall":{"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"bodySmall"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"UIFont","preciseIdentifier":"c:objc(cs)UIFont"}],"abstract":[],"role":"symbol","url":"\/documentation\/easecalluikit\/callfonttheme\/bodysmall","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallFontTheme\/bodySmall","title":"bodySmall","navigatorTitle":[{"kind":"identifier","text":"bodySmall"}],"type":"topic","kind":"symbol"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit":{"title":"EaseCallUIKit","type":"topic","url":"\/documentation\/easecalluikit","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit","abstract":[],"role":"collection","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"bodySmall"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"bodySmall"}]},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"text":"strong","kind":"keyword"},{"kind":"text","text":") "},{"preciseIdentifier":"c:objc(cs)UIFont","text":"UIFont","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"bodySmall"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallFontTheme\/title","value":"CallFontTheme"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallFontTheme\/fragments","op":"replace","value":[{"text":"CallFontTheme","kind":"identifier"}]},{"op":"replace","value":[{"kind":"identifier","text":"CallFontTheme"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallFontTheme\/navigatorTitle"},{"value":"bodySmall","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallFontTheme~1bodySmall\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallFontTheme~1bodySmall\/fragments","value":[{"text":"bodySmall","kind":"identifier"}]}]}]}