{"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallFontTheme"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"headlineLarge","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UIFont","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIFont"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallFontTheme\/headlineLarge"},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easecalluikit\/callfonttheme\/headlinelarge"]},{"paths":["\/documentation\/easecalluikit\/callfonttheme\/headlinelarge"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"role":"symbol","roleHeading":"Instance Property","title":"headlineLarge","modules":[{"name":"EaseCallUIKit"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"headlineLarge"},{"text":": ","kind":"text"},{"text":"UIFont","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIFont"}],"symbolKind":"property","navigatorTitle":[{"text":"headlineLarge","kind":"identifier"}],"externalID":"c:@M@EaseCallUIKit@objc(cs)CallFontTheme(py)headlineLarge"},"references":{"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallFontTheme/headlineLarge":{"navigatorTitle":[{"text":"headlineLarge","kind":"identifier"}],"abstract":[],"kind":"symbol","role":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallFontTheme\/headlineLarge","url":"\/documentation\/easecalluikit\/callfonttheme\/headlinelarge","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"headlineLarge","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIFont","kind":"typeIdentifier","text":"UIFont"}],"title":"headlineLarge"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallFontTheme":{"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallFontTheme","kind":"symbol","role":"symbol","url":"\/documentation\/easecalluikit\/callfonttheme","navigatorTitle":[{"text":"CallFontTheme","kind":"identifier"}],"title":"CallFontTheme","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CallFontTheme","kind":"identifier"}],"abstract":[]},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit":{"title":"EaseCallUIKit","type":"topic","url":"\/documentation\/easecalluikit","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit","abstract":[],"role":"collection","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"headlineLarge"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"value":[{"kind":"identifier","text":"headlineLarge"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"strong"},{"kind":"text","text":") "},{"preciseIdentifier":"c:objc(cs)UIFont","kind":"typeIdentifier","text":"UIFont"},{"kind":"text","text":" * "},{"text":"headlineLarge","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallFontTheme~1headlineLarge\/title","value":"headlineLarge"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallFontTheme~1headlineLarge\/fragments","value":[{"text":"headlineLarge","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallFontTheme\/title","value":"CallFontTheme"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallFontTheme\/fragments","op":"replace","value":[{"text":"CallFontTheme","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallFontTheme\/navigatorTitle","value":[{"text":"CallFontTheme","kind":"identifier"}],"op":"replace"}]}]}