{"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallFontTheme"]]},"sections":[],"variants":[{"paths":["\/documentation\/easecalluikit\/callfonttheme\/labelextrasmall"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easecalluikit\/callfonttheme\/labelextrasmall"]}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"labelExtraSmall"}],"role":"symbol","symbolKind":"property","title":"labelExtraSmall","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"labelExtraSmall","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIFont","kind":"typeIdentifier","text":"UIFont"}],"modules":[{"name":"EaseCallUIKit"}],"roleHeading":"Instance Property","externalID":"c:@M@EaseCallUIKit@objc(cs)CallFontTheme(py)labelExtraSmall"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"labelExtraSmall","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"UIFont","preciseIdentifier":"c:objc(cs)UIFont"}]}]}],"identifier":{"url":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallFontTheme\/labelExtraSmall","interfaceLanguage":"swift"},"references":{"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallFontTheme":{"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallFontTheme","kind":"symbol","role":"symbol","url":"\/documentation\/easecalluikit\/callfonttheme","navigatorTitle":[{"text":"CallFontTheme","kind":"identifier"}],"title":"CallFontTheme","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CallFontTheme","kind":"identifier"}],"abstract":[]},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallFontTheme/labelExtraSmall":{"navigatorTitle":[{"text":"labelExtraSmall","kind":"identifier"}],"abstract":[],"kind":"symbol","role":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallFontTheme\/labelExtraSmall","url":"\/documentation\/easecalluikit\/callfonttheme\/labelextrasmall","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"labelExtraSmall","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIFont","text":"UIFont"}],"title":"labelExtraSmall"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit":{"title":"EaseCallUIKit","type":"topic","url":"\/documentation\/easecalluikit","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit","abstract":[],"role":"collection","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"labelExtraSmall"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"labelExtraSmall","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"text":"strong","kind":"keyword"},{"text":") ","kind":"text"},{"text":"UIFont","preciseIdentifier":"c:objc(cs)UIFont","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"labelExtraSmall"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallFontTheme\/title","value":"CallFontTheme","op":"replace"},{"value":[{"kind":"identifier","text":"CallFontTheme"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallFontTheme\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallFontTheme\/navigatorTitle","value":[{"kind":"identifier","text":"CallFontTheme"}]},{"op":"replace","value":"labelExtraSmall","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallFontTheme~1labelExtraSmall\/title"},{"value":[{"kind":"identifier","text":"labelExtraSmall"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallFontTheme~1labelExtraSmall\/fragments","op":"replace"}]}]}