{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/MultiCallParticipantsController"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@"},{"kind":"attribute","text":"MainActor","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"kind":"keyword","text":"lazy"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"participantsList"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"UITableView","preciseIdentifier":"c:objc(cs)UITableView"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"text":" ","kind":"text"},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"platforms":["iOS"],"languages":["swift"]}]}],"identifier":{"url":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/MultiCallParticipantsController\/participantsList","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easecalluikit\/multicallparticipantscontroller\/participantslist"]}],"sections":[],"metadata":{"roleHeading":"Instance Property","symbolKind":"property","externalID":"s:13EaseCallUIKit05MultiB22ParticipantsControllerC16participantsListSo11UITableViewCvp","title":"participantsList","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"participantsList","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UITableView","text":"UITableView","kind":"typeIdentifier"}],"modules":[{"name":"EaseCallUIKit"}],"role":"symbol"},"references":{"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/MultiCallParticipantsController/participantsList":{"url":"\/documentation\/easecalluikit\/multicallparticipantscontroller\/participantslist","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"participantsList","kind":"identifier"},{"kind":"text","text":": "},{"text":"UITableView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UITableView"}],"kind":"symbol","role":"symbol","type":"topic","abstract":[],"title":"participantsList","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/MultiCallParticipantsController\/participantsList"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/MultiCallParticipantsController":{"url":"\/documentation\/easecalluikit\/multicallparticipantscontroller","role":"symbol","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/MultiCallParticipantsController","title":"MultiCallParticipantsController","navigatorTitle":[{"text":"MultiCallParticipantsController","kind":"identifier"}],"type":"topic","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MultiCallParticipantsController","kind":"identifier"}],"kind":"symbol"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit":{"title":"EaseCallUIKit","type":"topic","url":"\/documentation\/easecalluikit","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit","abstract":[],"role":"collection","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"MultiCallParticipantsController","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1MultiCallParticipantsController\/title"},{"value":[{"text":"MultiCallParticipantsController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1MultiCallParticipantsController\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1MultiCallParticipantsController\/navigatorTitle","value":[{"kind":"identifier","text":"MultiCallParticipantsController"}],"op":"replace"}]}]}