{"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"modules":[{"name":"EaseCallUIKit"}],"roleHeading":"Instance Method","extendedModule":"EaseCallUIKit","symbolKind":"method","title":"tableView(_:willDisplay:forRowAt:)","externalID":"c:@CM@EaseCallUIKit@objc(cs)MultiCallParticipantsController(im)tableView:willDisplayCell:forRowAtIndexPath:","role":"symbol","navigatorTitle":[{"text":"tableView:willDisplayCell:forRowAtIndexPath:","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"tableView","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UITableView","preciseIdentifier":"c:objc(cs)UITableView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"willDisplay"},{"text":": ","kind":"text"},{"text":"UITableViewCell","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UITableViewCell"},{"text":", ","kind":"text"},{"text":"forRowAt","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"IndexPath","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation9IndexPathV"},{"kind":"text","text":")"}]},"abstract":[{"type":"text","text":"Inherited from "},{"code":"UITableViewDelegate.tableView(_:willDisplay:forRowAt:)","type":"codeVoice"},{"text":".","type":"text"}],"variants":[{"paths":["\/documentation\/easecalluikit\/multicallparticipantscontroller\/tableview(_:willdisplay:forrowat:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/easecalluikit\/multicallparticipantscontroller\/tableview(_:willdisplay:forrowat:)"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","preciseIdentifier":"s:ScM","kind":"attribute"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"tableView","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"tableView"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"UITableView","preciseIdentifier":"c:objc(cs)UITableView"},{"text":", ","kind":"text"},{"text":"willDisplay","kind":"externalParam"},{"kind":"text","text":" "},{"text":"cell","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"UITableViewCell","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UITableViewCell"},{"text":", ","kind":"text"},{"text":"forRowAt","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"indexPath"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation9IndexPathV","text":"IndexPath"},{"text":")","kind":"text"}],"platforms":["iOS"]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/MultiCallParticipantsController\/tableView(_:willDisplay:forRowAt:)"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/MultiCallParticipantsController","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/MultiCallParticipantsController\/UITableViewDelegate-Implementations"]]},"sections":[],"references":{"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/MultiCallParticipantsController/UITableViewDelegate-Implementations":{"kind":"article","title":"UITableViewDelegate Implementations","type":"topic","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/MultiCallParticipantsController\/UITableViewDelegate-Implementations","url":"\/documentation\/easecalluikit\/multicallparticipantscontroller\/uitableviewdelegate-implementations","role":"collectionGroup","abstract":[]},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/MultiCallParticipantsController":{"url":"\/documentation\/easecalluikit\/multicallparticipantscontroller","role":"symbol","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/MultiCallParticipantsController","title":"MultiCallParticipantsController","navigatorTitle":[{"text":"MultiCallParticipantsController","kind":"identifier"}],"type":"topic","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MultiCallParticipantsController","kind":"identifier"}],"kind":"symbol"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/MultiCallParticipantsController/tableView(_:willDisplay:forRowAt:)":{"navigatorTitle":[{"text":"tableView:willDisplayCell:forRowAtIndexPath:","kind":"identifier"}],"abstract":[],"url":"\/documentation\/easecalluikit\/multicallparticipantscontroller\/tableview(_:willdisplay:forrowat:)","kind":"symbol","title":"tableView(_:willDisplay:forRowAt:)","type":"topic","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/MultiCallParticipantsController\/tableView(_:willDisplay:forRowAt:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"tableView","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)UITableView","text":"UITableView","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"willDisplay"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UITableViewCell","text":"UITableViewCell","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"forRowAt","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation9IndexPathV","kind":"typeIdentifier","text":"IndexPath"},{"text":")","kind":"text"}]},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit":{"title":"EaseCallUIKit","type":"topic","url":"\/documentation\/easecalluikit","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit","abstract":[],"role":"collection","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"value":"tableView:willDisplayCell:forRowAtIndexPath:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"tableView:willDisplayCell:forRowAtIndexPath:","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"text":"tableView:","kind":"identifier"},{"kind":"text","text":"("},{"text":"UITableView","preciseIdentifier":"c:objc(cs)UITableView","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"tableView"},{"kind":"text","text":" "},{"text":"willDisplayCell:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UITableViewCell","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UITableViewCell"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"cell"},{"text":" ","kind":"text"},{"text":"forRowAtIndexPath:","kind":"identifier"},{"kind":"text","text":"("},{"text":"NSIndexPath","preciseIdentifier":"c:objc(cs)NSIndexPath","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"indexPath"},{"kind":"text","text":";"}]}]}},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1MultiCallParticipantsController\/title","value":"MultiCallParticipantsController","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1MultiCallParticipantsController\/fragments","value":[{"text":"MultiCallParticipantsController","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1MultiCallParticipantsController\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"MultiCallParticipantsController"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1MultiCallParticipantsController~1tableView(_:willDisplay:forRowAt:)\/title","value":"tableView:willDisplayCell:forRowAtIndexPath:"},{"value":[{"text":"- ","kind":"text"},{"text":"tableView:willDisplayCell:forRowAtIndexPath:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1MultiCallParticipantsController~1tableView(_:willDisplay:forRowAt:)\/fragments","op":"replace"}]}]}