{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/MultiCallParticipantsController\/tableView(_:numberOfRowsInSection:)"},"metadata":{"externalID":"c:@CM@EaseCallUIKit@objc(cs)MultiCallParticipantsController(im)tableView:numberOfRowsInSection:","role":"symbol","modules":[{"name":"EaseCallUIKit"}],"symbolKind":"method","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"tableView","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)UITableView","text":"UITableView","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"numberOfRowsInSection","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"}],"navigatorTitle":[{"kind":"identifier","text":"tableView:numberOfRowsInSection:"}],"title":"tableView(_:numberOfRowsInSection:)","extendedModule":"EaseCallUIKit"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/MultiCallParticipantsController","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/MultiCallParticipantsController\/UITableViewDataSource-Implementations"]]},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@"},{"preciseIdentifier":"s:ScM","text":"MainActor","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"tableView","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"text":"tableView","kind":"internalParam"},{"kind":"text","text":": "},{"text":"UITableView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UITableView"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"numberOfRowsInSection"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"section"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"paths":["\/documentation\/easecalluikit\/multicallparticipantscontroller\/tableview(_:numberofrowsinsection:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easecalluikit\/multicallparticipantscontroller\/tableview(_:numberofrowsinsection:)"]}],"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"UITableViewDataSource.tableView(_:numberOfRowsInSection:)"},{"type":"text","text":"."}],"references":{"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/MultiCallParticipantsController":{"url":"\/documentation\/easecalluikit\/multicallparticipantscontroller","role":"symbol","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/MultiCallParticipantsController","title":"MultiCallParticipantsController","navigatorTitle":[{"text":"MultiCallParticipantsController","kind":"identifier"}],"type":"topic","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MultiCallParticipantsController","kind":"identifier"}],"kind":"symbol"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/MultiCallParticipantsController/UITableViewDataSource-Implementations":{"abstract":[],"kind":"article","title":"UITableViewDataSource Implementations","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/MultiCallParticipantsController\/UITableViewDataSource-Implementations","url":"\/documentation\/easecalluikit\/multicallparticipantscontroller\/uitableviewdatasource-implementations","role":"collectionGroup","type":"topic"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit":{"title":"EaseCallUIKit","type":"topic","url":"\/documentation\/easecalluikit","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit","abstract":[],"role":"collection","kind":"symbol"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/MultiCallParticipantsController/tableView(_:numberOfRowsInSection:)":{"navigatorTitle":[{"text":"tableView:numberOfRowsInSection:","kind":"identifier"}],"title":"tableView(_:numberOfRowsInSection:)","abstract":[],"type":"topic","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/MultiCallParticipantsController\/tableView(_:numberOfRowsInSection:)","url":"\/documentation\/easecalluikit\/multicallparticipantscontroller\/tableview(_:numberofrowsinsection:)","role":"symbol","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"tableView","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"UITableView","preciseIdentifier":"c:objc(cs)UITableView"},{"kind":"text","text":", "},{"text":"numberOfRowsInSection","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":") -> "},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"}]}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"tableView:numberOfRowsInSection:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"tableView:numberOfRowsInSection:"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"text":") ","kind":"text"},{"text":"tableView:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)UITableView","text":"UITableView","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"tableView"},{"kind":"text","text":" "},{"text":"numberOfRowsInSection:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"section"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1MultiCallParticipantsController\/title","op":"replace","value":"MultiCallParticipantsController"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1MultiCallParticipantsController\/fragments","value":[{"text":"MultiCallParticipantsController","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1MultiCallParticipantsController\/navigatorTitle","value":[{"text":"MultiCallParticipantsController","kind":"identifier"}]},{"value":"tableView:numberOfRowsInSection:","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1MultiCallParticipantsController~1tableView(_:numberOfRowsInSection:)\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1MultiCallParticipantsController~1tableView(_:numberOfRowsInSection:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"tableView:numberOfRowsInSection:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}