{"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/MultiCallParticipantsController"]]},"variants":[{"paths":["\/documentation\/easecalluikit\/multicallparticipantscontroller\/uitableviewdelegate-implementations"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/easecalluikit\/multicallparticipantscontroller\/uitableviewdelegate-implementations"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"article","topicSections":[{"generated":true,"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/MultiCallParticipantsController\/tableView(_:didSelectRowAt:)","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/MultiCallParticipantsController\/tableView(_:willDisplay:forRowAt:)"],"anchor":"Instance-Methods"}],"metadata":{"title":"UITableViewDelegate Implementations","roleHeading":"API Collection","modules":[{"name":"EaseCallUIKit"}],"role":"collectionGroup"},"identifier":{"url":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/MultiCallParticipantsController\/UITableViewDelegate-Implementations","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/MultiCallParticipantsController":{"url":"\/documentation\/easecalluikit\/multicallparticipantscontroller","role":"symbol","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/MultiCallParticipantsController","title":"MultiCallParticipantsController","navigatorTitle":[{"text":"MultiCallParticipantsController","kind":"identifier"}],"type":"topic","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MultiCallParticipantsController","kind":"identifier"}],"kind":"symbol"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/MultiCallParticipantsController/tableView(_:didSelectRowAt:)":{"title":"tableView(_:didSelectRowAt:)","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"tableView:didSelectRowAtIndexPath:"}],"url":"\/documentation\/easecalluikit\/multicallparticipantscontroller\/tableview(_:didselectrowat:)","role":"symbol","type":"topic","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"tableView"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)UITableView","text":"UITableView","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didSelectRowAt"},{"kind":"text","text":": "},{"text":"IndexPath","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation9IndexPathV"},{"text":")","kind":"text"}],"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/MultiCallParticipantsController\/tableView(_:didSelectRowAt:)"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit":{"title":"EaseCallUIKit","type":"topic","url":"\/documentation\/easecalluikit","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit","abstract":[],"role":"collection","kind":"symbol"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/MultiCallParticipantsController/tableView(_:willDisplay:forRowAt:)":{"navigatorTitle":[{"text":"tableView:willDisplayCell:forRowAtIndexPath:","kind":"identifier"}],"abstract":[],"url":"\/documentation\/easecalluikit\/multicallparticipantscontroller\/tableview(_:willdisplay:forrowat:)","kind":"symbol","title":"tableView(_:willDisplay:forRowAt:)","type":"topic","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/MultiCallParticipantsController\/tableView(_:willDisplay:forRowAt:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"tableView","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)UITableView","text":"UITableView","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"willDisplay"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UITableViewCell","text":"UITableViewCell","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"forRowAt","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation9IndexPathV","kind":"typeIdentifier","text":"IndexPath"},{"text":")","kind":"text"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/topicSections","value":[{"title":"Instance Methods","generated":true,"anchor":"Instance-Methods","identifiers":["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/MultiCallParticipantsController\/tableView(_:didSelectRowAt:)","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/MultiCallParticipantsController\/tableView(_:willDisplay:forRowAt:)"]}],"op":"replace"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":"MultiCallParticipantsController","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1MultiCallParticipantsController\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1MultiCallParticipantsController\/fragments","value":[{"text":"MultiCallParticipantsController","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1MultiCallParticipantsController\/navigatorTitle","value":[{"kind":"identifier","text":"MultiCallParticipantsController"}]},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1MultiCallParticipantsController~1tableView(_:didSelectRowAt:)\/title","op":"replace","value":"tableView:didSelectRowAtIndexPath:"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1MultiCallParticipantsController~1tableView(_:didSelectRowAt:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"tableView:didSelectRowAtIndexPath:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1MultiCallParticipantsController~1tableView(_:willDisplay:forRowAt:)\/title","value":"tableView:willDisplayCell:forRowAtIndexPath:"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"tableView:willDisplayCell:forRowAtIndexPath:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1MultiCallParticipantsController~1tableView(_:willDisplay:forRowAt:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}