{"identifier":{"url":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallUserProfileProvider\/fetchGroupProfiles(profileIds:)","interfaceLanguage":"swift"},"metadata":{"roleHeading":"Instance Method","externalID":"s:13EaseCallUIKit0B19UserProfileProviderP18fetchGroupProfiles10profileIdsSayAA0bE8Protocol_pGSaySSG_tYaF","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"fetchGroupProfiles","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"profileIds"},{"kind":"text","text":": ["},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"]) "},{"text":"async","kind":"keyword"},{"kind":"text","text":" -> ["},{"preciseIdentifier":"c:@M@EaseCallUIKit@objc(pl)CallProfileProtocol","text":"CallProfileProtocol","kind":"typeIdentifier"},{"kind":"text","text":"]"}],"symbolKind":"method","required":true,"role":"symbol","title":"fetchGroupProfiles(profileIds:)","modules":[{"name":"EaseCallUIKit"}]},"schemaVersion":{"patch":0,"minor":3,"major":0},"sections":[],"kind":"symbol","abstract":[{"text":"Coroutine obtains group information asynchronously.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"fetchGroupProfiles"},{"kind":"text","text":"("},{"text":"profileIds","kind":"externalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"]) ","kind":"text"},{"kind":"keyword","text":"async"},{"text":" -> [","kind":"text"},{"text":"CallProfileProtocol","preciseIdentifier":"c:@M@EaseCallUIKit@objc(pl)CallProfileProtocol","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallProfileProtocol"},{"kind":"text","text":"]"}],"platforms":["iOS"],"languages":["swift"]}]},{"parameters":[{"name":"profileIds","content":[{"inlineContent":[{"text":"The corresponding group id string array.","type":"text"}],"type":"paragraph"}]}],"kind":"parameters"},{"content":[{"type":"heading","text":"Return Value","anchor":"return-value","level":2},{"inlineContent":[{"type":"text","text":"Array of the conform"},{"code":"ChatUserProfileProtocol","type":"codeVoice"},{"type":"text","text":" object."}],"type":"paragraph"}],"kind":"content"}],"variants":[{"paths":["\/documentation\/easecalluikit\/calluserprofileprovider\/fetchgroupprofiles(profileids:)"],"traits":[{"interfaceLanguage":"swift"}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallUserProfileProvider"]]},"references":{"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallUserProfileProvider/fetchGroupProfiles(profileIds:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"fetchGroupProfiles","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"profileIds"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"]) ","kind":"text"},{"kind":"keyword","text":"async"},{"kind":"text","text":" -> ["},{"text":"CallProfileProtocol","kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseCallUIKit@objc(pl)CallProfileProtocol"},{"text":"]","kind":"text"}],"abstract":[{"type":"text","text":"Coroutine obtains group information asynchronously."}],"required":true,"kind":"symbol","type":"topic","title":"fetchGroupProfiles(profileIds:)","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallUserProfileProvider\/fetchGroupProfiles(profileIds:)","role":"symbol","url":"\/documentation\/easecalluikit\/calluserprofileprovider\/fetchgroupprofiles(profileids:)"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit":{"title":"EaseCallUIKit","type":"topic","url":"\/documentation\/easecalluikit","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit","abstract":[],"role":"collection","kind":"symbol"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallUserProfileProvider":{"kind":"symbol","title":"CallUserProfileProvider","navigatorTitle":[{"text":"CallUserProfileProvider","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallUserProfileProvider","url":"\/documentation\/easecalluikit\/calluserprofileprovider","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"CallUserProfileProvider","kind":"identifier"}],"abstract":[{"text":"Profile provider of the ChatUIKit.Only available in Swift language.","type":"text"}]},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallProfileProtocol":{"url":"\/documentation\/easecalluikit\/callprofileprotocol","role":"symbol","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallProfileProtocol","navigatorTitle":[{"kind":"identifier","text":"CallProfileProtocol"}],"abstract":[],"title":"CallProfileProtocol","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CallProfileProtocol"}]}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallProfileProtocol\/title","value":"CallProfileProtocol","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallProfileProtocol\/fragments","value":[{"text":"CallProfileProtocol","kind":"identifier"}],"op":"replace"},{"value":[{"text":"CallProfileProtocol","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallProfileProtocol\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}