{"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/Call1v1AudioViewController\/bottomView"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easecalluikit\/call1v1audioviewcontroller\/bottomview"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"text":"lazy","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"bottomView"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@EaseCallUIKit@objc(cs)Call1v1BottomView","text":"Call1v1BottomView","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/Call1v1BottomView","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"text":" }","kind":"text"}]}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/Call1v1AudioViewController"]]},"metadata":{"externalID":"s:13EaseCallUIKit26Call1v1AudioViewControllerC06bottomF0AA0d6BottomF0Cvp","symbolKind":"property","role":"symbol","roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"bottomView","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@EaseCallUIKit@objc(cs)Call1v1BottomView","text":"Call1v1BottomView","kind":"typeIdentifier"}],"title":"bottomView","modules":[{"name":"EaseCallUIKit"}]},"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/Call1v1AudioViewController":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Call1v1AudioViewController"}],"navigatorTitle":[{"kind":"identifier","text":"Call1v1AudioViewController"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/Call1v1AudioViewController","title":"Call1v1AudioViewController","type":"topic","role":"symbol","abstract":[],"url":"\/documentation\/easecalluikit\/call1v1audioviewcontroller"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit":{"title":"EaseCallUIKit","type":"topic","url":"\/documentation\/easecalluikit","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit","abstract":[],"role":"collection","kind":"symbol"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/Call1v1AudioViewController/bottomView":{"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/Call1v1AudioViewController\/bottomView","url":"\/documentation\/easecalluikit\/call1v1audioviewcontroller\/bottomview","type":"topic","abstract":[],"kind":"symbol","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"bottomView","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Call1v1BottomView","kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseCallUIKit@objc(cs)Call1v1BottomView"}],"title":"bottomView"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/Call1v1BottomView":{"navigatorTitle":[{"text":"Call1v1BottomView","kind":"identifier"}],"abstract":[],"kind":"symbol","role":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/Call1v1BottomView","url":"\/documentation\/easecalluikit\/call1v1bottomview","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Call1v1BottomView"}],"title":"Call1v1BottomView"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"Call1v1AudioViewController","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1Call1v1AudioViewController\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1Call1v1AudioViewController\/fragments","value":[{"text":"Call1v1AudioViewController","kind":"identifier"}],"op":"replace"},{"value":[{"text":"Call1v1AudioViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1Call1v1AudioViewController\/navigatorTitle","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1Call1v1BottomView\/title","value":"Call1v1BottomView"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1Call1v1BottomView\/fragments","op":"replace","value":[{"kind":"identifier","text":"Call1v1BottomView"}]},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1Call1v1BottomView\/navigatorTitle","value":[{"kind":"identifier","text":"Call1v1BottomView"}],"op":"replace"}]}]}