{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/Call1v1AudioViewController"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easecalluikit\/call1v1audioviewcontroller\/init(role:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easecalluikit\/call1v1audioviewcontroller\/init(role:)"]}],"sections":[],"metadata":{"roleHeading":"Initializer","externalID":"c:@M@EaseCallUIKit@objc(cs)Call1v1AudioViewController(im)initWithRole:","role":"symbol","modules":[{"name":"EaseCallUIKit"}],"title":"init(role:)","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"text":"role","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"CallRole","preciseIdentifier":"c:@M@EaseCallUIKit@E@CallRole"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"initWithRole:","kind":"identifier"}],"symbolKind":"init"},"identifier":{"url":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/Call1v1AudioViewController\/init(role:)","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"attribute","text":"@"},{"preciseIdentifier":"s:ScM","kind":"attribute","text":"MainActor"},{"kind":"text","text":" "},{"text":"init","kind":"keyword"},{"kind":"text","text":"("},{"kind":"externalParam","text":"role"},{"kind":"text","text":": "},{"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallRole","kind":"typeIdentifier","text":"CallRole","preciseIdentifier":"c:@M@EaseCallUIKit@E@CallRole"},{"kind":"text","text":")"}]}]}],"references":{"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/Call1v1AudioViewController":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Call1v1AudioViewController"}],"navigatorTitle":[{"kind":"identifier","text":"Call1v1AudioViewController"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/Call1v1AudioViewController","title":"Call1v1AudioViewController","type":"topic","role":"symbol","abstract":[],"url":"\/documentation\/easecalluikit\/call1v1audioviewcontroller"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/Call1v1AudioViewController/init(role:)":{"navigatorTitle":[{"text":"initWithRole:","kind":"identifier"}],"url":"\/documentation\/easecalluikit\/call1v1audioviewcontroller\/init(role:)","kind":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"role"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseCallUIKit@E@CallRole","text":"CallRole"},{"kind":"text","text":")"}],"title":"init(role:)","abstract":[],"type":"topic","role":"symbol","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/Call1v1AudioViewController\/init(role:)"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallRole":{"url":"\/documentation\/easecalluikit\/callrole","role":"symbol","title":"CallRole","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallRole","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"CallRole"}],"navigatorTitle":[{"text":"CallRole","kind":"identifier"}],"type":"topic"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit":{"title":"EaseCallUIKit","type":"topic","url":"\/documentation\/easecalluikit","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit","abstract":[],"role":"collection","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","value":"initWithRole:","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"initWithRole:","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"id","preciseIdentifier":"c:*Qo","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"initWithRole:","kind":"identifier"},{"kind":"text","text":"("},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:@M@EaseCallUIKit@E@CallRole","text":"CallRole","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallRole"},{"kind":"text","text":") "},{"text":"role","kind":"internalParam"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace"},{"op":"replace","value":"Call1v1AudioViewController","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1Call1v1AudioViewController\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1Call1v1AudioViewController\/fragments","value":[{"kind":"identifier","text":"Call1v1AudioViewController"}]},{"value":[{"text":"Call1v1AudioViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1Call1v1AudioViewController\/navigatorTitle","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1Call1v1AudioViewController~1init(role:)\/title","value":"initWithRole:","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1Call1v1AudioViewController~1init(role:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"initWithRole:","kind":"identifier"}],"op":"replace"},{"value":"CallRole","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallRole\/title","op":"replace"},{"value":[{"text":"CallRole","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallRole\/fragments","op":"replace"},{"value":[{"text":"CallRole","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallRole\/navigatorTitle"}]}]}