{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/Call1v1AudioViewController\/TimerServiceListener-Implementations"},"variants":[{"paths":["\/documentation\/easecalluikit\/call1v1audioviewcontroller\/timerservicelistener-implementations"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/easecalluikit\/call1v1audioviewcontroller\/timerservicelistener-implementations"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"modules":[{"name":"EaseCallUIKit"}],"role":"collectionGroup","title":"TimerServiceListener Implementations","roleHeading":"API Collection"},"kind":"article","hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/Call1v1AudioViewController"]]},"topicSections":[{"generated":true,"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/Call1v1AudioViewController\/timeChanged(_:interval:)"],"anchor":"Instance-Methods"}],"references":{"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit":{"title":"EaseCallUIKit","type":"topic","url":"\/documentation\/easecalluikit","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit","abstract":[],"role":"collection","kind":"symbol"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/Call1v1AudioViewController":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Call1v1AudioViewController"}],"navigatorTitle":[{"kind":"identifier","text":"Call1v1AudioViewController"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/Call1v1AudioViewController","title":"Call1v1AudioViewController","type":"topic","role":"symbol","abstract":[],"url":"\/documentation\/easecalluikit\/call1v1audioviewcontroller"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/Call1v1AudioViewController/timeChanged(_:interval:)":{"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/Call1v1AudioViewController\/timeChanged(_:interval:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"timeChanged","kind":"identifier"},{"text":"(","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"interval"},{"text":": ","kind":"text"},{"text":"UInt","kind":"typeIdentifier","preciseIdentifier":"s:Su"},{"text":")","kind":"text"}],"abstract":[{"text":"Called when the time interval for a timer changes.","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"timeChanged:interval:","kind":"identifier"}],"kind":"symbol","type":"topic","title":"timeChanged(_:interval:)","url":"\/documentation\/easecalluikit\/call1v1audioviewcontroller\/timechanged(_:interval:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":[{"anchor":"Instance-Methods","title":"Instance Methods","generated":true,"identifiers":["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/Call1v1AudioViewController\/timeChanged(_:interval:)"]}],"op":"replace","path":"\/topicSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":"Call1v1AudioViewController","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1Call1v1AudioViewController\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1Call1v1AudioViewController\/fragments","op":"replace","value":[{"kind":"identifier","text":"Call1v1AudioViewController"}]},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1Call1v1AudioViewController\/navigatorTitle","value":[{"text":"Call1v1AudioViewController","kind":"identifier"}],"op":"replace"},{"value":"timeChanged:interval:","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1Call1v1AudioViewController~1timeChanged(_:interval:)\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1Call1v1AudioViewController~1timeChanged(_:interval:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"timeChanged:interval:","kind":"identifier"}]}]}]}