{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/GlobalTimerManager","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/GlobalTimerManager\/TimerService-Implementations"]]},"metadata":{"extendedModule":"EaseCallUIKit","externalID":"c:@CM@EaseCallUIKit@objc(cs)GlobalTimerManager(im)removeListener:timerIdentify:","role":"symbol","symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"removeListener:timerIdentify:"}],"title":"removeListener(_:timerIdentify:)","modules":[{"name":"EaseCallUIKit"}],"roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"removeListener"},{"kind":"text","text":"("},{"kind":"keyword","text":"any"},{"text":" ","kind":"text"},{"text":"TimerServiceListener","preciseIdentifier":"c:@M@EaseCallUIKit@objc(pl)TimerServiceListener","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"timerIdentify"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}]},"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/GlobalTimerManager\/removeListener(_:timerIdentify:)"},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easecalluikit\/globaltimermanager\/removelistener(_:timeridentify:)"]},{"paths":["\/documentation\/easecalluikit\/globaltimermanager\/removelistener(_:timeridentify:)"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"removeListener"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"text":"listener","kind":"internalParam"},{"kind":"text","text":": "},{"kind":"keyword","text":"any"},{"text":" ","kind":"text"},{"text":"TimerServiceListener","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/TimerServiceListener","preciseIdentifier":"c:@M@EaseCallUIKit@objc(pl)TimerServiceListener","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"timerIdentify","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"An object conforming to the "},{"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/TimerServiceListener","type":"reference","isActive":true},{"text":" protocol that will no longer receive timer events.","type":"text"}]}],"name":"listener"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"A unique identifier for the timer, used to distinguish between different timers."}]}],"name":"timerIdentify"}]}],"abstract":[{"text":"Removes a previously added listener from receiving timer-related events.","type":"text"}],"references":{"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/GlobalTimerManager/TimerService-Implementations":{"url":"\/documentation\/easecalluikit\/globaltimermanager\/timerservice-implementations","kind":"article","role":"collectionGroup","abstract":[],"type":"topic","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/GlobalTimerManager\/TimerService-Implementations","title":"TimerService Implementations"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/GlobalTimerManager/removeListener(_:timerIdentify:)":{"navigatorTitle":[{"text":"removeListener:timerIdentify:","kind":"identifier"}],"abstract":[{"text":"Removes a previously added listener from receiving timer-related events.","type":"text"}],"kind":"symbol","role":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/GlobalTimerManager\/removeListener(_:timerIdentify:)","url":"\/documentation\/easecalluikit\/globaltimermanager\/removelistener(_:timeridentify:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"removeListener","kind":"identifier"},{"text":"(","kind":"text"},{"text":"any","kind":"keyword"},{"kind":"text","text":" "},{"preciseIdentifier":"c:@M@EaseCallUIKit@objc(pl)TimerServiceListener","kind":"typeIdentifier","text":"TimerServiceListener"},{"text":", ","kind":"text"},{"text":"timerIdentify","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":")","kind":"text"}],"title":"removeListener(_:timerIdentify:)"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit":{"title":"EaseCallUIKit","type":"topic","url":"\/documentation\/easecalluikit","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit","abstract":[],"role":"collection","kind":"symbol"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/GlobalTimerManager":{"kind":"symbol","title":"GlobalTimerManager","navigatorTitle":[{"text":"GlobalTimerManager","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/GlobalTimerManager","url":"\/documentation\/easecalluikit\/globaltimermanager","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GlobalTimerManager"}],"abstract":[]},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/TimerServiceListener":{"url":"\/documentation\/easecalluikit\/timerservicelistener","kind":"symbol","role":"symbol","title":"TimerServiceListener","navigatorTitle":[{"text":"TimerServiceListener","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/TimerServiceListener","abstract":[],"type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"TimerServiceListener"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"path":"\/metadata\/title","value":"removeListener:timerIdentify:","op":"replace"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"removeListener:timerIdentify:"}],"path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"removeListener:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:Qo@M@EaseCallUIKit@objc(pl)TimerServiceListener","text":"id<TimerServiceListener>"},{"text":") ","kind":"text"},{"text":"listener","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"timerIdentify:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"timerIdentify"},{"kind":"text","text":";"}]}],"kind":"declarations"}},{"value":"removeListener:timerIdentify:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1GlobalTimerManager~1removeListener(_:timerIdentify:)\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1GlobalTimerManager~1removeListener(_:timerIdentify:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"removeListener:timerIdentify:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1GlobalTimerManager\/title","value":"GlobalTimerManager","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1GlobalTimerManager\/fragments","value":[{"kind":"identifier","text":"GlobalTimerManager"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1GlobalTimerManager\/navigatorTitle","value":[{"text":"GlobalTimerManager","kind":"identifier"}]},{"value":"TimerServiceListener","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1TimerServiceListener\/title"},{"value":[{"kind":"identifier","text":"TimerServiceListener"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1TimerServiceListener\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1TimerServiceListener\/navigatorTitle","value":[{"kind":"identifier","text":"TimerServiceListener"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}