{"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"replaceTimer"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"text":"listener","kind":"internalParam"},{"kind":"text","text":": "},{"text":"any","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseCallUIKit@objc(pl)TimerServiceListener","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/TimerServiceListener","text":"TimerServiceListener"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"timerIdentify"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"listener","content":[{"inlineContent":[{"type":"text","text":"An object conforming to the "},{"isActive":true,"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/TimerServiceListener","type":"reference"},{"text":" protocol that will receive timer events.","type":"text"}],"type":"paragraph"}]},{"name":"timerIdentify","content":[{"type":"paragraph","inlineContent":[{"text":"A unique identifier for the timer, used to distinguish between different timers.","type":"text"}]}]}]}],"kind":"symbol","metadata":{"extendedModule":"EaseCallUIKit","title":"replaceTimer(_:timerIdentify:)","roleHeading":"Instance Method","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"replaceTimer"},{"kind":"text","text":"("},{"text":"any","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:@M@EaseCallUIKit@objc(pl)TimerServiceListener","kind":"typeIdentifier","text":"TimerServiceListener"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"timerIdentify"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"replaceTimer:timerIdentify:"}],"externalID":"c:@CM@EaseCallUIKit@objc(cs)GlobalTimerManager(im)replaceTimer:timerIdentify:","symbolKind":"method","modules":[{"name":"EaseCallUIKit"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/GlobalTimerManager","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/GlobalTimerManager\/TimerService-Implementations"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/GlobalTimerManager\/replaceTimer(_:timerIdentify:)"},"variants":[{"paths":["\/documentation\/easecalluikit\/globaltimermanager\/replacetimer(_:timeridentify:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easecalluikit\/globaltimermanager\/replacetimer(_:timeridentify:)"]}],"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"abstract":[{"type":"text","text":"Replaces an existing timer with a new one."}],"references":{"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/GlobalTimerManager/TimerService-Implementations":{"url":"\/documentation\/easecalluikit\/globaltimermanager\/timerservice-implementations","kind":"article","role":"collectionGroup","abstract":[],"type":"topic","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/GlobalTimerManager\/TimerService-Implementations","title":"TimerService Implementations"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/GlobalTimerManager":{"kind":"symbol","title":"GlobalTimerManager","navigatorTitle":[{"text":"GlobalTimerManager","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/GlobalTimerManager","url":"\/documentation\/easecalluikit\/globaltimermanager","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GlobalTimerManager"}],"abstract":[]},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/TimerServiceListener":{"url":"\/documentation\/easecalluikit\/timerservicelistener","kind":"symbol","role":"symbol","title":"TimerServiceListener","navigatorTitle":[{"text":"TimerServiceListener","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/TimerServiceListener","abstract":[],"type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"TimerServiceListener"}]},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit":{"title":"EaseCallUIKit","type":"topic","url":"\/documentation\/easecalluikit","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit","abstract":[],"role":"collection","kind":"symbol"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/GlobalTimerManager/replaceTimer(_:timerIdentify:)":{"abstract":[{"text":"Replaces an existing timer with a new one.","type":"text"}],"title":"replaceTimer(_:timerIdentify:)","url":"\/documentation\/easecalluikit\/globaltimermanager\/replacetimer(_:timeridentify:)","type":"topic","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/GlobalTimerManager\/replaceTimer(_:timerIdentify:)","navigatorTitle":[{"kind":"identifier","text":"replaceTimer:timerIdentify:"}],"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"replaceTimer"},{"kind":"text","text":"("},{"text":"any","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TimerServiceListener","kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseCallUIKit@objc(pl)TimerServiceListener"},{"text":", ","kind":"text"},{"text":"timerIdentify","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":")","kind":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"replaceTimer:timerIdentify:"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"replaceTimer:timerIdentify:","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"replaceTimer:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:Qo@M@EaseCallUIKit@objc(pl)TimerServiceListener","text":"id<TimerServiceListener>"},{"text":") ","kind":"text"},{"text":"listener","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"timerIdentify:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"timerIdentify"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1GlobalTimerManager\/title","value":"GlobalTimerManager"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1GlobalTimerManager\/fragments","op":"replace","value":[{"kind":"identifier","text":"GlobalTimerManager"}]},{"op":"replace","value":[{"text":"GlobalTimerManager","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1GlobalTimerManager\/navigatorTitle"},{"value":"TimerServiceListener","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1TimerServiceListener\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1TimerServiceListener\/fragments","value":[{"kind":"identifier","text":"TimerServiceListener"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1TimerServiceListener\/navigatorTitle","value":[{"text":"TimerServiceListener","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1GlobalTimerManager~1replaceTimer(_:timerIdentify:)\/title","op":"replace","value":"replaceTimer:timerIdentify:"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"replaceTimer:timerIdentify:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1GlobalTimerManager~1replaceTimer(_:timerIdentify:)\/fragments"}]}]}