{"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/GlobalTimerManager\/timerCache"},"kind":"symbol","abstract":[{"text":"Cache for timer start intervals with identify.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/GlobalTimerManager"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"timerCache"},{"kind":"text","text":": ["},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval"},{"text":"] { get }","kind":"text"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easecalluikit\/globaltimermanager\/timercache"]}],"metadata":{"modules":[{"name":"EaseCallUIKit"}],"symbolKind":"property","externalID":"s:13EaseCallUIKit18GlobalTimerManagerC10timerCacheSDySSSdGvp","title":"timerCache","roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"timerCache"},{"text":": [","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:@T@NSTimeInterval","kind":"typeIdentifier","text":"TimeInterval"},{"kind":"text","text":"]"}],"role":"symbol"},"references":{"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/GlobalTimerManager/timerCache":{"abstract":[{"type":"text","text":"Cache for timer start intervals with identify."}],"title":"timerCache","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/GlobalTimerManager\/timerCache","type":"topic","url":"\/documentation\/easecalluikit\/globaltimermanager\/timercache","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"timerCache","kind":"identifier"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"text":"TimeInterval","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval"},{"kind":"text","text":"]"}]},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/GlobalTimerManager":{"kind":"symbol","title":"GlobalTimerManager","navigatorTitle":[{"text":"GlobalTimerManager","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/GlobalTimerManager","url":"\/documentation\/easecalluikit\/globaltimermanager","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GlobalTimerManager"}],"abstract":[]},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit":{"title":"EaseCallUIKit","type":"topic","url":"\/documentation\/easecalluikit","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit","abstract":[],"role":"collection","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1GlobalTimerManager\/title","value":"GlobalTimerManager","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1GlobalTimerManager\/fragments","op":"replace","value":[{"kind":"identifier","text":"GlobalTimerManager"}]},{"value":[{"text":"GlobalTimerManager","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1GlobalTimerManager\/navigatorTitle","op":"replace"}]}]}