{"variants":[{"paths":["\/documentation\/easecalluikit\/globaltimermanager\/timerservice-implementations"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easecalluikit\/globaltimermanager\/timerservice-implementations"]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/GlobalTimerManager\/TimerService-Implementations"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/GlobalTimerManager"]]},"topicSections":[{"identifiers":["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/GlobalTimerManager\/registerListener(_:timerIdentify:)","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/GlobalTimerManager\/removeListener(_:timerIdentify:)","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/GlobalTimerManager\/replaceTimer(_:timerIdentify:)"],"title":"Instance Methods","generated":true,"anchor":"Instance-Methods"}],"kind":"article","metadata":{"title":"TimerService Implementations","roleHeading":"API Collection","modules":[{"name":"EaseCallUIKit"}],"role":"collectionGroup"},"sections":[],"references":{"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit":{"title":"EaseCallUIKit","type":"topic","url":"\/documentation\/easecalluikit","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit","abstract":[],"role":"collection","kind":"symbol"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/GlobalTimerManager/registerListener(_:timerIdentify:)":{"kind":"symbol","abstract":[{"text":"Adds a listener to receive timer-related events.","type":"text"}],"title":"registerListener(_:timerIdentify:)","type":"topic","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/GlobalTimerManager\/registerListener(_:timerIdentify:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"registerListener"},{"text":"(","kind":"text"},{"kind":"keyword","text":"any"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:@M@EaseCallUIKit@objc(pl)TimerServiceListener","text":"TimerServiceListener","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"timerIdentify","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"navigatorTitle":[{"text":"registerListener:timerIdentify:","kind":"identifier"}],"url":"\/documentation\/easecalluikit\/globaltimermanager\/registerlistener(_:timeridentify:)"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/GlobalTimerManager/removeListener(_:timerIdentify:)":{"navigatorTitle":[{"text":"removeListener:timerIdentify:","kind":"identifier"}],"abstract":[{"text":"Removes a previously added listener from receiving timer-related events.","type":"text"}],"kind":"symbol","role":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/GlobalTimerManager\/removeListener(_:timerIdentify:)","url":"\/documentation\/easecalluikit\/globaltimermanager\/removelistener(_:timeridentify:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"removeListener","kind":"identifier"},{"text":"(","kind":"text"},{"text":"any","kind":"keyword"},{"kind":"text","text":" "},{"preciseIdentifier":"c:@M@EaseCallUIKit@objc(pl)TimerServiceListener","kind":"typeIdentifier","text":"TimerServiceListener"},{"text":", ","kind":"text"},{"text":"timerIdentify","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":")","kind":"text"}],"title":"removeListener(_:timerIdentify:)"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/GlobalTimerManager/replaceTimer(_:timerIdentify:)":{"abstract":[{"text":"Replaces an existing timer with a new one.","type":"text"}],"title":"replaceTimer(_:timerIdentify:)","url":"\/documentation\/easecalluikit\/globaltimermanager\/replacetimer(_:timeridentify:)","type":"topic","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/GlobalTimerManager\/replaceTimer(_:timerIdentify:)","navigatorTitle":[{"kind":"identifier","text":"replaceTimer:timerIdentify:"}],"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"replaceTimer"},{"kind":"text","text":"("},{"text":"any","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TimerServiceListener","kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseCallUIKit@objc(pl)TimerServiceListener"},{"text":", ","kind":"text"},{"text":"timerIdentify","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/GlobalTimerManager":{"kind":"symbol","title":"GlobalTimerManager","navigatorTitle":[{"text":"GlobalTimerManager","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/GlobalTimerManager","url":"\/documentation\/easecalluikit\/globaltimermanager","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GlobalTimerManager"}],"abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":[{"title":"Instance Methods","generated":true,"identifiers":["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/GlobalTimerManager\/registerListener(_:timerIdentify:)","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/GlobalTimerManager\/removeListener(_:timerIdentify:)","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/GlobalTimerManager\/replaceTimer(_:timerIdentify:)"],"anchor":"Instance-Methods"}],"op":"replace","path":"\/topicSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":"registerListener:timerIdentify:","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1GlobalTimerManager~1registerListener(_:timerIdentify:)\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1GlobalTimerManager~1registerListener(_:timerIdentify:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"registerListener:timerIdentify:"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1GlobalTimerManager~1removeListener(_:timerIdentify:)\/title","value":"removeListener:timerIdentify:"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1GlobalTimerManager~1removeListener(_:timerIdentify:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"removeListener:timerIdentify:","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1GlobalTimerManager~1replaceTimer(_:timerIdentify:)\/title","value":"replaceTimer:timerIdentify:"},{"value":[{"kind":"text","text":"- "},{"text":"replaceTimer:timerIdentify:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1GlobalTimerManager~1replaceTimer(_:timerIdentify:)\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1GlobalTimerManager\/title","value":"GlobalTimerManager","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1GlobalTimerManager\/fragments","value":[{"kind":"identifier","text":"GlobalTimerManager"}]},{"op":"replace","value":[{"kind":"identifier","text":"GlobalTimerManager"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1GlobalTimerManager\/navigatorTitle"}]}]}