{"identifier":{"url":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallError\/CallErrorCodeGettable-Implementations","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallError"]]},"metadata":{"roleHeading":"API Collection","title":"CallErrorCodeGettable Implementations","role":"collectionGroup","modules":[{"name":"EaseCallUIKit"}]},"kind":"article","topicSections":[{"generated":true,"identifiers":["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallError\/getCallBusinessError()","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallError\/getIMError()","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallError\/getRTCError()"],"title":"Instance Methods","anchor":"Instance-Methods"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/easecalluikit\/callerror\/callerrorcodegettable-implementations"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easecalluikit\/callerror\/callerrorcodegettable-implementations"]}],"references":{"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallError":{"type":"topic","role":"symbol","title":"CallError","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"CallError","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"CallError"},{"type":"text","text":" class encapsulates errors that can occur in the call system, providing a structured way to handle errors from different modules such as IM, RTC, and business logic."}],"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallError","navigatorTitle":[{"kind":"identifier","text":"CallError"}],"url":"\/documentation\/easecalluikit\/callerror"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallError/getCallBusinessError()":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"getCallBusinessError"},{"text":"() -> ","kind":"text"},{"text":"CallBusinessErrorCode","preciseIdentifier":"c:@M@EaseCallUIKit@E@CallBusinessErrorCode","kind":"typeIdentifier"}],"kind":"symbol","abstract":[{"text":"Get error code from the business logic module.","type":"text"}],"url":"\/documentation\/easecalluikit\/callerror\/getcallbusinesserror()","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallError\/getCallBusinessError()","type":"topic","title":"getCallBusinessError()","navigatorTitle":[{"text":"getCallBusinessError","kind":"identifier"}],"role":"symbol"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallError/getRTCError()":{"type":"topic","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallError\/getRTCError()","abstract":[{"type":"text","text":"Get error code from the RTC module."}],"kind":"symbol","url":"\/documentation\/easecalluikit\/callerror\/getrtcerror()","title":"getRTCError()","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"getRTCError","kind":"identifier"},{"text":"() -> ","kind":"text"},{"kind":"typeIdentifier","text":"AgoraErrorCode","preciseIdentifier":"c:@E@AgoraErrorCode"}],"navigatorTitle":[{"text":"getRTCError","kind":"identifier"}]},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit":{"title":"EaseCallUIKit","type":"topic","url":"\/documentation\/easecalluikit","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit","abstract":[],"role":"collection","kind":"symbol"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallError/getIMError()":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"getIMError","kind":"identifier"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"s:13EaseCallUIKit13ChatErrorCodea","kind":"typeIdentifier","text":"ChatErrorCode"}],"kind":"symbol","abstract":[{"type":"text","text":"Get error code from the IM module."}],"url":"\/documentation\/easecalluikit\/callerror\/getimerror()","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallError\/getIMError()","type":"topic","title":"getIMError()","navigatorTitle":[{"text":"getIMError","kind":"identifier"}],"role":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":[{"anchor":"Instance-Methods","title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallError\/getCallBusinessError()","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallError\/getIMError()","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallError\/getRTCError()"],"generated":true}],"op":"replace","path":"\/topicSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":"CallError","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallError\/title"},{"op":"replace","value":[{"text":"CallError","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallError\/fragments"},{"value":[{"text":"CallError","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallError\/navigatorTitle"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallError~1getCallBusinessError()\/title","op":"replace","value":"getCallBusinessError"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"getCallBusinessError"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallError~1getCallBusinessError()\/fragments"},{"value":"getRTCError","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallError~1getRTCError()\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallError~1getRTCError()\/fragments","value":[{"kind":"text","text":"- "},{"text":"getRTCError","kind":"identifier"}],"op":"replace"},{"value":"getIMError","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallError~1getIMError()\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getIMError"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallError~1getIMError()\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}