{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallError"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easecalluikit\/callerror\/error"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easecalluikit\/callerror\/error"]}],"abstract":[{"type":"text","text":"The error details conforming to "},{"type":"codeVoice","code":"CallErrorCommonFeature"},{"type":"text","text":"."}],"identifier":{"url":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallError\/error","interfaceLanguage":"swift"},"metadata":{"roleHeading":"Instance Property","title":"error","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"error","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@EaseCallUIKit@objc(pl)CallErrorCommonFeature","kind":"typeIdentifier","text":"CallErrorCommonFeature"}],"symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"error"}],"modules":[{"name":"EaseCallUIKit"}],"role":"symbol","externalID":"c:@M@EaseCallUIKit@objc(cs)CallError(py)error"},"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"error"},{"kind":"text","text":": "},{"text":"CallErrorCommonFeature","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallErrorCommonFeature","preciseIdentifier":"c:@M@EaseCallUIKit@objc(pl)CallErrorCommonFeature","kind":"typeIdentifier"}],"languages":["swift"]}]}],"references":{"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit":{"title":"EaseCallUIKit","type":"topic","url":"\/documentation\/easecalluikit","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit","abstract":[],"role":"collection","kind":"symbol"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallErrorCommonFeature":{"navigatorTitle":[{"text":"CallErrorCommonFeature","kind":"identifier"}],"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"CallErrorCommonFeature","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"CallErrorCommonFeature 协议定义了通用的错误特性"}],"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallErrorCommonFeature","type":"topic","title":"CallErrorCommonFeature","url":"\/documentation\/easecalluikit\/callerrorcommonfeature","role":"symbol"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallError/error":{"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallError\/error","abstract":[{"text":"The error details conforming to ","type":"text"},{"type":"codeVoice","code":"CallErrorCommonFeature"},{"type":"text","text":"."}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"error"}],"url":"\/documentation\/easecalluikit\/callerror\/error","title":"error","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"error","kind":"identifier"},{"kind":"text","text":": "},{"text":"CallErrorCommonFeature","kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseCallUIKit@objc(pl)CallErrorCommonFeature"}],"kind":"symbol"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallError":{"type":"topic","role":"symbol","title":"CallError","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"CallError","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"CallError"},{"type":"text","text":" class encapsulates errors that can occur in the call system, providing a structured way to handle errors from different modules such as IM, RTC, and business logic."}],"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallError","navigatorTitle":[{"kind":"identifier","text":"CallError"}],"url":"\/documentation\/easecalluikit\/callerror"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"error"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"error"}]},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"id<CallErrorCommonFeature>","preciseIdentifier":"c:Qo@M@EaseCallUIKit@objc(pl)CallErrorCommonFeature"},{"text":" ","kind":"text"},{"text":"error","kind":"identifier"},{"kind":"text","text":";"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallErrorCommonFeature\/title","value":"CallErrorCommonFeature","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallErrorCommonFeature\/fragments","value":[{"text":"CallErrorCommonFeature","kind":"identifier"}]},{"value":[{"text":"CallErrorCommonFeature","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallErrorCommonFeature\/navigatorTitle","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallError~1error\/title","op":"replace","value":"error"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallError~1error\/fragments","value":[{"kind":"identifier","text":"error"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallError\/title","op":"replace","value":"CallError"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallError\/fragments","value":[{"kind":"identifier","text":"CallError"}]},{"op":"replace","value":[{"kind":"identifier","text":"CallError"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallError\/navigatorTitle"}]}]}