{"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallError\/getCallBusinessError()"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"getCallBusinessError","kind":"identifier"},{"kind":"text","text":"() -> "},{"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallBusinessErrorCode","text":"CallBusinessErrorCode","kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseCallUIKit@E@CallBusinessErrorCode"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"text":"Return Value","level":2,"anchor":"return-value","type":"heading"},{"inlineContent":[{"text":"","type":"text"},{"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallBusinessErrorCode","isActive":true,"type":"reference"},{"type":"text","text":" enums representing the error code from the business logic module."}],"type":"paragraph"}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallError","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallError\/CallErrorCodeGettable-Implementations"]]},"abstract":[{"text":"Get error code from the business logic module.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easecalluikit\/callerror\/getcallbusinesserror()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easecalluikit\/callerror\/getcallbusinesserror()"]}],"sections":[],"metadata":{"role":"symbol","extendedModule":"EaseCallUIKit","modules":[{"name":"EaseCallUIKit"}],"externalID":"c:@CM@EaseCallUIKit@objc(cs)CallError(im)getCallBusinessError","symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"getCallBusinessError"}],"roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"getCallBusinessError","kind":"identifier"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"c:@M@EaseCallUIKit@E@CallBusinessErrorCode","text":"CallBusinessErrorCode","kind":"typeIdentifier"}],"title":"getCallBusinessError()"},"kind":"symbol","references":{"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallError/CallErrorCodeGettable-Implementations":{"url":"\/documentation\/easecalluikit\/callerror\/callerrorcodegettable-implementations","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallError\/CallErrorCodeGettable-Implementations","role":"collectionGroup","abstract":[],"type":"topic","title":"CallErrorCodeGettable Implementations","kind":"article"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallError":{"type":"topic","role":"symbol","title":"CallError","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"CallError","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"CallError"},{"type":"text","text":" class encapsulates errors that can occur in the call system, providing a structured way to handle errors from different modules such as IM, RTC, and business logic."}],"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallError","navigatorTitle":[{"kind":"identifier","text":"CallError"}],"url":"\/documentation\/easecalluikit\/callerror"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit":{"title":"EaseCallUIKit","type":"topic","url":"\/documentation\/easecalluikit","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit","abstract":[],"role":"collection","kind":"symbol"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallBusinessErrorCode":{"abstract":[],"type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"CallBusinessErrorCode","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallBusinessErrorCode","role":"symbol","title":"CallBusinessErrorCode","navigatorTitle":[{"text":"CallBusinessErrorCode","kind":"identifier"}],"url":"\/documentation\/easecalluikit\/callbusinesserrorcode"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallError/getCallBusinessError()":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"getCallBusinessError"},{"text":"() -> ","kind":"text"},{"text":"CallBusinessErrorCode","preciseIdentifier":"c:@M@EaseCallUIKit@E@CallBusinessErrorCode","kind":"typeIdentifier"}],"kind":"symbol","abstract":[{"text":"Get error code from the business logic module.","type":"text"}],"url":"\/documentation\/easecalluikit\/callerror\/getcallbusinesserror()","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallError\/getCallBusinessError()","type":"topic","title":"getCallBusinessError()","navigatorTitle":[{"text":"getCallBusinessError","kind":"identifier"}],"role":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","value":"getCallBusinessError","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"getCallBusinessError","kind":"identifier"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallBusinessErrorCode","text":"CallBusinessErrorCode","kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseCallUIKit@E@CallBusinessErrorCode"},{"text":") ","kind":"text"},{"kind":"identifier","text":"getCallBusinessError"},{"kind":"text","text":";"}]}],"kind":"declarations"}},{"value":{"kind":"content","content":[{"text":"Return Value","anchor":"return-value","level":2,"type":"heading"},{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"type":"reference","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallBusinessErrorCode","isActive":true},{"type":"text","text":" enums representing the error code from the business logic module."}]}]},"op":"replace","path":"\/primaryContentSections\/1"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallError\/title","value":"CallError"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallError\/fragments","value":[{"text":"CallError","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallError\/navigatorTitle","value":[{"kind":"identifier","text":"CallError"}]},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallBusinessErrorCode\/title","value":"CallBusinessErrorCode","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"CallBusinessErrorCode"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallBusinessErrorCode\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"CallBusinessErrorCode"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallBusinessErrorCode\/navigatorTitle"},{"value":"getCallBusinessError","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallError~1getCallBusinessError()\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallError~1getCallBusinessError()\/fragments","value":[{"kind":"text","text":"- "},{"text":"getCallBusinessError","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}