{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallError","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallError\/CallErrorCodeGettable-Implementations"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallError\/getIMError()"},"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"getIMError","kind":"identifier"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"s:13EaseCallUIKit13ChatErrorCodea","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/ChatErrorCode","kind":"typeIdentifier","text":"ChatErrorCode"}],"platforms":["iOS"]}],"kind":"declarations"},{"content":[{"text":"Return Value","type":"heading","anchor":"return-value","level":2},{"inlineContent":[{"text":"","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/ChatErrorCode"},{"text":" enums representing the error code from the IM module.","type":"text"}],"type":"paragraph"}],"kind":"content"}],"kind":"symbol","metadata":{"symbolKind":"method","role":"symbol","modules":[{"name":"EaseCallUIKit"}],"roleHeading":"Instance Method","title":"getIMError()","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"getIMError"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"s:13EaseCallUIKit13ChatErrorCodea","kind":"typeIdentifier","text":"ChatErrorCode"}],"navigatorTitle":[{"text":"getIMError","kind":"identifier"}],"extendedModule":"EaseCallUIKit","externalID":"c:@CM@EaseCallUIKit@objc(cs)CallError(im)getIMError"},"abstract":[{"type":"text","text":"Get error code from the IM module."}],"variants":[{"paths":["\/documentation\/easecalluikit\/callerror\/getimerror()"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easecalluikit\/callerror\/getimerror()"]}],"sections":[],"references":{"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit":{"title":"EaseCallUIKit","type":"topic","url":"\/documentation\/easecalluikit","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit","abstract":[],"role":"collection","kind":"symbol"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallError/CallErrorCodeGettable-Implementations":{"url":"\/documentation\/easecalluikit\/callerror\/callerrorcodegettable-implementations","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallError\/CallErrorCodeGettable-Implementations","role":"collectionGroup","abstract":[],"type":"topic","title":"CallErrorCodeGettable Implementations","kind":"article"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/ChatErrorCode":{"role":"symbol","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/ChatErrorCode","url":"\/documentation\/easecalluikit\/chaterrorcode","fragments":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"text":"ChatErrorCode","kind":"identifier"}],"abstract":[],"kind":"symbol","title":"ChatErrorCode","navigatorTitle":[{"kind":"identifier","text":"ChatErrorCode"}],"type":"topic"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallError/getIMError()":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"getIMError","kind":"identifier"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"s:13EaseCallUIKit13ChatErrorCodea","kind":"typeIdentifier","text":"ChatErrorCode"}],"kind":"symbol","abstract":[{"type":"text","text":"Get error code from the IM module."}],"url":"\/documentation\/easecalluikit\/callerror\/getimerror()","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallError\/getIMError()","type":"topic","title":"getIMError()","navigatorTitle":[{"text":"getIMError","kind":"identifier"}],"role":"symbol"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallError":{"type":"topic","role":"symbol","title":"CallError","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"CallError","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"CallError"},{"type":"text","text":" class encapsulates errors that can occur in the call system, providing a structured way to handle errors from different modules such as IM, RTC, and business logic."}],"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallError","navigatorTitle":[{"kind":"identifier","text":"CallError"}],"url":"\/documentation\/easecalluikit\/callerror"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"value":"getIMError","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"getIMError","kind":"identifier"}]},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"text":"EMErrorCode","kind":"typeIdentifier","preciseIdentifier":"c:@E@EMErrorCode"},{"kind":"text","text":") "},{"text":"getIMError","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"},"op":"replace"},{"op":"replace","value":{"content":[{"type":"heading","text":"Return Value","anchor":"return-value","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/ChatErrorCode","isActive":true,"type":"reference"},{"type":"text","text":" enums representing the error code from the IM module."}]}],"kind":"content"},"path":"\/primaryContentSections\/1"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallError~1getIMError()\/title","value":"getIMError"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallError~1getIMError()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getIMError"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallError\/title","value":"CallError","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallError\/fragments","value":[{"kind":"identifier","text":"CallError"}]},{"value":[{"kind":"identifier","text":"CallError"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallError\/navigatorTitle"}]}]}