{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallError","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallError\/CallErrorCodeGettable-Implementations"]]},"variants":[{"paths":["\/documentation\/easecalluikit\/callerror\/getrtcerror()"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easecalluikit\/callerror\/getrtcerror()"]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"getRTCError","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"AgoraErrorCode","preciseIdentifier":"c:@E@AgoraErrorCode","kind":"typeIdentifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"},{"kind":"content","content":[{"level":2,"text":"Return Value","type":"heading","anchor":"return-value"},{"inlineContent":[{"text":"","type":"text"},{"type":"codeVoice","code":"AgoraErrorCode"},{"type":"text","text":" enums representing the error code from the RTC module."}],"type":"paragraph"}]}],"abstract":[{"type":"text","text":"Get error code from the RTC module."}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallError\/getRTCError()"},"sections":[],"metadata":{"role":"symbol","roleHeading":"Instance Method","navigatorTitle":[{"kind":"identifier","text":"getRTCError"}],"modules":[{"name":"EaseCallUIKit"}],"title":"getRTCError()","symbolKind":"method","externalID":"c:@CM@EaseCallUIKit@objc(cs)CallError(im)getRTCError","extendedModule":"EaseCallUIKit","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"getRTCError","kind":"identifier"},{"kind":"text","text":"() -> "},{"preciseIdentifier":"c:@E@AgoraErrorCode","text":"AgoraErrorCode","kind":"typeIdentifier"}]},"references":{"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallError":{"type":"topic","role":"symbol","title":"CallError","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"CallError","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"CallError"},{"type":"text","text":" class encapsulates errors that can occur in the call system, providing a structured way to handle errors from different modules such as IM, RTC, and business logic."}],"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallError","navigatorTitle":[{"kind":"identifier","text":"CallError"}],"url":"\/documentation\/easecalluikit\/callerror"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit":{"title":"EaseCallUIKit","type":"topic","url":"\/documentation\/easecalluikit","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit","abstract":[],"role":"collection","kind":"symbol"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallError/CallErrorCodeGettable-Implementations":{"url":"\/documentation\/easecalluikit\/callerror\/callerrorcodegettable-implementations","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallError\/CallErrorCodeGettable-Implementations","role":"collectionGroup","abstract":[],"type":"topic","title":"CallErrorCodeGettable Implementations","kind":"article"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallError/getRTCError()":{"type":"topic","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallError\/getRTCError()","abstract":[{"type":"text","text":"Get error code from the RTC module."}],"kind":"symbol","url":"\/documentation\/easecalluikit\/callerror\/getrtcerror()","title":"getRTCError()","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"getRTCError","kind":"identifier"},{"text":"() -> ","kind":"text"},{"kind":"typeIdentifier","text":"AgoraErrorCode","preciseIdentifier":"c:@E@AgoraErrorCode"}],"navigatorTitle":[{"text":"getRTCError","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"getRTCError"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"text","text":"- "},{"text":"getRTCError","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:@E@AgoraErrorCode","text":"AgoraErrorCode","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"identifier","text":"getRTCError"},{"text":";","kind":"text"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":{"content":[{"text":"Return Value","level":2,"type":"heading","anchor":"return-value"},{"type":"paragraph","inlineContent":[{"text":"","type":"text"},{"code":"AgoraErrorCode","type":"codeVoice"},{"type":"text","text":" enums representing the error code from the RTC module."}]}],"kind":"content"},"path":"\/primaryContentSections\/1"},{"value":"CallError","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallError\/title"},{"value":[{"text":"CallError","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallError\/fragments"},{"op":"replace","value":[{"text":"CallError","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallError\/navigatorTitle"},{"value":"getRTCError","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallError~1getRTCError()\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallError~1getRTCError()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"getRTCError","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}