{"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"roleHeading":"Case","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"accept"}],"role":"symbol","symbolKind":"case","title":"RingAlertAction.accept","modules":[{"name":"EaseCallUIKit"}],"externalID":"c:@M@EaseCallUIKit@E@RingAlertAction@RingAlertActionAccept","navigatorTitle":[{"kind":"identifier","text":"RingAlertActionAccept"}]},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"accept"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/easecalluikit\/ringalertaction\/accept"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/easecalluikit\/ringalertaction\/accept"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","identifier":{"url":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/RingAlertAction\/accept","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/RingAlertAction"]]},"sections":[],"references":{"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/RingAlertAction/accept":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/RingAlertAction\/accept","url":"\/documentation\/easecalluikit\/ringalertaction\/accept","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"accept"}],"navigatorTitle":[{"text":"RingAlertActionAccept","kind":"identifier"}],"title":"RingAlertAction.accept","type":"topic","role":"symbol","abstract":[]},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit":{"title":"EaseCallUIKit","type":"topic","url":"\/documentation\/easecalluikit","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit","abstract":[],"role":"collection","kind":"symbol"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/RingAlertAction":{"abstract":[],"role":"symbol","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RingAlertAction","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"RingAlertAction"}],"type":"topic","title":"RingAlertAction","url":"\/documentation\/easecalluikit\/ringalertaction","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/RingAlertAction"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Enumeration Case","path":"\/metadata\/roleHeading","op":"replace"},{"value":"RingAlertActionAccept","op":"replace","path":"\/metadata\/title"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"RingAlertActionAccept"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"tokens":[{"text":"RingAlertActionAccept","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"value":"RingAlertActionAccept","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1RingAlertAction~1accept\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1RingAlertAction~1accept\/fragments","op":"replace","value":[{"kind":"identifier","text":"RingAlertActionAccept"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1RingAlertAction\/title","value":"RingAlertAction"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1RingAlertAction\/fragments","value":[{"kind":"identifier","text":"RingAlertAction"}]},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1RingAlertAction\/navigatorTitle","value":[{"kind":"identifier","text":"RingAlertAction"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}