{"sections":[],"kind":"symbol","metadata":{"role":"symbol","title":"RingAlertAction.decline","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"decline"}],"symbolKind":"case","externalID":"c:@M@EaseCallUIKit@E@RingAlertAction@RingAlertActionDecline","modules":[{"name":"EaseCallUIKit"}],"roleHeading":"Case","navigatorTitle":[{"text":"RingAlertActionDecline","kind":"identifier"}]},"identifier":{"url":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/RingAlertAction\/decline","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/RingAlertAction"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easecalluikit\/ringalertaction\/decline"]},{"paths":["\/documentation\/easecalluikit\/ringalertaction\/decline"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"decline","kind":"identifier"}],"platforms":["iOS"]}]}],"references":{"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/RingAlertAction/decline":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/RingAlertAction\/decline","url":"\/documentation\/easecalluikit\/ringalertaction\/decline","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"decline"}],"navigatorTitle":[{"text":"RingAlertActionDecline","kind":"identifier"}],"title":"RingAlertAction.decline","type":"topic","role":"symbol","abstract":[]},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/RingAlertAction":{"abstract":[],"role":"symbol","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RingAlertAction","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"RingAlertAction"}],"type":"topic","title":"RingAlertAction","url":"\/documentation\/easecalluikit\/ringalertaction","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/RingAlertAction"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit":{"title":"EaseCallUIKit","type":"topic","url":"\/documentation\/easecalluikit","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit","abstract":[],"role":"collection","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"value":"RingAlertActionDecline","path":"\/metadata\/title","op":"replace"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"RingAlertActionDecline","kind":"identifier"}]},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"RingAlertActionDecline","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1RingAlertAction~1decline\/title","op":"replace","value":"RingAlertActionDecline"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1RingAlertAction~1decline\/fragments","value":[{"kind":"identifier","text":"RingAlertActionDecline"}]},{"value":"RingAlertAction","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1RingAlertAction\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1RingAlertAction\/fragments","value":[{"text":"RingAlertAction","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"RingAlertAction"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1RingAlertAction\/navigatorTitle"}]}]}