{"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/RingAlertAction"]]},"metadata":{"roleHeading":"Case","role":"symbol","title":"RingAlertAction.other","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"other","kind":"identifier"}],"navigatorTitle":[{"text":"RingAlertActionOther","kind":"identifier"}],"externalID":"c:@M@EaseCallUIKit@E@RingAlertAction@RingAlertActionOther","symbolKind":"case","modules":[{"name":"EaseCallUIKit"}]},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/RingAlertAction\/other"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easecalluikit\/ringalertaction\/other"]},{"paths":["\/documentation\/easecalluikit\/ringalertaction\/other"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"other","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"references":{"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit":{"title":"EaseCallUIKit","type":"topic","url":"\/documentation\/easecalluikit","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit","abstract":[],"role":"collection","kind":"symbol"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/RingAlertAction":{"abstract":[],"role":"symbol","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RingAlertAction","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"RingAlertAction"}],"type":"topic","title":"RingAlertAction","url":"\/documentation\/easecalluikit\/ringalertaction","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/RingAlertAction"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/RingAlertAction/other":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/RingAlertAction\/other","url":"\/documentation\/easecalluikit\/ringalertaction\/other","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"other"}],"navigatorTitle":[{"text":"RingAlertActionOther","kind":"identifier"}],"title":"RingAlertAction.other","type":"topic","role":"symbol","abstract":[]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"RingAlertActionOther"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"RingAlertActionOther"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"identifier","text":"RingAlertActionOther"}],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1RingAlertAction\/title","value":"RingAlertAction"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1RingAlertAction\/fragments","value":[{"text":"RingAlertAction","kind":"identifier"}]},{"value":[{"text":"RingAlertAction","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1RingAlertAction\/navigatorTitle","op":"replace"},{"value":"RingAlertActionOther","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1RingAlertAction~1other\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1RingAlertAction~1other\/fragments","value":[{"kind":"identifier","text":"RingAlertActionOther"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}