{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easecalluikit\/callendreason\/cancel"]},{"paths":["\/documentation\/easecalluikit\/callendreason\/cancel"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallEndReason\/cancel"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"cancel","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"}],"kind":"symbol","sections":[],"metadata":{"roleHeading":"Case","symbolKind":"case","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"cancel"}],"title":"CallEndReason.cancel","modules":[{"name":"EaseCallUIKit"}],"role":"symbol","externalID":"c:@M@EaseCallUIKit@E@CallEndReason@CallEndReasonCancel","navigatorTitle":[{"text":"CallEndReasonCancel","kind":"identifier"}]},"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallEndReason"]]},"references":{"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit":{"title":"EaseCallUIKit","type":"topic","url":"\/documentation\/easecalluikit","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit","abstract":[],"role":"collection","kind":"symbol"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallEndReason":{"type":"topic","kind":"symbol","title":"CallEndReason","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallEndReason","navigatorTitle":[{"text":"CallEndReason","kind":"identifier"}],"abstract":[],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CallEndReason"}],"url":"\/documentation\/easecalluikit\/callendreason","role":"symbol"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallEndReason/cancel":{"navigatorTitle":[{"text":"CallEndReasonCancel","kind":"identifier"}],"url":"\/documentation\/easecalluikit\/callendreason\/cancel","kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"cancel"}],"title":"CallEndReason.cancel","abstract":[],"type":"topic","role":"symbol","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallEndReason\/cancel"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"CallEndReasonCancel","op":"replace"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"CallEndReasonCancel","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"identifier","text":"CallEndReasonCancel"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallEndReason\/title","value":"CallEndReason","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallEndReason\/fragments","value":[{"kind":"identifier","text":"CallEndReason"}],"op":"replace"},{"op":"replace","value":[{"text":"CallEndReason","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallEndReason\/navigatorTitle"},{"value":"CallEndReasonCancel","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallEndReason~1cancel\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallEndReason~1cancel\/fragments","value":[{"text":"CallEndReasonCancel","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}