{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallEndReason"]]},"variants":[{"paths":["\/documentation\/easecalluikit\/callendreason\/remotecancel"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easecalluikit\/callendreason\/remotecancel"]}],"identifier":{"url":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallEndReason\/remoteCancel","interfaceLanguage":"swift"},"metadata":{"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"remoteCancel"}],"symbolKind":"case","roleHeading":"Case","externalID":"c:@M@EaseCallUIKit@E@CallEndReason@CallEndReasonRemoteCancel","title":"CallEndReason.remoteCancel","modules":[{"name":"EaseCallUIKit"}],"navigatorTitle":[{"text":"CallEndReasonRemoteCancel","kind":"identifier"}],"role":"symbol"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"remoteCancel"}],"languages":["swift"],"platforms":["iOS"]}]}],"sections":[],"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallEndReason/remoteCancel":{"role":"symbol","kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallEndReason\/remoteCancel","title":"CallEndReason.remoteCancel","url":"\/documentation\/easecalluikit\/callendreason\/remotecancel","navigatorTitle":[{"kind":"identifier","text":"CallEndReasonRemoteCancel"}],"type":"topic","abstract":[],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"remoteCancel","kind":"identifier"}]},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit":{"title":"EaseCallUIKit","type":"topic","url":"\/documentation\/easecalluikit","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit","abstract":[],"role":"collection","kind":"symbol"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallEndReason":{"type":"topic","kind":"symbol","title":"CallEndReason","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallEndReason","navigatorTitle":[{"text":"CallEndReason","kind":"identifier"}],"abstract":[],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CallEndReason"}],"url":"\/documentation\/easecalluikit\/callendreason","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","value":"CallEndReasonRemoteCancel","path":"\/metadata\/title"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"CallEndReasonRemoteCancel","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"identifier","text":"CallEndReasonRemoteCancel"}],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallEndReason~1remoteCancel\/title","op":"replace","value":"CallEndReasonRemoteCancel"},{"op":"replace","value":[{"kind":"identifier","text":"CallEndReasonRemoteCancel"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallEndReason~1remoteCancel\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallEndReason\/title","op":"replace","value":"CallEndReason"},{"value":[{"kind":"identifier","text":"CallEndReason"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallEndReason\/fragments"},{"value":[{"text":"CallEndReason","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallEndReason\/navigatorTitle"}]}]}