{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallEndReason"]]},"metadata":{"symbolKind":"case","title":"CallEndReason.remoteNoResponse","roleHeading":"Case","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"remoteNoResponse"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"CallEndReasonRemoteNoResponse"}],"externalID":"c:@M@EaseCallUIKit@E@CallEndReason@CallEndReasonRemoteNoResponse","modules":[{"name":"EaseCallUIKit"}]},"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"url":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallEndReason\/remoteNoResponse","interfaceLanguage":"swift"},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easecalluikit\/callendreason\/remotenoresponse"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easecalluikit\/callendreason\/remotenoresponse"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"remoteNoResponse","kind":"identifier"}],"platforms":["iOS"]}]}],"references":{"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallEndReason/remoteNoResponse":{"role":"symbol","title":"CallEndReason.remoteNoResponse","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"remoteNoResponse","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"CallEndReasonRemoteNoResponse","kind":"identifier"}],"abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallEndReason\/remoteNoResponse","url":"\/documentation\/easecalluikit\/callendreason\/remotenoresponse"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallEndReason":{"type":"topic","kind":"symbol","title":"CallEndReason","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallEndReason","navigatorTitle":[{"text":"CallEndReason","kind":"identifier"}],"abstract":[],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CallEndReason"}],"url":"\/documentation\/easecalluikit\/callendreason","role":"symbol"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit":{"title":"EaseCallUIKit","type":"topic","url":"\/documentation\/easecalluikit","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit","abstract":[],"role":"collection","kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","value":"CallEndReasonRemoteNoResponse","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"CallEndReasonRemoteNoResponse","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"CallEndReasonRemoteNoResponse"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallEndReason~1remoteNoResponse\/title","op":"replace","value":"CallEndReasonRemoteNoResponse"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallEndReason~1remoteNoResponse\/fragments","value":[{"text":"CallEndReasonRemoteNoResponse","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallEndReason\/title","op":"replace","value":"CallEndReason"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallEndReason\/fragments","value":[{"text":"CallEndReason","kind":"identifier"}]},{"value":[{"text":"CallEndReason","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallEndReason\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}