{"schemaVersion":{"patch":0,"minor":3,"major":0},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallEndReason"]]},"metadata":{"externalID":"c:@M@EaseCallUIKit@E@CallEndReason@CallEndReasonRemoteRefuse","symbolKind":"case","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"CallEndReasonRemoteRefuse"}],"roleHeading":"Case","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"remoteRefuse","kind":"identifier"}],"title":"CallEndReason.remoteRefuse","modules":[{"name":"EaseCallUIKit"}]},"identifier":{"url":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallEndReason\/remoteRefuse","interfaceLanguage":"swift"},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easecalluikit\/callendreason\/remoterefuse"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easecalluikit\/callendreason\/remoterefuse"]}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"remoteRefuse"}]}]}],"references":{"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallEndReason/remoteRefuse":{"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallEndReason\/remoteRefuse","title":"CallEndReason.remoteRefuse","role":"symbol","url":"\/documentation\/easecalluikit\/callendreason\/remoterefuse","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"remoteRefuse","kind":"identifier"}],"navigatorTitle":[{"text":"CallEndReasonRemoteRefuse","kind":"identifier"}],"type":"topic","kind":"symbol","abstract":[]},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallEndReason":{"type":"topic","kind":"symbol","title":"CallEndReason","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallEndReason","navigatorTitle":[{"text":"CallEndReason","kind":"identifier"}],"abstract":[],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CallEndReason"}],"url":"\/documentation\/easecalluikit\/callendreason","role":"symbol"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit":{"title":"EaseCallUIKit","type":"topic","url":"\/documentation\/easecalluikit","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit","abstract":[],"role":"collection","kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Enumeration Case","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"CallEndReasonRemoteRefuse"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"CallEndReasonRemoteRefuse"}]},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"CallEndReasonRemoteRefuse","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"op":"replace","value":"CallEndReasonRemoteRefuse","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallEndReason~1remoteRefuse\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallEndReason~1remoteRefuse\/fragments","value":[{"text":"CallEndReasonRemoteRefuse","kind":"identifier"}],"op":"replace"},{"value":"CallEndReason","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallEndReason\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallEndReason\/fragments","value":[{"text":"CallEndReason","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallEndReason\/navigatorTitle","value":[{"text":"CallEndReason","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}