{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"any"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easecalluikit\/dragdirection\/any"]},{"paths":["\/documentation\/easecalluikit\/dragdirection\/any"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/DragDirection\/any"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/DragDirection"]]},"kind":"symbol","sections":[],"metadata":{"externalID":"c:@M@EaseCallUIKit@E@DragDirection@DragDirectionAny","symbolKind":"case","title":"DragDirection.any","roleHeading":"Case","modules":[{"name":"EaseCallUIKit"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"DragDirectionAny"}],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"any","kind":"identifier"}]},"references":{"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/DragDirection":{"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/DragDirection","abstract":[],"url":"\/documentation\/easecalluikit\/dragdirection","kind":"symbol","role":"symbol","type":"topic","title":"DragDirection","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"DragDirection"}],"navigatorTitle":[{"text":"DragDirection","kind":"identifier"}]},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/DragDirection/any":{"url":"\/documentation\/easecalluikit\/dragdirection\/any","kind":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/DragDirection\/any","navigatorTitle":[{"kind":"identifier","text":"DragDirectionAny"}],"title":"DragDirection.any","abstract":[],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"any"}],"role":"symbol"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit":{"title":"EaseCallUIKit","type":"topic","url":"\/documentation\/easecalluikit","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit","abstract":[],"role":"collection","kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Enumeration Case","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"DragDirectionAny"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"DragDirectionAny"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"DragDirectionAny","kind":"identifier"}]}]},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1DragDirection\/title","op":"replace","value":"DragDirection"},{"value":[{"kind":"identifier","text":"DragDirection"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1DragDirection\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1DragDirection\/navigatorTitle","value":[{"kind":"identifier","text":"DragDirection"}]},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1DragDirection~1any\/title","op":"replace","value":"DragDirectionAny"},{"value":[{"text":"DragDirectionAny","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1DragDirection~1any\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}