{"kind":"article","hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/DragDirection"]]},"variants":[{"paths":["\/documentation\/easecalluikit\/dragdirection\/equatable-implementations"],"traits":[{"interfaceLanguage":"swift"}]}],"sections":[],"topicSections":[{"title":"Operators","identifiers":["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/DragDirection\/!=(_:_:)"],"generated":true,"anchor":"Operators"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/DragDirection\/Equatable-Implementations"},"metadata":{"roleHeading":"API Collection","modules":[{"name":"EaseCallUIKit"}],"role":"collectionGroup","title":"Equatable Implementations"},"references":{"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/DragDirection/!=(_:_:)":{"role":"symbol","kind":"symbol","url":"\/documentation\/easecalluikit\/dragdirection\/!=(_:_:)","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"!=","kind":"identifier"},{"text":" ","kind":"text"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":", "},{"text":"Self","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"abstract":[],"title":"!=(_:_:)","type":"topic","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/DragDirection\/!=(_:_:)"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/DragDirection":{"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/DragDirection","abstract":[],"url":"\/documentation\/easecalluikit\/dragdirection","kind":"symbol","role":"symbol","type":"topic","title":"DragDirection","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"DragDirection"}],"navigatorTitle":[{"text":"DragDirection","kind":"identifier"}]},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit":{"title":"EaseCallUIKit","type":"topic","url":"\/documentation\/easecalluikit","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit","abstract":[],"role":"collection","kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1DragDirection\/title","value":"DragDirection"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1DragDirection\/fragments","value":[{"text":"DragDirection","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1DragDirection\/navigatorTitle","value":[{"kind":"identifier","text":"DragDirection"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}