{"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/DragDirection\/horizontal"},"metadata":{"title":"DragDirection.horizontal","externalID":"c:@M@EaseCallUIKit@E@DragDirection@DragDirectionHorizontal","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"horizontal","kind":"identifier"}],"symbolKind":"case","roleHeading":"Case","role":"symbol","navigatorTitle":[{"text":"DragDirectionHorizontal","kind":"identifier"}],"modules":[{"name":"EaseCallUIKit"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/DragDirection"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"horizontal"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/easecalluikit\/dragdirection\/horizontal"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easecalluikit\/dragdirection\/horizontal"]}],"sections":[],"references":{"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/DragDirection":{"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/DragDirection","abstract":[],"url":"\/documentation\/easecalluikit\/dragdirection","kind":"symbol","role":"symbol","type":"topic","title":"DragDirection","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"DragDirection"}],"navigatorTitle":[{"text":"DragDirection","kind":"identifier"}]},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit":{"title":"EaseCallUIKit","type":"topic","url":"\/documentation\/easecalluikit","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit","abstract":[],"role":"collection","kind":"symbol"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/DragDirection/horizontal":{"url":"\/documentation\/easecalluikit\/dragdirection\/horizontal","title":"DragDirection.horizontal","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"horizontal"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"DragDirectionHorizontal"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/DragDirection\/horizontal","kind":"symbol","role":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"value":"DragDirectionHorizontal","path":"\/metadata\/title","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"value":[{"text":"DragDirectionHorizontal","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"DragDirectionHorizontal"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"value":"DragDirection","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1DragDirection\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1DragDirection\/fragments","value":[{"text":"DragDirection","kind":"identifier"}]},{"value":[{"text":"DragDirection","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1DragDirection\/navigatorTitle"},{"value":"DragDirectionHorizontal","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1DragDirection~1horizontal\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1DragDirection~1horizontal\/fragments","value":[{"text":"DragDirectionHorizontal","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}