{"metadata":{"externalID":"s:13EaseCallUIKit0B5ErrorC0B8BusinessC5error7messageAeA0beD4CodeO_SStcfc","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"error"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@EaseCallUIKit@E@CallBusinessErrorCode","kind":"typeIdentifier","text":"CallBusinessErrorCode"},{"text":", ","kind":"text"},{"text":"message","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}],"role":"symbol","modules":[{"name":"EaseCallUIKit"}],"title":"init(error:message:)","roleHeading":"Initializer","symbolKind":"init"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easecalluikit\/callerror\/callbusiness\/init(error:message:)"]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallError","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallError\/CallBusiness"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"init","kind":"keyword"},{"kind":"text","text":"("},{"text":"error","kind":"externalParam"},{"kind":"text","text":": "},{"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallBusinessErrorCode","kind":"typeIdentifier","text":"CallBusinessErrorCode","preciseIdentifier":"c:@M@EaseCallUIKit@E@CallBusinessErrorCode"},{"kind":"text","text":", "},{"text":"message","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":")","kind":"text"}],"languages":["swift"]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallError\/CallBusiness\/init(error:message:)"},"sections":[],"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"references":{"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallError/CallBusiness/init(error:message:)":{"title":"init(error:message:)","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallError\/CallBusiness\/init(error:message:)","type":"topic","url":"\/documentation\/easecalluikit\/callerror\/callbusiness\/init(error:message:)","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseCallUIKit@E@CallBusinessErrorCode","text":"CallBusinessErrorCode"},{"text":", ","kind":"text"},{"text":"message","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":")","kind":"text"}],"role":"symbol"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit":{"title":"EaseCallUIKit","type":"topic","url":"\/documentation\/easecalluikit","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit","abstract":[],"role":"collection","kind":"symbol"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallError/CallBusiness":{"navigatorTitle":[{"kind":"identifier","text":"CallBusiness"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CallBusiness"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallError\/CallBusiness","url":"\/documentation\/easecalluikit\/callerror\/callbusiness","type":"topic","title":"CallError.CallBusiness","kind":"symbol","abstract":[{"type":"text","text":"Convenience initializer for creating a "},{"code":"CallError","type":"codeVoice"},{"type":"text","text":" with a business logic error."}]},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallBusinessErrorCode":{"abstract":[],"type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"CallBusinessErrorCode","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallBusinessErrorCode","role":"symbol","title":"CallBusinessErrorCode","navigatorTitle":[{"text":"CallBusinessErrorCode","kind":"identifier"}],"url":"\/documentation\/easecalluikit\/callbusinesserrorcode"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallError":{"type":"topic","role":"symbol","title":"CallError","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"CallError","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"CallError"},{"type":"text","text":" class encapsulates errors that can occur in the call system, providing a structured way to handle errors from different modules such as IM, RTC, and business logic."}],"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallError","navigatorTitle":[{"kind":"identifier","text":"CallError"}],"url":"\/documentation\/easecalluikit\/callerror"}},"variantOverrides":[{"patch":[{"value":"CallBusinessErrorCode","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallBusinessErrorCode\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallBusinessErrorCode\/fragments","value":[{"kind":"identifier","text":"CallBusinessErrorCode"}]},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallBusinessErrorCode\/navigatorTitle","value":[{"text":"CallBusinessErrorCode","kind":"identifier"}],"op":"replace"},{"value":"CallError","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallError\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallError\/fragments","op":"replace","value":[{"text":"CallError","kind":"identifier"}]},{"op":"replace","value":[{"kind":"identifier","text":"CallError"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallError\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}