{"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"animationControllerForDismissedController:"}],"modules":[{"name":"EaseCallUIKit"}],"role":"symbol","extendedModule":"EaseCallUIKit","externalID":"c:@CM@EaseCallUIKit@objc(cs)FloatingAudioView(im)animationControllerForDismissedController:","title":"animationController(forDismissed:)","symbolKind":"method","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"animationController","kind":"identifier"},{"text":"(","kind":"text"},{"text":"forDismissed","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"text":"UIViewControllerAnimatedTransitioning","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)UIViewControllerAnimatedTransitioning"},{"text":"?","kind":"text"}]},"identifier":{"url":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/FloatingAudioView\/animationController(forDismissed:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/FloatingAudioView","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/FloatingAudioView\/UIViewControllerTransitioningDelegate-Implementations"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"@","kind":"attribute"},{"kind":"attribute","text":"MainActor","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"animationController"},{"kind":"text","text":"("},{"text":"forDismissed","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"dismissed","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"UIViewController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"UIViewControllerAnimatedTransitioning","preciseIdentifier":"c:objc(pl)UIViewControllerAnimatedTransitioning"},{"text":"?","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}],"sections":[],"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"UIViewControllerTransitioningDelegate.animationController(forDismissed:)"},{"type":"text","text":"."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easecalluikit\/floatingaudioview\/animationcontroller(fordismissed:)"]},{"paths":["\/documentation\/easecalluikit\/floatingaudioview\/animationcontroller(fordismissed:)"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/FloatingAudioView/UIViewControllerTransitioningDelegate-Implementations":{"type":"topic","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/FloatingAudioView\/UIViewControllerTransitioningDelegate-Implementations","kind":"article","abstract":[],"role":"collectionGroup","title":"UIViewControllerTransitioningDelegate Implementations","url":"\/documentation\/easecalluikit\/floatingaudioview\/uiviewcontrollertransitioningdelegate-implementations"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/FloatingAudioView":{"role":"symbol","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/FloatingAudioView","url":"\/documentation\/easecalluikit\/floatingaudioview","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"FloatingAudioView","kind":"identifier"}],"abstract":[],"kind":"symbol","title":"FloatingAudioView","navigatorTitle":[{"kind":"identifier","text":"FloatingAudioView"}],"type":"topic"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/FloatingAudioView/animationController(forDismissed:)":{"kind":"symbol","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/FloatingAudioView\/animationController(forDismissed:)","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"animationController"},{"text":"(","kind":"text"},{"text":"forDismissed","kind":"externalParam"},{"kind":"text","text":": "},{"text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:objc(pl)UIViewControllerAnimatedTransitioning","text":"UIViewControllerAnimatedTransitioning","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"animationControllerForDismissedController:","kind":"identifier"}],"title":"animationController(forDismissed:)","url":"\/documentation\/easecalluikit\/floatingaudioview\/animationcontroller(fordismissed:)"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit":{"title":"EaseCallUIKit","type":"topic","url":"\/documentation\/easecalluikit","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit","abstract":[],"role":"collection","kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"animationControllerForDismissedController:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"animationControllerForDismissedController:","kind":"identifier"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:Qoobjc(pl)UIViewControllerAnimatedTransitioning","text":"id<UIViewControllerAnimatedTransitioning>","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"animationControllerForDismissedController:","kind":"identifier"},{"kind":"text","text":"("},{"text":"UIViewController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController"},{"kind":"text","text":" *) "},{"text":"dismissed","kind":"internalParam"},{"text":";","kind":"text"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1FloatingAudioView\/title","op":"replace","value":"FloatingAudioView"},{"value":[{"kind":"identifier","text":"FloatingAudioView"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1FloatingAudioView\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1FloatingAudioView\/navigatorTitle","value":[{"text":"FloatingAudioView","kind":"identifier"}],"op":"replace"},{"value":"animationControllerForDismissedController:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1FloatingAudioView~1animationController(forDismissed:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1FloatingAudioView~1animationController(forDismissed:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"animationControllerForDismissedController:","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}