{"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/FloatingAudioView\/isFloatingViewVisible()"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/FloatingAudioView"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easecalluikit\/floatingaudioview\/isfloatingviewvisible()"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@","kind":"attribute"},{"kind":"attribute","text":"MainActor","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isFloatingViewVisible"},{"text":"() -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"platforms":["iOS"],"languages":["swift"]}]}],"kind":"symbol","metadata":{"extendedModule":"EaseCallUIKit","role":"symbol","title":"isFloatingViewVisible()","modules":[{"name":"EaseCallUIKit"}],"symbolKind":"method","externalID":"s:13EaseCallUIKit17FloatingAudioViewC02isdF7VisibleSbyFZ","roleHeading":"Type Method","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"isFloatingViewVisible"},{"kind":"text","text":"() -> "},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}]},"references":{"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/FloatingAudioView":{"role":"symbol","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/FloatingAudioView","url":"\/documentation\/easecalluikit\/floatingaudioview","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"FloatingAudioView","kind":"identifier"}],"abstract":[],"kind":"symbol","title":"FloatingAudioView","navigatorTitle":[{"kind":"identifier","text":"FloatingAudioView"}],"type":"topic"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/FloatingAudioView/isFloatingViewVisible()":{"kind":"symbol","type":"topic","url":"\/documentation\/easecalluikit\/floatingaudioview\/isfloatingviewvisible()","title":"isFloatingViewVisible()","role":"symbol","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/FloatingAudioView\/isFloatingViewVisible()","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"isFloatingViewVisible","kind":"identifier"},{"kind":"text","text":"() -> "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}]},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit":{"title":"EaseCallUIKit","type":"topic","url":"\/documentation\/easecalluikit","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit","abstract":[],"role":"collection","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"FloatingAudioView","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1FloatingAudioView\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1FloatingAudioView\/fragments","value":[{"text":"FloatingAudioView","kind":"identifier"}],"op":"replace"},{"value":[{"kind":"identifier","text":"FloatingAudioView"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1FloatingAudioView\/navigatorTitle"}]}]}