{"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/FloatingAudioView"]]},"variants":[{"paths":["\/documentation\/easecalluikit\/floatingaudioview\/present(on:)"],"traits":[{"interfaceLanguage":"swift"}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"present"},{"kind":"text","text":"("},{"text":"on","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIViewController","kind":"typeIdentifier","text":"UIViewController"},{"text":")","kind":"text"}],"symbolKind":"method","roleHeading":"Instance Method","externalID":"s:13EaseCallUIKit17FloatingAudioViewC7present2onySo16UIViewControllerC_tF","title":"present(on:)","modules":[{"name":"EaseCallUIKit"}],"role":"symbol"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/FloatingAudioView\/present(on:)"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@"},{"kind":"attribute","preciseIdentifier":"s:ScM","text":"MainActor"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"present","kind":"identifier"},{"text":"(","kind":"text"},{"text":"on","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"viewController"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController","kind":"typeIdentifier"},{"kind":"text","text":")"}]}]}],"references":{"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/FloatingAudioView/present(on:)":{"url":"\/documentation\/easecalluikit\/floatingaudioview\/present(on:)","abstract":[],"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"present","kind":"identifier"},{"kind":"text","text":"("},{"text":"on","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController"},{"text":")","kind":"text"}],"kind":"symbol","type":"topic","title":"present(on:)","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/FloatingAudioView\/present(on:)"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/FloatingAudioView":{"role":"symbol","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/FloatingAudioView","url":"\/documentation\/easecalluikit\/floatingaudioview","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"FloatingAudioView","kind":"identifier"}],"abstract":[],"kind":"symbol","title":"FloatingAudioView","navigatorTitle":[{"kind":"identifier","text":"FloatingAudioView"}],"type":"topic"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit":{"title":"EaseCallUIKit","type":"topic","url":"\/documentation\/easecalluikit","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit","abstract":[],"role":"collection","kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"FloatingAudioView","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1FloatingAudioView\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1FloatingAudioView\/fragments","value":[{"text":"FloatingAudioView","kind":"identifier"}],"op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"FloatingAudioView"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1FloatingAudioView\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}