{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easecalluikit\/floatingaudioview\/uiviewcontrollertransitioningdelegate-implementations"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easecalluikit\/floatingaudioview\/uiviewcontrollertransitioningdelegate-implementations"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/FloatingAudioView"]]},"identifier":{"url":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/FloatingAudioView\/UIViewControllerTransitioningDelegate-Implementations","interfaceLanguage":"swift"},"sections":[],"kind":"article","metadata":{"modules":[{"name":"EaseCallUIKit"}],"role":"collectionGroup","title":"UIViewControllerTransitioningDelegate Implementations","roleHeading":"API Collection"},"topicSections":[{"generated":true,"title":"Instance Methods","anchor":"Instance-Methods","identifiers":["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/FloatingAudioView\/animationController(forDismissed:)","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/FloatingAudioView\/animationController(forPresented:presenting:source:)"]}],"references":{"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/FloatingAudioView":{"role":"symbol","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/FloatingAudioView","url":"\/documentation\/easecalluikit\/floatingaudioview","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"FloatingAudioView","kind":"identifier"}],"abstract":[],"kind":"symbol","title":"FloatingAudioView","navigatorTitle":[{"kind":"identifier","text":"FloatingAudioView"}],"type":"topic"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit":{"title":"EaseCallUIKit","type":"topic","url":"\/documentation\/easecalluikit","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit","abstract":[],"role":"collection","kind":"symbol"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/FloatingAudioView/animationController(forDismissed:)":{"kind":"symbol","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/FloatingAudioView\/animationController(forDismissed:)","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"animationController"},{"text":"(","kind":"text"},{"text":"forDismissed","kind":"externalParam"},{"kind":"text","text":": "},{"text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:objc(pl)UIViewControllerAnimatedTransitioning","text":"UIViewControllerAnimatedTransitioning","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"animationControllerForDismissedController:","kind":"identifier"}],"title":"animationController(forDismissed:)","url":"\/documentation\/easecalluikit\/floatingaudioview\/animationcontroller(fordismissed:)"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/FloatingAudioView/animationController(forPresented:presenting:source:)":{"title":"animationController(forPresented:presenting:source:)","kind":"symbol","role":"symbol","url":"\/documentation\/easecalluikit\/floatingaudioview\/animationcontroller(forpresented:presenting:source:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"animationController","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"forPresented"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"presenting"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"source"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"UIViewControllerAnimatedTransitioning","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)UIViewControllerAnimatedTransitioning"},{"kind":"text","text":"?"}],"navigatorTitle":[{"text":"animationControllerForPresentedController:presentingController:sourceController:","kind":"identifier"}],"type":"topic","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/FloatingAudioView\/animationController(forPresented:presenting:source:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":[{"anchor":"Instance-Methods","title":"Instance Methods","generated":true,"identifiers":["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/FloatingAudioView\/animationController(forDismissed:)","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/FloatingAudioView\/animationController(forPresented:presenting:source:)"]}],"op":"replace","path":"\/topicSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":"FloatingAudioView","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1FloatingAudioView\/title"},{"value":[{"text":"FloatingAudioView","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1FloatingAudioView\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1FloatingAudioView\/navigatorTitle","value":[{"kind":"identifier","text":"FloatingAudioView"}],"op":"replace"},{"op":"replace","value":"animationControllerForDismissedController:","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1FloatingAudioView~1animationController(forDismissed:)\/title"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"animationControllerForDismissedController:"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1FloatingAudioView~1animationController(forDismissed:)\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1FloatingAudioView~1animationController(forPresented:presenting:source:)\/title","value":"animationControllerForPresentedController:presentingController:sourceController:","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1FloatingAudioView~1animationController(forPresented:presenting:source:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"animationControllerForPresentedController:presentingController:sourceController:","kind":"identifier"}],"op":"replace"}]}]}