{"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallButtonView"]]},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"buttonTag","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"paths":["\/documentation\/easecalluikit\/callbuttonview\/buttontag"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallButtonView\/buttonTag"},"sections":[],"metadata":{"modules":[{"name":"EaseCallUIKit"}],"title":"buttonTag","role":"symbol","symbolKind":"property","roleHeading":"Instance Property","externalID":"s:13EaseCallUIKit0B10ButtonViewC9buttonTagSivp","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"buttonTag"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}]},"references":{"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit":{"title":"EaseCallUIKit","type":"topic","url":"\/documentation\/easecalluikit","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit","abstract":[],"role":"collection","kind":"symbol"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallButtonView/buttonTag":{"kind":"symbol","abstract":[],"type":"topic","title":"buttonTag","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallButtonView\/buttonTag","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"buttonTag","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"url":"\/documentation\/easecalluikit\/callbuttonview\/buttontag"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallButtonView":{"title":"CallButtonView","role":"symbol","url":"\/documentation\/easecalluikit\/callbuttonview","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallButtonView","abstract":[],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"CallButtonView"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"CallButtonView","kind":"identifier"}],"type":"topic"}},"variantOverrides":[{"patch":[{"value":"CallButtonView","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallButtonView\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallButtonView\/fragments","value":[{"text":"CallButtonView","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallButtonView\/navigatorTitle","value":[{"kind":"identifier","text":"CallButtonView"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}