{"metadata":{"role":"symbol","symbolKind":"property","modules":[{"name":"EaseCallUIKit"}],"externalID":"s:13EaseCallUIKit0B10ButtonViewC14iconTitleSpace14CoreFoundation7CGFloatVvp","roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"iconTitleSpace","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat","kind":"typeIdentifier"}],"title":"iconTitleSpace"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallButtonView"]]},"schemaVersion":{"patch":0,"minor":3,"major":0},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"iconTitleSpace","kind":"identifier"},{"text":": ","kind":"text"},{"text":"CGFloat","kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easecalluikit\/callbuttonview\/icontitlespace"]}],"identifier":{"url":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallButtonView\/iconTitleSpace","interfaceLanguage":"swift"},"sections":[],"references":{"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallButtonView/iconTitleSpace":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"iconTitleSpace","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"kind":"symbol","url":"\/documentation\/easecalluikit\/callbuttonview\/icontitlespace","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallButtonView\/iconTitleSpace","type":"topic","title":"iconTitleSpace","role":"symbol"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit":{"title":"EaseCallUIKit","type":"topic","url":"\/documentation\/easecalluikit","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit","abstract":[],"role":"collection","kind":"symbol"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallButtonView":{"title":"CallButtonView","role":"symbol","url":"\/documentation\/easecalluikit\/callbuttonview","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallButtonView","abstract":[],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"CallButtonView"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"CallButtonView","kind":"identifier"}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallButtonView\/title","value":"CallButtonView"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallButtonView\/fragments","op":"replace","value":[{"text":"CallButtonView","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallButtonView\/navigatorTitle","value":[{"text":"CallButtonView","kind":"identifier"}],"op":"replace"}]}]}