{"kind":"symbol","metadata":{"extendedModule":"UIKit","modules":[{"name":"EaseCallUIKit","relatedModules":["UIKit"]}],"title":"callTheme","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"callTheme"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@EaseCallUIKit@objc(cs)CallFontTheme","text":"CallFontTheme","kind":"typeIdentifier"}],"externalID":"c:@CM@EaseCallUIKit@@objc(cs)UIFont(cpy)callTheme","symbolKind":"property","role":"symbol","roleHeading":"Type Property"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/UIKit","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/UIKit\/UIFont"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/UIKit\/UIFont\/callTheme"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easecalluikit\/uikit\/uifont\/calltheme"]}],"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"callTheme","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"CallFontTheme","preciseIdentifier":"c:@M@EaseCallUIKit@objc(cs)CallFontTheme","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallFontTheme"}],"platforms":["iOS"]}],"kind":"declarations"}],"references":{"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallFontTheme":{"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallFontTheme","kind":"symbol","role":"symbol","url":"\/documentation\/easecalluikit\/callfonttheme","navigatorTitle":[{"text":"CallFontTheme","kind":"identifier"}],"title":"CallFontTheme","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CallFontTheme","kind":"identifier"}],"abstract":[]},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit":{"title":"EaseCallUIKit","type":"topic","url":"\/documentation\/easecalluikit","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit","abstract":[],"role":"collection","kind":"symbol"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/UIKit/UIFont":{"kind":"symbol","title":"UIFont","navigatorTitle":[{"text":"UIFont","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/UIKit\/UIFont","url":"\/documentation\/easecalluikit\/uikit\/uifont","role":"symbol","fragments":[{"text":"extension","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UIFont","kind":"identifier","preciseIdentifier":"c:objc(cs)UIFont"}],"abstract":[{"type":"text","text":"A FontTheme extension to provide custom fonts for different text styles."}]},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/UIKit":{"abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/UIKit","title":"UIKit","url":"\/documentation\/easecalluikit\/uikit","kind":"symbol","role":"collection","type":"topic"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/UIKit/UIFont/callTheme":{"type":"topic","url":"\/documentation\/easecalluikit\/uikit\/uifont\/calltheme","kind":"symbol","role":"symbol","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/UIKit\/UIFont\/callTheme","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"callTheme","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseCallUIKit@objc(cs)CallFontTheme","text":"CallFontTheme"}],"title":"callTheme","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"CallFontTheme","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallFontTheme\/title","op":"replace"},{"value":[{"text":"CallFontTheme","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallFontTheme\/fragments","op":"replace"},{"value":[{"text":"CallFontTheme","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallFontTheme\/navigatorTitle","op":"replace"}]}]}