{"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/TimerService\/removeListener(_:timerIdentify:)"},"metadata":{"roleHeading":"Instance Method","required":true,"title":"removeListener(_:timerIdentify:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"removeListener"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@EaseCallUIKit@objc(pl)TimerServiceListener","kind":"typeIdentifier","text":"TimerServiceListener"},{"text":", ","kind":"text"},{"text":"timerIdentify","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"removeListener:timerIdentify:","kind":"identifier"}],"externalID":"c:@M@EaseCallUIKit@objc(pl)TimerService(im)removeListener:timerIdentify:","role":"symbol","symbolKind":"method","modules":[{"name":"EaseCallUIKit"}]},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/TimerService"]]},"abstract":[{"type":"text","text":"Removes a previously added listener from receiving timer-related events."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easecalluikit\/timerservice\/removelistener(_:timeridentify:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easecalluikit\/timerservice\/removelistener(_:timeridentify:)"]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"removeListener","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"text":"listener","kind":"internalParam"},{"kind":"text","text":": "},{"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/TimerServiceListener","preciseIdentifier":"c:@M@EaseCallUIKit@objc(pl)TimerServiceListener","kind":"typeIdentifier","text":"TimerServiceListener"},{"kind":"text","text":", "},{"kind":"externalParam","text":"timerIdentify"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":")","kind":"text"}]}]},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"type":"text","text":"An object conforming to the "},{"type":"reference","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/TimerServiceListener","isActive":true},{"type":"text","text":" protocol that will no longer receive timer events."}],"type":"paragraph"}],"name":"listener"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"A unique identifier for the timer, used to distinguish between different timers."}]}],"name":"timerIdentify"}]}],"references":{"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/TimerServiceListener":{"url":"\/documentation\/easecalluikit\/timerservicelistener","kind":"symbol","role":"symbol","title":"TimerServiceListener","navigatorTitle":[{"text":"TimerServiceListener","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/TimerServiceListener","abstract":[],"type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"TimerServiceListener"}]},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit":{"title":"EaseCallUIKit","type":"topic","url":"\/documentation\/easecalluikit","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit","abstract":[],"role":"collection","kind":"symbol"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/TimerService":{"title":"TimerService","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"TimerService"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/TimerService","url":"\/documentation\/easecalluikit\/timerservice","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TimerService","kind":"identifier"}],"abstract":[]},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/TimerService/removeListener(_:timerIdentify:)":{"abstract":[{"text":"Removes a previously added listener from receiving timer-related events.","type":"text"}],"required":true,"kind":"symbol","title":"removeListener(_:timerIdentify:)","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/TimerService\/removeListener(_:timerIdentify:)","url":"\/documentation\/easecalluikit\/timerservice\/removelistener(_:timeridentify:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"removeListener","kind":"identifier"},{"text":"(","kind":"text"},{"text":"TimerServiceListener","kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseCallUIKit@objc(pl)TimerServiceListener"},{"kind":"text","text":", "},{"text":"timerIdentify","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"removeListener:timerIdentify:","kind":"identifier"}],"role":"symbol","type":"topic"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"removeListener:timerIdentify:","op":"replace"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"removeListener:timerIdentify:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"text":") ","kind":"text"},{"kind":"identifier","text":"removeListener:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:Qo@M@EaseCallUIKit@objc(pl)TimerServiceListener","text":"id<TimerServiceListener>"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"listener"},{"kind":"text","text":" "},{"text":"timerIdentify:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"text":"timerIdentify","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}]},"op":"replace"},{"value":{"kind":"parameters","parameters":[{"name":"listener","content":[{"type":"paragraph","inlineContent":[{"text":"An object conforming to the ","type":"text"},{"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/TimerServiceListener","type":"reference","isActive":true},{"type":"text","text":" protocol that will no longer receive timer events."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"A unique identifier for the timer, used to distinguish between different timers."}]}],"name":"timerIdentify"}]},"op":"replace","path":"\/primaryContentSections\/1"},{"value":"TimerServiceListener","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1TimerServiceListener\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1TimerServiceListener\/fragments","value":[{"text":"TimerServiceListener","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1TimerServiceListener\/navigatorTitle","value":[{"text":"TimerServiceListener","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1TimerService\/title","op":"replace","value":"TimerService"},{"op":"replace","value":[{"text":"TimerService","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1TimerService\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1TimerService\/navigatorTitle","value":[{"text":"TimerService","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1TimerService~1removeListener(_:timerIdentify:)\/title","value":"removeListener:timerIdentify:"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1TimerService~1removeListener(_:timerIdentify:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"removeListener:timerIdentify:","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}