{"identifier":{"url":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/TimerService\/replaceTimer(_:timerIdentify:)","interfaceLanguage":"swift"},"sections":[],"metadata":{"symbolKind":"method","required":true,"externalID":"c:@M@EaseCallUIKit@objc(pl)TimerService(im)replaceTimer:timerIdentify:","title":"replaceTimer(_:timerIdentify:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"replaceTimer","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@EaseCallUIKit@objc(pl)TimerServiceListener","text":"TimerServiceListener","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"timerIdentify"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"replaceTimer:timerIdentify:"}],"modules":[{"name":"EaseCallUIKit"}],"role":"symbol"},"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","abstract":[{"type":"text","text":"Replaces an existing timer with a new one."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"replaceTimer"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"listener"},{"kind":"text","text":": "},{"text":"TimerServiceListener","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/TimerServiceListener","preciseIdentifier":"c:@M@EaseCallUIKit@objc(pl)TimerServiceListener","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"timerIdentify"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"listener","content":[{"type":"paragraph","inlineContent":[{"text":"An object conforming to the ","type":"text"},{"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/TimerServiceListener","type":"reference","isActive":true},{"text":" protocol that will receive timer events.","type":"text"}]}]},{"name":"timerIdentify","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"A unique identifier for the timer, used to distinguish between different timers."}]}]}]}],"variants":[{"paths":["\/documentation\/easecalluikit\/timerservice\/replacetimer(_:timeridentify:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easecalluikit\/timerservice\/replacetimer(_:timeridentify:)"]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/TimerService"]]},"references":{"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/TimerService":{"title":"TimerService","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"TimerService"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/TimerService","url":"\/documentation\/easecalluikit\/timerservice","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TimerService","kind":"identifier"}],"abstract":[]},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit":{"title":"EaseCallUIKit","type":"topic","url":"\/documentation\/easecalluikit","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit","abstract":[],"role":"collection","kind":"symbol"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/TimerService/replaceTimer(_:timerIdentify:)":{"title":"replaceTimer(_:timerIdentify:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"replaceTimer"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@EaseCallUIKit@objc(pl)TimerServiceListener","kind":"typeIdentifier","text":"TimerServiceListener"},{"kind":"text","text":", "},{"text":"timerIdentify","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":")","kind":"text"}],"abstract":[{"type":"text","text":"Replaces an existing timer with a new one."}],"kind":"symbol","type":"topic","url":"\/documentation\/easecalluikit\/timerservice\/replacetimer(_:timeridentify:)","required":true,"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/TimerService\/replaceTimer(_:timerIdentify:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"replaceTimer:timerIdentify:"}]},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/TimerServiceListener":{"url":"\/documentation\/easecalluikit\/timerservicelistener","kind":"symbol","role":"symbol","title":"TimerServiceListener","navigatorTitle":[{"text":"TimerServiceListener","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/TimerServiceListener","abstract":[],"type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"TimerServiceListener"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","value":"replaceTimer:timerIdentify:","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"replaceTimer:timerIdentify:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"replaceTimer:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"id<TimerServiceListener>","preciseIdentifier":"c:Qo@M@EaseCallUIKit@objc(pl)TimerServiceListener"},{"text":") ","kind":"text"},{"text":"listener","kind":"internalParam"},{"kind":"text","text":" "},{"text":"timerIdentify:","kind":"identifier"},{"kind":"text","text":"("},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"timerIdentify"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"type":"text","text":"An object conforming to the "},{"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/TimerServiceListener","isActive":true,"type":"reference"},{"text":" protocol that will receive timer events.","type":"text"}],"type":"paragraph"}],"name":"listener"},{"name":"timerIdentify","content":[{"inlineContent":[{"type":"text","text":"A unique identifier for the timer, used to distinguish between different timers."}],"type":"paragraph"}]}]}},{"op":"replace","value":"TimerService","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1TimerService\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1TimerService\/fragments","op":"replace","value":[{"text":"TimerService","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1TimerService\/navigatorTitle","value":[{"kind":"identifier","text":"TimerService"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1TimerService~1replaceTimer(_:timerIdentify:)\/title","value":"replaceTimer:timerIdentify:"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1TimerService~1replaceTimer(_:timerIdentify:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"replaceTimer:timerIdentify:"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1TimerServiceListener\/title","value":"TimerServiceListener"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1TimerServiceListener\/fragments","value":[{"text":"TimerServiceListener","kind":"identifier"}],"op":"replace"},{"value":[{"kind":"identifier","text":"TimerServiceListener"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1TimerServiceListener\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}