{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallPopupView"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"callCardAction"},{"text":": ((","kind":"text"},{"kind":"typeIdentifier","text":"RingAlertAction","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/RingAlertAction","preciseIdentifier":"c:@M@EaseCallUIKit@E@RingAlertAction"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"kind":"text","text":")?"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easecalluikit\/callpopupview\/callcardaction"]}],"sections":[],"kind":"symbol","identifier":{"url":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallPopupView\/callCardAction","interfaceLanguage":"swift"},"metadata":{"modules":[{"name":"EaseCallUIKit"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"callCardAction"},{"kind":"text","text":": (("},{"text":"RingAlertAction","kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseCallUIKit@E@RingAlertAction"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"kind":"text","text":")?"}],"role":"symbol","symbolKind":"property","title":"callCardAction","externalID":"s:13EaseCallUIKit0B9PopupViewC14callCardActionyAA09RingAlertH0OcSgvp","roleHeading":"Instance Property"},"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit":{"title":"EaseCallUIKit","type":"topic","url":"\/documentation\/easecalluikit","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit","abstract":[],"role":"collection","kind":"symbol"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/RingAlertAction":{"abstract":[],"role":"symbol","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RingAlertAction","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"RingAlertAction"}],"type":"topic","title":"RingAlertAction","url":"\/documentation\/easecalluikit\/ringalertaction","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/RingAlertAction"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallPopupView":{"kind":"symbol","url":"\/documentation\/easecalluikit\/callpopupview","abstract":[],"title":"CallPopupView","navigatorTitle":[{"kind":"identifier","text":"CallPopupView"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallPopupView","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CallPopupView"}],"role":"symbol"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallPopupView/callCardAction":{"title":"callCardAction","url":"\/documentation\/easecalluikit\/callpopupview\/callcardaction","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"callCardAction","kind":"identifier"},{"text":": ((","kind":"text"},{"preciseIdentifier":"c:@M@EaseCallUIKit@E@RingAlertAction","kind":"typeIdentifier","text":"RingAlertAction"},{"kind":"text","text":") -> "},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?"}],"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallPopupView\/callCardAction","kind":"symbol","abstract":[],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1RingAlertAction\/title","value":"RingAlertAction","op":"replace"},{"value":[{"kind":"identifier","text":"RingAlertAction"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1RingAlertAction\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1RingAlertAction\/navigatorTitle","value":[{"text":"RingAlertAction","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallPopupView\/title","op":"replace","value":"CallPopupView"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallPopupView\/fragments","op":"replace","value":[{"kind":"identifier","text":"CallPopupView"}]},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallPopupView\/navigatorTitle","op":"replace","value":[{"text":"CallPopupView","kind":"identifier"}]}]}]}