{"kind":"symbol","metadata":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"checkbox","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIImageView","text":"UIImageView","kind":"typeIdentifier"}],"roleHeading":"Instance Property","symbolKind":"property","modules":[{"name":"EaseCallUIKit"}],"title":"checkbox","externalID":"s:13EaseCallUIKit21GroupParticipantsCellC8checkboxSo11UIImageViewCvp","role":"symbol"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/GroupParticipantsCell\/checkbox"},"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/GroupParticipantsCell"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easecalluikit\/groupparticipantscell\/checkbox"]}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"kind":"keyword","text":"lazy"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"checkbox","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIImageView","text":"UIImageView","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"references":{"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/GroupParticipantsCell/checkbox":{"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"checkbox"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImageView","text":"UIImageView"}],"kind":"symbol","abstract":[],"url":"\/documentation\/easecalluikit\/groupparticipantscell\/checkbox","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/GroupParticipantsCell\/checkbox","type":"topic","title":"checkbox","role":"symbol"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/GroupParticipantsCell":{"kind":"symbol","title":"GroupParticipantsCell","navigatorTitle":[{"text":"GroupParticipantsCell","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/GroupParticipantsCell","url":"\/documentation\/easecalluikit\/groupparticipantscell","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"GroupParticipantsCell","kind":"identifier"}],"abstract":[]},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit":{"title":"EaseCallUIKit","type":"topic","url":"\/documentation\/easecalluikit","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit","abstract":[],"role":"collection","kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1GroupParticipantsCell\/title","value":"GroupParticipantsCell"},{"op":"replace","value":[{"kind":"identifier","text":"GroupParticipantsCell"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1GroupParticipantsCell\/fragments"},{"value":[{"kind":"identifier","text":"GroupParticipantsCell"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1GroupParticipantsCell\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}