{"metadata":{"roleHeading":"Case","role":"symbol","title":"ChatNavigationBarClickEvent.back","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"back"}],"navigatorTitle":[{"text":"ChatNavigationBarClickEventBack","kind":"identifier"}],"externalID":"c:@M@EaseCallUIKit@E@ChatNavigationBarClickEvent@ChatNavigationBarClickEventBack","symbolKind":"case","modules":[{"name":"EaseCallUIKit"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/ChatNavigationBarClickEvent"]]},"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/ChatNavigationBarClickEvent\/back"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"back","kind":"identifier"}],"languages":["swift"]}]}],"variants":[{"paths":["\/documentation\/easecalluikit\/chatnavigationbarclickevent\/back"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easecalluikit\/chatnavigationbarclickevent\/back"]}],"references":{"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/ChatNavigationBarClickEvent":{"title":"ChatNavigationBarClickEvent","role":"symbol","abstract":[],"type":"topic","kind":"symbol","navigatorTitle":[{"text":"ChatNavigationBarClickEvent","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"ChatNavigationBarClickEvent","kind":"identifier"}],"url":"\/documentation\/easecalluikit\/chatnavigationbarclickevent","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/ChatNavigationBarClickEvent"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/ChatNavigationBarClickEvent/back":{"navigatorTitle":[{"text":"ChatNavigationBarClickEventBack","kind":"identifier"}],"url":"\/documentation\/easecalluikit\/chatnavigationbarclickevent\/back","kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"back","kind":"identifier"}],"title":"ChatNavigationBarClickEvent.back","abstract":[],"type":"topic","role":"symbol","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/ChatNavigationBarClickEvent\/back"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit":{"title":"EaseCallUIKit","type":"topic","url":"\/documentation\/easecalluikit","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit","abstract":[],"role":"collection","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Enumeration Case","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"ChatNavigationBarClickEventBack"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"value":[{"text":"ChatNavigationBarClickEventBack","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"ChatNavigationBarClickEventBack"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1ChatNavigationBarClickEvent\/title","value":"ChatNavigationBarClickEvent"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1ChatNavigationBarClickEvent\/fragments","value":[{"kind":"identifier","text":"ChatNavigationBarClickEvent"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1ChatNavigationBarClickEvent\/navigatorTitle","value":[{"text":"ChatNavigationBarClickEvent","kind":"identifier"}]},{"op":"replace","value":"ChatNavigationBarClickEventBack","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1ChatNavigationBarClickEvent~1back\/title"},{"op":"replace","value":[{"text":"ChatNavigationBarClickEventBack","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1ChatNavigationBarClickEvent~1back\/fragments"}]}]}