{"kind":"article","sections":[],"metadata":{"roleHeading":"API Collection","modules":[{"name":"EaseCallUIKit"}],"title":"Equatable Implementations","role":"collectionGroup"},"identifier":{"url":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/ChatNavigationBarClickEvent\/Equatable-Implementations","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/ChatNavigationBarClickEvent"]]},"topicSections":[{"identifiers":["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/ChatNavigationBarClickEvent\/!=(_:_:)"],"generated":true,"title":"Operators","anchor":"Operators"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easecalluikit\/chatnavigationbarclickevent\/equatable-implementations"]}],"references":{"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit":{"title":"EaseCallUIKit","type":"topic","url":"\/documentation\/easecalluikit","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit","abstract":[],"role":"collection","kind":"symbol"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/ChatNavigationBarClickEvent":{"title":"ChatNavigationBarClickEvent","role":"symbol","abstract":[],"type":"topic","kind":"symbol","navigatorTitle":[{"text":"ChatNavigationBarClickEvent","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"ChatNavigationBarClickEvent","kind":"identifier"}],"url":"\/documentation\/easecalluikit\/chatnavigationbarclickevent","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/ChatNavigationBarClickEvent"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/ChatNavigationBarClickEvent/!=(_:_:)":{"title":"!=(_:_:)","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/ChatNavigationBarClickEvent\/!=(_:_:)","role":"symbol","url":"\/documentation\/easecalluikit\/chatnavigationbarclickevent\/!=(_:_:)","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"!=","kind":"identifier"},{"text":" ","kind":"text"},{"kind":"text","text":"("},{"text":"Self","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"type":"topic","kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"ChatNavigationBarClickEvent","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1ChatNavigationBarClickEvent\/title"},{"value":[{"text":"ChatNavigationBarClickEvent","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1ChatNavigationBarClickEvent\/fragments"},{"value":[{"text":"ChatNavigationBarClickEvent","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1ChatNavigationBarClickEvent\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}