{"kind":"symbol","metadata":{"modules":[{"name":"EaseCallUIKit"}],"roleHeading":"Case","title":"ChatNavigationBarClickEvent.rightTitle","navigatorTitle":[{"kind":"identifier","text":"ChatNavigationBarClickEventRightTitle"}],"role":"symbol","symbolKind":"case","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"rightTitle","kind":"identifier"}],"externalID":"c:@M@EaseCallUIKit@E@ChatNavigationBarClickEvent@ChatNavigationBarClickEventRightTitle"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/ChatNavigationBarClickEvent\/rightTitle"},"schemaVersion":{"patch":0,"minor":3,"major":0},"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/ChatNavigationBarClickEvent"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easecalluikit\/chatnavigationbarclickevent\/righttitle"]},{"paths":["\/documentation\/easecalluikit\/chatnavigationbarclickevent\/righttitle"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"rightTitle"}]}],"kind":"declarations"}],"references":{"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit":{"title":"EaseCallUIKit","type":"topic","url":"\/documentation\/easecalluikit","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit","abstract":[],"role":"collection","kind":"symbol"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/ChatNavigationBarClickEvent/rightTitle":{"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/ChatNavigationBarClickEvent\/rightTitle","kind":"symbol","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"rightTitle"}],"type":"topic","url":"\/documentation\/easecalluikit\/chatnavigationbarclickevent\/righttitle","abstract":[],"navigatorTitle":[{"text":"ChatNavigationBarClickEventRightTitle","kind":"identifier"}],"title":"ChatNavigationBarClickEvent.rightTitle"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/ChatNavigationBarClickEvent":{"title":"ChatNavigationBarClickEvent","role":"symbol","abstract":[],"type":"topic","kind":"symbol","navigatorTitle":[{"text":"ChatNavigationBarClickEvent","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"ChatNavigationBarClickEvent","kind":"identifier"}],"url":"\/documentation\/easecalluikit\/chatnavigationbarclickevent","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/ChatNavigationBarClickEvent"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"ChatNavigationBarClickEventRightTitle"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"ChatNavigationBarClickEventRightTitle","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"ChatNavigationBarClickEventRightTitle"}]}]}},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1ChatNavigationBarClickEvent~1rightTitle\/title","value":"ChatNavigationBarClickEventRightTitle","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1ChatNavigationBarClickEvent~1rightTitle\/fragments","value":[{"kind":"identifier","text":"ChatNavigationBarClickEventRightTitle"}]},{"value":"ChatNavigationBarClickEvent","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1ChatNavigationBarClickEvent\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1ChatNavigationBarClickEvent\/fragments","value":[{"text":"ChatNavigationBarClickEvent","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1ChatNavigationBarClickEvent\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"ChatNavigationBarClickEvent"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}