{"metadata":{"roleHeading":"Instance Property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"actionClosure"},{"kind":"text","text":": (("},{"preciseIdentifier":"c:@M@EaseCallUIKit@E@RingAlertAction","text":"RingAlertAction","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"kind":"text","text":")?"}],"role":"symbol","symbolKind":"property","title":"actionClosure","externalID":"s:13EaseCallUIKit9RingAlertC13actionClosureyAA0dE6ActionOcSgvp","modules":[{"name":"EaseCallUIKit"}]},"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easecalluikit\/ringalert\/actionclosure"]}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/RingAlert\/actionClosure"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@","kind":"attribute"},{"kind":"attribute","text":"MainActor","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"actionClosure"},{"text":": ((","kind":"text"},{"kind":"typeIdentifier","text":"RingAlertAction","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/RingAlertAction","preciseIdentifier":"c:@M@EaseCallUIKit@E@RingAlertAction"},{"text":") -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")?","kind":"text"}]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/RingAlert"]]},"references":{"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit":{"title":"EaseCallUIKit","type":"topic","url":"\/documentation\/easecalluikit","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit","abstract":[],"role":"collection","kind":"symbol"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/RingAlert/actionClosure":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/RingAlert\/actionClosure","abstract":[],"url":"\/documentation\/easecalluikit\/ringalert\/actionclosure","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"actionClosure","kind":"identifier"},{"text":": ((","kind":"text"},{"preciseIdentifier":"c:@M@EaseCallUIKit@E@RingAlertAction","text":"RingAlertAction","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"kind":"text","text":")?"}],"role":"symbol","type":"topic","title":"actionClosure"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/RingAlert":{"url":"\/documentation\/easecalluikit\/ringalert","type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"RingAlert"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/RingAlert","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RingAlert","kind":"identifier"}],"title":"RingAlert","abstract":[]},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/RingAlertAction":{"abstract":[],"role":"symbol","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RingAlertAction","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"RingAlertAction"}],"type":"topic","title":"RingAlertAction","url":"\/documentation\/easecalluikit\/ringalertaction","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/RingAlertAction"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"RingAlert","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1RingAlert\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1RingAlert\/fragments","value":[{"text":"RingAlert","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1RingAlert\/navigatorTitle","value":[{"text":"RingAlert","kind":"identifier"}]},{"value":"RingAlertAction","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1RingAlertAction\/title"},{"op":"replace","value":[{"kind":"identifier","text":"RingAlertAction"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1RingAlertAction\/fragments"},{"value":[{"text":"RingAlertAction","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1RingAlertAction\/navigatorTitle"}]}]}