{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallErrorPattern\/business(_:)"},"metadata":{"roleHeading":"Type Method","title":"business(_:)","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"business"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@EaseCallUIKit@E@CallBusinessErrorCode","text":"CallBusinessErrorCode","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"CallErrorPattern","preciseIdentifier":"s:13EaseCallUIKit0B12ErrorPatternV"}],"modules":[{"name":"EaseCallUIKit"}],"externalID":"s:13EaseCallUIKit0B12ErrorPatternV8businessyAcA0b8BusinessD4CodeOFZ","symbolKind":"method","role":"symbol"},"kind":"symbol","abstract":[{"type":"text","text":"Business logic error pattern"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallErrorPattern"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"paths":["\/documentation\/easecalluikit\/callerrorpattern\/business(_:)"],"traits":[{"interfaceLanguage":"swift"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"business","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"text":"error","kind":"internalParam"},{"kind":"text","text":": "},{"text":"CallBusinessErrorCode","preciseIdentifier":"c:@M@EaseCallUIKit@E@CallBusinessErrorCode","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallBusinessErrorCode"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:13EaseCallUIKit0B12ErrorPatternV","kind":"typeIdentifier","text":"CallErrorPattern","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallErrorPattern"}],"platforms":["iOS"]}]}],"sections":[],"references":{"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallErrorPattern/business(_:)":{"kind":"symbol","title":"business(_:)","url":"\/documentation\/easecalluikit\/callerrorpattern\/business(_:)","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"business","kind":"identifier"},{"kind":"text","text":"("},{"text":"CallBusinessErrorCode","preciseIdentifier":"c:@M@EaseCallUIKit@E@CallBusinessErrorCode","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:13EaseCallUIKit0B12ErrorPatternV","text":"CallErrorPattern","kind":"typeIdentifier"}],"role":"symbol","abstract":[{"text":"Business logic error pattern","type":"text"}],"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallErrorPattern\/business(_:)","type":"topic"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallErrorPattern":{"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CallErrorPattern","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"CallErrorPattern","kind":"identifier"}],"role":"symbol","url":"\/documentation\/easecalluikit\/callerrorpattern","title":"CallErrorPattern","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallErrorPattern","abstract":[{"type":"text","text":"First, define the CallErrorPattern struct to encapsulate the error pattern matching logic."}],"type":"topic"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit":{"title":"EaseCallUIKit","type":"topic","url":"\/documentation\/easecalluikit","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit","abstract":[],"role":"collection","kind":"symbol"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallBusinessErrorCode":{"abstract":[],"type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"CallBusinessErrorCode","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallBusinessErrorCode","role":"symbol","title":"CallBusinessErrorCode","navigatorTitle":[{"text":"CallBusinessErrorCode","kind":"identifier"}],"url":"\/documentation\/easecalluikit\/callbusinesserrorcode"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallBusinessErrorCode\/title","value":"CallBusinessErrorCode"},{"value":[{"text":"CallBusinessErrorCode","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallBusinessErrorCode\/fragments"},{"value":[{"kind":"identifier","text":"CallBusinessErrorCode"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallBusinessErrorCode\/navigatorTitle"}]}]}