{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"graduentColors6","kind":"identifier"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor","kind":"typeIdentifier"},{"text":"]","kind":"text"}],"languages":["swift"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/GradientColors"]]},"sections":[],"variants":[{"paths":["\/documentation\/easecalluikit\/gradientcolors\/graduentcolors6"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/easecalluikit\/gradientcolors\/graduentcolors6"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","metadata":{"modules":[{"name":"EaseCallUIKit"}],"externalID":"c:@M@EaseCallUIKit@objc(cs)GradientColors(cpy)graduentColors6","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"graduentColors6"},{"text":": [","kind":"text"},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":"]"}],"navigatorTitle":[{"text":"graduentColors6","kind":"identifier"}],"symbolKind":"property","role":"symbol","title":"graduentColors6","roleHeading":"Type Property"},"identifier":{"url":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/GradientColors\/graduentColors6","interfaceLanguage":"swift"},"references":{"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/GradientColors":{"type":"topic","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/GradientColors","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GradientColors"}],"kind":"symbol","title":"GradientColors","role":"symbol","navigatorTitle":[{"text":"GradientColors","kind":"identifier"}],"abstract":[],"url":"\/documentation\/easecalluikit\/gradientcolors"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit":{"title":"EaseCallUIKit","type":"topic","url":"\/documentation\/easecalluikit","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit","abstract":[],"role":"collection","kind":"symbol"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/GradientColors/graduentColors6":{"fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"graduentColors6","kind":"identifier"},{"kind":"text","text":": ["},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":"]"}],"navigatorTitle":[{"text":"graduentColors6","kind":"identifier"}],"abstract":[],"type":"topic","kind":"symbol","url":"\/documentation\/easecalluikit\/gradientcolors\/graduentcolors6","title":"graduentColors6","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/GradientColors\/graduentColors6","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Property"},{"path":"\/metadata\/title","op":"replace","value":"graduentColors6"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"graduentColors6"}]},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"class"},{"text":", ","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<UIColor *>","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"graduentColors6"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1GradientColors\/title","value":"GradientColors","op":"replace"},{"value":[{"kind":"identifier","text":"GradientColors"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1GradientColors\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1GradientColors\/navigatorTitle","value":[{"kind":"identifier","text":"GradientColors"}],"op":"replace"},{"value":"graduentColors6","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1GradientColors~1graduentColors6\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1GradientColors~1graduentColors6\/fragments","value":[{"kind":"identifier","text":"graduentColors6"}]}]}]}