{"sections":[],"metadata":{"symbolKind":"method","role":"symbol","modules":[{"name":"EaseCallUIKit"}],"fragments":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}],"roleHeading":"Instance Method","externalID":"c:@M@EaseCallUIKit@objc(cs)GradientColors(im)init","navigatorTitle":[{"kind":"identifier","text":"init"}],"title":"init"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"text":"id","kind":"typeIdentifier","preciseIdentifier":"c:*Qo"},{"text":") ","kind":"text"},{"kind":"identifier","text":"init"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}],"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easecalluikit\/gradientcolors\/init"]}],"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/GradientColors\/init"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/GradientColors"]]},"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/GradientColors":{"type":"topic","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/GradientColors","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GradientColors"}],"kind":"symbol","title":"GradientColors","role":"symbol","navigatorTitle":[{"text":"GradientColors","kind":"identifier"}],"abstract":[],"url":"\/documentation\/easecalluikit\/gradientcolors"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/GradientColors/init":{"navigatorTitle":[{"kind":"identifier","text":"init"}],"type":"topic","title":"init","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/GradientColors\/init","fragments":[{"kind":"text","text":"- "},{"text":"init","kind":"identifier"}],"role":"symbol","url":"\/documentation\/easecalluikit\/gradientcolors\/init","kind":"symbol","abstract":[]},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit":{"title":"EaseCallUIKit","type":"topic","url":"\/documentation\/easecalluikit","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit","abstract":[],"role":"collection","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"GradientColors","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1GradientColors\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1GradientColors\/fragments","op":"replace","value":[{"kind":"identifier","text":"GradientColors"}]},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1GradientColors\/navigatorTitle","value":[{"text":"GradientColors","kind":"identifier"}],"op":"replace"}]}]}