{"abstract":[{"type":"text","text":"The corner radius of the avatar image view of "},{"type":"codeVoice","code":"ChatInputBar"},{"type":"text","text":"."}],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"avatarRadius","kind":"identifier"},{"text":": EaseCallUIKit","kind":"text"},{"text":".","kind":"text"},{"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CornerRadius","preciseIdentifier":"s:13EaseCallUIKit12CornerRadiusO","kind":"typeIdentifier","text":"CornerRadius"}],"platforms":["iOS"],"languages":["swift"]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallAppearance\/avatarRadius"},"variants":[{"paths":["\/documentation\/easecalluikit\/callappearance\/avatarradius"],"traits":[{"interfaceLanguage":"swift"}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallAppearance"]]},"metadata":{"title":"avatarRadius","externalID":"s:13EaseCallUIKit0B10AppearanceC12avatarRadiusAA06CornerF0OvpZ","modules":[{"name":"EaseCallUIKit"}],"roleHeading":"Type Property","symbolKind":"property","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"avatarRadius"},{"text":": EaseCallUIKit","kind":"text"},{"text":".","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:13EaseCallUIKit12CornerRadiusO","text":"CornerRadius"}],"role":"symbol"},"references":{"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallAppearance/avatarRadius":{"abstract":[{"text":"The corner radius of the avatar image view of ","type":"text"},{"type":"codeVoice","code":"ChatInputBar"},{"text":".","type":"text"}],"title":"avatarRadius","url":"\/documentation\/easecalluikit\/callappearance\/avatarradius","type":"topic","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallAppearance\/avatarRadius","kind":"symbol","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"avatarRadius","kind":"identifier"},{"kind":"text","text":": EaseCallUIKit"},{"text":".","kind":"text"},{"text":"CornerRadius","kind":"typeIdentifier","preciseIdentifier":"s:13EaseCallUIKit12CornerRadiusO"}]},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit":{"title":"EaseCallUIKit","type":"topic","url":"\/documentation\/easecalluikit","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit","abstract":[],"role":"collection","kind":"symbol"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallAppearance":{"title":"CallAppearance","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CallAppearance"}],"url":"\/documentation\/easecalluikit\/callappearance","type":"topic","role":"symbol","navigatorTitle":[{"text":"CallAppearance","kind":"identifier"}],"abstract":[{"type":"text","text":"An object containing visual configurations for the whole application."}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallAppearance"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CornerRadius":{"url":"\/documentation\/easecalluikit\/cornerradius","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CornerRadius","kind":"symbol","navigatorTitle":[{"text":"CornerRadius","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"CornerRadius"}],"abstract":[{"text":"A set of convenience methods for configuring UIView properties, such as corner radius, background color, gradient, content mode, layer properties, user interaction, tag, center, and transform.","type":"text"}],"role":"symbol","title":"CornerRadius","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"CallAppearance","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallAppearance\/title","op":"replace"},{"op":"replace","value":[{"text":"CallAppearance","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallAppearance\/fragments"},{"op":"replace","value":[{"text":"CallAppearance","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallAppearance\/navigatorTitle"}]}]}