{"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"type":"text","text":"Language type."}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easecalluikit\/callappearance\/call_language"]}],"metadata":{"roleHeading":"Type Property","role":"symbol","modules":[{"name":"EaseCallUIKit"}],"externalID":"s:13EaseCallUIKit0B10AppearanceC13call_languageAA12LanguageTypeOvpZ","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"call_language"},{"text":": ","kind":"text"},{"text":"LanguageType","preciseIdentifier":"s:13EaseCallUIKit12LanguageTypeO","kind":"typeIdentifier"}],"symbolKind":"property","title":"call_language"},"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"call_language","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/LanguageType","preciseIdentifier":"s:13EaseCallUIKit12LanguageTypeO","text":"LanguageType"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallAppearance\/call_language"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallAppearance"]]},"references":{"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit":{"title":"EaseCallUIKit","type":"topic","url":"\/documentation\/easecalluikit","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit","abstract":[],"role":"collection","kind":"symbol"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/LanguageType":{"url":"\/documentation\/easecalluikit\/languagetype","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/LanguageType","role":"symbol","abstract":[],"type":"topic","title":"LanguageType","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"LanguageType","kind":"identifier"}],"navigatorTitle":[{"text":"LanguageType","kind":"identifier"}],"kind":"symbol"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallAppearance":{"title":"CallAppearance","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CallAppearance"}],"url":"\/documentation\/easecalluikit\/callappearance","type":"topic","role":"symbol","navigatorTitle":[{"text":"CallAppearance","kind":"identifier"}],"abstract":[{"type":"text","text":"An object containing visual configurations for the whole application."}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallAppearance"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallAppearance/call_language":{"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"call_language","kind":"identifier"},{"text":": ","kind":"text"},{"text":"LanguageType","preciseIdentifier":"s:13EaseCallUIKit12LanguageTypeO","kind":"typeIdentifier"}],"url":"\/documentation\/easecalluikit\/callappearance\/call_language","type":"topic","title":"call_language","role":"symbol","abstract":[{"text":"Language type.","type":"text"}],"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallAppearance\/call_language","kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallAppearance\/title","value":"CallAppearance"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallAppearance\/fragments","value":[{"text":"CallAppearance","kind":"identifier"}]},{"value":[{"text":"CallAppearance","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallAppearance\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}