{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@","kind":"attribute"},{"preciseIdentifier":"s:ScM","text":"MainActor","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"isAudioMuted","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/easecalluikit\/pixelbufferrenderview\/isaudiomuted"],"traits":[{"interfaceLanguage":"swift"}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/PixelBufferRenderView\/isAudioMuted"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/PixelBufferRenderView"]]},"kind":"symbol","sections":[],"metadata":{"externalID":"s:13EaseCallUIKit21PixelBufferRenderViewC12isAudioMutedSbvp","symbolKind":"property","title":"isAudioMuted","roleHeading":"Instance Property","modules":[{"name":"EaseCallUIKit"}],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"isAudioMuted","kind":"identifier"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}]},"references":{"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/PixelBufferRenderView":{"role":"symbol","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/PixelBufferRenderView","url":"\/documentation\/easecalluikit\/pixelbufferrenderview","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PixelBufferRenderView"}],"abstract":[],"kind":"symbol","title":"PixelBufferRenderView","navigatorTitle":[{"text":"PixelBufferRenderView","kind":"identifier"}],"type":"topic"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit":{"title":"EaseCallUIKit","type":"topic","url":"\/documentation\/easecalluikit","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit","abstract":[],"role":"collection","kind":"symbol"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/PixelBufferRenderView/isAudioMuted":{"url":"\/documentation\/easecalluikit\/pixelbufferrenderview\/isaudiomuted","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isAudioMuted"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"type":"topic","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/PixelBufferRenderView\/isAudioMuted","title":"isAudioMuted"}},"variantOverrides":[{"patch":[{"op":"replace","value":"PixelBufferRenderView","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1PixelBufferRenderView\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1PixelBufferRenderView\/fragments","op":"replace","value":[{"text":"PixelBufferRenderView","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1PixelBufferRenderView\/navigatorTitle","op":"replace","value":[{"text":"PixelBufferRenderView","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}