{"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easecalluikit\/hyphenatechat\/emchatmessage\/callinfo"]}],"metadata":{"roleHeading":"Instance Property","externalID":"s:So13EMChatMessageC13EaseCallUIKitE8callInfoAC0dG0CSgvp","role":"symbol","modules":[{"name":"EaseCallUIKit","relatedModules":["HyphenateChat"]}],"extendedModule":"HyphenateChat","title":"callInfo","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"callInfo","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseCallUIKit@objc(cs)CallInfo","text":"CallInfo"},{"text":"?","kind":"text"}],"symbolKind":"property"},"identifier":{"url":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/HyphenateChat\/EMChatMessage\/callInfo","interfaceLanguage":"swift"},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"callInfo"},{"text":": ","kind":"text"},{"text":"CallInfo","preciseIdentifier":"c:@M@EaseCallUIKit@objc(cs)CallInfo","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallInfo","kind":"typeIdentifier"},{"text":"? { ","kind":"text"},{"text":"get","kind":"keyword"},{"kind":"text","text":" }"}],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/HyphenateChat","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/HyphenateChat\/EMChatMessage"]]},"references":{"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/HyphenateChat/EMChatMessage/callInfo":{"url":"\/documentation\/easecalluikit\/hyphenatechat\/emchatmessage\/callinfo","role":"symbol","title":"callInfo","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/HyphenateChat\/EMChatMessage\/callInfo","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"callInfo"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@EaseCallUIKit@objc(cs)CallInfo","text":"CallInfo","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"type":"topic"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/HyphenateChat":{"kind":"symbol","title":"HyphenateChat","type":"topic","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/HyphenateChat","url":"\/documentation\/easecalluikit\/hyphenatechat","role":"collection","abstract":[]},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit":{"title":"EaseCallUIKit","type":"topic","url":"\/documentation\/easecalluikit","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit","abstract":[],"role":"collection","kind":"symbol"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/HyphenateChat/EMChatMessage":{"navigatorTitle":[{"kind":"identifier","text":"EMChatMessage"}],"abstract":[],"kind":"symbol","role":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/HyphenateChat\/EMChatMessage","url":"\/documentation\/easecalluikit\/hyphenatechat\/emchatmessage","fragments":[{"text":"extension","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ChatMessage","kind":"typeIdentifier","preciseIdentifier":"s:13EaseCallUIKit11ChatMessagea"}],"title":"EMChatMessage"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallInfo":{"navigatorTitle":[{"text":"CallInfo","kind":"identifier"}],"title":"CallInfo","url":"\/documentation\/easecalluikit\/callinfo","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CallInfo","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallInfo","type":"topic","kind":"symbol","abstract":[],"role":"symbol"}},"variantOverrides":[{"patch":[{"value":"CallInfo","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallInfo\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallInfo\/fragments","value":[{"text":"CallInfo","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallInfo\/navigatorTitle","value":[{"kind":"identifier","text":"CallInfo"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}