{"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/Theme\/init"},"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"roleHeading":"Instance Method","externalID":"c:@M@EaseCallUIKit@objc(cs)Theme(im)init","fragments":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}],"symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"init"}],"role":"symbol","title":"init","modules":[{"name":"EaseCallUIKit"}]},"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:*Qo","kind":"typeIdentifier","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"init"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/easecalluikit\/theme\/init"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/Theme"]]},"references":{"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit":{"title":"EaseCallUIKit","type":"topic","url":"\/documentation\/easecalluikit","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit","abstract":[],"role":"collection","kind":"symbol"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/Theme/init":{"abstract":[],"kind":"symbol","title":"init","url":"\/documentation\/easecalluikit\/theme\/init","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/Theme\/init","fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"init"}],"navigatorTitle":[{"text":"init","kind":"identifier"}],"role":"symbol","type":"topic"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/Theme":{"kind":"symbol","title":"Theme","navigatorTitle":[{"text":"Theme","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/Theme","url":"\/documentation\/easecalluikit\/theme","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Theme"}],"abstract":[{"type":"text","text":"The theme switching class is used for users to switch themes or register some user’s own views that comply with the ThemeSwitchProtocol protocol."},{"type":"text","text":" "},{"text":"How to use?","type":"text"},{"type":"text","text":" "},{"text":"A view conform ThemeSwitchProtocol.Then Implement protocol methods.When you want switch theme that light and dark themes provided by default chatroom UIKit  ","type":"text"},{"type":"codeVoice","code":"theme"},{"type":"text","text":" ."},{"text":" ","type":"text"},{"type":"text","text":"Call "},{"type":"codeVoice","code":"Theme.switchTheme(style: .dark)"},{"text":" method","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"A view conform ThemeSwitchProtocol.Then Implement protocol methods.When you want switch themes provided by customer ."}]}},"variantOverrides":[{"patch":[{"value":"Theme","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1Theme\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1Theme\/fragments","value":[{"text":"Theme","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1Theme\/navigatorTitle","value":[{"text":"Theme","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}