{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/Theme"]]},"identifier":{"url":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/Theme\/registerSwitchThemeViews(view:)","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"registerSwitchThemeViews","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"view"},{"kind":"text","text":": "},{"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/ThemeSwitchProtocol","text":"ThemeSwitchProtocol","preciseIdentifier":"c:@M@EaseCallUIKit@objc(pl)ThemeSwitchProtocol","kind":"typeIdentifier"},{"text":")","kind":"text"}]}]},{"parameters":[{"content":[{"inlineContent":[{"text":"The view conform ThemeSwitchProtocol.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"How to use?"},{"text":" ","type":"text"},{"type":"codeVoice","code":"Theme.registerSwitchThemeViews(view: Some view implement ThemeSwitchProtocol)"}],"type":"paragraph"}],"name":"view"}],"kind":"parameters"}],"kind":"symbol","metadata":{"symbolKind":"method","title":"registerSwitchThemeViews(view:)","role":"symbol","roleHeading":"Type Method","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"registerSwitchThemeViews","kind":"identifier"},{"kind":"text","text":"("},{"text":"view","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@EaseCallUIKit@objc(pl)ThemeSwitchProtocol","text":"ThemeSwitchProtocol","kind":"typeIdentifier"},{"kind":"text","text":")"}],"navigatorTitle":[{"text":"registerSwitchThemeViewsWithView:","kind":"identifier"}],"modules":[{"name":"EaseCallUIKit"}],"externalID":"c:@M@EaseCallUIKit@objc(cs)Theme(cm)registerSwitchThemeViewsWithView:"},"abstract":[{"text":"Register some user’s own views that Implement with the ThemeSwitchProtocol protocol.","type":"text"}],"variants":[{"paths":["\/documentation\/easecalluikit\/theme\/registerswitchthemeviews(view:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easecalluikit\/theme\/registerswitchthemeviews(view:)"]}],"sections":[],"references":{"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/Theme/registerSwitchThemeViews(view:)":{"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/Theme\/registerSwitchThemeViews(view:)","type":"topic","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"registerSwitchThemeViews"},{"kind":"text","text":"("},{"kind":"externalParam","text":"view"},{"kind":"text","text":": "},{"text":"ThemeSwitchProtocol","kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseCallUIKit@objc(pl)ThemeSwitchProtocol"},{"text":")","kind":"text"}],"url":"\/documentation\/easecalluikit\/theme\/registerswitchthemeviews(view:)","navigatorTitle":[{"text":"registerSwitchThemeViewsWithView:","kind":"identifier"}],"title":"registerSwitchThemeViews(view:)","abstract":[{"text":"Register some user’s own views that Implement with the ThemeSwitchProtocol protocol.","type":"text"}],"kind":"symbol"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/Theme":{"kind":"symbol","title":"Theme","navigatorTitle":[{"text":"Theme","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/Theme","url":"\/documentation\/easecalluikit\/theme","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Theme"}],"abstract":[{"type":"text","text":"The theme switching class is used for users to switch themes or register some user’s own views that comply with the ThemeSwitchProtocol protocol."},{"type":"text","text":" "},{"text":"How to use?","type":"text"},{"type":"text","text":" "},{"text":"A view conform ThemeSwitchProtocol.Then Implement protocol methods.When you want switch theme that light and dark themes provided by default chatroom UIKit  ","type":"text"},{"type":"codeVoice","code":"theme"},{"type":"text","text":" ."},{"text":" ","type":"text"},{"type":"text","text":"Call "},{"type":"codeVoice","code":"Theme.switchTheme(style: .dark)"},{"text":" method","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"A view conform ThemeSwitchProtocol.Then Implement protocol methods.When you want switch themes provided by customer ."}]},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit":{"title":"EaseCallUIKit","type":"topic","url":"\/documentation\/easecalluikit","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit","abstract":[],"role":"collection","kind":"symbol"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/ThemeSwitchProtocol":{"type":"topic","url":"\/documentation\/easecalluikit\/themeswitchprotocol","kind":"symbol","navigatorTitle":[{"text":"ThemeSwitchProtocol","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/ThemeSwitchProtocol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"ThemeSwitchProtocol","kind":"identifier"}],"title":"ThemeSwitchProtocol","abstract":[{"text":"When the system theme changes, you can use this static method to switch between the light and dark themes of the ease chat UIKit.","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Type Method","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"registerSwitchThemeViewsWithView:"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"registerSwitchThemeViewsWithView:","kind":"identifier"}]},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"+ (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"text":") ","kind":"text"},{"kind":"identifier","text":"registerSwitchThemeViewsWithView:"},{"kind":"text","text":"("},{"text":"id<ThemeSwitchProtocol>","preciseIdentifier":"c:Qo@M@EaseCallUIKit@objc(pl)ThemeSwitchProtocol","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"view","kind":"internalParam"},{"text":";","kind":"text"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/primaryContentSections\/1","value":{"parameters":[{"content":[{"inlineContent":[{"type":"text","text":"The view conform ThemeSwitchProtocol."},{"text":" ","type":"text"},{"type":"text","text":"How to use?"},{"text":" ","type":"text"},{"code":"Theme.registerSwitchThemeViews(view: Some view implement ThemeSwitchProtocol)","type":"codeVoice"}],"type":"paragraph"}],"name":"view"}],"kind":"parameters"}},{"op":"replace","value":"registerSwitchThemeViewsWithView:","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1Theme~1registerSwitchThemeViews(view:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1Theme~1registerSwitchThemeViews(view:)\/fragments","value":[{"kind":"text","text":"+ "},{"text":"registerSwitchThemeViewsWithView:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1Theme\/title","value":"Theme","op":"replace"},{"value":[{"kind":"identifier","text":"Theme"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1Theme\/fragments"},{"value":[{"kind":"identifier","text":"Theme"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1Theme\/navigatorTitle","op":"replace"},{"op":"replace","value":"ThemeSwitchProtocol","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1ThemeSwitchProtocol\/title"},{"value":[{"text":"ThemeSwitchProtocol","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1ThemeSwitchProtocol\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1ThemeSwitchProtocol\/navigatorTitle","value":[{"text":"ThemeSwitchProtocol","kind":"identifier"}],"op":"replace"}]}]}