{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@"},{"preciseIdentifier":"s:ScM","text":"MainActor","kind":"attribute"},{"kind":"text","text":" "},{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"switchTheme"},{"text":"(","kind":"text"},{"text":"style","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"ThemeStyle","preciseIdentifier":"c:@M@EaseCallUIKit@E@ThemeStyle","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/ThemeStyle"},{"kind":"text","text":")"}]}]},{"kind":"parameters","parameters":[{"name":"style","content":[{"inlineContent":[{"type":"text","text":"ThemeStyle"},{"type":"text","text":" "},{"text":"How to use?","type":"text"},{"type":"text","text":" "},{"type":"codeVoice","code":"Theme.switchTheme(style: .dark)"}],"type":"paragraph"}]}]}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/Theme\/switchTheme(style:)"},"metadata":{"role":"symbol","modules":[{"name":"EaseCallUIKit"}],"fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"switchTheme","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"style"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseCallUIKit@E@ThemeStyle","text":"ThemeStyle"},{"text":")","kind":"text"}],"symbolKind":"method","navigatorTitle":[{"text":"switchThemeWithStyle:","kind":"identifier"}],"externalID":"c:@M@EaseCallUIKit@objc(cs)Theme(cm)switchThemeWithStyle:","roleHeading":"Type Method","title":"switchTheme(style:)"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easecalluikit\/theme\/switchtheme(style:)"]},{"paths":["\/documentation\/easecalluikit\/theme\/switchtheme(style:)"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"abstract":[{"type":"text","text":"The method"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/Theme"]]},"references":{"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/ThemeStyle":{"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/ThemeStyle","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ThemeStyle"}],"type":"topic","abstract":[{"type":"text","text":"Contain light and dark themes of the ease chat UIKit.If you want to switch custom theme,you’ll modify primary&secondary&error&neutral&neutralSpecial hues properties in "},{"code":"Appearance","type":"codeVoice"},{"type":"text","text":".Then call "},{"type":"codeVoice","code":"Theme.switchTheme(style: .custom)"},{"text":" method","type":"text"}],"url":"\/documentation\/easecalluikit\/themestyle","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ThemeStyle"}],"title":"ThemeStyle"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit":{"title":"EaseCallUIKit","type":"topic","url":"\/documentation\/easecalluikit","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit","abstract":[],"role":"collection","kind":"symbol"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/Theme":{"kind":"symbol","title":"Theme","navigatorTitle":[{"text":"Theme","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/Theme","url":"\/documentation\/easecalluikit\/theme","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Theme"}],"abstract":[{"type":"text","text":"The theme switching class is used for users to switch themes or register some user’s own views that comply with the ThemeSwitchProtocol protocol."},{"type":"text","text":" "},{"text":"How to use?","type":"text"},{"type":"text","text":" "},{"text":"A view conform ThemeSwitchProtocol.Then Implement protocol methods.When you want switch theme that light and dark themes provided by default chatroom UIKit  ","type":"text"},{"type":"codeVoice","code":"theme"},{"type":"text","text":" ."},{"text":" ","type":"text"},{"type":"text","text":"Call "},{"type":"codeVoice","code":"Theme.switchTheme(style: .dark)"},{"text":" method","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"A view conform ThemeSwitchProtocol.Then Implement protocol methods.When you want switch themes provided by customer ."}]},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/Theme/switchTheme(style:)":{"role":"symbol","type":"topic","url":"\/documentation\/easecalluikit\/theme\/switchtheme(style:)","abstract":[{"type":"text","text":"The method"}],"fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"switchTheme","kind":"identifier"},{"kind":"text","text":"("},{"text":"style","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseCallUIKit@E@ThemeStyle","text":"ThemeStyle"},{"text":")","kind":"text"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"switchThemeWithStyle:"}],"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/Theme\/switchTheme(style:)","title":"switchTheme(style:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Type Method","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"switchThemeWithStyle:","op":"replace"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"value":[{"kind":"text","text":"+ "},{"text":"switchThemeWithStyle:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"+ (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"text":"switchThemeWithStyle:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"ThemeStyle","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/ThemeStyle","preciseIdentifier":"c:@M@EaseCallUIKit@E@ThemeStyle","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"internalParam","text":"style"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"value":{"kind":"parameters","parameters":[{"name":"style","content":[{"inlineContent":[{"text":"ThemeStyle","type":"text"},{"type":"text","text":" "},{"type":"text","text":"How to use?"},{"text":" ","type":"text"},{"type":"codeVoice","code":"Theme.switchTheme(style: .dark)"}],"type":"paragraph"}]}]},"op":"replace","path":"\/primaryContentSections\/1"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1ThemeStyle\/title","value":"ThemeStyle"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1ThemeStyle\/fragments","value":[{"text":"ThemeStyle","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1ThemeStyle\/navigatorTitle","value":[{"text":"ThemeStyle","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1Theme\/title","value":"Theme"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1Theme\/fragments","value":[{"kind":"identifier","text":"Theme"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1Theme\/navigatorTitle","value":[{"kind":"identifier","text":"Theme"}]},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1Theme~1switchTheme(style:)\/title","op":"replace","value":"switchThemeWithStyle:"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1Theme~1switchTheme(style:)\/fragments","value":[{"kind":"text","text":"+ "},{"text":"switchThemeWithStyle:","kind":"identifier"}],"op":"replace"}]}]}