{"topicSections":[{"generated":true,"anchor":"Instance-Methods","title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/Call1v1VideoViewController\/pictureInPictureController(_:failedToStartPictureInPictureWithError:)","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/Call1v1VideoViewController\/pictureInPictureController(_:restoreUserInterfaceForPictureInPictureStopWithCompletionHandler:)","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/Call1v1VideoViewController\/pictureInPictureControllerDidStartPictureInPicture(_:)","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/Call1v1VideoViewController\/pictureInPictureControllerDidStopPictureInPicture(_:)","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/Call1v1VideoViewController\/pictureInPictureControllerWillStartPictureInPicture(_:)","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/Call1v1VideoViewController\/pictureInPictureControllerWillStopPictureInPicture(_:)"]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"modules":[{"name":"EaseCallUIKit"}],"role":"collectionGroup","title":"AVPictureInPictureControllerDelegate Implementations","roleHeading":"API Collection"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/Call1v1VideoViewController"]]},"identifier":{"url":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/Call1v1VideoViewController\/AVPictureInPictureControllerDelegate-Implementations","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/easecalluikit\/call1v1videoviewcontroller\/avpictureinpicturecontrollerdelegate-implementations"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/easecalluikit\/call1v1videoviewcontroller\/avpictureinpicturecontrollerdelegate-implementations"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"article","sections":[],"references":{"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/Call1v1VideoViewController/pictureInPictureControllerWillStartPictureInPicture(_:)":{"type":"topic","abstract":[],"url":"\/documentation\/easecalluikit\/call1v1videoviewcontroller\/pictureinpicturecontrollerwillstartpictureinpicture(_:)","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/Call1v1VideoViewController\/pictureInPictureControllerWillStartPictureInPicture(_:)","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"pictureInPictureControllerWillStartPictureInPicture:"}],"title":"pictureInPictureControllerWillStartPictureInPicture(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"pictureInPictureControllerWillStartPictureInPicture"},{"text":"(","kind":"text"},{"text":"AVPictureInPictureController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AVPictureInPictureController"},{"kind":"text","text":")"}],"role":"symbol"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/Call1v1VideoViewController/pictureInPictureControllerDidStartPictureInPicture(_:)":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/Call1v1VideoViewController\/pictureInPictureControllerDidStartPictureInPicture(_:)","type":"topic","url":"\/documentation\/easecalluikit\/call1v1videoviewcontroller\/pictureinpicturecontrollerdidstartpictureinpicture(_:)","navigatorTitle":[{"kind":"identifier","text":"pictureInPictureControllerDidStartPictureInPicture:"}],"abstract":[],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"pictureInPictureControllerDidStartPictureInPicture","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AVPictureInPictureController","text":"AVPictureInPictureController"},{"text":")","kind":"text"}],"title":"pictureInPictureControllerDidStartPictureInPicture(_:)"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/Call1v1VideoViewController/pictureInPictureController(_:restoreUserInterfaceForPictureInPictureStopWithCompletionHandler:)":{"type":"topic","url":"\/documentation\/easecalluikit\/call1v1videoviewcontroller\/pictureinpicturecontroller(_:restoreuserinterfaceforpictureinpicturestopwithcompletionhandler:)","kind":"symbol","title":"pictureInPictureController(_:restoreUserInterfaceForPictureInPictureStopWithCompletionHandler:)","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/Call1v1VideoViewController\/pictureInPictureController(_:restoreUserInterfaceForPictureInPictureStopWithCompletionHandler:)","abstract":[],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"pictureInPictureController","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)AVPictureInPictureController","kind":"typeIdentifier","text":"AVPictureInPictureController"},{"kind":"text","text":", "},{"text":"restoreUserInterfaceForPictureInPictureStopWithCompletionHandler","kind":"externalParam"},{"text":": (","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"role":"symbol","navigatorTitle":[{"text":"pictureInPictureController:restoreUserInterfaceForPictureInPictureStopWithCompletionHandler:","kind":"identifier"}]},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/Call1v1VideoViewController/pictureInPictureControllerDidStopPictureInPicture(_:)":{"kind":"symbol","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"pictureInPictureControllerDidStopPictureInPicture"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AVPictureInPictureController","text":"AVPictureInPictureController"},{"text":")","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"pictureInPictureControllerDidStopPictureInPicture:"}],"role":"symbol","title":"pictureInPictureControllerDidStopPictureInPicture(_:)","url":"\/documentation\/easecalluikit\/call1v1videoviewcontroller\/pictureinpicturecontrollerdidstoppictureinpicture(_:)","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/Call1v1VideoViewController\/pictureInPictureControllerDidStopPictureInPicture(_:)"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/Call1v1VideoViewController":{"abstract":[],"type":"topic","kind":"symbol","title":"Call1v1VideoViewController","navigatorTitle":[{"kind":"identifier","text":"Call1v1VideoViewController"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"Call1v1VideoViewController","kind":"identifier"}],"role":"symbol","url":"\/documentation\/easecalluikit\/call1v1videoviewcontroller","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/Call1v1VideoViewController"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit":{"title":"EaseCallUIKit","type":"topic","url":"\/documentation\/easecalluikit","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit","abstract":[],"role":"collection","kind":"symbol"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/Call1v1VideoViewController/pictureInPictureControllerWillStopPictureInPicture(_:)":{"navigatorTitle":[{"kind":"identifier","text":"pictureInPictureControllerWillStopPictureInPicture:"}],"title":"pictureInPictureControllerWillStopPictureInPicture(_:)","abstract":[],"type":"topic","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/Call1v1VideoViewController\/pictureInPictureControllerWillStopPictureInPicture(_:)","url":"\/documentation\/easecalluikit\/call1v1videoviewcontroller\/pictureinpicturecontrollerwillstoppictureinpicture(_:)","role":"symbol","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"pictureInPictureControllerWillStopPictureInPicture","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)AVPictureInPictureController","text":"AVPictureInPictureController","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/Call1v1VideoViewController/pictureInPictureController(_:failedToStartPictureInPictureWithError:)":{"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/Call1v1VideoViewController\/pictureInPictureController(_:failedToStartPictureInPictureWithError:)","url":"\/documentation\/easecalluikit\/call1v1videoviewcontroller\/pictureinpicturecontroller(_:failedtostartpictureinpicturewitherror:)","role":"symbol","type":"topic","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"pictureInPictureController","kind":"identifier"},{"kind":"text","text":"("},{"text":"AVPictureInPictureController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AVPictureInPictureController"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"failedToStartPictureInPictureWithError"},{"kind":"text","text":": "},{"text":"any","kind":"keyword"},{"kind":"text","text":" "},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"pictureInPictureController:failedToStartPictureInPictureWithError:","kind":"identifier"}],"abstract":[],"title":"pictureInPictureController(_:failedToStartPictureInPictureWithError:)"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/topicSections","op":"replace","value":[{"generated":true,"identifiers":["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/Call1v1VideoViewController\/pictureInPictureController(_:failedToStartPictureInPictureWithError:)","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/Call1v1VideoViewController\/pictureInPictureController(_:restoreUserInterfaceForPictureInPictureStopWithCompletionHandler:)","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/Call1v1VideoViewController\/pictureInPictureControllerDidStartPictureInPicture(_:)","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/Call1v1VideoViewController\/pictureInPictureControllerDidStopPictureInPicture(_:)","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/Call1v1VideoViewController\/pictureInPictureControllerWillStartPictureInPicture(_:)","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/Call1v1VideoViewController\/pictureInPictureControllerWillStopPictureInPicture(_:)"],"title":"Instance Methods","anchor":"Instance-Methods"}]},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1Call1v1VideoViewController~1pictureInPictureControllerWillStartPictureInPicture(_:)\/title","value":"pictureInPictureControllerWillStartPictureInPicture:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1Call1v1VideoViewController~1pictureInPictureControllerWillStartPictureInPicture(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"pictureInPictureControllerWillStartPictureInPicture:"}]},{"op":"replace","value":"pictureInPictureControllerDidStartPictureInPicture:","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1Call1v1VideoViewController~1pictureInPictureControllerDidStartPictureInPicture(_:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1Call1v1VideoViewController~1pictureInPictureControllerDidStartPictureInPicture(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"pictureInPictureControllerDidStartPictureInPicture:"}]},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1Call1v1VideoViewController~1pictureInPictureController(_:restoreUserInterfaceForPictureInPictureStopWithCompletionHandler:)\/title","op":"replace","value":"pictureInPictureController:restoreUserInterfaceForPictureInPictureStopWithCompletionHandler:"},{"value":[{"kind":"text","text":"- "},{"text":"pictureInPictureController:restoreUserInterfaceForPictureInPictureStopWithCompletionHandler:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1Call1v1VideoViewController~1pictureInPictureController(_:restoreUserInterfaceForPictureInPictureStopWithCompletionHandler:)\/fragments"},{"value":"pictureInPictureControllerDidStopPictureInPicture:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1Call1v1VideoViewController~1pictureInPictureControllerDidStopPictureInPicture(_:)\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1Call1v1VideoViewController~1pictureInPictureControllerDidStopPictureInPicture(_:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"pictureInPictureControllerDidStopPictureInPicture:","kind":"identifier"}],"op":"replace"},{"value":"Call1v1VideoViewController","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1Call1v1VideoViewController\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1Call1v1VideoViewController\/fragments","value":[{"kind":"identifier","text":"Call1v1VideoViewController"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1Call1v1VideoViewController\/navigatorTitle","value":[{"text":"Call1v1VideoViewController","kind":"identifier"}]},{"value":"pictureInPictureControllerWillStopPictureInPicture:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1Call1v1VideoViewController~1pictureInPictureControllerWillStopPictureInPicture(_:)\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1Call1v1VideoViewController~1pictureInPictureControllerWillStopPictureInPicture(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"pictureInPictureControllerWillStopPictureInPicture:","kind":"identifier"}],"op":"replace"},{"value":"pictureInPictureController:failedToStartPictureInPictureWithError:","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1Call1v1VideoViewController~1pictureInPictureController(_:failedToStartPictureInPictureWithError:)\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"pictureInPictureController:failedToStartPictureInPictureWithError:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1Call1v1VideoViewController~1pictureInPictureController(_:failedToStartPictureInPictureWithError:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}