{"sections":[],"metadata":{"externalID":"s:13EaseCallUIKit26Call1v1VideoViewControllerC04callF0AA017PixelBufferRenderF0Cvp","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"callView"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@EaseCallUIKit@objc(cs)PixelBufferRenderView","kind":"typeIdentifier","text":"PixelBufferRenderView"}],"roleHeading":"Instance Property","title":"callView","symbolKind":"property","modules":[{"name":"EaseCallUIKit"}]},"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"text":"lazy","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"callView","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/PixelBufferRenderView","text":"PixelBufferRenderView","preciseIdentifier":"c:@M@EaseCallUIKit@objc(cs)PixelBufferRenderView"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"kind":"text","text":" "},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/Call1v1VideoViewController\/callView"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/Call1v1VideoViewController"]]},"kind":"symbol","variants":[{"paths":["\/documentation\/easecalluikit\/call1v1videoviewcontroller\/callview"],"traits":[{"interfaceLanguage":"swift"}]}],"references":{"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/Call1v1VideoViewController":{"abstract":[],"type":"topic","kind":"symbol","title":"Call1v1VideoViewController","navigatorTitle":[{"kind":"identifier","text":"Call1v1VideoViewController"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"Call1v1VideoViewController","kind":"identifier"}],"role":"symbol","url":"\/documentation\/easecalluikit\/call1v1videoviewcontroller","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/Call1v1VideoViewController"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit":{"title":"EaseCallUIKit","type":"topic","url":"\/documentation\/easecalluikit","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit","abstract":[],"role":"collection","kind":"symbol"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/PixelBufferRenderView":{"role":"symbol","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/PixelBufferRenderView","url":"\/documentation\/easecalluikit\/pixelbufferrenderview","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PixelBufferRenderView"}],"abstract":[],"kind":"symbol","title":"PixelBufferRenderView","navigatorTitle":[{"text":"PixelBufferRenderView","kind":"identifier"}],"type":"topic"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/Call1v1VideoViewController/callView":{"title":"callView","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/Call1v1VideoViewController\/callView","url":"\/documentation\/easecalluikit\/call1v1videoviewcontroller\/callview","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"callView","kind":"identifier"},{"kind":"text","text":": "},{"text":"PixelBufferRenderView","preciseIdentifier":"c:@M@EaseCallUIKit@objc(cs)PixelBufferRenderView","kind":"typeIdentifier"}],"type":"topic","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"Call1v1VideoViewController","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1Call1v1VideoViewController\/title","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"Call1v1VideoViewController"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1Call1v1VideoViewController\/fragments"},{"value":[{"kind":"identifier","text":"Call1v1VideoViewController"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1Call1v1VideoViewController\/navigatorTitle"},{"value":"PixelBufferRenderView","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1PixelBufferRenderView\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1PixelBufferRenderView\/fragments","value":[{"kind":"identifier","text":"PixelBufferRenderView"}],"op":"replace"},{"value":[{"text":"PixelBufferRenderView","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1PixelBufferRenderView\/navigatorTitle"}]}]}