{"kind":"symbol","sections":[],"identifier":{"url":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/Call1v1VideoViewController\/floatView","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easecalluikit\/call1v1videoviewcontroller\/floatview"]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/Call1v1VideoViewController"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM"},{"kind":"text","text":" "},{"kind":"keyword","text":"lazy"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"floatView","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/PixelBufferRenderView","text":"PixelBufferRenderView","preciseIdentifier":"c:@M@EaseCallUIKit@objc(cs)PixelBufferRenderView"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"kind":"text","text":" "},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"role":"symbol","symbolKind":"property","modules":[{"name":"EaseCallUIKit"}],"externalID":"s:13EaseCallUIKit26Call1v1VideoViewControllerC05floatF0AA017PixelBufferRenderF0Cvp","roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"floatView","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@EaseCallUIKit@objc(cs)PixelBufferRenderView","text":"PixelBufferRenderView","kind":"typeIdentifier"}],"title":"floatView"},"references":{"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit":{"title":"EaseCallUIKit","type":"topic","url":"\/documentation\/easecalluikit","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit","abstract":[],"role":"collection","kind":"symbol"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/Call1v1VideoViewController/floatView":{"url":"\/documentation\/easecalluikit\/call1v1videoviewcontroller\/floatview","kind":"symbol","type":"topic","role":"symbol","title":"floatView","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"floatView","kind":"identifier"},{"text":": ","kind":"text"},{"text":"PixelBufferRenderView","kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseCallUIKit@objc(cs)PixelBufferRenderView"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/Call1v1VideoViewController\/floatView"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/PixelBufferRenderView":{"role":"symbol","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/PixelBufferRenderView","url":"\/documentation\/easecalluikit\/pixelbufferrenderview","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PixelBufferRenderView"}],"abstract":[],"kind":"symbol","title":"PixelBufferRenderView","navigatorTitle":[{"text":"PixelBufferRenderView","kind":"identifier"}],"type":"topic"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/Call1v1VideoViewController":{"abstract":[],"type":"topic","kind":"symbol","title":"Call1v1VideoViewController","navigatorTitle":[{"kind":"identifier","text":"Call1v1VideoViewController"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"Call1v1VideoViewController","kind":"identifier"}],"role":"symbol","url":"\/documentation\/easecalluikit\/call1v1videoviewcontroller","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/Call1v1VideoViewController"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"PixelBufferRenderView","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1PixelBufferRenderView\/title","op":"replace"},{"value":[{"text":"PixelBufferRenderView","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1PixelBufferRenderView\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"PixelBufferRenderView"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1PixelBufferRenderView\/navigatorTitle"},{"op":"replace","value":"Call1v1VideoViewController","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1Call1v1VideoViewController\/title"},{"value":[{"kind":"identifier","text":"Call1v1VideoViewController"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1Call1v1VideoViewController\/fragments"},{"op":"replace","value":[{"text":"Call1v1VideoViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1Call1v1VideoViewController\/navigatorTitle"}]}]}