{"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/Call1v1VideoViewController"]]},"metadata":{"title":"init(role:)","externalID":"c:@M@EaseCallUIKit@objc(cs)Call1v1VideoViewController(im)initWithRole:","modules":[{"name":"EaseCallUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"initWithRole:"}],"symbolKind":"init","roleHeading":"Initializer","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"role","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@EaseCallUIKit@E@CallRole","text":"CallRole","kind":"typeIdentifier"},{"text":")","kind":"text"}],"role":"symbol"},"kind":"symbol","identifier":{"url":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/Call1v1VideoViewController\/init(role:)","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/easecalluikit\/call1v1videoviewcontroller\/init(role:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/easecalluikit\/call1v1videoviewcontroller\/init(role:)"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"attribute","text":"@"},{"kind":"attribute","preciseIdentifier":"s:ScM","text":"MainActor"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"role"},{"kind":"text","text":": "},{"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallRole","text":"CallRole","kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseCallUIKit@E@CallRole"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"references":{"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit":{"title":"EaseCallUIKit","type":"topic","url":"\/documentation\/easecalluikit","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit","abstract":[],"role":"collection","kind":"symbol"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/Call1v1VideoViewController/init(role:)":{"url":"\/documentation\/easecalluikit\/call1v1videoviewcontroller\/init(role:)","kind":"symbol","type":"topic","role":"symbol","title":"init(role:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"role","kind":"externalParam"},{"kind":"text","text":": "},{"text":"CallRole","kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseCallUIKit@E@CallRole"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/Call1v1VideoViewController\/init(role:)","navigatorTitle":[{"kind":"identifier","text":"initWithRole:"}]},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/Call1v1VideoViewController":{"abstract":[],"type":"topic","kind":"symbol","title":"Call1v1VideoViewController","navigatorTitle":[{"kind":"identifier","text":"Call1v1VideoViewController"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"Call1v1VideoViewController","kind":"identifier"}],"role":"symbol","url":"\/documentation\/easecalluikit\/call1v1videoviewcontroller","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/Call1v1VideoViewController"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallRole":{"url":"\/documentation\/easecalluikit\/callrole","role":"symbol","title":"CallRole","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallRole","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"CallRole"}],"navigatorTitle":[{"text":"CallRole","kind":"identifier"}],"type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"value":"initWithRole:","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"value":[{"text":"- ","kind":"text"},{"text":"initWithRole:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:*Qo","kind":"typeIdentifier","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithRole:"},{"kind":"text","text":"("},{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallRole","preciseIdentifier":"c:@M@EaseCallUIKit@E@CallRole","kind":"typeIdentifier","text":"CallRole"},{"text":") ","kind":"text"},{"text":"role","kind":"internalParam"},{"kind":"text","text":";"}]}],"kind":"declarations"},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1Call1v1VideoViewController~1init(role:)\/title","value":"initWithRole:"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1Call1v1VideoViewController~1init(role:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithRole:"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1Call1v1VideoViewController\/title","value":"Call1v1VideoViewController","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"Call1v1VideoViewController"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1Call1v1VideoViewController\/fragments"},{"op":"replace","value":[{"text":"Call1v1VideoViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1Call1v1VideoViewController\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallRole\/title","value":"CallRole"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallRole\/fragments","value":[{"text":"CallRole","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallRole\/navigatorTitle","value":[{"kind":"identifier","text":"CallRole"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}