{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easecalluikit\/call1v1videoviewcontroller\/pictureinpicturecontrollerdidstartpictureinpicture(_:)"]},{"paths":["\/documentation\/easecalluikit\/call1v1videoviewcontroller\/pictureinpicturecontrollerdidstartpictureinpicture(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/Call1v1VideoViewController\/pictureInPictureControllerDidStartPictureInPicture(_:)"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@"},{"preciseIdentifier":"s:ScM","kind":"attribute","text":"MainActor"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"pictureInPictureControllerDidStartPictureInPicture"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"text":"pictureInPictureController","kind":"internalParam"},{"kind":"text","text":": "},{"text":"AVPictureInPictureController","preciseIdentifier":"c:objc(cs)AVPictureInPictureController","kind":"typeIdentifier"},{"kind":"text","text":")"}]}],"kind":"declarations"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"AVPictureInPictureControllerDelegate.pictureInPictureControllerDidStartPictureInPicture(_:)"},{"type":"text","text":"."}],"metadata":{"externalID":"c:@CM@EaseCallUIKit@objc(cs)Call1v1VideoViewController(im)pictureInPictureControllerDidStartPictureInPicture:","title":"pictureInPictureControllerDidStartPictureInPicture(_:)","roleHeading":"Instance Method","role":"symbol","modules":[{"name":"EaseCallUIKit"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"pictureInPictureControllerDidStartPictureInPicture"},{"text":"(","kind":"text"},{"text":"AVPictureInPictureController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AVPictureInPictureController"},{"text":")","kind":"text"}],"extendedModule":"EaseCallUIKit","symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"pictureInPictureControllerDidStartPictureInPicture:"}],"platforms":[{"deprecated":false,"beta":false,"name":"iOS","introducedAt":"15.0","unavailable":false},{"deprecated":false,"introducedAt":"15.0","beta":false,"unavailable":false,"name":"iPadOS"},{"beta":false,"unavailable":false,"introducedAt":"15.0","deprecated":false,"name":"Mac Catalyst"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/Call1v1VideoViewController","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/Call1v1VideoViewController\/AVPictureInPictureControllerDelegate-Implementations"]]},"references":{"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit":{"title":"EaseCallUIKit","type":"topic","url":"\/documentation\/easecalluikit","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit","abstract":[],"role":"collection","kind":"symbol"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/Call1v1VideoViewController/AVPictureInPictureControllerDelegate-Implementations":{"abstract":[],"kind":"article","type":"topic","title":"AVPictureInPictureControllerDelegate Implementations","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/Call1v1VideoViewController\/AVPictureInPictureControllerDelegate-Implementations","role":"collectionGroup","url":"\/documentation\/easecalluikit\/call1v1videoviewcontroller\/avpictureinpicturecontrollerdelegate-implementations"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/Call1v1VideoViewController":{"abstract":[],"type":"topic","kind":"symbol","title":"Call1v1VideoViewController","navigatorTitle":[{"kind":"identifier","text":"Call1v1VideoViewController"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"Call1v1VideoViewController","kind":"identifier"}],"role":"symbol","url":"\/documentation\/easecalluikit\/call1v1videoviewcontroller","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/Call1v1VideoViewController"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/Call1v1VideoViewController/pictureInPictureControllerDidStartPictureInPicture(_:)":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/Call1v1VideoViewController\/pictureInPictureControllerDidStartPictureInPicture(_:)","type":"topic","url":"\/documentation\/easecalluikit\/call1v1videoviewcontroller\/pictureinpicturecontrollerdidstartpictureinpicture(_:)","navigatorTitle":[{"kind":"identifier","text":"pictureInPictureControllerDidStartPictureInPicture:"}],"abstract":[],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"pictureInPictureControllerDidStartPictureInPicture","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AVPictureInPictureController","text":"AVPictureInPictureController"},{"text":")","kind":"text"}],"title":"pictureInPictureControllerDidStartPictureInPicture(_:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"value":"pictureInPictureControllerDidStartPictureInPicture:","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"value":[{"kind":"text","text":"- "},{"text":"pictureInPictureControllerDidStartPictureInPicture:","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"text":"pictureInPictureControllerDidStartPictureInPicture:","kind":"identifier"},{"kind":"text","text":"("},{"text":"AVPictureInPictureController","preciseIdentifier":"c:objc(cs)AVPictureInPictureController","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"pictureInPictureController"},{"text":";","kind":"text"}]}],"kind":"declarations"},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1Call1v1VideoViewController\/title","value":"Call1v1VideoViewController"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1Call1v1VideoViewController\/fragments","op":"replace","value":[{"kind":"identifier","text":"Call1v1VideoViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1Call1v1VideoViewController\/navigatorTitle","value":[{"kind":"identifier","text":"Call1v1VideoViewController"}]},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1Call1v1VideoViewController~1pictureInPictureControllerDidStartPictureInPicture(_:)\/title","op":"replace","value":"pictureInPictureControllerDidStartPictureInPicture:"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"pictureInPictureControllerDidStartPictureInPicture:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1Call1v1VideoViewController~1pictureInPictureControllerDidStartPictureInPicture(_:)\/fragments"}]}]}