{"metadata":{"roleHeading":"Instance Method","navigatorTitle":[{"kind":"identifier","text":"pictureInPictureControllerDidStopPictureInPicture:"}],"role":"symbol","modules":[{"name":"EaseCallUIKit"}],"symbolKind":"method","title":"pictureInPictureControllerDidStopPictureInPicture(_:)","extendedModule":"EaseCallUIKit","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"pictureInPictureControllerDidStopPictureInPicture"},{"text":"(","kind":"text"},{"text":"AVPictureInPictureController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AVPictureInPictureController"},{"text":")","kind":"text"}],"platforms":[{"deprecated":false,"introducedAt":"15.0","name":"iOS","unavailable":false,"beta":false},{"name":"iPadOS","beta":false,"unavailable":false,"deprecated":false,"introducedAt":"15.0"},{"deprecated":false,"name":"Mac Catalyst","unavailable":false,"beta":false,"introducedAt":"15.0"}],"externalID":"c:@CM@EaseCallUIKit@objc(cs)Call1v1VideoViewController(im)pictureInPictureControllerDidStopPictureInPicture:"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/Call1v1VideoViewController","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/Call1v1VideoViewController\/AVPictureInPictureControllerDelegate-Implementations"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@"},{"kind":"attribute","preciseIdentifier":"s:ScM","text":"MainActor"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"pictureInPictureControllerDidStopPictureInPicture","kind":"identifier"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"pictureInPictureController"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)AVPictureInPictureController","kind":"typeIdentifier","text":"AVPictureInPictureController"},{"text":")","kind":"text"}],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easecalluikit\/call1v1videoviewcontroller\/pictureinpicturecontrollerdidstoppictureinpicture(_:)"]},{"paths":["\/documentation\/easecalluikit\/call1v1videoviewcontroller\/pictureinpicturecontrollerdidstoppictureinpicture(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/Call1v1VideoViewController\/pictureInPictureControllerDidStopPictureInPicture(_:)"},"kind":"symbol","abstract":[{"type":"text","text":"Inherited from "},{"code":"AVPictureInPictureControllerDelegate.pictureInPictureControllerDidStopPictureInPicture(_:)","type":"codeVoice"},{"text":".","type":"text"}],"references":{"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/Call1v1VideoViewController/AVPictureInPictureControllerDelegate-Implementations":{"abstract":[],"kind":"article","type":"topic","title":"AVPictureInPictureControllerDelegate Implementations","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/Call1v1VideoViewController\/AVPictureInPictureControllerDelegate-Implementations","role":"collectionGroup","url":"\/documentation\/easecalluikit\/call1v1videoviewcontroller\/avpictureinpicturecontrollerdelegate-implementations"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/Call1v1VideoViewController":{"abstract":[],"type":"topic","kind":"symbol","title":"Call1v1VideoViewController","navigatorTitle":[{"kind":"identifier","text":"Call1v1VideoViewController"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"Call1v1VideoViewController","kind":"identifier"}],"role":"symbol","url":"\/documentation\/easecalluikit\/call1v1videoviewcontroller","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/Call1v1VideoViewController"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/Call1v1VideoViewController/pictureInPictureControllerDidStopPictureInPicture(_:)":{"kind":"symbol","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"pictureInPictureControllerDidStopPictureInPicture"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AVPictureInPictureController","text":"AVPictureInPictureController"},{"text":")","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"pictureInPictureControllerDidStopPictureInPicture:"}],"role":"symbol","title":"pictureInPictureControllerDidStopPictureInPicture(_:)","url":"\/documentation\/easecalluikit\/call1v1videoviewcontroller\/pictureinpicturecontrollerdidstoppictureinpicture(_:)","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/Call1v1VideoViewController\/pictureInPictureControllerDidStopPictureInPicture(_:)"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit":{"title":"EaseCallUIKit","type":"topic","url":"\/documentation\/easecalluikit","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit","abstract":[],"role":"collection","kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"pictureInPictureControllerDidStopPictureInPicture:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"value":[{"text":"- ","kind":"text"},{"text":"pictureInPictureControllerDidStopPictureInPicture:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"kind":"text","text":") "},{"text":"pictureInPictureControllerDidStopPictureInPicture:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"AVPictureInPictureController","preciseIdentifier":"c:objc(cs)AVPictureInPictureController"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"pictureInPictureController"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1Call1v1VideoViewController\/title","value":"Call1v1VideoViewController","op":"replace"},{"value":[{"text":"Call1v1VideoViewController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1Call1v1VideoViewController\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1Call1v1VideoViewController\/navigatorTitle","value":[{"text":"Call1v1VideoViewController","kind":"identifier"}]},{"op":"replace","value":"pictureInPictureControllerDidStopPictureInPicture:","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1Call1v1VideoViewController~1pictureInPictureControllerDidStopPictureInPicture(_:)\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1Call1v1VideoViewController~1pictureInPictureControllerDidStopPictureInPicture(_:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"pictureInPictureControllerDidStopPictureInPicture:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}