{"identifier":{"url":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/Call1v1VideoViewController\/pictureInPictureControllerWillStartPictureInPicture(_:)","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"abstract":[{"type":"text","text":"Inherited from "},{"code":"AVPictureInPictureControllerDelegate.pictureInPictureControllerWillStartPictureInPicture(_:)","type":"codeVoice"},{"type":"text","text":"."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@","kind":"attribute"},{"preciseIdentifier":"s:ScM","text":"MainActor","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"pictureInPictureControllerWillStartPictureInPicture","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"pictureInPictureController","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)AVPictureInPictureController","text":"AVPictureInPictureController","kind":"typeIdentifier"},{"kind":"text","text":")"}]}]}],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"pictureInPictureControllerWillStartPictureInPicture:"}],"roleHeading":"Instance Method","title":"pictureInPictureControllerWillStartPictureInPicture(_:)","modules":[{"name":"EaseCallUIKit"}],"platforms":[{"unavailable":false,"beta":false,"deprecated":false,"introducedAt":"15.0","name":"iOS"},{"unavailable":false,"beta":false,"introducedAt":"15.0","deprecated":false,"name":"iPadOS"},{"name":"Mac Catalyst","beta":false,"deprecated":false,"unavailable":false,"introducedAt":"15.0"}],"role":"symbol","symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"pictureInPictureControllerWillStartPictureInPicture","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)AVPictureInPictureController","text":"AVPictureInPictureController","kind":"typeIdentifier"},{"kind":"text","text":")"}],"extendedModule":"EaseCallUIKit","externalID":"c:@CM@EaseCallUIKit@objc(cs)Call1v1VideoViewController(im)pictureInPictureControllerWillStartPictureInPicture:"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/Call1v1VideoViewController","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/Call1v1VideoViewController\/AVPictureInPictureControllerDelegate-Implementations"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easecalluikit\/call1v1videoviewcontroller\/pictureinpicturecontrollerwillstartpictureinpicture(_:)"]},{"paths":["\/documentation\/easecalluikit\/call1v1videoviewcontroller\/pictureinpicturecontrollerwillstartpictureinpicture(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","references":{"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/Call1v1VideoViewController/AVPictureInPictureControllerDelegate-Implementations":{"abstract":[],"kind":"article","type":"topic","title":"AVPictureInPictureControllerDelegate Implementations","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/Call1v1VideoViewController\/AVPictureInPictureControllerDelegate-Implementations","role":"collectionGroup","url":"\/documentation\/easecalluikit\/call1v1videoviewcontroller\/avpictureinpicturecontrollerdelegate-implementations"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/Call1v1VideoViewController/pictureInPictureControllerWillStartPictureInPicture(_:)":{"type":"topic","abstract":[],"url":"\/documentation\/easecalluikit\/call1v1videoviewcontroller\/pictureinpicturecontrollerwillstartpictureinpicture(_:)","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/Call1v1VideoViewController\/pictureInPictureControllerWillStartPictureInPicture(_:)","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"pictureInPictureControllerWillStartPictureInPicture:"}],"title":"pictureInPictureControllerWillStartPictureInPicture(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"pictureInPictureControllerWillStartPictureInPicture"},{"text":"(","kind":"text"},{"text":"AVPictureInPictureController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AVPictureInPictureController"},{"kind":"text","text":")"}],"role":"symbol"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/Call1v1VideoViewController":{"abstract":[],"type":"topic","kind":"symbol","title":"Call1v1VideoViewController","navigatorTitle":[{"kind":"identifier","text":"Call1v1VideoViewController"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"Call1v1VideoViewController","kind":"identifier"}],"role":"symbol","url":"\/documentation\/easecalluikit\/call1v1videoviewcontroller","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/Call1v1VideoViewController"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit":{"title":"EaseCallUIKit","type":"topic","url":"\/documentation\/easecalluikit","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit","abstract":[],"role":"collection","kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"pictureInPictureControllerWillStartPictureInPicture:"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"pictureInPictureControllerWillStartPictureInPicture:"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"pictureInPictureControllerWillStartPictureInPicture:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AVPictureInPictureController","text":"AVPictureInPictureController"},{"text":" *) ","kind":"text"},{"text":"pictureInPictureController","kind":"internalParam"},{"kind":"text","text":";"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1Call1v1VideoViewController~1pictureInPictureControllerWillStartPictureInPicture(_:)\/title","value":"pictureInPictureControllerWillStartPictureInPicture:","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1Call1v1VideoViewController~1pictureInPictureControllerWillStartPictureInPicture(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"pictureInPictureControllerWillStartPictureInPicture:"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1Call1v1VideoViewController\/title","value":"Call1v1VideoViewController","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1Call1v1VideoViewController\/fragments","op":"replace","value":[{"text":"Call1v1VideoViewController","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1Call1v1VideoViewController\/navigatorTitle","value":[{"text":"Call1v1VideoViewController","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}