{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@"},{"preciseIdentifier":"s:ScM","text":"MainActor","kind":"attribute"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"pictureInPictureController","kind":"identifier"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"pictureInPictureController","kind":"internalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AVPictureInPictureController","text":"AVPictureInPictureController"},{"kind":"text","text":", "},{"text":"restoreUserInterfaceForPictureInPictureStopWithCompletionHandler","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"completionHandler","kind":"internalParam"},{"text":": ","kind":"text"},{"kind":"attribute","text":"@escaping"},{"kind":"text","text":" ("},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"kind":"text","text":")"}],"platforms":["iOS"],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/Call1v1VideoViewController","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/Call1v1VideoViewController\/AVPictureInPictureControllerDelegate-Implementations"]]},"metadata":{"externalID":"c:@CM@EaseCallUIKit@objc(cs)Call1v1VideoViewController(im)pictureInPictureController:restoreUserInterfaceForPictureInPictureStopWithCompletionHandler:","roleHeading":"Instance Method","platforms":[{"deprecated":false,"beta":false,"name":"iOS","introducedAt":"15.0","unavailable":false},{"deprecated":false,"beta":false,"introducedAt":"15.0","name":"iPadOS","unavailable":false},{"deprecated":false,"introducedAt":"15.0","unavailable":false,"name":"Mac Catalyst","beta":false}],"extendedModule":"EaseCallUIKit","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"pictureInPictureController"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)AVPictureInPictureController","text":"AVPictureInPictureController","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"restoreUserInterfaceForPictureInPictureStopWithCompletionHandler","kind":"externalParam"},{"text":": (","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":") -> "},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"kind":"text","text":")"}],"modules":[{"name":"EaseCallUIKit"}],"role":"symbol","title":"pictureInPictureController(_:restoreUserInterfaceForPictureInPictureStopWithCompletionHandler:)","navigatorTitle":[{"text":"pictureInPictureController:restoreUserInterfaceForPictureInPictureStopWithCompletionHandler:","kind":"identifier"}],"symbolKind":"method"},"identifier":{"url":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/Call1v1VideoViewController\/pictureInPictureController(_:restoreUserInterfaceForPictureInPictureStopWithCompletionHandler:)","interfaceLanguage":"swift"},"kind":"symbol","abstract":[{"text":"Inherited from ","type":"text"},{"code":"AVPictureInPictureControllerDelegate.pictureInPictureController(_:restoreUserInterfaceForPictureInPictureStopWithCompletionHandler:)","type":"codeVoice"},{"text":".","type":"text"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easecalluikit\/call1v1videoviewcontroller\/pictureinpicturecontroller(_:restoreuserinterfaceforpictureinpicturestopwithcompletionhandler:)"]},{"paths":["\/documentation\/easecalluikit\/call1v1videoviewcontroller\/pictureinpicturecontroller(_:restoreuserinterfaceforpictureinpicturestopwithcompletionhandler:)"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit":{"title":"EaseCallUIKit","type":"topic","url":"\/documentation\/easecalluikit","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit","abstract":[],"role":"collection","kind":"symbol"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/Call1v1VideoViewController":{"abstract":[],"type":"topic","kind":"symbol","title":"Call1v1VideoViewController","navigatorTitle":[{"kind":"identifier","text":"Call1v1VideoViewController"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"Call1v1VideoViewController","kind":"identifier"}],"role":"symbol","url":"\/documentation\/easecalluikit\/call1v1videoviewcontroller","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/Call1v1VideoViewController"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/Call1v1VideoViewController/AVPictureInPictureControllerDelegate-Implementations":{"abstract":[],"kind":"article","type":"topic","title":"AVPictureInPictureControllerDelegate Implementations","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/Call1v1VideoViewController\/AVPictureInPictureControllerDelegate-Implementations","role":"collectionGroup","url":"\/documentation\/easecalluikit\/call1v1videoviewcontroller\/avpictureinpicturecontrollerdelegate-implementations"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/Call1v1VideoViewController/pictureInPictureController(_:restoreUserInterfaceForPictureInPictureStopWithCompletionHandler:)":{"type":"topic","url":"\/documentation\/easecalluikit\/call1v1videoviewcontroller\/pictureinpicturecontroller(_:restoreuserinterfaceforpictureinpicturestopwithcompletionhandler:)","kind":"symbol","title":"pictureInPictureController(_:restoreUserInterfaceForPictureInPictureStopWithCompletionHandler:)","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/Call1v1VideoViewController\/pictureInPictureController(_:restoreUserInterfaceForPictureInPictureStopWithCompletionHandler:)","abstract":[],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"pictureInPictureController","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)AVPictureInPictureController","kind":"typeIdentifier","text":"AVPictureInPictureController"},{"kind":"text","text":", "},{"text":"restoreUserInterfaceForPictureInPictureStopWithCompletionHandler","kind":"externalParam"},{"text":": (","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"role":"symbol","navigatorTitle":[{"text":"pictureInPictureController:restoreUserInterfaceForPictureInPictureStopWithCompletionHandler:","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","value":"pictureInPictureController:restoreUserInterfaceForPictureInPictureStopWithCompletionHandler:","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"pictureInPictureController:restoreUserInterfaceForPictureInPictureStopWithCompletionHandler:","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"pictureInPictureController:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"AVPictureInPictureController","preciseIdentifier":"c:objc(cs)AVPictureInPictureController"},{"kind":"text","text":" *) "},{"text":"pictureInPictureController","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"restoreUserInterfaceForPictureInPictureStopWithCompletionHandler:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"text":" (^","kind":"text"},{"text":")(","kind":"text"},{"preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier","text":"BOOL"},{"kind":"text","text":" "},{"kind":"internalParam","text":""},{"text":")) ","kind":"text"},{"text":"completionHandler","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1Call1v1VideoViewController\/title","value":"Call1v1VideoViewController"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1Call1v1VideoViewController\/fragments","value":[{"kind":"identifier","text":"Call1v1VideoViewController"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1Call1v1VideoViewController\/navigatorTitle","op":"replace","value":[{"text":"Call1v1VideoViewController","kind":"identifier"}]},{"op":"replace","value":"pictureInPictureController:restoreUserInterfaceForPictureInPictureStopWithCompletionHandler:","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1Call1v1VideoViewController~1pictureInPictureController(_:restoreUserInterfaceForPictureInPictureStopWithCompletionHandler:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"pictureInPictureController:restoreUserInterfaceForPictureInPictureStopWithCompletionHandler:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1Call1v1VideoViewController~1pictureInPictureController(_:restoreUserInterfaceForPictureInPictureStopWithCompletionHandler:)\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}