{"kind":"symbol","metadata":{"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"clickClosure","kind":"identifier"},{"text":": ((","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseCallUIKit@E@ChatNavigationBarClickEvent","text":"ChatNavigationBarClickEvent"},{"kind":"text","text":", "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation9IndexPathV","text":"IndexPath"},{"text":"?) -> ())?","kind":"text"}],"navigatorTitle":[{"text":"clickClosure","kind":"identifier"}],"title":"clickClosure","externalID":"c:@M@EaseCallUIKit@objc(cs)CallNavigationBar(py)clickClosure","symbolKind":"property","role":"symbol","modules":[{"name":"EaseCallUIKit"}],"roleHeading":"Instance Property"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallNavigationBar"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallNavigationBar\/clickClosure"},"variants":[{"paths":["\/documentation\/easecalluikit\/callnavigationbar\/clickclosure"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/easecalluikit\/callnavigationbar\/clickclosure"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"@","kind":"attribute"},{"preciseIdentifier":"s:ScM","text":"MainActor","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"clickClosure"},{"text":": ((","kind":"text"},{"kind":"typeIdentifier","text":"ChatNavigationBarClickEvent","preciseIdentifier":"c:@M@EaseCallUIKit@E@ChatNavigationBarClickEvent","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/ChatNavigationBarClickEvent"},{"kind":"text","text":", "},{"preciseIdentifier":"s:10Foundation9IndexPathV","kind":"typeIdentifier","text":"IndexPath"},{"text":"?) -> ())?","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}],"references":{"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallNavigationBar/clickClosure":{"type":"topic","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallNavigationBar\/clickClosure","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"clickClosure","kind":"identifier"},{"text":": ((","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseCallUIKit@E@ChatNavigationBarClickEvent","text":"ChatNavigationBarClickEvent"},{"text":", ","kind":"text"},{"text":"IndexPath","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation9IndexPathV"},{"kind":"text","text":"?) -> ())?"}],"url":"\/documentation\/easecalluikit\/callnavigationbar\/clickclosure","navigatorTitle":[{"text":"clickClosure","kind":"identifier"}],"title":"clickClosure","abstract":[],"kind":"symbol"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/ChatNavigationBarClickEvent":{"title":"ChatNavigationBarClickEvent","role":"symbol","abstract":[],"type":"topic","kind":"symbol","navigatorTitle":[{"text":"ChatNavigationBarClickEvent","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"ChatNavigationBarClickEvent","kind":"identifier"}],"url":"\/documentation\/easecalluikit\/chatnavigationbarclickevent","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/ChatNavigationBarClickEvent"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallNavigationBar":{"type":"topic","title":"CallNavigationBar","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallNavigationBar","url":"\/documentation\/easecalluikit\/callnavigationbar","role":"symbol","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CallNavigationBar"}],"navigatorTitle":[{"text":"CallNavigationBar","kind":"identifier"}],"abstract":[{"text":"Navigation  bar of the ChatUIKit.","type":"text"}]},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit":{"title":"EaseCallUIKit","type":"topic","url":"\/documentation\/easecalluikit","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit","abstract":[],"role":"collection","kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"clickClosure","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"clickClosure","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":") "},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":" (^","kind":"text"},{"text":"clickClosure","kind":"identifier"},{"text":")(","kind":"text"},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"preciseIdentifier":"c:@M@EaseCallUIKit@E@ChatNavigationBarClickEvent","kind":"typeIdentifier","text":"ChatNavigationBarClickEvent","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/ChatNavigationBarClickEvent"},{"text":" ","kind":"text"},{"text":"","kind":"internalParam"},{"text":", ","kind":"text"},{"kind":"typeIdentifier","text":"NSIndexPath","preciseIdentifier":"c:objc(cs)NSIndexPath"},{"text":" * ","kind":"text"},{"kind":"internalParam","text":""},{"kind":"text","text":");"}]}],"kind":"declarations"},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallNavigationBar~1clickClosure\/title","value":"clickClosure"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallNavigationBar~1clickClosure\/fragments","value":[{"text":"clickClosure","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1ChatNavigationBarClickEvent\/title","value":"ChatNavigationBarClickEvent"},{"value":[{"kind":"identifier","text":"ChatNavigationBarClickEvent"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1ChatNavigationBarClickEvent\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1ChatNavigationBarClickEvent\/navigatorTitle","op":"replace","value":[{"text":"ChatNavigationBarClickEvent","kind":"identifier"}]},{"value":"CallNavigationBar","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallNavigationBar\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallNavigationBar\/fragments","value":[{"kind":"identifier","text":"CallNavigationBar"}]},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallNavigationBar\/navigatorTitle","value":[{"text":"CallNavigationBar","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}