{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallNavigationBar"]]},"variants":[{"paths":["\/documentation\/easecalluikit\/callnavigationbar\/init(show:showleftitem:textalignment:placeholder:avatarurl:rightimages:hiddenavatar:nearstatusbar:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/easecalluikit\/callnavigationbar\/init(show:showleftitem:textalignment:placeholder:avatarurl:rightimages:hiddenavatar:nearstatusbar:)"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"abstract":[{"text":"EaseChatNavigationBar init method with right items kind of images.","type":"text"}],"metadata":{"title":"init(show:showLeftItem:textAlignment:placeHolder:avatarURL:rightImages:hiddenAvatar:nearStatusBar:)","externalID":"c:@M@EaseCallUIKit@objc(cs)CallNavigationBar(im)initWithShow:showLeftItem:textAlignment:placeHolder:avatarURL:rightImages:hiddenAvatar:nearStatusBar:","navigatorTitle":[{"text":"initWithShow:showLeftItem:textAlignment:placeHolder:avatarURL:rightImages:hiddenAvatar:nearStatusBar:","kind":"identifier"}],"symbolKind":"init","roleHeading":"Initializer","role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"show"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect","text":"CGRect"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"showLeftItem"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"textAlignment"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@E@NSTextAlignment","kind":"typeIdentifier","text":"NSTextAlignment"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"placeHolder"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"text":"avatarURL","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"text":"rightImages","kind":"externalParam"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"},{"kind":"text","text":"], "},{"text":"hiddenAvatar","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"nearStatusBar"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":")","kind":"text"}],"modules":[{"name":"EaseCallUIKit"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"attribute","text":"@"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"kind":"keyword","text":"convenience"},{"kind":"text","text":" "},{"text":"init","kind":"keyword"},{"kind":"text","text":"("},{"text":"show","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"frame","kind":"internalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"CGRect","preciseIdentifier":"c:@S@CGRect"},{"kind":"text","text":" = CGRect(x: 0, y: 0, width: ScreenWidth, height: NavigationHeight), "},{"kind":"externalParam","text":"showLeftItem"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":", "},{"text":"textAlignment","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NSTextAlignment","kind":"typeIdentifier","preciseIdentifier":"c:@E@NSTextAlignment"},{"text":" = .center, ","kind":"text"},{"text":"placeHolder","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIImage","kind":"typeIdentifier","text":"UIImage"},{"text":"? = nil, ","kind":"text"},{"kind":"externalParam","text":"avatarURL"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"? = nil, ","kind":"text"},{"text":"rightImages","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage","kind":"typeIdentifier"},{"kind":"text","text":"] = [], "},{"kind":"externalParam","text":"hiddenAvatar"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"text":" = false, ","kind":"text"},{"kind":"externalParam","text":"nearStatusBar"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"kind":"text","text":" = true)"}],"platforms":["iOS"],"languages":["swift"]}]},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"Whether show left button or not.","type":"text"}]}],"name":"showLeftItem"},{"name":"textAlignment","content":[{"inlineContent":[{"text":"Title and subtitle text alignment.","type":"text"}],"type":"paragraph"}]},{"name":"placeHolder","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Avatar default image."}]}]},{"content":[{"inlineContent":[{"text":"Avatar url.","type":"text"}],"type":"paragraph"}],"name":"avatarURL"},{"name":"rightImages","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Right buttons kind of "},{"code":"[UIImage]","type":"codeVoice"},{"type":"text","text":"."}]}]},{"content":[{"inlineContent":[{"text":"Whether hide avatar or not.","type":"text"}],"type":"paragraph"}],"name":"hiddenAvatar"}],"kind":"parameters"}],"schemaVersion":{"patch":0,"minor":3,"major":0},"identifier":{"url":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallNavigationBar\/init(show:showLeftItem:textAlignment:placeHolder:avatarURL:rightImages:hiddenAvatar:nearStatusBar:)","interfaceLanguage":"swift"},"kind":"symbol","references":{"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallNavigationBar/init(show:showLeftItem:textAlignment:placeHolder:avatarURL:rightImages:hiddenAvatar:nearStatusBar:)":{"type":"topic","title":"init(show:showLeftItem:textAlignment:placeHolder:avatarURL:rightImages:hiddenAvatar:nearStatusBar:)","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallNavigationBar\/init(show:showLeftItem:textAlignment:placeHolder:avatarURL:rightImages:hiddenAvatar:nearStatusBar:)","url":"\/documentation\/easecalluikit\/callnavigationbar\/init(show:showleftitem:textalignment:placeholder:avatarurl:rightimages:hiddenavatar:nearstatusbar:)","role":"symbol","kind":"symbol","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"show","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CGRect","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"showLeftItem"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"textAlignment","kind":"externalParam"},{"kind":"text","text":": "},{"text":"NSTextAlignment","kind":"typeIdentifier","preciseIdentifier":"c:@E@NSTextAlignment"},{"text":", ","kind":"text"},{"text":"placeHolder","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage"},{"text":"?, ","kind":"text"},{"text":"avatarURL","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"rightImages","kind":"externalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage","kind":"typeIdentifier"},{"text":"], ","kind":"text"},{"kind":"externalParam","text":"hiddenAvatar"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":", "},{"text":"nearStatusBar","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"initWithShow:showLeftItem:textAlignment:placeHolder:avatarURL:rightImages:hiddenAvatar:nearStatusBar:","kind":"identifier"}],"abstract":[{"type":"text","text":"EaseChatNavigationBar init method with right items kind of images."}]},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit":{"title":"EaseCallUIKit","type":"topic","url":"\/documentation\/easecalluikit","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit","abstract":[],"role":"collection","kind":"symbol"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallNavigationBar":{"type":"topic","title":"CallNavigationBar","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallNavigationBar","url":"\/documentation\/easecalluikit\/callnavigationbar","role":"symbol","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CallNavigationBar"}],"navigatorTitle":[{"text":"CallNavigationBar","kind":"identifier"}],"abstract":[{"text":"Navigation  bar of the ChatUIKit.","type":"text"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"initWithShow:showLeftItem:textAlignment:placeHolder:avatarURL:rightImages:hiddenAvatar:nearStatusBar:"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithShow:showLeftItem:textAlignment:placeHolder:avatarURL:rightImages:hiddenAvatar:nearStatusBar:"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"id","preciseIdentifier":"c:*Qo","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"initWithShow:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"CGRect","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect"},{"text":") ","kind":"text"},{"text":"frame","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"showLeftItem:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"kind":"text","text":") "},{"kind":"internalParam","text":"showLeftItem"},{"text":" ","kind":"text"},{"text":"textAlignment:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSTextAlignment","kind":"typeIdentifier","preciseIdentifier":"c:@E@NSTextAlignment"},{"kind":"text","text":") "},{"text":"textAlignment","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"placeHolder:"},{"text":"(","kind":"text"},{"text":"UIImage","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage"},{"kind":"text","text":" *) "},{"text":"placeHolder","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"avatarURL:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"text":"avatarURL","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"rightImages:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<UIImage *>"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"rightImages"},{"text":" ","kind":"text"},{"text":"hiddenAvatar:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@T@BOOL","text":"BOOL","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"hiddenAvatar","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"nearStatusBar:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@T@BOOL","text":"BOOL","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"nearStatusBar","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","value":{"kind":"parameters","parameters":[{"name":"showLeftItem","content":[{"inlineContent":[{"type":"text","text":"Whether show left button or not."}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"text":"Title and subtitle text alignment.","type":"text"}],"type":"paragraph"}],"name":"textAlignment"},{"name":"placeHolder","content":[{"inlineContent":[{"type":"text","text":"Avatar default image."}],"type":"paragraph"}]},{"name":"avatarURL","content":[{"inlineContent":[{"text":"Avatar url.","type":"text"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"text":"Right buttons kind of ","type":"text"},{"type":"codeVoice","code":"[UIImage]"},{"type":"text","text":"."}],"type":"paragraph"}],"name":"rightImages"},{"name":"hiddenAvatar","content":[{"inlineContent":[{"text":"Whether hide avatar or not.","type":"text"}],"type":"paragraph"}]}]},"path":"\/primaryContentSections\/1"},{"value":"initWithShow:showLeftItem:textAlignment:placeHolder:avatarURL:rightImages:hiddenAvatar:nearStatusBar:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallNavigationBar~1init(show:showLeftItem:textAlignment:placeHolder:avatarURL:rightImages:hiddenAvatar:nearStatusBar:)\/title"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithShow:showLeftItem:textAlignment:placeHolder:avatarURL:rightImages:hiddenAvatar:nearStatusBar:"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallNavigationBar~1init(show:showLeftItem:textAlignment:placeHolder:avatarURL:rightImages:hiddenAvatar:nearStatusBar:)\/fragments"},{"op":"replace","value":"CallNavigationBar","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallNavigationBar\/title"},{"op":"replace","value":[{"kind":"identifier","text":"CallNavigationBar"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallNavigationBar\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallNavigationBar\/navigatorTitle","value":[{"kind":"identifier","text":"CallNavigationBar"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}