{"abstract":[{"type":"text","text":"EaseChatNavigationBar init method with right item kind of text."}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallNavigationBar\/init(show:textAlignment:rightTitle:)"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallNavigationBar"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"@","kind":"attribute"},{"preciseIdentifier":"s:ScM","text":"MainActor","kind":"attribute"},{"kind":"text","text":" "},{"text":"convenience","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"text":"show","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"frame"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect","text":"CGRect"},{"kind":"text","text":" = CGRect(x: 0, y: 0, width: ScreenWidth, height: NavigationHeight), "},{"kind":"externalParam","text":"textAlignment"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@E@NSTextAlignment","kind":"typeIdentifier","text":"NSTextAlignment"},{"text":" = .center, ","kind":"text"},{"kind":"externalParam","text":"rightTitle"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"? = nil)","kind":"text"}]}]},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"type":"codeVoice","code":"NSTextAlignment"}]}],"name":"textAlignment"},{"content":[{"type":"paragraph","inlineContent":[{"text":"Title of the right item.","type":"text"}]}],"name":"rightTitle"}]}],"metadata":{"navigatorTitle":[{"text":"initWithShow:textAlignment:rightTitle:","kind":"identifier"}],"symbolKind":"init","externalID":"c:@M@EaseCallUIKit@objc(cs)CallNavigationBar(im)initWithShow:textAlignment:rightTitle:","role":"symbol","roleHeading":"Initializer","modules":[{"name":"EaseCallUIKit"}],"fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"show"},{"kind":"text","text":": "},{"text":"CGRect","preciseIdentifier":"c:@S@CGRect","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"textAlignment"},{"kind":"text","text":": "},{"text":"NSTextAlignment","kind":"typeIdentifier","preciseIdentifier":"c:@E@NSTextAlignment"},{"kind":"text","text":", "},{"text":"rightTitle","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"title":"init(show:textAlignment:rightTitle:)"},"schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easecalluikit\/callnavigationbar\/init(show:textalignment:righttitle:)"]},{"paths":["\/documentation\/easecalluikit\/callnavigationbar\/init(show:textalignment:righttitle:)"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"references":{"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallNavigationBar/init(show:textAlignment:rightTitle:)":{"navigatorTitle":[{"kind":"identifier","text":"initWithShow:textAlignment:rightTitle:"}],"url":"\/documentation\/easecalluikit\/callnavigationbar\/init(show:textalignment:righttitle:)","kind":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"text":"show","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect","text":"CGRect"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"textAlignment"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@NSTextAlignment","text":"NSTextAlignment"},{"kind":"text","text":", "},{"text":"rightTitle","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?)"}],"title":"init(show:textAlignment:rightTitle:)","abstract":[{"type":"text","text":"EaseChatNavigationBar init method with right item kind of text."}],"type":"topic","role":"symbol","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallNavigationBar\/init(show:textAlignment:rightTitle:)"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallNavigationBar":{"type":"topic","title":"CallNavigationBar","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallNavigationBar","url":"\/documentation\/easecalluikit\/callnavigationbar","role":"symbol","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CallNavigationBar"}],"navigatorTitle":[{"text":"CallNavigationBar","kind":"identifier"}],"abstract":[{"text":"Navigation  bar of the ChatUIKit.","type":"text"}]},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit":{"title":"EaseCallUIKit","type":"topic","url":"\/documentation\/easecalluikit","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit","abstract":[],"role":"collection","kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"initWithShow:textAlignment:rightTitle:"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithShow:textAlignment:rightTitle:"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"id","preciseIdentifier":"c:*Qo","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithShow:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@S@CGRect","text":"CGRect","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"frame","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"textAlignment:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@NSTextAlignment","text":"NSTextAlignment"},{"text":") ","kind":"text"},{"text":"textAlignment","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"rightTitle:"},{"kind":"text","text":"("},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"rightTitle"},{"kind":"text","text":";"}]}]}},{"op":"replace","value":{"kind":"parameters","parameters":[{"name":"textAlignment","content":[{"inlineContent":[{"type":"text","text":""},{"type":"codeVoice","code":"NSTextAlignment"}],"type":"paragraph"}]},{"name":"rightTitle","content":[{"inlineContent":[{"type":"text","text":"Title of the right item."}],"type":"paragraph"}]}]},"path":"\/primaryContentSections\/1"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallNavigationBar~1init(show:textAlignment:rightTitle:)\/title","value":"initWithShow:textAlignment:rightTitle:"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallNavigationBar~1init(show:textAlignment:rightTitle:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithShow:textAlignment:rightTitle:"}],"op":"replace"},{"op":"replace","value":"CallNavigationBar","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallNavigationBar\/title"},{"value":[{"text":"CallNavigationBar","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallNavigationBar\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallNavigationBar\/navigatorTitle","value":[{"kind":"identifier","text":"CallNavigationBar"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}