{"kind":"article","hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallNavigationBar"]]},"identifier":{"url":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallNavigationBar\/ThemeSwitchProtocol-Implementations","interfaceLanguage":"swift"},"sections":[],"topicSections":[{"generated":true,"anchor":"Instance-Methods","title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallNavigationBar\/switchTheme(style:)"]}],"metadata":{"title":"ThemeSwitchProtocol Implementations","roleHeading":"API Collection","modules":[{"name":"EaseCallUIKit"}],"role":"collectionGroup"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easecalluikit\/callnavigationbar\/themeswitchprotocol-implementations"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easecalluikit\/callnavigationbar\/themeswitchprotocol-implementations"]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallNavigationBar":{"type":"topic","title":"CallNavigationBar","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallNavigationBar","url":"\/documentation\/easecalluikit\/callnavigationbar","role":"symbol","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CallNavigationBar"}],"navigatorTitle":[{"text":"CallNavigationBar","kind":"identifier"}],"abstract":[{"text":"Navigation  bar of the ChatUIKit.","type":"text"}]},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit":{"title":"EaseCallUIKit","type":"topic","url":"\/documentation\/easecalluikit","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit","abstract":[],"role":"collection","kind":"symbol"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallNavigationBar/switchTheme(style:)":{"type":"topic","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallNavigationBar\/switchTheme(style:)","navigatorTitle":[{"text":"switchThemeWithStyle:","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"When some view Implement the protocol method,you can use "},{"type":"codeVoice","code":"Theme.switchTheme(style: .dark)"},{"text":" to switch theme.","type":"text"}],"role":"symbol","title":"switchTheme(style:)","url":"\/documentation\/easecalluikit\/callnavigationbar\/switchtheme(style:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"switchTheme","kind":"identifier"},{"text":"(","kind":"text"},{"text":"style","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseCallUIKit@E@ThemeStyle","text":"ThemeStyle"},{"kind":"text","text":")"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/topicSections","value":[{"generated":true,"identifiers":["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallNavigationBar\/switchTheme(style:)"],"title":"Instance Methods","anchor":"Instance-Methods"}]},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":"CallNavigationBar","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallNavigationBar\/title"},{"value":[{"kind":"identifier","text":"CallNavigationBar"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallNavigationBar\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallNavigationBar\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"CallNavigationBar"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallNavigationBar~1switchTheme(style:)\/title","value":"switchThemeWithStyle:"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"switchThemeWithStyle:"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallNavigationBar~1switchTheme(style:)\/fragments"}]}]}