{"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"externalID":"c:@M@EaseCallUIKit@objc(cs)CallNavigationBar(py)titleAttribute","symbolKind":"property","roleHeading":"Instance Property","title":"titleAttribute","modules":[{"name":"EaseCallUIKit"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"titleAttribute"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"titleAttribute"},{"kind":"text","text":": "},{"text":"NSAttributedString","preciseIdentifier":"c:objc(cs)NSAttributedString","kind":"typeIdentifier"},{"kind":"text","text":"?"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@"},{"kind":"attribute","text":"MainActor","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"titleAttribute"},{"kind":"text","text":": "},{"text":"NSAttributedString","preciseIdentifier":"c:objc(cs)NSAttributedString","kind":"typeIdentifier"},{"text":"? { ","kind":"text"},{"text":"get","kind":"keyword"},{"kind":"text","text":" "},{"text":"set","kind":"keyword"},{"kind":"text","text":" }"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"paths":["\/documentation\/easecalluikit\/callnavigationbar\/titleattribute"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/easecalluikit\/callnavigationbar\/titleattribute"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","identifier":{"url":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallNavigationBar\/titleAttribute","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallNavigationBar"]]},"sections":[],"abstract":[{"type":"text","text":"Title kind of the "},{"code":"NSAttributedString","type":"codeVoice"},{"type":"text","text":"."}],"references":{"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallNavigationBar/titleAttribute":{"type":"topic","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallNavigationBar\/titleAttribute","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"titleAttribute"},{"text":": ","kind":"text"},{"text":"NSAttributedString","preciseIdentifier":"c:objc(cs)NSAttributedString","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"url":"\/documentation\/easecalluikit\/callnavigationbar\/titleattribute","navigatorTitle":[{"text":"titleAttribute","kind":"identifier"}],"title":"titleAttribute","abstract":[{"type":"text","text":"Title kind of the "},{"code":"NSAttributedString","type":"codeVoice"},{"text":".","type":"text"}],"kind":"symbol"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit":{"title":"EaseCallUIKit","type":"topic","url":"\/documentation\/easecalluikit","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit","abstract":[],"role":"collection","kind":"symbol"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallNavigationBar":{"type":"topic","title":"CallNavigationBar","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallNavigationBar","url":"\/documentation\/easecalluikit\/callnavigationbar","role":"symbol","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CallNavigationBar"}],"navigatorTitle":[{"text":"CallNavigationBar","kind":"identifier"}],"abstract":[{"text":"Navigation  bar of the ChatUIKit.","type":"text"}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"titleAttribute","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"titleAttribute"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSAttributedString","text":"NSAttributedString","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"titleAttribute","kind":"identifier"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]}},{"value":"titleAttribute","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallNavigationBar~1titleAttribute\/title","op":"replace"},{"value":[{"kind":"identifier","text":"titleAttribute"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallNavigationBar~1titleAttribute\/fragments","op":"replace"},{"value":"CallNavigationBar","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallNavigationBar\/title"},{"op":"replace","value":[{"kind":"identifier","text":"CallNavigationBar"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallNavigationBar\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallNavigationBar\/navigatorTitle","op":"replace","value":[{"text":"CallNavigationBar","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}