{"metadata":{"role":"symbol","modules":[{"name":"EaseCallUIKit"}],"roleHeading":"Type Method","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"localValue"},{"kind":"text","text":"("},{"kind":"externalParam","text":"key"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":") -> ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"externalID":"s:13EaseCallUIKit17LanguageConvertorC10localValue3keyS2S_tFZ","title":"localValue(key:)","symbolKind":"method"},"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"paths":["\/documentation\/easecalluikit\/languageconvertor\/localvalue(key:)"],"traits":[{"interfaceLanguage":"swift"}]}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"localValue","kind":"identifier"},{"text":"(","kind":"text"},{"text":"key","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/LanguageConvertor\/localValue(key:)"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/LanguageConvertor"]]},"references":{"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/LanguageConvertor/localValue(key:)":{"url":"\/documentation\/easecalluikit\/languageconvertor\/localvalue(key:)","title":"localValue(key:)","type":"topic","role":"symbol","kind":"symbol","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/LanguageConvertor\/localValue(key:)","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"localValue"},{"kind":"text","text":"("},{"kind":"externalParam","text":"key"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}]},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/LanguageConvertor":{"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/LanguageConvertor","url":"\/documentation\/easecalluikit\/languageconvertor","abstract":[{"text":"A utility class for converting language keys to localized strings.","type":"text"}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"LanguageConvertor"}],"navigatorTitle":[{"kind":"identifier","text":"LanguageConvertor"}],"role":"symbol","kind":"symbol","title":"LanguageConvertor"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit":{"title":"EaseCallUIKit","type":"topic","url":"\/documentation\/easecalluikit","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit","abstract":[],"role":"collection","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"LanguageConvertor","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1LanguageConvertor\/title"},{"value":[{"text":"LanguageConvertor","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1LanguageConvertor\/fragments","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"LanguageConvertor"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1LanguageConvertor\/navigatorTitle"}]}]}