{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"call","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"text":" ","kind":"text"},{"text":"userId","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"text":"type","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@EaseCallUIKit@E@CallType","kind":"typeIdentifier","text":"CallType","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallType"},{"kind":"text","text":", "},{"text":"extensionInfo","kind":"externalParam"},{"kind":"text","text":": ["},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]?)"}],"platforms":["iOS"],"languages":["swift"]}]},{"parameters":[{"name":"userId","content":[{"type":"paragraph","inlineContent":[{"text":"The ID of the user to call.","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The type of call to initiate (multiAudio or multiVideo)."},{"type":"reference","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallType","isActive":true}]}],"name":"type"},{"content":[{"inlineContent":[{"text":"Optional additional information to include with the call, such as custom data or metadata.","type":"text"}],"type":"paragraph"}],"name":"extensionInfo"}],"kind":"parameters"}],"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallMessageService"]]},"abstract":[{"type":"text","text":"Initiates a call with the specified user ID and call type."}],"metadata":{"navigatorTitle":[{"text":"callWith:type:extensionInfo:","kind":"identifier"}],"externalID":"c:@M@EaseCallUIKit@objc(pl)CallMessageService(im)callWith:type:extensionInfo:","symbolKind":"method","role":"symbol","required":true,"roleHeading":"Instance Method","modules":[{"name":"EaseCallUIKit"}],"title":"call(with:type:extensionInfo:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"call","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"with"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"type"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CallType","preciseIdentifier":"c:@M@EaseCallUIKit@E@CallType"},{"kind":"text","text":", "},{"kind":"externalParam","text":"extensionInfo"},{"kind":"text","text":": ["},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":" : ","kind":"text"},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]?)"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easecalluikit\/callmessageservice\/call(with:type:extensioninfo:)"]},{"paths":["\/documentation\/easecalluikit\/callmessageservice\/call(with:type:extensioninfo:)"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"url":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallMessageService\/call(with:type:extensionInfo:)","interfaceLanguage":"swift"},"references":{"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallMessageService/call(with:type:extensionInfo:)":{"navigatorTitle":[{"text":"callWith:type:extensionInfo:","kind":"identifier"}],"abstract":[{"text":"Initiates a call with the specified user ID and call type.","type":"text"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallMessageService\/call(with:type:extensionInfo:)","type":"topic","url":"\/documentation\/easecalluikit\/callmessageservice\/call(with:type:extensioninfo:)","required":true,"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"call"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"type"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CallType","preciseIdentifier":"c:@M@EaseCallUIKit@E@CallType"},{"kind":"text","text":", "},{"kind":"externalParam","text":"extensionInfo"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"kind":"keyword","text":"Any"},{"text":"]?)","kind":"text"}],"title":"call(with:type:extensionInfo:)"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallMessageService":{"type":"topic","url":"\/documentation\/easecalluikit\/callmessageservice","kind":"symbol","navigatorTitle":[{"text":"CallMessageService","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallMessageService","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"CallMessageService","kind":"identifier"}],"title":"CallMessageService","abstract":[]},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit":{"title":"EaseCallUIKit","type":"topic","url":"\/documentation\/easecalluikit","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit","abstract":[],"role":"collection","kind":"symbol"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallType":{"kind":"symbol","title":"CallType","navigatorTitle":[{"text":"CallType","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallType","url":"\/documentation\/easecalluikit\/calltype","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CallType"}],"abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"value":"callWith:type:extensionInfo:","path":"\/metadata\/title","op":"replace"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"callWith:type:extensionInfo:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"callWith:"},{"kind":"text","text":"("},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"userId","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"type:"},{"text":"(","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallType","kind":"typeIdentifier","text":"CallType","preciseIdentifier":"c:@M@EaseCallUIKit@E@CallType"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"type"},{"kind":"text","text":" "},{"text":"extensionInfo:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSDictionary<NSString *,id>","preciseIdentifier":"c:Q$objc(cs)NSDictionary","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"extensionInfo","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"]}]}},{"op":"replace","path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"name":"userId","content":[{"type":"paragraph","inlineContent":[{"text":"The ID of the user to call.","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The type of call to initiate (multiAudio or multiVideo)."},{"isActive":true,"type":"reference","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallType"}]}],"name":"type"},{"name":"extensionInfo","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Optional additional information to include with the call, such as custom data or metadata."}]}]}]}},{"op":"replace","value":"callWith:type:extensionInfo:","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallMessageService~1call(with:type:extensionInfo:)\/title"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"callWith:type:extensionInfo:"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallMessageService~1call(with:type:extensionInfo:)\/fragments"},{"value":"CallMessageService","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallMessageService\/title","op":"replace"},{"value":[{"kind":"identifier","text":"CallMessageService"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallMessageService\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallMessageService\/navigatorTitle","value":[{"text":"CallMessageService","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallType\/title","value":"CallType","op":"replace"},{"op":"replace","value":[{"text":"CallType","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallType\/fragments"},{"value":[{"text":"CallType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallType\/navigatorTitle"}]}]}