{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallMessageService\/removeListener(_:)"},"sections":[],"metadata":{"symbolKind":"method","roleHeading":"Instance Method","required":true,"externalID":"c:@M@EaseCallUIKit@objc(pl)CallMessageService(im)removeListener:","navigatorTitle":[{"kind":"identifier","text":"removeListener:"}],"role":"symbol","title":"removeListener(_:)","modules":[{"name":"EaseCallUIKit"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"removeListener","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@EaseCallUIKit@objc(pl)CallServiceListener","kind":"typeIdentifier","text":"CallServiceListener"},{"text":")","kind":"text"}]},"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","abstract":[{"type":"text","text":"Removes a previously added listener from receiving call-related events."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"removeListener"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"text":"listener","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"CallServiceListener","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallServiceListener","preciseIdentifier":"c:@M@EaseCallUIKit@objc(pl)CallServiceListener","kind":"typeIdentifier"},{"kind":"text","text":")"}],"platforms":["iOS"]}]},{"parameters":[{"name":"listener","content":[{"type":"paragraph","inlineContent":[{"text":"An object conforming to the ","type":"text"},{"type":"reference","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallServiceListener","isActive":true},{"text":" protocol that will no longer receive call events.","type":"text"}]}]}],"kind":"parameters"}],"variants":[{"paths":["\/documentation\/easecalluikit\/callmessageservice\/removelistener(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/easecalluikit\/callmessageservice\/removelistener(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallMessageService"]]},"references":{"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallMessageService":{"type":"topic","url":"\/documentation\/easecalluikit\/callmessageservice","kind":"symbol","navigatorTitle":[{"text":"CallMessageService","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallMessageService","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"CallMessageService","kind":"identifier"}],"title":"CallMessageService","abstract":[]},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallServiceListener":{"abstract":[],"kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"CallServiceListener"}],"url":"\/documentation\/easecalluikit\/callservicelistener","title":"CallServiceListener","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CallServiceListener"}],"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallServiceListener","role":"symbol"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallMessageService/removeListener(_:)":{"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallMessageService\/removeListener(_:)","type":"topic","url":"\/documentation\/easecalluikit\/callmessageservice\/removelistener(_:)","kind":"symbol","title":"removeListener(_:)","required":true,"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"removeListener","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@EaseCallUIKit@objc(pl)CallServiceListener","text":"CallServiceListener","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"removeListener:"}],"abstract":[{"text":"Removes a previously added listener from receiving call-related events.","type":"text"}],"role":"symbol"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit":{"title":"EaseCallUIKit","type":"topic","url":"\/documentation\/easecalluikit","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit","abstract":[],"role":"collection","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"removeListener:"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"removeListener:"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"removeListener:"},{"text":"(","kind":"text"},{"text":"id<CallServiceListener>","preciseIdentifier":"c:Qo@M@EaseCallUIKit@objc(pl)CallServiceListener","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"listener"},{"kind":"text","text":";"}]}]},"op":"replace"},{"path":"\/primaryContentSections\/1","value":{"parameters":[{"name":"listener","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"An object conforming to the "},{"isActive":true,"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallServiceListener","type":"reference"},{"type":"text","text":" protocol that will no longer receive call events."}]}]}],"kind":"parameters"},"op":"replace"},{"op":"replace","value":"CallMessageService","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallMessageService\/title"},{"value":[{"kind":"identifier","text":"CallMessageService"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallMessageService\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallMessageService\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"CallMessageService"}]},{"op":"replace","value":"CallServiceListener","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallServiceListener\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallServiceListener\/fragments","value":[{"text":"CallServiceListener","kind":"identifier"}],"op":"replace"},{"op":"replace","value":[{"text":"CallServiceListener","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallServiceListener\/navigatorTitle"},{"value":"removeListener:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallMessageService~1removeListener(_:)\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallMessageService~1removeListener(_:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"removeListener:","kind":"identifier"}]}]}]}