{"abstract":[{"type":"text","text":"Asynchronously get the call token."}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"getRelationsAsync","kind":"identifier"},{"text":"(","kind":"text"},{"text":"rtc","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"uids","kind":"internalParam"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"UInt32","preciseIdentifier":"s:s6UInt32V"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"completion"},{"text":": ","kind":"text"},{"text":"@escaping","kind":"attribute"},{"kind":"text","text":" (["},{"preciseIdentifier":"s:s6UInt32V","text":"UInt32","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"]) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"text":")","kind":"text"}]}],"kind":"declarations"},{"parameters":[{"content":[{"inlineContent":[{"type":"text","text":"The user ID array."}],"type":"paragraph"}],"name":"uids"},{"content":[{"type":"paragraph","inlineContent":[{"text":"Callback, returns a dictionary where keys are user IDs and values are the corresponding tokens.","type":"text"}]}],"name":"completion"}],"kind":"parameters"}],"identifier":{"url":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallTokenProvider\/getRelationsAsync(rtc:completion:)","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/easecalluikit\/calltokenprovider\/getrelationsasync(rtc:completion:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/easecalluikit\/calltokenprovider\/getrelationsasync(rtc:completion:)"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallTokenProvider"]]},"kind":"symbol","metadata":{"title":"getRelationsAsync(rtc:completion:)","roleHeading":"Instance Method","externalID":"c:@M@EaseCallUIKit@objc(pl)CallTokenProvider(im)getRelationsAsyncWithRtc:completion:","symbolKind":"method","navigatorTitle":[{"text":"getRelationsAsyncWithRtc:completion:","kind":"identifier"}],"modules":[{"name":"EaseCallUIKit"}],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"getRelationsAsync","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"rtc"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s6UInt32V","text":"UInt32"},{"kind":"text","text":"], "},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": (["},{"preciseIdentifier":"s:s6UInt32V","kind":"typeIdentifier","text":"UInt32"},{"text":" : ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"]) -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"text":")","kind":"text"}],"required":true},"references":{"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallTokenProvider":{"url":"\/documentation\/easecalluikit\/calltokenprovider","abstract":[],"navigatorTitle":[{"text":"CallTokenProvider","kind":"identifier"}],"kind":"symbol","title":"CallTokenProvider","type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CallTokenProvider","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallTokenProvider","role":"symbol"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit":{"title":"EaseCallUIKit","type":"topic","url":"\/documentation\/easecalluikit","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit","abstract":[],"role":"collection","kind":"symbol"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallTokenProvider/getRelationsAsync(rtc:completion:)":{"title":"getRelationsAsync(rtc:completion:)","required":true,"abstract":[{"type":"text","text":"Asynchronously get the call token."}],"navigatorTitle":[{"text":"getRelationsAsyncWithRtc:completion:","kind":"identifier"}],"url":"\/documentation\/easecalluikit\/calltokenprovider\/getrelationsasync(rtc:completion:)","role":"symbol","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getRelationsAsync"},{"kind":"text","text":"("},{"text":"rtc","kind":"externalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:s6UInt32V","text":"UInt32","kind":"typeIdentifier"},{"text":"], ","kind":"text"},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": (["},{"kind":"typeIdentifier","preciseIdentifier":"s:s6UInt32V","text":"UInt32"},{"text":" : ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"]) -> "},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":")","kind":"text"}],"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallTokenProvider\/getRelationsAsync(rtc:completion:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"value":"getRelationsAsyncWithRtc:completion:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"getRelationsAsyncWithRtc:completion:"}]},{"path":"\/topicSections","op":"add","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"kind":"identifier","text":"getRelationsAsyncWithRtc:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:Q$objc(cs)NSArray","kind":"typeIdentifier","text":"NSArray<NSNumber *>"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"uids"},{"kind":"text","text":" "},{"text":"completion:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"text":" (^","kind":"text"},{"text":")(","kind":"text"},{"text":"NSDictionary<NSNumber *,NSString *>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSDictionary"},{"text":" * ","kind":"text"},{"text":"","kind":"internalParam"},{"kind":"text","text":")) "},{"kind":"internalParam","text":"completion"},{"text":";","kind":"text"}]}]}},{"path":"\/primaryContentSections\/1","value":{"parameters":[{"content":[{"inlineContent":[{"type":"text","text":"The user ID array."}],"type":"paragraph"}],"name":"uids"},{"name":"completion","content":[{"type":"paragraph","inlineContent":[{"text":"Callback, returns a dictionary where keys are user IDs and values are the corresponding tokens.","type":"text"}]}]}],"kind":"parameters"},"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallTokenProvider\/title","value":"CallTokenProvider","op":"replace"},{"value":[{"kind":"identifier","text":"CallTokenProvider"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallTokenProvider\/fragments","op":"replace"},{"value":[{"text":"CallTokenProvider","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallTokenProvider\/navigatorTitle"},{"op":"replace","value":"getRelationsAsyncWithRtc:completion:","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallTokenProvider~1getRelationsAsync(rtc:completion:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getRelationsAsyncWithRtc:completion:"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallTokenProvider~1getRelationsAsync(rtc:completion:)\/fragments"}]}]}