{"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallTokenProvider\/getRelations(rtc:)","interfaceLanguage":"swift"},"kind":"symbol","sections":[],"abstract":[{"type":"text","text":"Get the call token synchronously."}],"variants":[{"paths":["\/documentation\/easecalluikit\/calltokenprovider\/getrelations(rtc:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easecalluikit\/calltokenprovider\/getrelations(rtc:)"]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallTokenProvider"]]},"metadata":{"modules":[{"name":"EaseCallUIKit"}],"externalID":"c:@M@EaseCallUIKit@objc(pl)CallTokenProvider(im)getRelationsWithRtc:","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"getRelations","kind":"identifier"},{"kind":"text","text":"("},{"text":"rtc","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"UInt32","kind":"typeIdentifier","preciseIdentifier":"s:s6UInt32V"},{"text":"]) -> [","kind":"text"},{"preciseIdentifier":"s:s6UInt32V","kind":"typeIdentifier","text":"UInt32"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"]"}],"roleHeading":"Instance Method","symbolKind":"method","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"getRelationsWithRtc:"}],"required":true,"title":"getRelations(rtc:)"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getRelations"},{"kind":"text","text":"("},{"kind":"externalParam","text":"rtc"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"uids"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s6UInt32V","text":"UInt32"},{"kind":"text","text":"]) -> ["},{"kind":"typeIdentifier","preciseIdentifier":"s:s6UInt32V","text":"UInt32"},{"kind":"text","text":" : "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"]","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"type":"text","text":"The user ID array."}],"type":"paragraph"}],"name":"uids"}]},{"kind":"content","content":[{"level":2,"type":"heading","text":"Return Value","anchor":"return-value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"A dictionary where keys are user IDs and values are the corresponding tokens."}]}]}],"references":{"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallTokenProvider":{"url":"\/documentation\/easecalluikit\/calltokenprovider","abstract":[],"navigatorTitle":[{"text":"CallTokenProvider","kind":"identifier"}],"kind":"symbol","title":"CallTokenProvider","type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CallTokenProvider","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallTokenProvider","role":"symbol"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit":{"title":"EaseCallUIKit","type":"topic","url":"\/documentation\/easecalluikit","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit","abstract":[],"role":"collection","kind":"symbol"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallTokenProvider/getRelations(rtc:)":{"navigatorTitle":[{"text":"getRelationsWithRtc:","kind":"identifier"}],"abstract":[{"text":"Get the call token synchronously.","type":"text"}],"kind":"symbol","role":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallTokenProvider\/getRelations(rtc:)","url":"\/documentation\/easecalluikit\/calltokenprovider\/getrelations(rtc:)","required":true,"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"getRelations"},{"text":"(","kind":"text"},{"text":"rtc","kind":"externalParam"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s6UInt32V","text":"UInt32"},{"text":"]) -> [","kind":"text"},{"kind":"typeIdentifier","text":"UInt32","preciseIdentifier":"s:s6UInt32V"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"]"}],"title":"getRelations(rtc:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"getRelationsWithRtc:"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"getRelationsWithRtc:","kind":"identifier"}]},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:Q$objc(cs)NSDictionary","text":"NSDictionary<NSNumber *,NSString *>","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"getRelationsWithRtc:"},{"text":"(","kind":"text"},{"text":"NSArray<NSNumber *>","preciseIdentifier":"c:Q$objc(cs)NSArray","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"uids"},{"text":";","kind":"text"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","value":{"parameters":[{"name":"uids","content":[{"type":"paragraph","inlineContent":[{"text":"The user ID array.","type":"text"}]}]}],"kind":"parameters"},"path":"\/primaryContentSections\/1"},{"path":"\/primaryContentSections\/2","value":{"content":[{"text":"Return Value","type":"heading","level":2,"anchor":"return-value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"A dictionary where keys are user IDs and values are the corresponding tokens."}]}],"kind":"content"},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallTokenProvider\/title","value":"CallTokenProvider"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallTokenProvider\/fragments","value":[{"kind":"identifier","text":"CallTokenProvider"}]},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallTokenProvider\/navigatorTitle","value":[{"text":"CallTokenProvider","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallTokenProvider~1getRelations(rtc:)\/title","value":"getRelationsWithRtc:","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallTokenProvider~1getRelations(rtc:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"getRelationsWithRtc:","kind":"identifier"}],"op":"replace"}]}]}