{"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","sections":[],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getCallBusinessError"},{"text":"() -> ","kind":"text"},{"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallBusinessErrorCode","preciseIdentifier":"c:@M@EaseCallUIKit@E@CallBusinessErrorCode","kind":"typeIdentifier","text":"CallBusinessErrorCode"}],"platforms":["iOS"]}],"kind":"declarations"},{"content":[{"type":"heading","level":2,"text":"Return Value","anchor":"return-value"},{"inlineContent":[{"type":"text","text":""},{"isActive":true,"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallBusinessErrorCode","type":"reference"},{"type":"text","text":" enums representing the error code from the business logic module."}],"type":"paragraph"}],"kind":"content"}],"abstract":[{"type":"text","text":"Get error code from the business logic module."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easecalluikit\/callerrorcodegettable\/getcallbusinesserror()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easecalluikit\/callerrorcodegettable\/getcallbusinesserror()"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallErrorCodeGettable\/getCallBusinessError()"},"metadata":{"symbolKind":"method","modules":[{"name":"EaseCallUIKit"}],"externalID":"c:@M@EaseCallUIKit@objc(pl)CallErrorCodeGettable(im)getCallBusinessError","roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"getCallBusinessError","kind":"identifier"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"c:@M@EaseCallUIKit@E@CallBusinessErrorCode","kind":"typeIdentifier","text":"CallBusinessErrorCode"}],"navigatorTitle":[{"kind":"identifier","text":"getCallBusinessError"}],"title":"getCallBusinessError()","role":"symbol","required":true},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallErrorCodeGettable"]]},"references":{"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallBusinessErrorCode":{"abstract":[],"type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"CallBusinessErrorCode","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallBusinessErrorCode","role":"symbol","title":"CallBusinessErrorCode","navigatorTitle":[{"text":"CallBusinessErrorCode","kind":"identifier"}],"url":"\/documentation\/easecalluikit\/callbusinesserrorcode"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallErrorCodeGettable":{"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallErrorCodeGettable","abstract":[{"text":"The ","type":"text"},{"code":"CallErrorCodeGettable","type":"codeVoice"},{"type":"text","text":" protocol defines methods to retrieve error codes from different modules."}],"url":"\/documentation\/easecalluikit\/callerrorcodegettable","navigatorTitle":[{"text":"CallErrorCodeGettable","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"CallErrorCodeGettable","kind":"identifier"}],"type":"topic","title":"CallErrorCodeGettable","role":"symbol","kind":"symbol"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit":{"title":"EaseCallUIKit","type":"topic","url":"\/documentation\/easecalluikit","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit","abstract":[],"role":"collection","kind":"symbol"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallErrorCodeGettable/getCallBusinessError()":{"abstract":[{"type":"text","text":"Get error code from the business logic module."}],"type":"topic","required":true,"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"getCallBusinessError","kind":"identifier"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"c:@M@EaseCallUIKit@E@CallBusinessErrorCode","text":"CallBusinessErrorCode","kind":"typeIdentifier"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallErrorCodeGettable\/getCallBusinessError()","role":"symbol","title":"getCallBusinessError()","navigatorTitle":[{"text":"getCallBusinessError","kind":"identifier"}],"url":"\/documentation\/easecalluikit\/callerrorcodegettable\/getcallbusinesserror()"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"getCallBusinessError"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"getCallBusinessError","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallBusinessErrorCode","preciseIdentifier":"c:@M@EaseCallUIKit@E@CallBusinessErrorCode","kind":"typeIdentifier","text":"CallBusinessErrorCode"},{"kind":"text","text":") "},{"text":"getCallBusinessError","kind":"identifier"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":{"kind":"content","content":[{"type":"heading","level":2,"text":"Return Value","anchor":"return-value"},{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"isActive":true,"type":"reference","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallBusinessErrorCode"},{"type":"text","text":" enums representing the error code from the business logic module."}]}]},"op":"replace","path":"\/primaryContentSections\/1"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallBusinessErrorCode\/title","value":"CallBusinessErrorCode"},{"value":[{"text":"CallBusinessErrorCode","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallBusinessErrorCode\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallBusinessErrorCode\/navigatorTitle","op":"replace","value":[{"text":"CallBusinessErrorCode","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallErrorCodeGettable\/title","value":"CallErrorCodeGettable","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallErrorCodeGettable\/fragments","value":[{"text":"CallErrorCodeGettable","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallErrorCodeGettable\/navigatorTitle","value":[{"text":"CallErrorCodeGettable","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallErrorCodeGettable~1getCallBusinessError()\/title","op":"replace","value":"getCallBusinessError"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"getCallBusinessError","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallErrorCodeGettable~1getCallBusinessError()\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}