{"metadata":{"role":"symbol","required":true,"externalID":"c:@M@EaseCallUIKit@objc(pl)CallErrorCodeGettable(im)getIMError","modules":[{"name":"EaseCallUIKit"}],"symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"getIMError"}],"roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"getIMError","kind":"identifier"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"s:13EaseCallUIKit13ChatErrorCodea","text":"ChatErrorCode","kind":"typeIdentifier"}],"title":"getIMError()"},"schemaVersion":{"patch":0,"minor":3,"major":0},"kind":"symbol","abstract":[{"text":"Get error code from the IM module.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easecalluikit\/callerrorcodegettable\/getimerror()"]},{"paths":["\/documentation\/easecalluikit\/callerrorcodegettable\/getimerror()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallErrorCodeGettable\/getIMError()","interfaceLanguage":"swift"},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"getIMError","kind":"identifier"},{"text":"() -> ","kind":"text"},{"kind":"typeIdentifier","text":"ChatErrorCode","preciseIdentifier":"s:13EaseCallUIKit13ChatErrorCodea","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/ChatErrorCode"}],"languages":["swift"],"platforms":["iOS"]}]},{"content":[{"type":"heading","anchor":"return-value","level":2,"text":"Return Value"},{"inlineContent":[{"text":"","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/ChatErrorCode"},{"text":" enums representing the error code from the IM module.","type":"text"}],"type":"paragraph"}],"kind":"content"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallErrorCodeGettable"]]},"references":{"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/ChatErrorCode":{"role":"symbol","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/ChatErrorCode","url":"\/documentation\/easecalluikit\/chaterrorcode","fragments":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"text":"ChatErrorCode","kind":"identifier"}],"abstract":[],"kind":"symbol","title":"ChatErrorCode","navigatorTitle":[{"kind":"identifier","text":"ChatErrorCode"}],"type":"topic"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallErrorCodeGettable":{"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallErrorCodeGettable","abstract":[{"text":"The ","type":"text"},{"code":"CallErrorCodeGettable","type":"codeVoice"},{"type":"text","text":" protocol defines methods to retrieve error codes from different modules."}],"url":"\/documentation\/easecalluikit\/callerrorcodegettable","navigatorTitle":[{"text":"CallErrorCodeGettable","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"CallErrorCodeGettable","kind":"identifier"}],"type":"topic","title":"CallErrorCodeGettable","role":"symbol","kind":"symbol"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallErrorCodeGettable/getIMError()":{"abstract":[{"type":"text","text":"Get error code from the IM module."}],"required":true,"role":"symbol","navigatorTitle":[{"text":"getIMError","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallErrorCodeGettable\/getIMError()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"getIMError","kind":"identifier"},{"text":"() -> ","kind":"text"},{"kind":"typeIdentifier","text":"ChatErrorCode","preciseIdentifier":"s:13EaseCallUIKit13ChatErrorCodea"}],"url":"\/documentation\/easecalluikit\/callerrorcodegettable\/getimerror()","title":"getIMError()","type":"topic"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit":{"title":"EaseCallUIKit","type":"topic","url":"\/documentation\/easecalluikit","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit","abstract":[],"role":"collection","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"getIMError","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"getIMError"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"text":"EMErrorCode","kind":"typeIdentifier","preciseIdentifier":"c:@E@EMErrorCode"},{"text":") ","kind":"text"},{"text":"getIMError","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]}},{"value":{"kind":"content","content":[{"text":"Return Value","type":"heading","anchor":"return-value","level":2},{"inlineContent":[{"type":"text","text":""},{"type":"reference","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/ChatErrorCode","isActive":true},{"text":" enums representing the error code from the IM module.","type":"text"}],"type":"paragraph"}]},"op":"replace","path":"\/primaryContentSections\/1"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallErrorCodeGettable\/title","value":"CallErrorCodeGettable"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallErrorCodeGettable\/fragments","value":[{"text":"CallErrorCodeGettable","kind":"identifier"}],"op":"replace"},{"value":[{"text":"CallErrorCodeGettable","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallErrorCodeGettable\/navigatorTitle"},{"value":"getIMError","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallErrorCodeGettable~1getIMError()\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallErrorCodeGettable~1getIMError()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getIMError"}]}]}]}