{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easecalluikit\/callerrorcodegettable\/getrtcerror()"]},{"paths":["\/documentation\/easecalluikit\/callerrorcodegettable\/getrtcerror()"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"abstract":[{"text":"Get error code from the RTC module.","type":"text"}],"metadata":{"navigatorTitle":[{"text":"getRTCError","kind":"identifier"}],"modules":[{"name":"EaseCallUIKit"}],"externalID":"c:@M@EaseCallUIKit@objc(pl)CallErrorCodeGettable(im)getRTCError","role":"symbol","title":"getRTCError()","symbolKind":"method","roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"getRTCError","kind":"identifier"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"c:@E@AgoraErrorCode","text":"AgoraErrorCode","kind":"typeIdentifier"}],"required":true},"identifier":{"url":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallErrorCodeGettable\/getRTCError()","interfaceLanguage":"swift"},"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit","doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallErrorCodeGettable"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"getRTCError"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@AgoraErrorCode","text":"AgoraErrorCode"}]}]},{"kind":"content","content":[{"type":"heading","text":"Return Value","anchor":"return-value","level":2},{"inlineContent":[{"type":"text","text":""},{"type":"codeVoice","code":"AgoraErrorCode"},{"type":"text","text":" enums representing the error code from the RTC module."}],"type":"paragraph"}]}],"kind":"symbol","references":{"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallErrorCodeGettable/getRTCError()":{"type":"topic","kind":"symbol","title":"getRTCError()","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallErrorCodeGettable\/getRTCError()","navigatorTitle":[{"text":"getRTCError","kind":"identifier"}],"required":true,"abstract":[{"text":"Get error code from the RTC module.","type":"text"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"getRTCError"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"c:@E@AgoraErrorCode","kind":"typeIdentifier","text":"AgoraErrorCode"}],"url":"\/documentation\/easecalluikit\/callerrorcodegettable\/getrtcerror()","role":"symbol"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit":{"title":"EaseCallUIKit","type":"topic","url":"\/documentation\/easecalluikit","identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit","abstract":[],"role":"collection","kind":"symbol"},"doc://org.cocoapods.EaseCallUIKit/documentation/EaseCallUIKit/CallErrorCodeGettable":{"identifier":"doc:\/\/org.cocoapods.EaseCallUIKit\/documentation\/EaseCallUIKit\/CallErrorCodeGettable","abstract":[{"text":"The ","type":"text"},{"code":"CallErrorCodeGettable","type":"codeVoice"},{"type":"text","text":" protocol defines methods to retrieve error codes from different modules."}],"url":"\/documentation\/easecalluikit\/callerrorcodegettable","navigatorTitle":[{"text":"CallErrorCodeGettable","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"CallErrorCodeGettable","kind":"identifier"}],"type":"topic","title":"CallErrorCodeGettable","role":"symbol","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"getRTCError"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"getRTCError"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:@E@AgoraErrorCode","kind":"typeIdentifier","text":"AgoraErrorCode"},{"text":") ","kind":"text"},{"text":"getRTCError","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/primaryContentSections\/1","value":{"kind":"content","content":[{"type":"heading","level":2,"text":"Return Value","anchor":"return-value"},{"inlineContent":[{"text":"","type":"text"},{"code":"AgoraErrorCode","type":"codeVoice"},{"text":" enums representing the error code from the RTC module.","type":"text"}],"type":"paragraph"}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallErrorCodeGettable~1getRTCError()\/title","value":"getRTCError"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallErrorCodeGettable~1getRTCError()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"getRTCError","kind":"identifier"}]},{"value":"CallErrorCodeGettable","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallErrorCodeGettable\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallErrorCodeGettable\/fragments","value":[{"text":"CallErrorCodeGettable","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseCallUIKit~1documentation~1EaseCallUIKit~1CallErrorCodeGettable\/navigatorTitle","value":[{"kind":"identifier","text":"CallErrorCodeGettable"}]}]}]}